### ISSUE TITLE
Filter out downloaded anime

### ISSUE THREAD

**Issue by su042002** [erengy/taiga#1000]
I have around 300 planned to watch anime and some of them are downloaded onto my hard drive and they are highlighted blue, is there a way to get Taiga to only show the downloaded animes that I have on my hard drive?

**Comment by paulo27ms** [comment]
That highlighted is exactly what you want. Select the option so they sort at the top.

**Comment by paulo27ms** [comment]
![image](https://user-images.githubusercontent.com/13546823/117167415-23728a80-adbf-11eb-9ac5-0ad32ddd7a69.png)

**Comment by su042002** [comment]
Thank you, Paulo, this is exactly what I wanted
