### ISSUE TITLE
Subber name gets interpreted as episode number

### ISSUE THREAD

**Issue by Atario** [erengy/taiga#1001]
File name = `[0x539] Miss Kobayashi's Dragon Maid - S01E01 (BD 1080p x264 Hi10P FLAC) [8373D991].mkv`
Video title = `Miss Kobayashi's Dragon Maid - S01E01 - The Strongest Maid in History, Tohru! (Come On, She's a Dragon)`
Using VLC, so the video title is used as the window title

According to the notification, Taiga thinks the show's name is "Miss Kobayashi's Dragon Maid - S01E01"and that this is "Episode 539"

**Comment by erengy** [comment]
See erengy/anitomy#14. Fixed with erengy/anitomy@668cce41388c5d7d9800399ec59543796881a7d3.
