### ISSUE TITLE
feature request : Dark or Solarized theme

### ISSUE THREAD

**Issue by beep4beep** [erengy/taiga#1002]
I found this option, but no documentation:
![ui theme change](https://user-images.githubusercontent.com/56201153/117583372-162f0600-b107-11eb-8f8d-ac0b49a0f48d.JPG)

I really would like to change the colors or theme, because on a HDR10+ device with a four digit nits in HJDR mode it's the only app in extremely-glaring-white.  It's so bright that it's getting very difficult to read without using a pair of sunglasses.  Very distracting since every other tool or browser I use on Windows 10 are either implementing the dark theme automatically, or have an option to do so. 

Tried to edit the theme file. But all I manage is changing the colors for the progress bar.

**Comment by paulo27ms** [comment]
See https://github.com/erengy/taiga/issues/807 and related issues.

**Comment by beep4beep** [comment]
@paulo27ms missed that one, thanks for pointing it out.
