### ISSUE TITLE
Funimation recognition not working

### ISSUE THREAD

**Issue by wongjn** [erengy/taiga#1003]
Taiga is no longer recognizing Funimation episodes, I believe it may be because the URL structure for shows have changed slightly from this regex:
https://github.com/erengy/taiga/blob/e2cd462bfb2fc02ba7ec8407d342516841f1050b/src/track/media_stream.cpp#L76
This matches for `funimation.com/shows/show-name/episode-name` but now stream/episode pages now have a language code prefix <code>funimation.com/<b>en/</b>shows/show-name/episode-name</code>.

Or perhaps the tab title no longer matches the regex:
https://github.com/erengy/taiga/blob/e2cd462bfb2fc02ba7ec8407d342516841f1050b/src/track/media_stream.cpp#L77
Episode pages now seem to delineate with a pipe (`|`) instead of a dash (`-`) before "Funimation" now, e.g.
> Watch SHOW NAME Season 1 Episode 5 Sub & Dub | Anime Simulcast | Funimation

**Comment by Roxburn** [comment]
PR https://github.com/erengy/taiga/pull/1011 fixes this.

If you desperately want this feature I released the build here https://github.com/Roxburn/taiga/releases/tag/v1.4.0-beta.3
