### ISSUE TITLE
Torrent search only displays latest few episodes of an airing anime (when searching nyaa.si)

### ISSUE THREAD

**Issue by TheInfamousAlk** [erengy/taiga#1008]
![image](https://user-images.githubusercontent.com/29339124/119523759-03454400-bd4b-11eb-91ee-9d460de183da.png)

![image](https://user-images.githubusercontent.com/29339124/119523841-17894100-bd4b-11eb-9369-ceff96536856.png)

This happens when I right click an anime in my list and go search > nyaa.si. 

Above are my search results and filter list. It should show all episodes by [Subsplease] or [Horriblesubs] that are 1080p. And it works, except in every search it always misses episodes that are older than a few weeks. Of course, anime that has finished airing doesn't show up at all. I don't know if this has to do with not being able to search several pages into nyaa.si or what.

**Comment by TheInfamousAlk** [comment]
Another thing to note is that episodes show up in the search (and I'm notified about them) for a while after they air but if I neglect to download them, they later do not show up in search. So I know the episodes themselves are available and I usually download them manually when this happens anyway.

**Comment by paulo27ms** [comment]
Because the RSS feed only shows like 75 items. You need to make a link that excludes result you usually don't want so you can see more relevant things.

**Comment by TheInfamousAlk** [comment]
Oh, I didn't know this was an RSS issue. My bad. I'll figure it out, thanks!
