### ISSUE TITLE
Issue in recognizing Crunchyroll anime in portuguese web browser

### ISSUE THREAD

**Issue by ivesnc** [erengy/taiga#1012]
Hi,

I notice some time ago that when I use the Crunchyroll in portugueses version of website the anime recognition don't work.
I had looked the code and I might have found the problem with it.

When the site is in portuguese, the "Episode" string that is used to identify the anime episode is translated as "Episódio" with an accented o in portuguese version, and this word isn't described in the table on keyword.cpp

To correct it, just add the Keyword L"EPISóDIO" at kElementEpisodePrefix vector.

There is a final catch here though, the "ó" on this string is on the extended ASCII table so the uppercase isn't converted correctly to the lowercase version, so maybe, is safer to add the two versions of this string, with the lowercase ó and the uppercase Ó
The same happens with the word "Capitulo" that is translated as "Capítulo" in portuguese.

I could have done this myself, but the change is so small that I don't want to fork it and etc.

Hope you could understand my poor english skill.

**Comment by Greydus** [comment]
`Settings->Recognition->Streaming media`
> Works best with a browser in English language.
