### ISSUE TITLE
Season 2 Part 2 Problem

### ISSUE THREAD

**Issue by funforgiven** [erengy/taiga#1015]
Tensei shitara Slime Datta Ken has 2 seasons and 2nd season is split in two part. 2nd season Part 1 has 12 episodes. Taiga detects 37th episode as 2nd season, Part 1, episode 13, but it should detect it as 2nd season, Part 2, episode 1. How can I solve it?

![image](https://user-images.githubusercontent.com/35855146/124642117-21e54180-de98-11eb-925c-5e4e00b66929.png)
![image](https://user-images.githubusercontent.com/35855146/124642217-45a88780-de98-11eb-9b8c-5fc50b6b5164.png)

**Comment by paulo27ms** [comment]
Help > Check for updates to update the relations.

**Comment by funforgiven** [comment]
> Help > Check for updates to update the relations.

I didn't know this. It works now. Thanks.
