### ISSUE TITLE
Taiga problem

### ISSUE THREAD

**Issue by CorruptNitro** [erengy/taiga#1016]
I've been using taiga for over a year now and recently I ran into a problem with it. For some reason, taiga does not let me search up new torrents. I keep getting error#7 at the bottom which hasn't before. I can download episodes that are on my anilist, but it won't allow me to search for new torrents outside of that list. I even changed the RSS feed to see if it was that problem but no luck with it. I then decided to reinstall and connected back into my account on taiga but now I'm getting a new error saying cannot authenticate; which is weird since I can see my list still. I've attached some images too.
![unknown](https://user-images.githubusercontent.com/16809952/124982147-642b9180-e004-11eb-8518-25b5da6f18b3.png)
![unknown (1)](https://user-images.githubusercontent.com/16809952/124982167-68f04580-e004-11eb-8ac9-675587e9eaeb.png)
![unknown (2)](https://user-images.githubusercontent.com/16809952/124982173-6a217280-e004-11eb-9863-b56a1176691c.png)

**Comment by paulo27ms** [comment]
None of the 2 sites you're using exist anymore.
And you probably input the wrong username or something on the settings.

**Comment by CorruptNitro** [comment]
> None of the 2 sites you're using exist anymore.
> And you probably input the wrong username or something on the settings.

which RSS feeds do you recommend.

**Comment by paulo27ms** [comment]
The default one, Nyaa.si.

**Comment by CorruptNitro** [comment]
> The default one, Nyaa.si.

So I tried that and got the same error#7
![unknown](https://user-images.githubusercontent.com/16809952/124989463-2a12bd80-e00d-11eb-8de9-430b82c68803.png)
![unknown (1)](https://user-images.githubusercontent.com/16809952/124989473-2aab5400-e00d-11eb-9258-1d6fd1add14f.png)

**Comment by wopian** [comment]
Can you access https://nyaa.si on your browser or is it blocked by your network/ISP?

**Comment by paulo27ms** [comment]
He's has Verizon which is why he can't access.

**Comment by CorruptNitro** [comment]
Yeah it was being blocked by my ISP. Its all good now since i used a vpn. Thank you yall
