### ISSUE TITLE
Avoid sharing private anime

### ISSUE THREAD

**Issue by rustokomuska** [erengy/taiga#1019]
On AniList, you can set certain anime or manga as private. This lets you have anime on your list that you hide from people other than yourself when viewing it. I use this to watch isekai bullshit without letting my friends know.
It would be nice if you could make it so that when a private anime is detected, Taiga does NOT share it as a status to discord rich presence (so you don't have to disable it in the settings). 
It would also be convenient if you could set anime as private or check what anime within your list are private within Taiga.

**Comment by darkash** [comment]
perhaps a duplicate #954

**Comment by rustokomuska** [comment]
> perhaps a duplicate #954

no, the guy in that thread misread the way the feature works first off and second off he didn't suggest the same features even if it did work like anilist

**Comment by darkash** [comment]
> > perhaps a duplicate #954
> 
> no, the guy in that thread misread the way the feature works first off and second off he didn't suggest the same features even if it did work like anilist

I initially asked for private anime entry and an addition with it being automated based on genre blacklist, but it seems you want it a step ahead with discord RPC as well

my apologies for not noticing that
