### ISSUE TITLE
Scan available episodes for completed anime

### ISSUE THREAD

**Issue by su042002** [erengy/taiga#1022]
If you press F5 you can scan anime in your folders and it's highlighted blue and put to the top. This works in the currently watching tab and the plan to watch tab. 

Is there a way for taiga to scan and highlight anime in your completed tab? I can't seem to highlight anime in my completed tab.

**Comment by erengy** [comment]
An anime being highlighted means its next episode is available in your library folders. Completed anime by definition cannot have a next episode, therefore they're not highlighted.

See the relevant options at *Settings → Application → Anime list*:

![image](https://user-images.githubusercontent.com/1078430/136538894-0f1c2903-dd53-4069-9053-8a07bfb86bdf.png)
