### ISSUE TITLE
Taiga doesn't recognized part 2 of anime

### ISSUE THREAD

**Issue by ArgjendZ** [erengy/taiga#1023]
As I mentioned in the title, Taiga doesn't recognized part 2 of the anime, it registers it as the part 1. Example being Reincarnated as a Slime season 2 part 2 is getting recognized as season 2 part 1 and it doesn't scan its available episodes. Same thing happened before with re;zero s2 part 2.

**Comment by paulo27ms** [comment]
https://github.com/erengy/taiga/issues/1014
