### ISSUE TITLE
Windows 11

### ISSUE THREAD

**Issue by erengy** [erengy/taiga#1032]
Has anyone used Taiga on Windows 11 so far? Let me know how it works for you.

**Comment by Damarugaki** [comment]
Works fine
![image](https://user-images.githubusercontent.com/68849809/136086545-8d682657-6e0a-4b88-9f8c-d2762fafb28b.png)

**Comment by TiresomeLime** [comment]
Works fine, discord rich presence still works
New/updated icons
![Screenshot_510](https://user-images.githubusercontent.com/13847198/136092023-76f9152f-ad19-488e-b05e-e19cb2af8ba2.png)

**Comment by oplexz** [comment]
A bit late, but works perfectly on Windows 11 Build 22471.1000.
Most likely because Windows 11 is still pretty much Windows 10 under the hood.

![image](https://user-images.githubusercontent.com/12859907/136869053-eae31290-c5d1-45d4-add4-8c0de44ab918.png)

**Comment by erengy** [comment]
I've been using Windows 11 for a while now and there doesn't seem to be any issues. The only problem I noticed is that if you hover over a partially hidden anime title on Anime List, the tooltip (i.e. `LVS_EX_LABELTIP`) does not disappear after moving the cursor below. Not sure if this is specific to Taiga or related to other tooltip bugs Windows 11 has (e.g. displaying the date or network status while hovering over empty space on taskbar), but this wasn't the case in previous versions.

**Comment by suabahasa** [comment]
I have an issue when scrolling, both using the scrollbar on the left side, and with mouse scroll. some areas of the screen don't update. I need to hover the area to get it re-rendered.

![1651903820_Taiga](https://user-images.githubusercontent.com/5080378/167241238-ba393e9e-6bf7-43ed-ba8a-adaaccc49464.gif)

Windows 11 Build 22616.1

**Comment by oplexz** [comment]
@suabahasa I'm running the same build with no issues. Have you tried updating your graphics drivers?

**Comment by suabahasa** [comment]
> @suabahasa I'm running the same build with no issues. Have you tried updating your graphics drivers?

I just received the windows update notification and update it right now. it seems the notification is late and I didn't notice if it will have a graphic driver update.

Now the issue is resolved. Thank you for reminding me about the graphic driver update
