### ISSUE TITLE
Problems recognizing in Crunchyroll

### ISSUE THREAD

**Issue by levirod** [erengy/taiga#1043]
After updating the web browser version, Taiga started having problems recognizing the anime I'm watching.

**Comment by olee** [comment]
Also not working for me ... how is it even recognizing the active browser / url?
Because I usually have more than a single browser window active, I wonder if that might be an issue.

**Comment by ShaunV2** [comment]
The beta Crunchyroll website that everyone is forced to use now is what has broken Taiga from detecting what you're watching on Crunchyroll through a web browser, the browser having updated isn't the problem in this case.

**Comment by olee** [comment]
Yeah, though it does not work for me even for the non-beta website

**Comment by ShaunV2** [comment]
Pretty sure you can't use the non-beta version of the site anymore, there is no option to switch back to the non-beta version that I can find anyways.

**Comment by Letsplaybar** [comment]
see issue #994
