### ISSUE TITLE
Add a favorite anime/character/manga section

### ISSUE THREAD

**Issue by patschipatsch** [erengy/taiga#105]
I thought it would be nice to have a section for your favorites from MAL

And use the icons from the respective shows/characters/mangas maybe

**Comment by erengy** [comment]
Unfortunately, [MyAnimeList's API](http://myanimelist.net/modules.php?go=api) doesn't provide this kind of information and functionality. There are alternatives such as parsing HTML pages or using an unofficial API, but in my opinion they're both unfavorable.

**Comment by nbooba** [comment]
What about anilist, now that taiga supports it?
