### ISSUE TITLE
Dead images on the homepage

### ISSUE THREAD

**Issue by John09f9** [erengy/taiga#1051]
On https://taiga.moe two images are missing: 

![2022-02-06_010252](https://user-images.githubusercontent.com/14362564/152662037-aa6712eb-e865-4f6e-abf0-2d27158154d0.png)

The leftmost image is also hosted on imgur so you may want to rehost that too. 

In case you don't have the screenshots anymore a recent snapshot of the homepage has them: https://archive.fo/YCbLZ

Cheers!

**Comment by ifonefox** [comment]
There's already an open issue in the website's repo, but it's from another time those images got removed: [taiga-moe#2](https://github.com/erengy/taiga-moe/issues/2)

**Comment by erengy** [comment]
Re-uploaded the images now, thanks for the heads up.
