### ISSUE TITLE
[ Feature Request ] Support for Stremio

### ISSUE THREAD

**Issue by 8227846265** [erengy/taiga#1055]
Please add support to Stremio on `Automatic media detection`

https://www.stremio.com/

**Comment by EnArvy** [comment]
Any updates on this? I know you are busy with v2 but this would be a really nice thing to have!

**Comment by erengy** [comment]
Just tried the latest version (4.4.165) and doesn't seem like it'd be possible to support Stremio. Taiga uses either open file handles or the window title to detect the currently playing media. File handles don't exist for streaming players and the window title doesn't include the necessary information (it's just "Stremio - Freedom to Stream" whether it's playing something or not).
