### ISSUE TITLE
Torrent download error: Torrent file does not exist

### ISSUE THREAD

**Issue by GameBurrow** [erengy/taiga#1059]
For some time now, I've had an error that Taiga fails to download torrent files, it gets this error:
![image](https://user-images.githubusercontent.com/4341091/159028343-1c5c3049-b9b9-4b7d-979a-1fe357e57fcd.png)

I need right click > view torrent info and download/magnet it from the browser.
Happens with all listings.

**Comment by GameBurrow** [comment]
Thanks, that actually works. Though with default method, it hasn't worked for me this entire season, not for a single anime.

**Comment by GameBurrow** [comment]
Any idea how I could get this setting to save? It resets every time Taiga restarts

**Comment by EnergoStalin** [comment]
> Any idea how I could get this setting to save? It resets every time Taiga restarts

Normally it shouldn't reset. I didnt encountered with such problem so i cant suggest anything without extra information such as logs(%APPDATA%\Roaming\Taiga\Taiga.log) from taiga restart. And knowing method how(and from) you installed it.

**Comment by GameBurrow** [comment]
Of course. 

My Taiga is installed in `D:\Program Files\Taiga`, which is my secondary drive. I am using the Beta version

My Taiga log from `"D:\Program Files\Taiga\Taiga.log"` (didn't have any thing in appdata, just empty Taiga folder): https://gist.github.com/GameBurrow/fb9167c3d91525a81ee940aa5b6e8367

Don't see anything in the log at all for the last month? Just restarted Taiga right before getting the log (2022-04-01 11:36) and the issue occured again.

**Comment by EnergoStalin** [comment]
First of all from logs we can see taiga can determinde proper settings path but cant open it cuz file not found. So question where your settings file. From codebase only this case possible _**http://www.cplusplus.com/forum/general/58562/**_. What i can suggest for now basically resinstalling taiga(stable 1.3 or beta 1.4) frow wizard to **D:\Program Files** or reinstall it with default path(which more recommended).

**Comment by GameBurrow** [comment]
Look at the date, that's from last year :)

**Comment by GameBurrow** [comment]
Whatever changed, the setting finally saved itself.

**Comment by EnergoStalin** [comment]
Glad to hear it. Guess it's time to close this issue.

**Comment by EnergoStalin** [comment]
First time trying to solve unexisting problem xD

**Comment by erengy** [comment]
From the [FAQ](https://taiga.moe/#support):

> If you have it installed under a protected directory such as *Program Files*, User Account Control may prevent Taiga from saving its settings and other data.

Taiga's installer has a [warning](https://github.com/erengy/taiga/blob/3d3738588d60e49748c2b3b98d4859e7e0cd0c82/setup/Taiga.nsi#L88-L89) about this too.

See also: #310, #199, #154
