### ISSUE TITLE
A way to specify when to switch to the next episode 

### ISSUE THREAD

**Issue by MooseZM** [erengy/taiga#1060]
Is there a way to specify when to switch to the next episode in mal for example. Like, switch to episode 6 once you reach 80% of episode 5? I tried scouring the settings but couldn't find anything, this is kinda annoying especially since i have double click set to "play next episode" so i always play the next ep even though i watched like 3 minutes of the "last" one

**Comment by paulo27ms** [comment]
You need to rephrase your question. You want Taiga to move to the next episode or mark the current episode as watched?

**Comment by MooseZM** [comment]
sorry if i was unclear, but is there a way to specify when taiga marks an episode as watched. Like when you reach 75% it becomes watched (basically asking if there's a way to change the value of that 75%)

**Comment by paulo27ms** [comment]
There's no option for a % of the episode but you can set the time, so after 5 or 10 or whatever it's marked as watched. Obviously doesn't work the same for everything like short episodes if you set it to 15 minutes.

**Comment by MooseZM** [comment]
where can I find that option because I looked everywhere in the settings and couldn't find it. Thanks btw

**Comment by MooseZM** [comment]
thank you
