### ISSUE TITLE
No (normal) way to set default download location???

### ISSUE THREAD

**Issue by Gmayor61** [erengy/taiga#1062]
Okay, this is pretty baffling. I just set up a seedbox for my torrents and I'm mid working things out. My plan was to have the torrent client watch a folder for new torrent files which taiga would be downloading for me (sonarr and the likes are really bad with this stuff), but I've had to dig through every single setting twice before realizing that for whatever reason, there's no way to just set up a default location for your torrent file to be downloaded to. 
Well, to be precise, there _is,_ but its an utterly surreal roundabout way wherein your downloaded .torrent files are dumped to the same folder where the torrent's contents are. Or, well, _one of them,_ if you happen to have multiple locations for tidiness' sake. Without any method of even specifying _which_ of the "anime folders" you want your .torrent files downloaded to. 
Then as if it was made to tease you, there's another option right below that actually _does_ let you specify where your torrent files need to be downloaded, but it **only** works if you remove all of your library folders from the monitoring system, thus locking you out of the convenient single click button to watch the next episode of your show.
Sincerely, what the hell?

**Comment by erengy** [comment]
If you mean the .torrent files themselves rather than their contents, they're downloaded to Taiga's `data\feed` directory by default. There's an option to change this at *Settings → Advanced → Torrents / Download path for .torrent files* since v1.4 beta.

See also #123.

**Comment by Gmayor61** [comment]
> v1.4 beta.

Well I guess I'll try that out then. I'm only growing more confused by the download location settings while trying to toy around with it. Uh, case closed for now.
