### ISSUE TITLE
Unrecognised episode with hyphens/dashes directly before or after episode number

### ISSUE THREAD

**Issue by nategasm** [erengy/taiga#1069]
For example, the following filenames do not get recognised

- "S01E01-Title.mkv"
- "Title-S01E01.mkv"

But these work:

- "S01E01 Title.mkv"
- "S01E01.Title.mkv"
- "S01E01_Title.mkv"
- "S01E01- Title.mkv"

Version 1.4.0-beta2 with mpv

**Comment by oplexz** [comment]
Looks like a problem with [erengy/anitomy](https://github.com/erengy/anitomy) to me.

**Comment by erengy** [comment]
This is now fixed in Anitomy's development branch. Will be available in v2.

```
>anitomy "S01E01-Title.mkv"
┌────────────────────────┐
│ Element        │ Value │
│────────────────────────│
│ season         │ 01    │
│ episode        │ 01    │
│ title          │ Title │
│ file_extension │ mkv   │
└────────────────────────┘
```

```
>anitomy "Title-S01E01.mkv"
┌────────────────────────┐
│ Element        │ Value │
│────────────────────────│
│ title          │ Title │
│ season         │ 01    │
│ episode        │ 01    │
│ file_extension │ mkv   │
└────────────────────────┘
```
