### ISSUE TITLE
Episodes under anime folder go unrecognized

### ISSUE THREAD

**Issue by FunkyJustin** [erengy/taiga#1071]
I know that since taiga uses the name of the currently playing video to detect whether or not it is an anime. However, it is unable to recognize the anime if the naming convention of the episodes do not contain the title of the anime itself but rather, the name of the episode itself despite the episodes following the S01E01 and so on convention.

I suggest that there should be a way for it to use the folder name as a fallback to know what anime it is and use the title of the video to detect what episode it is. 

![image](https://user-images.githubusercontent.com/18019897/182048666-c4fa5ba4-3a39-40cc-9e68-7104e6127831.png)

**Comment by erengy** [comment]
Taiga already falls back to the folder name when it's unable to identify the anime from the file, so that's not the issue.

The problem in this case is twofold:

1. Taiga parses the anime title as "Gaikotsu Kishi-sama, Tadaima Isekai e Odekakechuu S01" from the folder name (note the "S01" at the end). You need to either add this as an alternative title to the series, or rename the folder.
2. Dashes are significant (see #1069). You need to add spaces around them (e.g. "S01E01 - The") for the file name to be parsed correctly.

**Comment by soredake** [comment]
Same with this release:
![image](https://github.com/erengy/taiga/assets/5204968/1a2e6d06-1a37-425c-9dbd-0e945e459d1c)

**Comment by erengy** [comment]
> Dashes are significant (see #1069). You need to add spaces around them (e.g. "S01E01 - The") for the file name to be parsed correctly.

Fixed in Anitomy's development branch, will be available in v2.

```
>anitomy "S01E01-The Wandering Knight Sets Out to Make the World a Better Place [0C9A7520].mkv"
┌─────────────────────────────────────────────────────────────────────────────────┐
│ Element        │ Value                                                          │
│─────────────────────────────────────────────────────────────────────────────────│
│ season         │ 01                                                             │
│ episode        │ 01                                                             │
│ title          │ The Wandering Knight Sets Out to Make the World a Better Place │
│ file_checksum  │ 0C9A7520                                                       │
│ file_extension │ mkv                                                            │
└─────────────────────────────────────────────────────────────────────────────────┘
```

```
>anitomy "S01E01-Senpai is a bit ..., Senpai, don't you ever get angry [72FF1098].mkv"
┌────────────────────────────────────────────────────────────────────────┐
│ Element        │ Value                                                 │
│────────────────────────────────────────────────────────────────────────│
│ season         │ 01                                                    │
│ episode        │ 01                                                    │
│ title          │ Senpai is a bit ..., Senpai, don't you ever get angry │
│ file_checksum  │ 72FF1098                                              │
│ file_extension │ mkv                                                   │
└────────────────────────────────────────────────────────────────────────┘
```

**Comment by soredake** [comment]
@erengy thank you!!!!
