### ISSUE TITLE
Alternative titles wildcard characters

### ISSUE THREAD

**Issue by Shadoxfix** [erengy/taiga#108]
Currently we have the ability to add alternative titles but sometimes the titles are not known before the episode is released. Small example: "Knights of Sidonia S2 - The Ninth Planet Crusade". This fansub group adds episode titles in the name which causes Taiga to not pick it up. A nice addition to alternative titles would be to add support for wildcard characters such as % in SQL. If that's supported you would be able add "Knights of Sidonia S2%" as an alternative title which means it will still get picked up.

**Comment by erengy** [comment]
It's the first time I see a fansub group putting the episode title before the episode number. Are there any other examples of this? I'd rather avoid the extra complexity and a potential performance decrease, if it's indeed an extreme case.

**Comment by Shadoxfix** [comment]
I actually hadn't noticed the title was before the episode number. From what I can tell it's pretty rare for a group to put the episode title before the episode number. There's some other cases where this might be useful such as files that use both the Japanese and English title in the name but those cases can be  resolved by the user itself by adding the combination of both names as an alternative title.

If it complicates the code too much I'd be fine with closing the issue.

**Comment by Shadoxfix** [comment]
"The Ninth Planet Crusade" is the English translation of "Daikyuu Wakusei Seneki" so it's not a episode title but the name of the show. My bad.

**Comment by erengy** [comment]
Yep, I too just realized that while checking the alternative titles. Still, I went through my database of 100k+ filenames, and there doesn't seem to be any case where episode title comes before the episode number. I'm glad it turned out this way. :whale:
