### ISSUE TITLE
Request for Portable Version

### ISSUE THREAD

**Issue by MrxHellsing** [erengy/taiga#1087]
Requesting for a portable version if possible.

**Comment by erengy** [comment]
Taiga is already portable in the sense that everything is stored in a single directory that you can move around. Also see #941.

**Comment by MrxHellsing** [comment]
I checked that out, so if I extract it using 7-zip, the program would function in portable mode?

**Comment by erengy** [comment]
Indeed, you can treat the setup as a .zip file. Taiga stores everything in its current directory, whereever it may be installed or extracted to. It's essentially a portable app with an installer. This may change in future releases, but in that case, I will provide portable versions as well.

**Comment by MrxHellsing** [comment]
@erengy  That's cool. Thank a lot.
