### ISSUE TITLE
Taiga display English titles instead of Japanese romaji

### ISSUE THREAD

**Issue by Kokxer** [erengy/taiga#109]
I found some anime's title is displayed as English. I didn't check the "Display English titles if possible" option so I think titles should be in Japanese romaji.

for example, the anime titled **My Teen Romantic Comedy SNAFU TOO!**. I think it should be **Yahari Ore no Seishun Love Comedy wa Machigatteiru**. However other animes look good.

![untitled](https://cloud.githubusercontent.com/assets/4020067/7330630/bb9bd65e-eb24-11e4-93e5-23caf961f79b.png)

Taiga 1.2.0, sync with hummingbird.

**Comment by erengy** [comment]
By default, both Hummingbird and Taiga display the canonical title. Apparently, the canonical title for this series is set as the English one in Hummingbird's database. You can confirm by visiting the [anime page of the series](https://hummingbird.me/anime/8478).

That said, I may be able to make Taiga ignore what's canonical or not by setting the relevant API calls' `title_language_preference` parameter to `romanized`.
