### ISSUE TITLE
Taiga doesn't support Deluge >=2.0

### ISSUE THREAD

**Issue by master117** [erengy/taiga#1103]
Starting with 2.0 the deluge cli has changed and the current parameters do no longer work:

![grafik](https://user-images.githubusercontent.com/444009/208290252-06f82c96-a450-4b8a-ac31-1fbd0580d402.png)
![grafik](https://user-images.githubusercontent.com/444009/208290254-bd393bc2-eefd-42e9-9844-caa2247a99b0.png)
![grafik](https://user-images.githubusercontent.com/444009/208290260-022d0e41-87f0-4684-8b8a-416c79de3d28.png)

**Comment by master117** [comment]
Nevermind, it's a deluge bug:

https://dev.deluge-torrent.org/ticket/3546#ticket

**Comment by jasperfirecai2** [comment]
this bug has been in deluge for 3+ years now.. it's joever.
