### ISSUE TITLE
Reduce tile width in season's detailed view to fit more entries

### ISSUE THREAD

**Issue by tophf** [erengy/taiga#1108]
As the app's author mentioned somewhere, the app's window is meant to be small and unobtrusive, but browsing a season in detailed view becomes inconvenient as only one or two entries would be shown per row, so we'd have to scroll a lot.

Suggesting to add an option like `Number of columns` input or `Tile width` slider in the toolbar, shown only when detailed view is active.

For a 1280x800 window a mere 25% width reduction allows to fit another column and show 9 entries instead of 6, i.e. +50% of info!

![image](https://user-images.githubusercontent.com/1310400/212027448-82fe3854-7c39-46f4-baef-c3e30d912858.png)

**Comment by erengy** [comment]
For v2, I'm planning to try making the columns responsive so that all available horizontal space is used. If it works out, it should provide the same result without introducing an option.

**Comment by erengy** [comment]
v2 now displays 1 to 4 columns, depending on the window size. List items are dynamically resized along with the window, to make sure they use the entire horizontal space.
