### ISSUE TITLE
Scores not displayed

### ISSUE THREAD

**Issue by James-Slam** [erengy/taiga#111]
-Version 1.2.0
-Windows 8.1 64 bit

No scores are displayed except those that I have explicitly given a rating. 

I have tried deleting anime.xml and having it repopulate. The scores are visible from within the anime.xml file, but still do not appear in the taiga windows. I have tried re-installing, running in admin, and running in compatibility mode. 

![ss 2015-04-26 at 09 56 53](https://cloud.githubusercontent.com/assets/3708601/7337530/0481d338-ebfb-11e4-8ce5-0f28117216f3.png)

**Comment by erengy** [comment]
The *Score* column displays your own ratings. If you'd like to view the community ratings as well, you can right-click on the list header and select the *Average Score* column.

**Comment by James-Slam** [comment]
Oh, I must not have read all of the patch notes. The last iteration had the average score populating the score column if I didn't manually set one.

Thanks for the clarification, and great project! :D

**Comment by erengy** [comment]
Yeah, the *"Display community ratings (Hummingbird only)"* option is removed from the Settings dialog as well. Since it's now possible to customize the list columns, I decided to add it as a separate column instead.

Have a nice day!
