### ISSUE TITLE
Command-line argument to select sync service

### ISSUE THREAD

**Issue by bto2** [erengy/taiga#1111]
I'm running two instances of Taiga, each using a different service (MAL/AL), but when I open up the second instance with the -allowmultipleinstances argument, it comes with the same service as the first instance and I have to manually switch every time, is there any argument I can pair with the -allowmultipleinstances one so that it picks a specific service?
Something like -myanimelist or -service:myanimelist

**Comment by erengy** [comment]
Each instance of Taiga is supposed to be a different copy. In your case, you should have two different directories with separate executables and settings. For example:

```
└─📂 %AppData%
  ├─ 📂 Taiga AniList
  │  ├─ 📁 data
  │  └─ 📄 Taiga.exe
  └─ 📂 Taiga MyAnimeList
     ├─ 📁 data
     └─ 📄 Taiga.exe
```
