### ISSUE TITLE
Add support for Memento (mpv-based player)

### ISSUE THREAD

**Issue by ayseru** [erengy/taiga#1117]
https://github.com/ripose-jp/Memento
> Memento is a FOSS, mpv-based video player for studying Japanese.

This is my regex for the player list. I haven't been able to get it to work, but it is a good representation of the title format.
`^Memento|(.+) - Memento`

**Comment by odysseaspapadimas** [comment]
Did you find a solution? @ayseru

**Comment by wopian** [comment]
> Did you find a solution? @ayseru

It's supported in 1.4.0

**Comment by odysseaspapadimas** [comment]
> > Did you find a solution? @ayseru
> 
> It's supported in 1.4.0

I have 1.4.0 and I don't see it in the supported media players. When I open an episode using Memento it doesn't recognize it

**Comment by Laesx** [comment]
This should get reopened as it can't recognize Memento 1.4.0 or newer (Memento 1.2.2 works fine for example)
