### ISSUE TITLE
Taiga detects movie files on network shares when "Ignore files outside of library folder" is checked

### ISSUE THREAD

**Issue by Woozie321** [erengy/taiga#112]
I currently have mapped network share and Taiga detects when I'm playing movies from there even if "Ignore files outside of library folder" option is ticked.

**Comment by erengy** [comment]
I believe I fixed the issue now, but I'm unable to test it. Could you try out [this build](http://taiga.erengy.com/latest.html) and see if the files are ignored? First, make sure you can still reproduce the issue with your current build, though.

**Comment by Woozie321** [comment]
I'm sorry for no reply, but the issue is fixed since the last release. GitHub decided not to inform me about new bug replies ^^
