### ISSUE TITLE
[Question] Why is it not possible to import a list to taiga?

### ISSUE THREAD

**Issue by SacredZenpie** [erengy/taiga#1122]
Is there any reason this feature is not implemented or is it simply not wanted?

**Comment by erengy** [comment]
Could you elaborate? Do you mean exporting your list from one service (e.g. MyAnimeList) and importing from another?

**Comment by SacredZenpie** [comment]
Importing MALs list exports for example.

**Comment by erengy** [comment]
Depending on the selected service, it's either not possible, or you're better off importing directly on the website:

- AniList: https://anilist.co/settings/import
- Kitsu: https://kitsu.io/settings/imports
- MyAnimeList: https://myanimelist.net/import.php
