### ISSUE TITLE
When you search for nyaa.si torrents it returns a limited amount of torrents, many episodes missing

### ISSUE THREAD

**Issue by niin44** [erengy/taiga#1132]
When you search for a torrent by right click-> Search -> nyaa.si, it seems to only return a limited list of torrents and many episodes that are available on nyaa are missing. Including some of the most seeded ones. All filters are turned off, tried running in administrator mode. 

Same result for multiple shows. And it doesn't seem to find everything when I do a normal "Check new torrents" search either. It seems to not load all the results from the RSS or maybe nyaa.si is limiting the results.

![Taiga_jzQUk8z5GA](https://github.com/erengy/taiga/assets/18237728/a38e4b49-22b3-4832-a660-7f7b327da97e)
![chrome_hLCJAW9ovv](https://github.com/erengy/taiga/assets/18237728/44401f34-008b-4cd9-ad93-6eb51bee631b)

**Comment by erengy** [comment]
Nyaa's RSS feed returns the most recent 75 items and, unlike the website, does not allow for sorting or pagination. You'll need to make a more specific search (e.g. `Oshi no Ko SubsPlease 1080p`) to get more relevant results.
