### ISSUE TITLE
Add suport for ani-cli recognition

### ISSUE THREAD

**Issue by vvirtues** [erengy/taiga#1133]
Add  support for [ani-cli](https://github.com/pystardust/ani-cli)'s way of naming files, since the team over there are [unwilling](https://github.com/pystardust/ani-cli/issues/569) to change their naming format, which is quite readable to taiga, albeit it is not perfect to taiga's standards.

(Below is not a good example, One Piece seems to have changed into `1p`, but i havent noticed any others doing this)
![mpv_OUNtXpdmaN](https://github.com/erengy/taiga/assets/81705406/c1417929-9e9b-4be5-b744-d2cb9e93c69b)

**Comment by erengy** [comment]
This is somewhat similar to #1071, #1069 and #683. Anitomy considers `-` significant, so it's not an [allowed delimiter](https://github.com/erengy/anitomy/blob/a4fa0a5604e988f6a4802a81c2d2649f98f99d93/anitomy/options.h#L18). You could [modify the option](https://github.com/erengy/taiga/blob/b6f440e48b2827dd9b0c680861cf6c498748c306/src/track/recognition.cpp#L52-L54), but it's almost certainly going to cause issues for other cases. So I'm afraid it's not an easy fix for Taiga either.

**Comment by erengy** [comment]
Anitomy's development branch is now able to parse this correctly. Will be available in v2.

```
>anitomy "1p-episode-122-sub"
┌───────────────────┐
│ Element   │ Value │
│───────────────────│
│ title     │ 1p    │
│ episode   │ 122   │
│ subtitles │ sub   │
└───────────────────┘
```

Of course, you'd still need to add "1p" as an alternative title to *One Piece*.
