### ISSUE TITLE
Sync causes wrong "next episode" to be opened

### ISSUE THREAD

**Issue by Malspherus** [erengy/taiga#1135]
Hi,

When syncing between two devices the wrong episode is played when selecting "play next" even though the correct number is shown.

How this happens for me:
1. Open Taiga on two devices named A & B
2. Watch an episode on device A, eg episode 3
3. Sync after watching on device A
4. Sync on device B
5. Select "play next" on device B
6. Episode 1 is played instead of episode 4

I can fix this issue by restarting Taiga on device B. When reducing the episode instead (eg. from 5 to 4) the episode next to the original is opened (episode 6 in this case).

**Comment by erengy** [comment]
Hi there. This looks like the same issue as #1109.

**Comment by Malspherus** [comment]
I agree, didn't find that one when searching
