### ISSUE TITLE
[Enhancement] Anime List Title columns for language, rather than global setting

### ISSUE THREAD

**Issue by MrTwisT007** [erengy/taiga#1138]
Requesting a rework where instead of setting a global Title Language option under Settings->Application->Appearance, the user is allowed to enable relevant or multiple columns in the Anime List view by right clicking, i.e. "Anime title (English)", "Anime title (Romaji)", etc.

Reasoning - some titles are more known under one or the other name, it would be useful to be able to have both on display at once, rather than changing the global setting in the Settings.

**Comment by erengy** [comment]
The plan for v2 is to allow choosing the preferred title for each anime (#132), which will override the global setting.

See also #655 and #782.
