### ISSUE TITLE
Attack on Titan OAD

### ISSUE THREAD

**Issue by m1nuzz** [erengy/taiga#1155]
the program cannot detect the video file as Attack on Titan OAD
![image](https://github.com/erengy/taiga/assets/109736024/7497aad4-566c-4790-b127-2d55010973c0)

**Comment by erengy** [comment]
What's the full name of the video file?

Did you try clicking the Search link below the suggestions?

First three episodes should be correctly identified as [Shingeki no Kyojin OVA](https://myanimelist.net/anime/18397/Shingeki_no_Kyojin_OVA), while the others being redirected to [Shingeki no Kyojin: Kuinaki Sentaku](https://myanimelist.net/anime/25781/Shingeki_no_Kyojin__Kuinaki_Sentaku) and [Shingeki no Kyojin: Lost Girls](https://myanimelist.net/anime/36106/Shingeki_no_Kyojin__Lost_Girls).

**Comment by m1nuzz** [comment]
> What's the full name of the video file?
> 
> Did you try clicking the Search link below the suggestions?
> 
> First three episodes should be correctly identified as [Shingeki no Kyojin OVA](https://myanimelist.net/anime/18397/Shingeki_no_Kyojin_OVA), while the others being redirected to [Shingeki no Kyojin: Kuinaki Sentaku](https://myanimelist.net/anime/25781/Shingeki_no_Kyojin__Kuinaki_Sentaku) and [Shingeki no Kyojin: Lost Girls](https://myanimelist.net/anime/36106/Shingeki_no_Kyojin__Lost_Girls).

I tried renaming the files to match the name of Ova, also searched in the search, in the manual search Taiga it finds Attack on Titan OAD but when you add in the Now playing tab nothing happens

**Comment by erengy** [comment]
1. Close Taiga.
2. Download the [latest build](https://taiga.moe/latest.html) and put it into your installation directory.
3. Run Taiga and click *Help → Check for updates* to get the latest anime relations.
4. Go to Search page and search for `Attack on Titan`.
5. Try playing the video again.

**Comment by m1nuzz** [comment]
> 1. Close Taiga.
> 2. Download the [latest build](https://taiga.moe/latest.html) and put it into your installation directory.
> 3. Run Taiga and click _Help → Check for updates_ to get the latest anime relations.
> 4. Go to Search page and search for `Attack on Titan`.
> 5. Try playing the video again.

It's not the main Attack on Titan series itself that's not working, it's Attack on Titan OAD and also Attack on Titan: No Regrets

**Comment by m1nuzz** [comment]
> What's the full name of the video file?
> 
> Did you try clicking the Search link below the suggestions?
> 
> First three episodes should be correctly identified as [Shingeki no Kyojin OVA](https://myanimelist.net/anime/18397/Shingeki_no_Kyojin_OVA), while the others being redirected to [Shingeki no Kyojin: Kuinaki Sentaku](https://myanimelist.net/anime/25781/Shingeki_no_Kyojin__Kuinaki_Sentaku) and [Shingeki no Kyojin: Lost Girls](https://myanimelist.net/anime/36106/Shingeki_no_Kyojin__Lost_Girls).

This is https://myanimelist.net/anime/18397/Shingeki_no_Kyojin_OVA?q=Attack%20on%20Titan%20Ova&cat=anime

**Comment by erengy** [comment]
I know. It's just in case Taiga doesn't have the OVAs available in its local database. Searching for `Attack on Titan` returns those in the results as well.

**Comment by m1nuzz** [comment]
> 1. Close Taiga.
> 2. Download the [latest build](https://taiga.moe/latest.html) and put it into your installation directory.
> 3. Run Taiga and click _Help → Check for updates_ to get the latest anime relations.
> 4. Go to Search page and search for `Attack on Titan`.
> 5. Try playing the video again.

The latest build isn't 1.4.0, is it?

**Comment by erengy** [comment]
No, it's v1.4.0 plus all the changes made since then. It's basically a preview of v1.4.1.

**Comment by SacredZenpie** [comment]
> > What's the full name of the video file?
> > Did you try clicking the Search link below the suggestions?
> > First three episodes should be correctly identified as [Shingeki no Kyojin OVA](https://myanimelist.net/anime/18397/Shingeki_no_Kyojin_OVA), while the others being redirected to [Shingeki no Kyojin: Kuinaki Sentaku](https://myanimelist.net/anime/25781/Shingeki_no_Kyojin__Kuinaki_Sentaku) and [Shingeki no Kyojin: Lost Girls](https://myanimelist.net/anime/36106/Shingeki_no_Kyojin__Lost_Girls).
> 
> I tried renaming the files to match the name of Ova, also searched in the search, in the manual search Taiga it finds Attack on Titan OAD but when you add in the Now playing tab nothing happens

You can make it recognize manually too:
- Rename 1st 3 OAD eps to Shingeki no Kyojin OVA eps 1 to 3. 
- Rename OAD eps 4 and 5 to "Shingeki no Kyojin Gaiden: Kuinaki Sentaku" episode 1 and 2.
- Rename OAD eps 7,8 and 9 to "Shingeki no Kyojin: LOST GIRLS" eps 1,2 and 3

**Comment by m1nuzz** [comment]
> > > What's the full name of the video file?
> > > Did you try clicking the Search link below the suggestions?
> > > First three episodes should be correctly identified as [Shingeki no Kyojin OVA](https://myanimelist.net/anime/18397/Shingeki_no_Kyojin_OVA), while the others being redirected to [Shingeki no Kyojin: Kuinaki Sentaku](https://myanimelist.net/anime/25781/Shingeki_no_Kyojin__Kuinaki_Sentaku) and [Shingeki no Kyojin: Lost Girls](https://myanimelist.net/anime/36106/Shingeki_no_Kyojin__Lost_Girls).
> > 
> > 
> > I tried renaming the files to match the name of Ova, also searched in the search, in the manual search Taiga it finds Attack on Titan OAD but when you add in the Now playing tab nothing happens
> 
> You can make it recognize manually too:
> 
> * Rename 1st 3 OAD eps to Shingeki no Kyojin OVA eps 1 to 3.
> * Rename OAD eps 4 and 5 to "Shingeki no Kyojin Gaiden: Kuinaki Sentaku" (if youre using MAL its "Shingeki no Kyojin: Kuinaki Sentaku") episode 1 and 2.
> * Rename OAD eps 7,8 and 9 to "Shingeki no Kyojin: LOST GIRLS" eps 1,2 and 3

![image](https://github.com/erengy/taiga/assets/109736024/a88688de-baa3-47db-8bbf-cd6c98cd7bd2)

downloaded what you provided taiga.exe replaced in the folder with the original exe file, renamed the episodes, does not work.

**Comment by SacredZenpie** [comment]
Can you send your file names

**Comment by m1nuzz** [comment]
> Can you send your file names

![image](https://github.com/erengy/taiga/assets/109736024/11d16039-c9e2-492c-a3ba-2fa514f90dca)
originally from the torrent look like this

**Comment by erengy** [comment]
There's no way Taiga can identify those files with that numbering scheme, you need to rename them one way or the other. You can either do as what @SacredZenpie suggested (works out of the box), or rename them as following (works with the latest anime relations rules):

```
Shingeki no Kyojin OVA
[Baws] Attack on Titan OAD E01 - Ilse's Notebook (BD 1080p Hi10 FLAC AAC) [CC857E14].mkv
[Baws] Attack on Titan OAD E02 - A Sudden Visitor (BD 1080p Hi10 FLAC AAC) [2FB95280].mkv
[Baws] Attack on Titan OAD E03 - Distress (BD 1080p Hi10 FLAC AAC) [AF901FC8].mkv

Shingeki no Kyojin: Kuinaki Sentaku
[Baws] Attack on Titan OAD E04 - A Choice With No Regrets (Part 1) (BD 1080p Hi10 FLAC AAC) [FCC1C180].mkv
[Baws] Attack on Titan OAD E05 - A Choice With No Regrets (Part 2) (BD 1080p Hi10 FLAC AAC) [D9D63330].mkv

Shingeki no Kyojin: Lost Girls
[Baws] Attack on Titan OAD E06 - Wall Sina, Goodbye (Part 1) (BD 1080p Hi10 FLAC AAC) [532460AC].mkv
[Baws] Attack on Titan OAD E07 - Wall Sina, Goodbye (Part 2) (BD 1080p Hi10 FLAC AAC) [25433C7B].mkv
[Baws] Attack on Titan OAD E08 - Lost in the Cruel World (BD 1080p Hi10 FLAC AAC) [AD4EAFDC].mkv
```

I tested both cases with a fresh installation of Taiga. If you're still having issues, try clearing all alternative titles for the series from *Anime Information → Local settings*.

**Comment by m1nuzz** [comment]
> There's no way Taiga can identify those files with that numbering scheme, you need to rename them one way or the other. You can either do as what @SacredZenpie suggested (works out of the box), or rename them as following (works with the latest anime relations rules):
> 
> ```
> Shingeki no Kyojin OVA
> [Baws] Attack on Titan OAD E01 - Ilse's Notebook (BD 1080p Hi10 FLAC AAC) [CC857E14].mkv
> [Baws] Attack on Titan OAD E02 - A Sudden Visitor (BD 1080p Hi10 FLAC AAC) [2FB95280].mkv
> [Baws] Attack on Titan OAD E03 - Distress (BD 1080p Hi10 FLAC AAC) [AF901FC8].mkv
> 
> Shingeki no Kyojin: Kuinaki Sentaku
> [Baws] Attack on Titan OAD E04 - A Choice With No Regrets (Part 1) (BD 1080p Hi10 FLAC AAC) [FCC1C180].mkv
> [Baws] Attack on Titan OAD E05 - A Choice With No Regrets (Part 2) (BD 1080p Hi10 FLAC AAC) [D9D63330].mkv
> 
> Shingeki no Kyojin: Lost Girls
> [Baws] Attack on Titan OAD E06 - Wall Sina, Goodbye (Part 1) (BD 1080p Hi10 FLAC AAC) [532460AC].mkv
> [Baws] Attack on Titan OAD E07 - Wall Sina, Goodbye (Part 2) (BD 1080p Hi10 FLAC AAC) [25433C7B].mkv
> [Baws] Attack on Titan OAD E08 - Lost in the Cruel World (BD 1080p Hi10 FLAC AAC) [AD4EAFDC].mkv
> ```
> 
> I tested both cases with a fresh installation of Taiga. If you're still having issues, try clearing all alternative titles for the series from _Anime Information → Local settings_.

![image](https://github.com/erengy/taiga/assets/109736024/986d6df0-6991-467f-92df-dd8e148ab618)
![image](https://github.com/erengy/taiga/assets/109736024/49284ab0-6424-42d0-a15c-8ca827a44d52)

I tried changing the main service and metadata provider to kitsu, still doesn't find automatically, manual search finds, manually added selected folder, still doesn't work.
