### ISSUE TITLE
[Feature Request] Roku Channel?

### ISSUE THREAD

**Issue by Yankees4life** [erengy/taiga#1159]
Any plans to add the [Roku Channel](https://therokuchannel.roku.com/) to the list of streaming detection? The episode name and season/episode number is on the tab along with the show so it should an easy get
![rokuchannel](https://github.com/erengy/taiga/assets/39246923/98c3ee02-057d-47a8-9e51-125e91f411f5)

An example url
https://therokuchannel.roku.com/watch/20350e88a8485384af2c1345b9b4d564

**Comment by erengy** [comment]
Added in 8e643e220034b52c3cbe6dc62ea31c87de861f68. Could you try the [latest build](https://taiga.moe/latest.html) to see if it works for you? I'm unable to test properly due to regional restriction.

**Comment by Yankees4life** [comment]
It works but not with Librewolf. Had to use a different browser for that (that may be a separate issue I may need to post). Thanks

**Comment by erengy** [comment]
Added support for LibreWolf in erengy/anisthesia@056e06a2c90fc289cfacf97a0f653bcf84cefc60 and updated the latest build.
