### ISSUE TITLE
[Feature Request] Tubi?

### ISSUE THREAD

**Issue by Yankees4life** [erengy/taiga#1160]
Any plans to add [Tubi](tubitv.com)? I think it is doable as the tab title has the show name, season/episode number and episode name
![tubi](https://github.com/erengy/taiga/assets/39246923/d0da6801-5396-40c2-9811-06ed47c2902e)
Heres a url example
https://tubitv.com/tv-shows/401901/s01-e01-surprised-to-be-dead

**Comment by erengy** [comment]
Added in c4824fde022c22e3abe8246b40869217cc6e3b37. Could you try it with the [latest build](https://taiga.moe/latest.html)? As in #1159, I'm unable to test it properly.

**Comment by Yankees4life** [comment]
It works but not with Librewolf. Had to use a different browser for that (that may be a separate issue I may need to post). Thanks
