### ISSUE TITLE
[Suggestion] Add support to mpv-manga-reader to track mangas chapters

### ISSUE THREAD

**Issue by eldonita** [erengy/taiga#1177]
Since i found mpv manga reader i have been using it to read my digital mangas, though its a bit difficult tracking the chapters manually and it would be really good if you could add support for this so that i can track my mangas more easily maybe by making it read the number of the files so that it automatically recognizes if i finished a chapter

**Comment by erengy** [comment]
Manga support isn't planned at the moment and we already have #107 open, so I'll be closing this one.

Thanks for the suggestion though, I didn't know you could use mpv for reading manga too.
