### ISSUE TITLE
[SUGGESTION] Anime Weekly Schedule

### ISSUE THREAD

**Issue by ErrayDineri** [erengy/taiga#1179]
First of all, I'd like to thank everyone that is building this project ! 
And I have a feature in mind that could help make the experience for users (such as myself) better

Proposal: Integrating an anime weekly schedule option into the platform's sidebar, just like this website: https://animeschedule.net

**Comment by erengy** [comment]
Thanks for the suggestion, but I'm closing this one since we aready have #59.
