### ISSUE TITLE
Anime recognition doesn't work with dots in the name

### ISSUE THREAD

**Issue by Creqaw** [erengy/taiga#118]
Using a file name such as "Dragon.Ball.KAI.-.01.-.1080p.BluRay.x264.DHD.mkv" doesn't work. It will detect the anime as "Dragon.Ball.KAI.-.01" and even if you select the appropriate anime it doesn't work because it assumes that the episode number is part of the name for some reason.

**Comment by erengy** [comment]
Fixed in erengy/anitomy@7f1624d08d872858ad823c7d66820b862146f765.
