### ISSUE TITLE
Anime Poster Preview

### ISSUE THREAD

**Issue by emukus** [erengy/taiga#1180]
Add a poster image preview to the left-hand side of the main window.

One of the forks has this nifty feature (https://github.com/koteq/taiga/releases/tag/v1.4.0-mod). 

<img width="625" alt="230746428-7e4fd76b-a0d6-4b54-aa83-f259bcb72c4d" src="https://github.com/erengy/taiga/assets/101443265/f38d9858-1d72-4d68-8ff3-d62ee1ff8038">

**Comment by erengy** [comment]
Closing since we already have #237 by the owner of that fork.

**Comment by emukus** [comment]
Damn, so it's been a feature request for almost a decade now 💀💀

I guess the only thing to do is wait for @koteq to update their fork

**Comment by koteq** [comment]
Wow, neat! A new Taiga release! Thank you, the BDFL @erengy, I appreciate you maintaining the project.

As for the fork, I think it should naturally work just fine with the GH actions workflow. I just need to pull the upstream changes.
