### ISSUE TITLE
[Feature Request/Bug] Alternate titles issue

### ISSUE THREAD

**Issue by JShiesty-dev** [erengy/taiga#1188]
Series like Gintama have different numbers of seasons depending on the source. Anilist combines seasons 1-4 into season 1. Taiga should allow some alternate title format to accommodate that merge. So Taiga should be able to recognize season 1 episodes 1-10 for example and then take season 2 episodes 1-10 and interpret them as season 1.

**Comment by erengy** [comment]
Thanks, but we already have #186 for the same issue.
