### ISSUE TITLE
Problem Recognizing Anime Titles Containing Numbers

### ISSUE THREAD

**Issue by ghostosenpai** [erengy/taiga#1196]
Taiga has problem recognizing anime titles containing numbers in it. It will recognize the numbers as the episode count.

There are 3 shows this season for examples:

1. **NieR:Automata Ver1.1a Part 2 (SubsPlease)** 

> Filename: [SubsPlease] NieR Automata Ver1.1a - 13 (1080p) [DF36D5E3].mkv

![Screenshot 2024-07-08 132104](https://github.com/erengy/anime-relations/assets/77113812/a72c60ac-8e2e-4837-93f2-dcd367fbd772)

As you can see it recognized episode 01 of the 1st cour, not episode 1 of 2nd cour. Even if you open any episode in Part 1 you will achieve the same result.

2. **2.5 Dimensional Seduction (SubsPlus+)** 

> Filename: [SubsPlus+] 2.5 Dimensional Seduction - S01E01 (CR WEB 1080p AVC EAC3) [388F142A].mkv

![Screenshot 2024-07-08 132126](https://github.com/erengy/anime-relations/assets/77113812/38abccd6-ea58-418b-8d74-246ce345ef44)

Here it recognized as episode 2.5.

3. **Fairy Tail: 100 Years Quest (SubsPlease)** 

> Filename: [SubsPlease] Fairy Tail - 100 Years Quest - 01 (1080p) [1107F3A9].mkv

![Screenshot 2024-07-08 132145](https://github.com/erengy/anime-relations/assets/77113812/a051a0d1-f106-448e-990b-070b4421ae7c)

It recognized as ep100 of S1, not ep1 of S4.

---

With that said, this problem maybe nothing new, as I mentioned it happened when 1st cour of Nier was airing too. I was/can patiently do manual tracking back then. But now, you got three shows having the same problem hence I can't keep silence of this anymore.

**Comment by erengy** [comment]
All three cases will be fixed in v2.

> Filename: [SubsPlease] NieR Automata Ver1.1a - 13 (1080p) [DF36D5E3].mkv

See #1110.

> Filename: [SubsPlus+] 2.5 Dimensional Seduction - S01E01 (CR WEB 1080p AVC EAC3) [388F142A].mkv

Haven't seen this one before, but Anitomy's development version is able to parse it correctly. I'll add it as a test case.

```
>anitomy "[SubsPlus+] 2.5 Dimensional Seduction - S01E01 (CR WEB 1080p AVC EAC3) [388F142A].mkv"
┌──────────────────────────────────────────────┐
│ Element          │ Value                     │
│──────────────────────────────────────────────│
│ release_group    │ SubsPlus+                 │
│ title            │ 2.5 Dimensional Seduction │
│ season           │ 01                        │
│ episode          │ 01                        │
│ source           │ CR                        │
│ source           │ WEB                       │
│ video_resolution │ 1080p                     │
│ video_term       │ AVC                       │
│ audio_term       │ EAC3                      │
│ file_checksum    │ 388F142A                  │
│ file_extension   │ mkv                       │
└──────────────────────────────────────────────┘
```

> Filename: [SubsPlease] Fairy Tail - 100 Years Quest - 01 (1080p) [1107F3A9].mkv

See #1195.
