### ISSUE TITLE
Anime disappearing from History tab

### ISSUE THREAD

**Issue by Raitoningu-D** [erengy/taiga#120]
For some reason or another anime that I've watched in the last 3 months have disappeared from the history tab, and it doesn't look like they're coming back. It is a very minor thing, but I do like the History tab as if someone asks me "what anime have you watched recently", I can just go there to take a quick look.

![ss 2015-05-28 at 05 47 23](https://cloud.githubusercontent.com/assets/12639308/7855016/abf4b5a2-0561-11e5-8540-7174e90ebeb6.png)

**Comment by erengy** [comment]
Normally this happens only when Taiga encounters an anime in your history that doesn't exist in the local anime database. Do you have `History::Load | Item does not exist in the database` warnings in `Taiga\Taiga.log` file? Did you do something out of ordinary before the anime disappeared? Did you switch accounts or change the active service?

**Comment by Raitoningu-D** [comment]
I do actually have a lot of "History::Load | Item does not exist in the database" stuff, it's more or less my entire log. The only of note thing I did was I noticed that my Taiga didn't recognise any of my anime at one point, so I had it scan through all my available episodes. It was after that I went into History on a whim and noticed a big chunk were gone, though it's possible it was already gone before I did this. I only have the one account and service, so I have never changed that.

...Now that I think about it, I may have deleted some anime to redownload around that time...

Is there any way for me to get all those history stuff back?

**Comment by erengy** [comment]
You could get them back, but that'd require manually editing `history.xml` and re-adding missing entries in the right order by copy-pasting the warnings in `Taiga.log`. So, yeah, it's probably not worth it.

While it's not a complete solution, d463377c2143c0e70da94327156ee62d5d49dd7b should prevent this issue from happenning in the future.
