### ISSUE TITLE
Kitsu has changed their domain to Kitsu.App

### ISSUE THREAD

**Issue by xyzzyy** [erengy/taiga#1206]
Kitsu syncing in the app no longer works due to references to kitsu.io rather than the new domain, kitsu.app. Changes were just made in the Kitsu repo: [in this commit](https://github.com/hummingbird-me/kitsu-server/commit/244fdccca9754d8579c049e738832843001b33b1)

**Comment by ShaunV2** [comment]
It looks like the change has been merged but no new release has been made to include the change not even the latest build found here https://taiga.moe/latest.html
Taiga is still usable with Kitsu right now since io is back online and syncing does work.

**Comment by erengy** [comment]
I'm not planning to update v1 anymore, but #1207 was merged into the development branch and v2 will use the new domain.
