### ISSUE TITLE
Can't update Twitter, HTTP Error #35 : SSL Connect Error 

### ISSUE THREAD

**Issue by ARealSnake** [erengy/taiga#122]
So it's seems like I can't connect/update my Twitter Feed anymore. Everytime Taiga just send me the HTTP Error #35 
I tried to get into debug mode to see where the problem was at and the only thing was : 

> 2015-06-07 12:20:03 [Debug] http_callback.cpp:123 base::http::Client::DebugHandler | schannel: next InitializeSecurityContext failed: Unknown error (0x80092013) - The revocation function was unable to check revocation because the revocation server was offline.

After that Taiga close the connection and send the error.

**Comment by erengy** [comment]
Previously: #44, #63, #114

Could it be that your computer's time and date setting is incorrect? From what I read, this seems to be one of the causes of the 0x80092013 error. Some people mention that changing the DNS setting (e.g. to Google Public DNS or OpenDNS) resolves the issue. Others say that it's related to AVG's security products... In any case, it seems to be a local and temporary issue.

**Comment by ARealSnake** [comment]
The thing is, I have the right time, I already use Google Public DNS and I already checked my antivirus (Which is BitDefender)

**Comment by erengy** [comment]
Does [this suggestion](http://curl.haxx.se/mail/lib-2012-10/0182.html) work?

> The problem persists until I do a restart of the machine OR I open Internet Explorer and try to reach the same website. After that everything works fine again.
> 
> I assume Internet Explorer does some kind of 'reset' of the schannel-component and after that it works fine again.

**Comment by ARealSnake** [comment]
Still no improve sadly, I also restarted my computer to check and... Nope still nothing

**Comment by mchubby** [comment]
I had the same issue with BitDefender Total Security 2015.
The workaround I found was to temporarily disable the firewall (Protection > Firewall > uncheck the blue mark).
After you log in, the client reuses its HttpClient, so you can re-enable the FW afterwards. However, if you quit and launch Taiga again, the same problem will occur.

(Note: all sorts of SSL analysis is turned off in Web Protection, too)

**Comment by mchubby** [comment]
More info from https://github.com/rust-lang/cargo/issues/1689#issuecomment-145215276
Setting network adapter to "trusted" and stealth enabled completely solves the issue without resorting to toggling off the Bitdefender firewall.

**Comment by erengy** [comment]
I'll consider this issue resolved, thanks to @mchubby.
