### ISSUE TITLE
Specify a folder for automatically downloaded .torrent files

### ISSUE THREAD

**Issue by otvenharom** [erengy/taiga#123]
Currently it seems that all .torrents files get saved to "%appdata%/Taiga/data/feed/[random string]". Would it be possible to implement an option to save .torrent files to a different folder?

**Comment by erengy** [comment]
Could you explain your use case? Is it because you'd like to save the files to a folder monitored by another application? If so, is it not possible to make it monitor multiple folders?

**Comment by otvenharom** [comment]
That's exactly it, while monitoring multiple folders would be possible in that application, it uses those folders for the download location and tagging as well. So it's more of a limitation of that app itself, although I'm sure others could find some use for this option too, assuming it's not too hard to implement.

**Comment by otvenharom** [comment]
Another reason would be saving torrents to a networked directory, where it could be handled by an application running on the remote machine.

Although that could be handled by scripts, it'd definitely make things easier.

**Comment by MightEMatt** [comment]
Is this still on the table for an upcoming release? I handle all of my torrents through a remote server, and being able to have Taiga automatically load up .torrents to the networked watch directory without a script would be a treat.

**Comment by chronisaurous** [comment]
This feature would be great. I use a seedbox - having a folder somewhere a bit easier to find through the ruTorrent file browser would be nice...

**Comment by c0rr0sive88** [comment]
I would like to add that this would be great to have... Right now I have to right click, view torrent info, copy a magnet or torrent link, log into a WebUI for my torrent client which is hosted on my server on the other end of the house, and paste it into there and wait.

I set it up this way as some torrents take too long to download and I don't like keeping my desktop on while I am asleep, thus setting a torrent client up on a server in another room is an easier option.

While yes I could technically point the torrent client to %appdata%/Roaming/Taiga/Data/Feed, that in it self becomes a security risk as I would have to share that directory.
