### ISSUE TITLE
Torrent download error: Invalid content type: application/force-download

### ISSUE THREAD

**Issue by IvanBye** [erengy/taiga#124]
Quite frustrative error.

**Comment by erengy** [comment]
Related to #29. Could you share which RSS feed and torrent causes the issue?

The problem here is that `application/force-download` is not a standard MIME type. Basically, the server you're trying to download the torrent from is misconfigured. It's supposed to return `application/x-bittorrent` for `.torrent` files. Taiga checks the type to avoid downloading invalid files.

**Comment by IvanBye** [comment]
I've just found out this happens if torrent file already in queue (I'm using qbittorrent v3.2.0).

**Comment by erengy** [comment]
I don't think it's related. The error is displayed *before* Taiga saves the `.torrent` file and executes the associated application. At that point, Taiga isn't even aware if you actually have a BitTorrent application installed or not.

**Comment by IvanBye** [comment]
Yeah, right. I've made a video https://youtu.be/VSYwwZ4L_k4 Any thoughts?

**Comment by erengy** [comment]
I'm able to reproduce the issue following your video. Here's the reqeust header Taiga sends to the server:

```
GET /torrents/download_torrent/anime/166 HTTP/1.1
Host: animerg.net
User-Agent: Taiga/1.2
Accept: */*
```

And here's the response header the server returns:

```
HTTP/1.1 200 OK
Date: Fri, 26 Jun 2015 13:57:16 GMT
Server: Apache/2.2.15 (CentOS) DAV/2
Set-Cookie: (...)
Cache-Control: public
Content-Disposition: attachment; filename="82498ef9755d50bb3cb417439dcb48f5659bde52-Danna-ga-Nani-wo-Itteiru-ka-Wakaranai-Ken-2-Sure-me---10.torrent"
Content-Length: 4107
Connection: close
Content-Type: application/force-download
```

As I mentioned previously, the server is supposed to return `Content-Type: application/x-bittorrent` for `.torrent` files. I've notified their staff of this behavior. I'll change the request header to `Accept: application/x-bittorrent` if required, although it currently doesn't have any effect.
