### ISSUE TITLE
Can we set more than 1 type of Twitter status updates?

### ISSUE THREAD

**Issue by KikunXyy** [erengy/taiga#125]
I want to automatically Tweet two things:
- What episode I'm currently watching
- If I just completed an anime, post the title and score. (the default)

**Comment by erengy** [comment]
This should work:

```
$ifequal(%episode%,%total%,Just completed: %title%$if(%score%, (Score: %score%)),Just watched: %title% #%episode%) %animeurl%
```

**Comment by KikunXyy** [comment]
Thanks!

**Comment by KikunXyy** [comment]
Hi again.

I'd like a similar code like the above, but change it such that:
- If I watched an episode and the anime is still airing, I post.
- If I watched an episode and the anime has finished airing, I don't post.
- If I completed an anime, I post.

(Basically, I don't want to post about old anime unless I completed them.)

**Comment by KikunXyy** [comment]
Thanks in advanced!

Oh and, is there a guide on how to write these codes for both Skype/Twitter (the default messages are different so I think they work differently)? I'm no programmer.

**Comment by erengy** [comment]
There's no variable to check the airing status of the anime, so what you want to do is currently not possible.

For more information on format strings, you can check out the relevant entry under the [FAQ](http://taiga.erengy.com/#support) page.
