### ISSUE TITLE
Large fonts

### ISSUE THREAD

**Issue by Zenithtb** [erengy/taiga#126]
I use a 26" TV across the room, with a wireless keyboard/trackpad. To be able to view text, I have Windows set to use 150% font sizes, which works well. 

However, a lot of the windows on Taiga are truncated, although there is a lot of 'white space'. 

Would it be possible to allow scrollbars if all the content will not fit on screen? I believe that's simply a =True when creating the new window...

Best regards for a brilliant program!

Mark

**Comment by erengy** [comment]
Could you try out [this build](http://taiga.erengy.com/latest.html) and see if it works any better? I haven't actually done anything new; it's just that I've recently improved the display on high-DPI settings.

If that doesn't work out, please attach some screenshots so I can see what you see. I believe there shouldn't be any trouble, except for the Now Playing page.

**Comment by Zenithtb** [comment]
I do not see much of a change to be honest  =)
Attached, screenshots:

![taiga](https://cloud.githubusercontent.com/assets/13133658/8475598/92df293a-20b9-11e5-8a88-b414b5c19a3b.png)
![taiganew](https://cloud.githubusercontent.com/assets/13133658/8475599/92ea004e-20b9-11e5-9005-cbc8938314ed.png)

**Comment by erengy** [comment]
I see. The problem here is that high-DPI settings are almost never used on low resolutions. Taiga does support resolutions as low as 1024x768 and text scaling as high as 250%, but they don't go well together. Unfortunately, the solution isn't as easy as you think.

**Comment by Zenithtb** [comment]
Oh, OK. It's not a major show-stopper, but I'd be pleased if something could be figured out, of course.

Many thanks for replying. Feel free to close this if you think it appropriate.

Mark

**Comment by Zenithtb** [comment]
And if it's not apparent, this is what I meant (courtesy  of VLC's settings)

![vlc](https://cloud.githubusercontent.com/assets/13133658/8507975/b42c827e-225b-11e5-90f8-dd818b6e3154.png)

Again, many thanks,

**Comment by erengy** [comment]
I'm afraid I won't be able to do much about this issue. Not until v2.0, at least.
