### ISSUE TITLE
Is it possible to automatically update my Skype status without going to Taiga and clicking "Share"?

### ISSUE THREAD

**Issue by ShedoSurashu** [erengy/taiga#131]
When I watch a new episode, I have to go to Taiga's interface to click the Share button to update my Skype status. Would it be possible to do this automatically? I understand it can be spammy on services like Twitter but for Skype, I don't think that would be the case.

**Comment by erengy** [comment]
If *Tools → Enable auto sharing* and *Settings → Sharing → Skype → Update mood message* options are enabled, it will change the status automatically. Note that the delay time under *Settings → Recognition* affects automatic sharing too.

**Comment by ShedoSurashu** [comment]
Ah that explains it! I thought it would update immediately. I didn't know it was reliant on the Recognition time delay set.
