### ISSUE TITLE
Taiga doesn't detect SMPlayer

### ISSUE THREAD

**Issue by Lightwolf219** [erengy/taiga#133]
![Screenshot](https://cloud.githubusercontent.com/assets/6026441/8713724/203a3808-2b21-11e5-9122-749f25047a45.png)

**Comment by erengy** [comment]
Looks like we have multiple issues here:

- SMPlayer runs as an elevated process. We're unable to access it unless Taiga is run as administrator.
- *smplayer.exe* doesn't own the file handle for the video, its subprocess *mplayer.exe* does.

For now, you should be able to make Taiga detect SMPlayer by doing the following things:

1. Open SMPlayer's Preferences window and disable *Advanced → Show tag info in window title* option.
2. Run Taiga as administrator.
3. Open Taiga's Settings window and clear *Advanced → Recognition / Media player detection method* (it's set to `prioritize_file_handle` by default).

**Comment by Lightwolf219** [comment]
Ah thanks, it works now.
