### ISSUE TITLE
Torrent list rearrange columns

### ISSUE THREAD

**Issue by OsaSoft** [erengy/taiga#135]
Pretty much what it says in the title. Wanted to check when some of the torrents were released and figured Id like to see that every time I open the torrent list, without having to scroll to the side, so Id place it in front of, lets say seed/leech count. 
Since its already possible in anime list, figured it shouldnt be too hard, although from experience I know that when something works somewhere, putting it elsewhere (albeit seeming extremely similar) may take quite some effort.

PS. Already posted this on twitter when I discovered Taiga, but man I love this app. Would love to get involved when I have more time (although I have limited c++ experience, mostly Java/Groovy)

**Comment by erengy** [comment]
The relevant code is pretty much embedded into the Anime List page, and it'd indeed require quite an effort to refactor it to be used in multiple places. In general, I'm trying to avoid meddling too much with the UI until v2.0. For now, I'd rather work on something else and try to live with the minor inconvenience. :)

**Comment by OsaSoft** [comment]
i see, so theres a problem with the ui abstraction layer. Well guess itll have to wait till QT
