### ISSUE TITLE
Ran into a big of a snag with Seasons (Specifically Idolmaster Cinderella S1 and S2)

### ISSUE THREAD

**Issue by gamesbe** [erengy/taiga#136]
It has two separate entries on MAL, that is fine. However, HorribleSubs sticks to the Daisuki numbering system so it comes up as Season One E14 which results it in being grayed out on Taiga.

Is there a way to fix this? Thanks :D

Here is my filter code just in case: http://pastebin.com/UaAiYbZa

**Comment by erengy** [comment]
Fixed with 659ac9ef9f583390729deffabcfa07fb5147fe81.
