### ISSUE TITLE
Setting anime as "rewatching" on hold doesn't work

### ISSUE THREAD

**Issue by wiiaboo** [erengy/taiga#137]
Reproduction: setting a series as "rewatching" automatically puts it the Currently watching tab even if set to On Hold.

![image](http://i.fsbn.eu/hn4D.png)

Using build from a21fa82c66e78b58b048187ca63592a22869b617.

**Comment by erengy** [comment]
This is intentional. Rewatching anime are displayed under the Currently Watching tab whatever their actual status may be, which replicates the behavior on MAL's website.

**Comment by wiiaboo** [comment]
Oh, ok. Nevermind then.
