### ISSUE TITLE
Cannot add unapproved anime to list

### ISSUE THREAD

**Issue by PopescuStefanRadu** [erengy/taiga#138]
Title: Akagami no Shirayuki-hime 2
Reason: This anime has not been approved yet.

Explanation: The list doesn't update in any way because there's this unapproved anime added to it, but the unapproved anime cannot be removed so that the error doesn't occur any more because it requires to first update the list (which ends up with an error)

**Comment by erengy** [comment]
You can simply go to History and remove it from the queue.

This happens due to a [recent change](http://myanimelist.net/forum/?topicid=1407894) where MAL no longer allows users to add unapproved anime to their list. The problem is, their API still returns unapproved entries, and there's no way to distinguish them until you actually try to add one to your list...

**Comment by PopescuStefanRadu** [comment]
Wow, it's kinda late. I appreciate you answering to this. What you said makes sense. You also helped me fix my issue, but there must be a way to fix this overall, maybe give an error-log for an entire update rather than block the update at the first error. Treat each anime successful update as one transaction rather than a bulk of anime updates as one transaction that must be rolled back if failed. Tell me if it's possible please and if there are any difficulties in doing this, I am interested in this subject.

**Comment by erengy** [comment]
One thing we could do is to handle the error and prompt the user to remove the relevant entries from the update queue. This way, they won't get stuck, at least.

**Comment by PopescuStefanRadu** [comment]
Or just skip past the errors and prompt the user that X changes weren't
propagated on the server and he can view which ones and why in his update
list, ideally with a selection button/dropdown/option as well and the
option to retry the operation to selected items.

These failed updates should also try to update normally each time, but they
should only throw an error for the first time they don't work, afterwards
you can just have an occasional reminder pop-up. That way, if an unapproved
anime from your list gets approved the transition is lean.

It's more work, though and you need to make an API error handling method
anyway, in order to know which action to take.

Iirc the unapproved anime errors were considered fatal and made you quit
the update loop.

**Comment by erengy** [comment]
Changing the way the update queue works is too risky at the moment. I may give it a try for v1.3. For now, I just changed the relevant error message:

![not_approved](https://cloud.githubusercontent.com/assets/1078430/12546185/c212a5e4-c350-11e5-889e-38c7c45a87d7.png)

**Comment by PopescuStefanRadu** [comment]
Good work. C++ is hard. Thanks for great app.
