### ISSUE TITLE
Cannot compile taiga with Visual Studio 2015

### ISSUE THREAD

**Issue by AsukaLangleyfag** [erengy/taiga#139]
Error C3688: invalid literal suffix 'L'; literal operator or literal operator template 'operator ""L' not found	 in taiga\src\library\anime_db.cpp line 640

**Comment by AsukaLangleyfag** [comment]
Could this be connected with https://github.com/erengy/anitomy/issues/2 ?

**Comment by erengy** [comment]
Don't think so. It might be possible to fix the issue by adding a space before each `L"`. In any case, `Database::ClearInvalidValues` function is no longer relevant, so we can just remove that and its call in `Database::HandleCompatibility` as well.

**Comment by AsukaLangleyfag** [comment]
Sorry, but I can't help you with removing `Database::ClearInvalidValues`, but adding a space before each `"L` worked fine. But another error: 
Error C2397: conversion from 'int' to 'unsigned short' requires a narrowing conversion in \taiga\src\ui\dlg\dlg_anime_list.cpp at lines 1412, 1415, 1418, 1421, 1424, 1427, 1430, 1433

**Comment by tophf** [comment]
FYI, to make utf8proc dependency compile in VS2015 I had to add `UTF8PROC_EXPORTS` in C++ preprocessor definitions. This value is specified in CMake file of utf8proc but for some reason (not required for VS2017?) isn't present in Taiga.vcxproj.

**Comment by erengy** [comment]
That shouldn't be necessary since eac4d9c4b6012eab0db37e8d46985cff521c934f. From what I can see, you don't have this commit in your fork.

**Comment by tophf** [comment]
I don't update that fork but locally I have the latest master.

**Comment by tophf** [comment]
Huh, apparently re-fetching the submodule failed to use the new git url `https://github.com/erengy/utf8proc.git`, and was still using the old one.
