### ISSUE TITLE
Search List More Than 20 Entries

### ISSUE THREAD

**Issue by CRS-ECHO51** [erengy/taiga#141]
I've been searching anime on Taiga and it never show search entry more than 20.
Can anybody fix this problem?

**Comment by erengy** [comment]
I assume that you use it with a Hummingbird account, right? Hummingbird's API [limits the search method to 20 results](https://github.com/hummingbird-me/hummingbird/blob/438853263a838fa7f92f02b63d62900086085ee4/app/api/api_v1.rb#L540), so there's no way to change that in Taiga. Previously the limit was 5, but then it was [increased](https://github.com/hummingbird-me/hummingbird/commit/0ee38c3d05fea5aa31d472bc9d2cd86e00eb0dab) to 20, although it's probably still not enough for large franchises.
