### ISSUE TITLE
Recognition is no longer attempted

### ISSUE THREAD

**Issue by Atario** [erengy/taiga#148]
Not sure how long it's been now, but for some days (weeks?), Taiga doesn't try to recognize shows anymore.  I have both Notifiy Me and Go To Now Playing turned on for both recognized and unrecognized shows, but neither ever happen.  All players are still checked (I'm using VLC v.2.2.1).  The library does seem to see when there's an unwatched show available, though.  It even plays such shows correctly when middle-clicked or "Play next episode" is clicked.  But it never advances the counter either.

This is on v.1.2.1.

**Comment by erengy** [comment]
1. Does this happen for all anime, or are there any files Taiga's able to detect?
2. Can you give an example path and filename that Taiga's not able to detect?  
(e.g. `D:\Anime\Toradora\Episode 1.mkv`)
3. Do you always have a web browser running along with the media player and Taiga?
4. Did you change anything (e.g. a setting in Taiga, the media player you use, etc.) around the time anime recognition stopped working?

Here's a couple of things you could try:

1. Make sure *Tools → Enable anime recognition* is checked.
2. Disable *Settings → Recognition → General → Ignore files outside of library folders* option.
3. Disable *Settings → Recognition → Streaming media → Enable streaming media detection* option.

**Comment by Atario** [comment]
>Does this happen for all anime, or are there any files Taiga's able to detect?

All anime, and all non-anime.  No notifications either way, no "Now Playing" either way.  No episode counter change on anime either.

>Can you give an example path and filename that Taiga's not able to detect?
(e.g. `D:\Anime\Toradora\Episode 1.mkv`)

`Z:\Video\Toradora!\Toradora [BD 1080p Dual-Audio FLAC]\Toradora! - 01 - Tiger and Dragon.mkv`

`Z:\Video\Toradora!\[Coalgirls]_Toradora_01_(1280x720_Blu-ray_FLAC)_[21ACE6B9].mkv`

`Z:\Video\Toradora!\[HorribleSubs] Toradora! (DUB) (01-25) [1080p]\[HorribleSubs] Toradora! (DUB) - 01 [1080p].mkv`

None of those work now.

>Do you always have a web browser running along with the media player and Taiga?

Yes (Firefox v.39.0).  But I never have any Crunchyroll/etc. tabs open.  I also just tried it with the browser closed; still no dice.

>Did you change anything (e.g. a setting in Taiga, the media player you use, etc.) around the time anime recognition stopped working?

Not sure when it even was that this started.  But I can't think of any significant changes either.

>Disable Settings → Recognition → General → Ignore files outside of library folders option.

This makes recognition happen once again.  But the files I tested with (the _Toradora!_ ones above) are inside one of my configured library folders (`Z:\Video`)!

**Comment by erengy** [comment]
All right, at least we now know why the files are ignored. I'll check out if it's somehow related to the drive letter being `Z:`. In the meantime, could you tell me whether that drive is an internal or an external one?

**Comment by Atario** [comment]
It's a network drive.  Samba share from an Ubuntu Server box.

**Comment by erengy** [comment]
I see. This is probably related to #112, then. I have an old Ubuntu laptop lying around, will try to set up a server and reproduce the issue. I haven't done this before, but shouldn't be too hard (famous last words).

**Comment by erengy** [comment]
Could you try out [this build](http://taiga.erengy.com/latest.html) and see if it fixes the issue?

**Comment by Atario** [comment]
Sorry for the delay.  Yes, that one seems to do it properly.

Thanks for attending to this!
