### ISSUE TITLE
Allow adding of different columns to the different tabs

### ISSUE THREAD

**Issue by Zetka** [erengy/taiga#15]
So I see that Taiga pulls in all of the data for the anime from MAL. Could we have a feature where we can right-click on the top of the columns and add some more information that we'd like to see/sort by? 
For example in uTorrent there is this list: http://puu.sh/a2VVs/139cbbf785.png
Perhaps for Taiga we can choose to sort by popularity or score and perhaps some other useful data.

**Comment by Zyst** [comment]
+1 for @MistahK suggestion.

It would be nice to be able to remove some of the information that a user never uses, as an example season, which would get rid of the Horizontal scrolling line (Since I resize the window to hide it) and do wonders for my OCD.

**Comment by rr-** [comment]
@erengy, column hiding is a nice feature to have. I imagine that most effort would go into GUI editor, but since everyone here seem to be a power user, I presume we'd be happy even if you made it editable only via configuration files.

**Comment by erengy** [comment]
I've already made some preparation in regards to this. Not sure if all of them are going to be included in v1.2, but it's going to be possible to:

- [ ] Right-click on the Anime List header to show/hide columns
- [ ] Resize columns (Taiga will remember their sizes)
- [ ] Reorder columns (Taiga will remember their ordering)
- [ ] Add new columns (e.g. time last watched/updated)

**Comment by Zyst** [comment]
Awesome! Will look forward to that

**Comment by erengy** [comment]
It is now possible to add, remove and reposition Anime List columns. The only new column is "Last updated" at the moment, but I may add more columns in the future.

**Comment by Zyst** [comment]
@erengy thanks man! Awesome stuff
