### ISSUE TITLE
Torrents aren't downloading 

### ISSUE THREAD

**Issue by kilik102** [erengy/taiga#151]
Every time I go to download a torrent through Taiga it downloads the file but doesn't open it in utorrent.   Both Taiga and utorrent are up to date and I use the default Nyaa RSS feed.

**Comment by erengy** [comment]
It seems uTorrent's latest version sets the file association for .torrent files with the additional `/SHELLASSOC` parameter, which Taiga did not expect. Trying to run the application with an invalid path caused an `ERROR_FILE_NOT_FOUND` error. I'll be fixing this shortly.

For now, you can select the *Use a custom application* option from *Settings → Torrents → Downloads* and enter uTorrent's location manually.

**Comment by sauyon** [comment]
Can we get a release for this?
Too lazy to set up a dev environment on windows, especially since I'm probably going to wipe my windows partition soon anyway.

**Comment by erengy** [comment]
Not planning to release a new version just yet, but:

> For now, you can select the *Use a custom application* option from *Settings → Torrents → Downloads* and enter uTorrent's location manually (e.g. `C:\Users\kilik102\AppData\Roaming\uTorrent\uTorrent.exe`).
