### ISSUE TITLE
[Feature Request] Adding KissAnime to Streaming List

### ISSUE THREAD

**Issue by Pixelicious** [erengy/taiga#155]
Hello

Is it possible to add Kissanime to the streaming list as I love this program but I use kissanime to watch most my anime. The anime name and episode are in the url.

Thank you :)

**Comment by erengy** [comment]
Hi there. Sorry, but there are currently no plans to support unofficial streaming sites. There's an [FAQ](http://taiga.erengy.com/#support) entry related to this question, and it was previously mentioned on #75.
