### ISSUE TITLE
Taiga doesn't start torrents in uTorrent

### ISSUE THREAD

**Issue by Koroeskohr** [erengy/taiga#156]
It has only recently happened, I haven't changed my configuration whatsoever.
I don't automatically download my torrents, I just click "Download marked torrents". Taiga doesn't start uTorrent anymore even though it downloads the torrent files, I can see them in the appdata folder. Even if I start uTorrent beforehand, it doesn't do anything.

**Comment by erengy** [comment]
I've recently fixed this. See: #151 

> For now, you can select the *Use a custom application* option from *Settings → Torrents → Downloads* and enter uTorrent's location manually (e.g. `C:\Users\<username>\AppData\Roaming\uTorrent\uTorrent.exe`).
