### ISSUE TITLE
Visual glitch on update screen

### ISSUE THREAD

**Issue by ConnorKrammer** [erengy/taiga#158]
There appears to be a layering issue where the Taiga icon overlaps text on the update prompt screen:

![screenshot 2015-08-10](https://cloud.githubusercontent.com/assets/1044441/9180472/f739900e-3f5f-11e5-9562-7a046061a238.png)

Highlighting the affected text fixed the issue. This was for version 1.2.1 updating to 1.2.2.

**Comment by erengy** [comment]
Yeah, I noticed that as well, but a little too late. I previously fixed a similar issue in 4b38eb01853113c68c5dd3163444cf0cadab0aaa, but looks like I forgot about this dialog. Te-he.

**Comment by ConnorKrammer** [comment]
And by the time you notice, the next version's already pushed out. ~.~;
