### ISSUE TITLE
Filter Discard All

### ISSUE THREAD

**Issue by sand500** [erengy/taiga#160]
If I click "discard all" in torrent screen, what does it actually do? does it make it so the torrents can never be selected again?

**Comment by ConnorKrammer** [comment]
It deselects those particular torrents (not torrents for the entire show) and stops any associated desktop notifications for them. Future torrents for the same shows will still be selected by default unless they are filtered using new torrent filter rules; it also doesn't prevent you from just hitting the checkbox next to the torrent you want (or double-clicking) and downloading it.

**Comment by sand500** [comment]
So there is no way to re apply the filters to the torrents that have already been unselected?

**Comment by ConnorKrammer** [comment]
Here's how it works:
1. There's an RSS feed that aggregates torrents. All of these are displayed on Taiga's Torrents view.
2. Torrent filters (`Tools > Settings > Torrents > Filters`) auto-select some of these from the feed and either notify you or automatically download them. If I remember correctly, the default is to select shows in your currently watching list.
3. If the torrents are not set to auto-download, you can discard them by hitting the "Discard All" button on the Torrents view. This just deselects those particular torrents and stops the notification from recurring every update interval (default: 1 hour). Discarding them does not affect your filters, which means that future torrents for your selected shows will still be selected by default, along with all that entails (notification or automatic download). If you decide you want to download one of previously discarded torrents, you can just check it off and hit "Download marked torrents" or double-click on it.

Essentially, "Discard all" works like the "mark as read" feature in your email client. You can still read the email, but it won't be included in your unread count afterward unless you mark it as such.

**Comment by erengy** [comment]
Taiga keeps a history of downloaded torrents in `Taiga\data\feed\history.xml`. *Discard all* button adds all currently selected torrents to this history, as if you've downloaded them. You can still manually select and download these torrents, but they will no longer be automatically selected by any filters. If, for some reason, you wish to revert this behavior, you can just delete/modify `history.xml` and restart Taiga.
