### ISSUE TITLE
Countdown to next airing episode/notification when an episode has started/finished airing.

### ISSUE THREAD

**Issue by llyyr** [erengy/taiga#165]
Exactly what it says on the tin, it'd be nice to have a countdown to the next airing episode in Taiga. Perhaps as a column in "Currently Watching" list or maybe in the "Seasons" tab.

Could use [Anilist API](http://anilist-api.readthedocs.org/en/latest/anime.html#airing) for that, or maybe host the required data on a server.

**Comment by erengy** [comment]
Closing this issue in favor of #59.
