### ISSUE TITLE
Problem with detecting crunchyroll while using Chrome Version 44.0.2403.155 m

### ISSUE THREAD

**Issue by FatSweatyOtaku** [erengy/taiga#166]
Taiga detects crunchyroll and the episode perfectly but it doesn't know when it closes, it only stops detecting it when I completely exit chrome or Taiga.  It also doesn't see if I change to a different episode.

**Comment by erengy** [comment]
Could you describe your use case? Do you have multiple monitors? Are there multiple Chrome windows or other media players running? Do you close the Crunchyroll tab or navigate to some other page on the same tab? Are there any other Crunchyroll tabs open? I need as much information as possible to be able to reproduce the issue.

**Comment by FatSweatyOtaku** [comment]
I do have multiple monitors and most of the time multiple windows of chrome but always one tab open of Crunchyroll.  When I close the tab or move onto the next episode Tiaga does not see that it has been closed and keeps detecting the first episode that it detected, for example if I am watching episode 1 of Moeblob Adventures X and move onto episode 2 then Tiaga would still say I am on episode 1 in the now playing tab.

**Comment by FatSweatyOtaku** [comment]
It looks like it was a problem with switching from one episode to the next without first closing the tab.
