### ISSUE TITLE
After 1.2.2 recognition won't work sequentially 

### ISSUE THREAD

**Issue by xcom923** [erengy/taiga#168]
After the last update I noticed that when I watch crunchyroll I no longer get notifications. so I dove a little deeper and apparently taiga sticks to whatever episode I was last watching and won't update when I watch something else. 

For example: I was watching "GATE" and my episode updated but when I moved over to watching "Ushio and Tora" not only did I not get a notification about watching the new episode Taiga still showed "GATE" under the Now Playing section. If I exit taiga and open it back up Taiga will update and show "Ushio and Tora" just fine, but if I switch "Ushio and Tora" will still be in Now playing until I restart the app.

**Comment by erengy** [comment]
Might be related to #166:

> It looks like it was a problem with switching from one episode to the next without first closing the tab.

Did you close the tab for *GATE* before moving on to *Ushio and Tora*?

**Comment by xcom923** [comment]
I didn't leave the tab. I just hit "shows" and selected the next show.

**Comment by xcom923** [comment]
also just letting you know I closed the tab and opened crunchyroll in another tab and still frozen on the previous anime I watched. so I didn't get credit for what I just watched (I'll have to do it manually later)

**Comment by xcom923** [comment]
another update I closed Taiga and played "classroom crisis" then closed the tab and checked now playing and it was stuck on Classroom crisis. Opened a new chrome tab and played "MONSTER MUSUME EVERYDAY LIFE WITH MONSTER GIRLS Episode 7" and taiga didn't respond to the change

then I tried opening up a different anime "Fate/kaleid liner PRISMA ILLYA 2wei Herz! Episode 5" and taiga was still stuck on "Classroom☆Crisis" so I think this pretty much confirms that Taiga just gets stuck after a web recognition

**Comment by xcom923** [comment]
>_< sorry but just figured I'd do another update. Apparently if you have taiga play an episode from the animelist section it will update the Now playing section

**Comment by xcom923** [comment]
another update...I closed a tab and reopened Crunchyroll for a different series and Taiga didn't update the "now playing" BUT when I full screened and then reverted (to take a message) Taiga's notification popped up letting me know that it updated. I'll continue to keep an eye on it. Maybe I just need to full screen in order for it to actually notice Crunchyroll

**Comment by erengy** [comment]
Here's hoping that 2babfa5910ecf9130b5901a524a2e1528d2ebcaa will fix this issue.
