### ISSUE TITLE
Durarara X2 relations

### ISSUE THREAD

**Issue by zertap** [erengy/taiga#169]
[HorribleSubs] Durarara!! X2 - 01 [1080p].mkv
[HorribleSubs] Durarara!! X2 - 02 [1080p].mkv
[HorribleSubs] Durarara!! X2 - 03 [1080p].mkv
...
Episodes 1-12 are Durarara!!x2 Shou
Episodes past 12 should be specified as Durarara!!x2 Ten

https://github.com/erengy/taiga/blob/17527704bc23b7ea03a700f7262fe0d87d41c7d7/data/db/anime_relations.json
I wasn't exactly sure how to specify the rules so I'm just posting an issue.

**Comment by erengy** [comment]
Thanks, but the file you linked to is quite old. The [latest version](https://github.com/erengy/taiga/blob/f64473ddf56d5928c0dbc1a50c46efc629839a43/data/db/anime_relations.txt#L122-L127) already redirects the episodes between 13 and 24 to *Durarara!!x2 Ten*:

```
# Durarara!! -> ~ Specials
- 6746|4696:25 -> 8408|5324:2
# Durarara!!x2 Shou -> Durarara!!x2 Ten
- 23199|8314:13-24 -> 27831|9726:1-12!
# Durarara!!x2 Shou -> Durarara!!x2 Ketsu
- 23199|8314:25-36 -> 27833|9725:1-12!
```

Note that you may need to add `Durarara!! X2` as an alternative title to *Durarara!!x2 Shou* for this to work.

**Comment by zertap** [comment]
ah, my bad, thanks
