### ISSUE TITLE
Windows Defender detects installer (TaigaSetup.exe) as a Trojan

### ISSUE THREAD

**Issue by Devian50** [erengy/taiga#173]

**Comment by erengy** [comment]
See #159 and #19.

Another user recently [reported](https://forums.hummingbird.me/t/windows-taiga/10565/421) the same issue:

> I just tried to download via the button under the apps page and Microsoft Security Essentials blocked it saying a virus was detected! Now, I trust you but it looks like Microsoft doesn't. Just wanted to give you a heads up.

I'm [still](https://github.com/erengy/taiga/issues/159#issuecomment-130803918) unable to reproduce the issue, and VirusTotal [says](https://www.virustotal.com/en/file/6ebd9254be96429b70d998830eabbb19cfe3d87834604a5ee968ad7b0e649cbb/analysis/) that the file is clean according to Microsoft. I have no idea why the same program with the same definitions gives different results to different people.

**Comment by Devian50** [comment]
I'm not entirely sure why it detected it myself, as it was not during download. I've had the setup installer on my thumb drive from reinstalling windows for over a week, with it plugged into my desktop the whole time without issue. It just noticed it now. Naturally if it was a heuristic false positive it would be present with anyone using the same version of the installer with the same AV Database but that doesn't appear to be the case.

(I apologize for creating a new issue btw, was in a rush to head out for something.)

I'll contribute the detected "threat" to #19 for you.

**Comment by erengy** [comment]
I've [submitted](https://www.microsoft.com/security/portal/submission/submissionhistory.aspx?SubmissionId=24068b6c-e6bd-44f5-8faf-24720c80982e) the file to Microsoft, and here's their reply:

> The Microsoft Malware Protection Center (MMPC) has investigated the following file(s) which we received on 9/5/2015 7:13:08 AM Pacific Time.
> Below is the determination for your submission.

> Submission ID MMPC15090517953855

> Submitted Files
> TaigaSetup.exe [Not Malware]

> Your submission was scanned using antimalware definition version 1.205.1764.0.
