### ISSUE TITLE
External links

### ISSUE THREAD

**Issue by erengy** [erengy/taiga#178]
Now that [Mahou Showtime Schedule](http://www.mahou.org/Showtime/?o=ET#Current) and [The Fansub Wiki](http://www.fansubwiki.com) are both down for quite a while, Taiga's [external links](https://github.com/erengy/taiga/blob/adab8662e5f9313aa0712ba55b910b6b38a7a356/src/taiga/settings.cpp#L49-L54) need a revision. Here's what I have in mind:

Link|Alternatives
---|---
Mahou Showtime Schedule|:heavy_minus_sign: [AnimeCalendar](http://animecalendar.net)<br/>:heavy_plus_sign: [AniChart](http://anichart.net/airing)<br/>:heavy_minus_sign: [LiveChart - Anime Schedule](https://www.livechart.me/schedule/tv)<br/>:heavy_plus_sign: [Monthly.moe](http://www.monthly.moe/weekly)<br/>:heavy_plus_sign: [Senpai Anime Charts](http://www.senpai.moe/?mode=calendar)
The Fansub Wiki|:heavy_plus_sign: [The Fansub Database](http://fansubdb.com)
Other|:heavy_plus_sign: [Anime Streaming Search Engine](http://because.moe)<br/>:heavy_minus_sign: [fansub.co](http://fansub.co)<br/>:heavy_plus_sign: [Hummingbird Tools](https://hb.wopian.me)<br/>:heavy_minus_sign: [openings.moe](http://openings.moe)

Do you have any other suggestions?

**Comment by wopian** [comment]
There's [http://cal.syoboi.jp/](Syoboi) although it's only in Japanese. Pretty useful for seasonal anime as it actually has detailed information on when stuff airs and their specials or changes in airing schedule/dates.
