### ISSUE TITLE
[Feature Request] Add custom extension to detect unofficial streaming site?

### ISSUE THREAD

**Issue by dipu-bd** [erengy/taiga#184]
Hello,
I found from issue [#155](https://github.com/erengy/taiga/issues/155) that there is no intention to add unofficial streaming site. So instead can you let us add our own extension to dectect streaming site in taiga?

**Comment by dasu** [comment]
Since the project is open source, you always have the ability to fork it and add support for your streaming site of choice.  Seems somewhat simple, assuming the website you're using shows the name/episode # on the window title.

**Comment by dipu-bd** [comment]
I am not very familiar with C++ projects. It will be hard for me to grasp it altogether. But, Is there abosolutely no chance of adding custom support in the near future?

**Comment by erengy** [comment]
Sorry, I don't plan on adding support for unofficial streaming sites anytime soon. This includes indirect support as well.

If anyone wants to give it a go for their personal use, the relevant code resides at the end of [media_stream.cpp](https://github.com/erengy/taiga/blob/81f0acf3ea857f063e2a957ace1ad7538891f4a0/src/track/media_stream.cpp).

**Comment by dipu-bd** [comment]
Hi, I have managed to add [support for KissAnime](https://github.com/dipu-bd/taiga).  But there is a tiny little problem. When a video running in chrome browser and I launch **taiga**, the video gets recognized. But after that when I switch to other video, they do not get recognized. YouTube and some other streaming sites has the same problem. Is this an issue?

**Comment by Qwerty-Space** [comment]
Has the issue been fixed?

**Comment by dipu-bd** [comment]
Yes it is fixed. 

I have another question. Does **taiga** supports HTML5 player? The player from KissAnime is not getting recognized by it. If I wanted to add support for a player, where should I start?

**Comment by Diablofan** [comment]
@Qwerty-Space: Please see @erengy's reply from Oct. 21, this will not be fixed.

@dipu-bd: The player is completely irrelevant in the recognition process for web browser based recognition as Taiga sees the browser as the player, so whatever KissAnime or Crunchyroll or Hulu uses is ignored by Tagia. All that Taiga cares about is that the page has its Title tag including the series name and the episode number. If those are set then whatever it says its playing should be recognized. Some sanitation of the page title (aka, removing everything except the series title and episode number) is needed as can be seen in the CleanStreamTitle function in the same file @erengy linked in his comment above.

**Comment by Qwerty-Space** [comment]
Kissanime does say the anime name and episode number in the title. 
http://i.imgur.com/tGccYhy.png Sunday, 29 November 2015, 08:22am +00:00 from Diablofan < notifications@github.com> :

**Comment by dipu-bd** [comment]
Thank you @Diablofan and @Qwerty-Space 
I took you advice and looked up the url and title recognizer patter I wrote. And I found my mistake. Now it is fine and working good. Thanks again.

**Comment by dipu-bd** [comment]
To anyone who is interested in this release, the installer can be found here-
https://github.com/dipu-bd/taiga/releases/tag/v1.2.1
