### ISSUE TITLE
Custom player recognition?

### ISSUE THREAD

**Issue by tsukari** [erengy/taiga#185]
I'm currently using http://bakamplayer.u8sand.net/ due to some issues with my  graphics card, is it possible to add it to custom detection some how? I'd added this parse to the media.xml playlist but i can't figure out how else it could work or i'm probably jsut not doing it correctly.

	<player>
		<name>Baka Mplayer</name>
		<enabled>1</enabled>
		<visible>1</visible>
		<mode>4</mode>
		<class>QWidget</class>
		<file>Baka_MPlayer.exe</file>
		<folder>%ProgramFiles%\Baka-MPlayer.x86_64\</folder>
		<folder>%ProgramW6432%\Baka-MPlayer.x86_64\</folder>
	</player

**Comment by erengy** [comment]
This seems to work for the latest version (2.0.3) of Baka MPlayer:

```xml
	<!-- Baka MPlayer -->
	<player>
		<name>Baka MPlayer</name>
		<enabled>1</enabled>
		<visible>1</visible>
		<mode>1</mode>
		<class>Qt5QWindowIcon</class>
		<file>Baka MPlayer.exe</file>
		<folder>%ProgramFiles%\Baka-MPlayer.i686\</folder>
		<folder>%ProgramW6432%\Baka-MPlayer.i686\</folder>
		<folder>%ProgramFiles%\Baka-MPlayer.x86_64\</folder>
		<folder>%ProgramW6432%\Baka-MPlayer.x86_64\</folder>
	</player>
```

**Comment by tsukari** [comment]
Ah thanks a ton.
