### ISSUE TITLE
AniDB support

### ISSUE THREAD

**Issue by anzerman** [erengy/taiga#188]
Hi, 
Have you looked at providing support for anidb?

Cheers

**Comment by erengy** [comment]
Hi there @anzerman,

I've been thinking about this since the earliest days of Taiga (i.e. 2008). Even then, AniDB had an archaic and unfriendly [API](http://wiki.anidb.net/w/API). I'm afraid not much has changed in the past seven years in that regard.

**Comment by anzerman** [comment]
Thanks for the response @erengy 

Yeah I have heard it isnt great. It might however be worth checking out https://github.com/japanesemediamanager which seem to have implemented a method to keep watched status up to date as well as other features. :)

**Comment by erengy** [comment]
I'm closing this issue, as AniDB support is not going to be on the horizon anytime soon.
