### ISSUE TITLE
Fall 2015 missing from Seasons interface

### ISSUE THREAD

**Issue by such-doge** [erengy/taiga#189]
Fall 2015 has been underway for quite a while now, but it's still missing from Taiga's list of seasons available to browse. (Version 1.2.2)

**Comment by erengy** [comment]
I haven't had much spare time lately, which is why it's been delayed so far. I think I'll be able to put things together next week and make a release afterwards.

**Comment by erengy** [comment]
It seems I won't be able to make a release this month (I'm going to be abroad for a while), but I managed to prepare the season data a few days ago. If anyone's *dying* to see the Fall 2015 season in Taiga:

1. Download [`2015_fall.xml`](https://raw.githubusercontent.com/erengy/taiga/e3ea38c04351a85c63fe26a5a488e2f1e5b6eb43/data/db/season/2015_fall.xml) and place it under `Taiga\data\db\season\` directory.
2. Get the [latest build](http://taiga.moe/latest.html) of Taiga by following the instructions.
