### ISSUE TITLE
Not recognizing episode that is in folder

### ISSUE THREAD

**Issue by Roxastheman** [erengy/taiga#194]
I have all 25 episode of Toradora!, but only episode 7 isn't recognized for whatever reason. Episode 7's naming scheme isn't any different from the other episodes.

**Comment by fumetsuu** [comment]
Same thing is happening with me, except nothing is being recognized in any media player and Taiga isn't changing to Now Playing when I open an episode.

**Comment by erengy** [comment]
@Roxastheman

Not recognizing *Toradora!* is a serious crime in my book. We need to get this issue resolved immediately!

Is episode 7 under the same folder as the other episodes? Could you copy-paste the filenames or take a screenshot of the anime folder?

@fumetsuu
- Make sure that *Tools → Enable anime recognition* option is enabled.
- Make sure that *Settings → Recognition → Media players → Enable media player detection* option is enabled and the media player you use is selected on the same page.
- If you have the *Settings → Recognition → General → Ignore files outside of library folders* option enabled, try disabling it.
- Try running Taiga as administrator and see if it makes any difference.

**Comment by Roxastheman** [comment]
Here you go, a screenshot of the folder in question and Taiga opened: http://puu.sh/lTGyS/16baa84257.PNG

**Comment by erengy** [comment]
Ah, I see. It's because the title of this episode is "Pool Opening", and Taiga ignores filenames that include keywords such as `OP` and `Opening`. I think I'll be able to fix this by improving the anime type parser.

**Comment by Roxastheman** [comment]
Yup that's it. Glad I was able to help find a very specific bug.

**Comment by erengy** [comment]
This is now fixed with erengy/anitomy@b486125fb8b4cc8acb0cdfd866a742b4d96d4a06.
