### ISSUE TITLE
Entries not on MAL (maybe Hummingbird too) can't be deleted from local database.

### ISSUE THREAD

**Issue by such-doge** [erengy/taiga#195]
I'm using browser recognition with Crunchyroll to update MAL, and Taiga defaults to adding the show as an ONA when the title doesn't match up with what's on MAL. Since Taiga attempts to delete an entry from MAL when it's deleted from its local database, deletion is impossible because it needs to exist on MAL before any action can be carried out. The error returned says, "This anime has not been approved yet." MAL doesn't appear to have Crunchyroll's title listed as an alternate title so there's no way to associate the two, except perhaps by listing it as an alternate in settings. I'm not sure if that would delete the duplicate, though.

The show in question is Wooser no Sono Higurashi: Mugen-hen. On Crunchyroll it is listed as Wooser’s Hand-to-Mouth Life: Phantasmagoric Arc.

http://www.crunchyroll.com/woosers-hand-to-mouth-life-phantasmagoric-arc
http://myanimelist.net/anime/29017/Wooser_no_Sono_Higurashi:_Mugen-hen

**Comment by erengy** [comment]
Was there an ONA with the same name that got deleted from MAL's database? Since it no longer shows up in search results, I'm going to need the following files to be able to replicate the issue:

- `Taiga\data\db\anime.xml`
- `Taiga\data\user\<username>@myanimelist\anime.xml`
- `Taiga\data\user\<username>@myanimelist\history.xml`

**Comment by such-doge** [comment]
It looks like deleting them from the update queue solves the issue for me. It may be an entry that was deleted from MAL. Oddly enough, it displays some correct info in the Now Playing area (image and synopsis). Reproducing the error can be accomplished by turning on browser recognition, list auto-update and watching an episode of the show. Taiga queues the update under the mistaken name.

**Comment by such-doge** [comment]
[data.zip](https://github.com/erengy/taiga/files/63792/data.zip)

**Comment by erengy** [comment]
Until next release, you may add `Wooser’s Hand-to-Mouth Life: Phantasmagoric Arc` as an alternative title to *[Wooser no Sono Higurashi: Mugen-hen](http://myanimelist.net/anime/29017/)* so that Taiga doesn't bring up the deleted entry again when you watch it on Crunchyroll.
