### ISSUE TITLE
Detection of renamed MPC-HC executables

### ISSUE THREAD

**Issue by Shiggydiggy** [erengy/taiga#197]
I had to change the name of MPC-HC from mpc-hc.exe so that it would use my gpu instead of the integrated card, but after doing so it no longer updates my MAL or recognizes that I watched an episode. Is there a way to change what filename Taiga will accept for MPC-HC?

**Comment by Shiggydiggy** [comment]
Scratch that I found where to change the expected filename.

**Comment by erengy** [comment]
If the filename is commonly used, we can add it to [media.xml](https://github.com/erengy/taiga/blob/e1f404e6985683daf6a6a930365a91ebd2eb2826/data/media.xml#L175-L178). Otherwise you can rename your MPC-HC executable to `mpc-hc_nvo.exe`, since Taiga already supports that.

**Comment by Shiggydiggy** [comment]
Mine's currently mpc-hc-gpu.exe since that was just the default one I saw in the guide to fix MPC-HC to work with optimus.

**Comment by erengy** [comment]
The problem is that people can use arbitrary filenames such as `mpc-hc-gpu.exe`, `mpc-hc - gpu.exe`, `mpc-hc2.exe` and so on. We can't just put all possible combinations to media.xml.

Note to self: In the future, we might want to use patterns rather than constant filenames for cases like this.
