### ISSUE TITLE
history.xml won't update

### ISSUE THREAD

**Issue by Raitoningu-D** [erengy/taiga#199]
I have watched a lot of anime from December 10, and Taiga recognizes that the history is being updated. However, today I only noticed that I have a huge gap from December 10 till now. As a test, I watched two anime and the history tab in Taiga showed it being updated. I closed the program, and reopened it. The anime that had been added disappeared.

Last time I had a problem with history, it was from deleting anime. Here the file just won't seem to update. Even the file is telling me that the last time it's been modified is December 10. I'm not sure if it's exclusive to the file or not... but I have also noticed that I haven't been able to download torrents through Taiga for a while. I keep getting a "Torrent download error: Torrent doesn't exist".

I did update to Windows 10 32bit from Windows 7 a couple weeks ago though, probably around that timeframe. Maybe that has something to do with it?

**Comment by erengy** [comment]
It seems that Taiga is unable to write to its `data` directory. This may be the same issue as #85 and #154.

> (...) it may be related to the fact that you've installed the application under Program Files directory. Since Taiga doesn't require administrator rights to run, User Account Control may prevent Taiga from overwriting `feed.xml`, and any other file under the `data` directory, for that matter. If that's the case, you should either move Taiga to the default installation directory (which is `%AppData%\Taiga`), or run it as administrator.


> Where did you install Taiga? If you installed it under a protected directory (such as Program Files) rather than the default location, User Account Control might be preventing Taiga from saving the .torrent files. If that is the case, you can either run Taiga as administrator or reinstall it to its default location where it doesn't need the privileges.

**Comment by Raitoningu-D** [comment]
Looks like you are correct. Giving Taiga full control fixes the issue.

Will use this opportunity to say I really appreciate what you have done with Taiga, and it greatly enhances and eases my anime viewing experience. Keep up the great work!
