### ISSUE TITLE
Using Taiga without an account

### ISSUE THREAD

**Issue by DeadlySync** [erengy/taiga#20]
Hello dear Devs!
I'm new to Taiga and a real slacker, so I tend to use a hole drive to store my watching/watched/plan to watch anime episodes.

By whole drive I mean, my "D:\" drive is my "root folder".

And while scanning for episodes on it, this error pops up:
2014-07-30 20:54:24 [Error] file_search.cpp:44 FileSearchHelper::Search | Access denied.
2014-07-30 20:54:24 [Error] file_search.cpp:45 FileSearchHelper::Search | Path: \\?\D:\System Volume Information\*

Question is: Could I add folders to an "Ignore List" of sorts or could you fix this error?

Off topic: Could I use Taiga as a aggregator of sorts?
I don't have/want MAL account, don't care about social networks.
I'd love to use Taiga as a RSS Reader that Knows what I have/watch and downloads new releases from the groups I like (doesn't Taiga already does that?) without having to be logged on MAL.
You already know all series and know how many episodes it will have, you also know what episodes I have and you know witch episode I've watched, so there is no need to depend on MAL for Taiga to work.
(Or I can't see that due to my "Access denied" error... ;P)

Thanks! :D

**Comment by erengy** [comment]
This is unlikely to happen in near future, but I'm planning to revisit the idea after MAL API v2 comes around (heh).
