### ISSUE TITLE
Aired episodes offset in local settings

### ISSUE THREAD

**Issue by such-doge** [erengy/taiga#200]
Currently, Taiga determines the number of episodes that have been broadcasted for an airing series by counting how many weeks have passed since the start date listed on MAL. However, many series often take a 1-week break and air a special or recap episode instead, sometimes more than once in the series' run. This causes Taiga's count to be one week ahead, so having a local offset would allow users to correct for this.

**Comment by erengy** [comment]
I find this kind of settings less than adequate in most situations. Taiga's [unreliable estimates](https://github.com/erengy/taiga/blob/2d90682c6ddca7c0c9098bffb49236ff464aa1f0/src/library/anime_util.cpp#L81-L106) are indeed a problem, but the solution shouldn't require manual effort on each user's part. At the very least, there should be a public file (as in [`anime_relations.txt`](https://github.com/erengy/taiga/blob/2d90682c6ddca7c0c9098bffb49236ff464aa1f0/data/db/anime_relations.txt)) that benefits all users. The proper solution, though, would be to make Taiga aware of airing times via some external API (see: #59 and #165).

**Comment by such-doge** [comment]
Parsing livechart.me looks like a viable solution. Each anime has a link to its MAL entry, and it provides a nice static fallback page when JavaScript isn't running. I'd limit it to once per 24 hours because they don't appear to have an API, though.

https://www.livechart.me/schedule/tv

**Comment by erengy** [comment]
Closing this issue in favor of #59. I'd rather not make Taiga parse HTML pages, though.
