### ISSUE TITLE
Wrong file chosen as next episode

### ISSUE THREAD

**Issue by Sinthrill** [erengy/taiga#202]
Currently watching a show that has a lot of BD extras that are in a sub-folder to the main show. Every time I try to have Taiga play the next episode it picks one of the extras instead. Thankfully the extras are numbered by what BD volume they were from so I won't have to worry about it past that point, but I have a few other shows that have extras setup like that. Would it be possible to have Taiga remember which folder specifically an episode was played from, and only choose episodes from that folder for that show?

**Comment by such-doge** [comment]
How are the files named? It may be possible to separate them by specifying an alternate title and adding the anime entry for the specials to your watching list.

**Comment by Sinthrill** [comment]
The file I am trying to play and the file Taiga ends up playing are named as follows.

[EveTaku] AKB0048 - 03 (BDRip 1080p H.264-Hi10P FLAC)[A208C1F0].mkv

[EveTaku] AKB0048 Vol.03 - Making of Kibou-ni-Tsuite Music Video (BDRip 1080i H.264-Hi10P FLAC)[C09462E2].mkv

The problems with adding them as specials are they are stuff like character PV videos and making of videos so they aren't on MAL, and there are multiple specials per volume that only share the show name, the sub group, and what volume they are from.

**Comment by erengy** [comment]
Note to self: Doing breadth-first search should fix this issue and improve the results overall.
