### ISSUE TITLE
Season data hasn't updated in forever

### ISSUE THREAD

**Issue by kyodjinn** [erengy/taiga#204]
The last season I can view is Summer 2015. Is this a problem on my end? I'm on version 1.2.2

**Comment by kasokz** [comment]
See #189, seems he doesn't have enough time for that :)

**Comment by kyodjinn** [comment]
@kasokz Ah ok, thanks. That's unfortunate, I didn't know it all had to be done manually.

**Comment by erengy** [comment]
I'm planning to release v1.2.3 sometime this month, possibly the next weekend, which will include both Fall 2015 and Winter 2016 season data. I'm also working on [something](https://github.com/erengy/taiga/issues/162#issuecomment-168812323) that makes pushing new seasons to Taiga easier than before.
