### ISSUE TITLE
New anime relation: GATE 2

### ISSUE THREAD

**Issue by Le-R** [erengy/taiga#206]
```
# Gate: Jieitai Kanochi nite, Kaku Tatakaeri -> ~ Enryuu-hen (2nd Season)
- 28907|10085:13-24 -> 31637|11376:1-12!
```

Not really sure if the "!"  should be at the end of the line or not, but it worked here with this ("GATE - 13" redirected to the 2nd Season ep. 1).

As always, thanks for your work with Taiga. :)

**Comment by erengy** [comment]
`!` doesn't seem to be necessary at the moment. But it's generally a good idea to add it to TV series, in case another fansub group shows up with a filename such as `GATE 2 - 13`.

We have #208 now, so I'm closing this issue. Thanks!
