### ISSUE TITLE
High network usage

### ISSUE THREAD

**Issue by xzro500** [erengy/taiga#210]
heres a screenshot i have taken:
http://i.imgur.com/PnClmGD.png

as you could see taiga is shown to consume GB of data, i really have no idea how this happened.. im quite sure taiga uses low data usage.. anyone can understand whats happening ?

**Comment by wopian** [comment]
Taiga has downloaded 35 MiB and uploaded 2 MiB in 2 months for me. 

Are you sure that Windows bandwidth measurer thing is even accurate though? For me its telling me I've used several hundred GB *more* than my actual system usage. (11.9 TB vs 11.2 TB...so I don't really trust it)

**Comment by erengy** [comment]
To be clear, does that display monthly usage, or is it for a larger frame of time? It's pretty much impossible for Taiga to transfer that much data in a month, even if you have an extremely large anime list that you synchronize a hundred times a day.

Do you download torrents via Taiga? If Windows somehow counts the network usage of a child process (e.g. uTorrent) to its parent (Taiga), the numbers you have would make sense.

**Comment by xzro500** [comment]
i recently formatted the pc that i am using with this (around jan 3, 2016) and install taiga with it.

and i forgot, i watch anime videos downloaded from other PC via LAN file sharing
does it mean its LAN data? im baffled about this because our internet have data cap

thanks

**Comment by gunt3001** [comment]
I am also seeing the huge numbers on my PC running Windows 10. I am also storing my anime on a mapped network drive.

[Screenshot](https://cloud.githubusercontent.com/assets/5871589/12271904/1865534e-b990-11e5-93e6-1e91c3c24fc6.png)

After a little bit of experimenting, it seems like Windows counts any file opened via Taiga (that is on a network drive) towards that usage meter. I tried opening a video, seeking through the file for a bit, and seeing the numbers go up.

**Comment by erengy** [comment]
Thanks for the information, @gunt3001. I've now tried it out myself and confirmed that that is indeed the case. In other words, there's nothing to worry about in terms of Taiga eating up your internet quota.
