### ISSUE TITLE
Torrents: Navigate to torrent description via context menu

### ISSUE THREAD

**Issue by thekot** [erengy/taiga#213]
Both Nyaa and TokyoTosho RSS feeds contains `<guid>` element with url to torrent description page. It would be great to have context menu option to navigate to that url.

**Comment by erengy** [comment]
Could you give an example where this feature would be beneficial for Taiga users?

**Comment by thekot** [comment]
I could give you my use case. Sometimes there are more than one torrents to choose from and I feel that I need go to Nyaa to read the torrents descriptions and user comments. My route is context menu > Information > copy title > Nyaa > fill in filter form > look thru results to find same records. After repeating that routine nth time I submit that feature request of mine.

To be honest I don't know if that feature will be important for other Taiga users.
