### ISSUE TITLE
Volume number to episode range

### ISSUE THREAD

**Issue by erengy** [erengy/taiga#214]
Given a BD/DVD volume (e.g. `Vol.2`) of an anime series, is it possible to programmatically determine which episodes (e.g. 3-4 or 4-5) that volume contains?

From what I can see, each volume has either 2 or 3 episodes, but the pattern changes from one anime to another (e.g. the first volume of a 13-episode series doesn't always have 3 episodes).

Context: Anitomy no longer parses [volume numbers as episode numbers](https://github.com/erengy/anitomy/commit/d52e046896415d73178268dacb602fa522ebba50), so I wanted to make use of this for batch releases in Torrents page.

**Comment by wopian** [comment]
Volume 1 can also contain just one episode, 2-cour (shorts) and above can contain something like 4-6 episodes per volume rarely.

**Comment by erengy** [comment]
It seems that this isn't quite possible. For now, I made it so that the Episode column displays `Vol. 2` instead of just `2` as before, and the column is sorted properly.
