### ISSUE TITLE
starting episode convert

### ISSUE THREAD

**Issue by amboris** [erengy/taiga#216]
hm... dunno if i should make new post, this topic is kina old to revive(#58,#90) but still needed and haven't been done jet.

my solution is that you write a simple math convert funktion for the episode scan added to alternative name box or add a new box called "starting episode value".
what i mean is that when taiger scan the folder it should search for the episode number+the set starting number. formula:update if: n+(b-1)=a-(b-1)   n...current episode  a....current episode scanned      b... set starting episode value. both side should have even number count
this function is only for taiger episode recognizion scan and wont change the taiga update script or function. only the n factor will be passed for update

for example.
i'm watching major current s4
season 4 have a episode range of 26
the sub group did a batch with the filename "major" without season added
s4 starts with the episode 79
i add major s4 to anime list in taiger 
edit
i set starting episode to 79 (in the function i want to add to scan for new episode function)
i set alternative name to major (if it doesnt recognize)
so it scans folder with the starting episode 79 ( scanned number a=79, starting value b=79 ; n+b=a-b-1; "1+79=79-(79-1)" )
taiga recognize episode 79 as episode 1 
video player started
episode played
taiga update to 1

**Comment by erengy** [comment]
Is *Major* the only series you're having a problem with? There's no need to provide a user option for this; adding the series to [`anime_relations.txt`](https://github.com/erengy/taiga/blob/f9b6272c8f64fd79d2b31c1661770d5e62ed8feb/data/db/anime_relations.txt) will make it work for all Taiga users.

You can try adding the following to your own `Taiga\data\db\anime_relations.txt`, and it should work after restarting Taiga:

```
# Major S1 -> ~ S2,S3,S4,S5,S6
- 627|582:27-52 -> 558|515:1-26!
- 627|582:53-78 -> 1842|1659:1-26!
- 627|582:79-104 -> 3226|2869:1-26!
- 627|582:105-129 -> 5028|3891:1-25!
- 627|582:130-154 -> 7655|5070:1-25!
```

**Comment by amboris** [comment]
if this is gonna be about anime relations

there is also 
digimon&tri, Ano Hi Mita Hana, Ano Natsu de Matteru, Baka to Test to Shoukanjuu, Berserk: Ougon Jidaihen, Chihayafuru, Chitose Get You, Clannad&afterstory, Code Geass, D-Frag!, Full Metal Panic!, Gantz, Genshiken, Grisaia no Rakuen, Gyakkyou Burai Kaiji, Hakuouki, High School DxD, Higurashi no Naku Koro ni, Hokuto no Ken, Initial D, Kamisama Hajimemashita, Kingdom, Log Horizon, Maria-sama ga Miteru, Minami-ke, Mirai Nikki, Mobile Suit Gundam 00, Natsume Yuujinchou, Psycho-Pass, Sayonara Zetsubou Sensei, School Rumble, Seitokai Yakuindomo, Seto no Hanayome, Strike the Blood, Tenjou Tenge, Thermae Romae, Tonari no Kaibutsu-kun, , Tsubasa Chronicle, XXXHolic, Working!!!, Yahari Ore no Seishun Love Comedy, Yondemasu yo, Azazel-san, 

is there a synch with the sever and local data anime_relations.txt?


Date: Tue, 19 Jan 2016 19:51:04 -0800

**Comment by tomerghelber** [comment]
How about guessing by the connections of the animes?
Mal saves sequal sand so on, and OVA and staff can be counted too.

**Comment by erengy** [comment]
> there is also (...)

I've checked all of your suggestions but could only find releases that require the following anime to be added to `anime_relations.txt`:

- [x] digimon&tri
- [ ] Ano Hi Mita Hana
- [x] Ano Natsu de Matteru
- [ ] Baka to Test to Shoukanjuu
- [ ] Berserk: Ougon Jidaihen
- [x] Chihayafuru
- [ ] Chitose Get You
- [x] Clannad&afterstory
- [x] Code Geass
- [ ] D-Frag!
- [ ] Full Metal Panic!
- [x] Gantz
- [ ] Genshiken
- [ ] Grisaia no Rakuen
- [ ] Gyakkyou Burai Kaiji
- [ ] Hakuouki
- [x] High School DxD
- [ ] Higurashi no Naku Koro ni
- [ ] Hokuto no Ken
- [ ] Initial D
- [ ] Kamisama Hajimemashita
- [ ] Kingdom
- [x] Log Horizon
- [x] Maria-sama ga Miteru
- [ ] Minami-ke
- [ ] Mirai Nikki
- [ ] Mobile Suit Gundam 00
- [ ] Natsume Yuujinchou
- [ ] Psycho-Pass
- [ ] Sayonara Zetsubou Sensei
- [ ] School Rumble
- [x] Seitokai Yakuindomo
- [x] Seto no Hanayome
- [ ] Strike the Blood
- [x] Tenjou Tenge
- [ ] Thermae Romae
- [ ] Tonari no Kaibutsu-kun
- [x] Tsubasa Chronicle
- [ ] XXXHolic
- [x] Working!!!
- [ ] Yahari Ore no Seishun Love Comedy
- [ ] Yondemasu yo, Azazel-san

I'll be closing this issue with an upcoming commit that adds these anime relations.

> is there a synch with the sever and local data anime_relations.txt?

Yes, the local data is updated whenever you check for an application update (either automatically at startup, or manually via *Help → Check for updates*), even if there's no new version of Taiga available.

> How about guessing by the connections of the animes?
> Mal saves sequal sand so on, and OVA and staff can be counted too.

MAL's API doesn't provide these connections to Taiga or other third-party applications. Even if it did, episode redirection still requires human supervision in many cases.
