### ISSUE TITLE
Recognition delay by percentage

### ISSUE THREAD

**Issue by Malou95** [erengy/taiga#218]
That's pretty annoying to set recognition delay to 90sec for 2-3min long animes and when you watch half of 24min ones (or just the beginning), Taiga put them as "watched".

I guess that's a bit more complicated to do cause the program have to check metadatas, but that should be really cool.

**Comment by erengy** [comment]
We've previously had some discussion about this on #164, but I ended up closing the issue. If you have any suggestions, let's continue on that one.
