### ISSUE TITLE
Add LiveChart to External links

### ISSUE THREAD

**Issue by wopian** [erengy/taiga#221]
[LiveChart](https://www.livechart.me) is one of the more popular seasonal/weekly anime trackers that display all key information about the shows.

**Comment by erengy** [comment]
I had already considered adding LiveChart to the list (see #178), but ultimately decided that the features of its alternatives were more fitting.

Please use #178 for further requests and suggestions regarding external links. Note that I'd like to have as few links as possible, not the opposite.
