### ISSUE TITLE
Append title of anime as label in torrent client

### ISSUE THREAD

**Issue by treborabc** [erengy/taiga#223]
I'm not sure if this is something that's possible, but I would like when torrents are added to have the box for label filled out, or to add it in some other means.

**Comment by erengy** [comment]
Which torrent client do you use?

Assuming that it's uTorrent, as far as I know, it's not possible to set the label via command line parameters. I haven't used uTorrent for quite a while, but isn't it possible to set up automatic labeling rules via the program's preferences?

**Comment by treborabc** [comment]
qBittorent 3.2.4, and yeah it seems so after googling that uTorrent has that functionality. I honestly didn't think that would be a thing that would work but I suppose if you set the string right it can pull the right data.

**Comment by erengy** [comment]
qBittorent doesn't have this kind of functionality, unfortunately.

I'm closing this issue in favor of #86.
