### ISSUE TITLE
Daylight savings is not recognised in torrent release dates

### ISSUE THREAD

**Issue by Princess-Luna** [erengy/taiga#224]
My current timezone is GMT+11 (which is GMT+10 without daylight savings), but the release dates all show +10.

**Comment by erengy** [comment]
Note that the `HH:MM:SS` part displays the correct local time. It's just the `+ZZZZ` part that displays your geographical time zone, even if DST is in effect. This is fairly easy to change, but I'm not sure which one's more appropriate or correct. I'll give this another thought later on, when I feel less tired.

**Comment by Princess-Luna** [comment]
My HH:MM:SS part shows the incorrect time as well.
