### ISSUE TITLE
Manually set folder not scanned for available episodes.

### ISSUE THREAD

**Issue by sachaw** [erengy/taiga#225]
When a series in my collection has naming that does not match that of hummingbird, for example            "[HorribleSubs] Active Raid [1080p]" is not recognized, so I select this folder as the series folder in taiga, but when i scan for available episodes nothing is shown for this series.

**Comment by erengy** [comment]
Setting `Active Raid` as an alternative title for the series is all you need to do. If you did that, Taiga would automatically set the folder and identify the episodes.

**Comment by sachaw** [comment]
can i do that within taiga or request a change in the hummingbird DB?

**Comment by sachaw** [comment]
just realized i could do that, thanks.
