### ISSUE TITLE
Supporting streaming sites

### ISSUE THREAD

**Issue by Rulasmur** [erengy/taiga#226]
Would it be possible to add a feature that looks at the url of a website and marks episodes as viewed based on regex(or something) provided by the user?

I've seen a few websites with url layouts like:
`http://somesite.com/anime-name-here/episode-15`

**Comment by erengy** [comment]
If it's an official streaming site and the page title includes the necessary information (the URL alone isn't enough), I can try adding support for it. Otherwise, please see #184 and the [FAQ page](http://taiga.moe/#support).
