### ISSUE TITLE
Streaming media detection fails with multiple browser windows open

### ISSUE THREAD

**Issue by canadianakin** [erengy/taiga#227]
After auto-detecting an episode from Crunchyroll (on Chrome), that episode will stay as "Now Playing" until Taiga is restarted OR until a show/episode is watched from local files. Watching a different show/episode on Crunchyroll does not auto-update after the first time.

**Comment by erengy** [comment]
Might be related to #166 or #168.

**Comment by canadianakin** [comment]
Yes, it seems as though they are related. However, it seems like nothing I do regarding Crunchyroll will update the auto-detection. Closing the tab and opening a new one does not appear to work like [#166](https://github.com/erengy/taiga/issues/166) and going to fullscreen and exiting in a new tab like [#168](https://github.com/erengy/taiga/issues/168) does not work either. 

I am using dual monitors, typically with a chrome window on each. I have not had multiple Crunchyroll tabs open, all my Crunchyroll browsing is done in a single tab. I don't have any other media running while watching either. 

The only way I've found to clear the episode from now playing is like in my original post, by closing Taiga or by playing an episode from a local file.

**Comment by Californ1a** [comment]
I'm having the same issue, have to manually close and reopen Taiga to get it to detect Crunchyroll in chrome. I'm using spanned triple monitors (3*1920x1080, spanned nvidia surround 5760x1080), only one Crunchyroll tab, although multiple chrome windows and other tabs. Closing the tab and reopening Crunchyroll in a new tab doesn't fix it, and neither does opening and closing fullscreen.

**Comment by erengy** [comment]
I basically rewrote the entire media detection code for [Anisthesia](https://github.com/erengy/anisthesia). Here's hoping v1.3 fixes this. 🙏
