### ISSUE TITLE
Random Invalid content type: text/html error

### ISSUE THREAD

**Issue by gamesbe** [erengy/taiga#228]
It started happening yesterday: http://i.imgur.com/8dbtMt1.png

I  use this rss feed: http://tokyotosho.info/rss.php?filter=1,11&zwnj=0

Some torrents work, others don't.

**Comment by wopian** [comment]
Tosho and nyaa are getting DDoS'd on and off, so most chances are is its because of that.

**Comment by erengy** [comment]
It's because the [download link](http://www.nyaa.se/?page=download&tid=782425) for the [torrent](https://www.tokyotosho.info/details.php?id=964239) is invalid. This usually happens when a torrent submission is removed from Nyaa, but isn't removed from other sites or RSS feeds.
