### ISSUE TITLE
Please add proxy support

### ISSUE THREAD

**Issue by x5f3759df** [erengy/taiga#231]
Is Taiga support proxy settings for torrent searching? In mother Russia most ISPs block nyaa.eu/se (and bunch of other chinese cartoons resources for "child porn" reason), so I can't use dis program fully featured. Maybe you can do it, please?

**Comment by kiljacken** [comment]
@x5f3759df It's already supported. Check out the `Advanced` tab of the settings menu.

**Comment by x5f3759df** [comment]
Oh, my bad. Sorry for inconvenience! And thank you.
