### ISSUE TITLE
"Use anime folders as the download folder" doesn't work

### ISSUE THREAD

**Issue by VivaLaPanda** [erengy/taiga#232]
If I enable the option using Deluge in daemon mode, and with the console exe selected, the file will add, but deluge will not show anything on the "Move completed" option.

**Comment by wopian** [comment]
#229

**Comment by VivaLaPanda** [comment]
As I said, I followed those options already.

**Comment by erengy** [comment]
Taiga sets the initial download path (which can be seen under the Details tab of Deluge) rather than the "Move completed" option. Is it not the case for you?

**Comment by VivaLaPanda** [comment]
Oh, okay! I missed that. Thanks!
