### ISSUE TITLE
Anime List: "Start new rewatch" option in context menu

### ISSUE THREAD

**Issue by ConnorKrammer** [erengy/taiga#234]
For completed series, I think it would be nice to have an option that you can click to start a new rewatch. Here's the proposed process:
1. Right-click an anime on the completed list
2. Select "Start rewatch"/ " Start new rewatch"
3. Several things happen in the background:
   - the show is set as being in a rewatch (normally toggled via settings tab in the information view)
   - the episode watch count is set to 0
   - the anime is moved to the currently watching list
   - the first episode is opened in the default media player if it can be found locally

This makes it the same number of steps to rewatch a show as it is to start a new one.

I also wonder if having a "cancel rewatch" option might be useful, but I don't know that doing that is a very common action.

**Comment by robflop** [comment]
Any updates on this? Would also appreciate if it was possible.

**Comment by cnguy** [comment]
Hi! I've been working on this feature since I'm a fan of it as well. @erengy Would something like this work?

https://imgur.com/a/nkjOrIo
