### ISSUE TITLE
Nyaa feed doesn't work since Cloudflare implementation

### ISSUE THREAD

**Issue by Schuuby** [erengy/taiga#236]
Error showing:
```
2016-02-25 18:31:01 [Error] http.cpp:89 taiga::HttpClient::OnError | HTTP error #6: Couldn't resolve host name (8;URL=)
Connection mode: 9
```

**Comment by erengy** [comment]
There seems to be two issues here:

1. Nyaa is using the non-standard HTTP header `Refresh: 8;URL=/cdn-cgi/l/chk_jschl?pass=(...)` to redirect Taiga to another location. I have previously (and reluctantly) added support for this header in 795a0feddee18e8533c90c620495c13a1f5f522b, but the code needs to be updated to support uppercase `URL=`.

2. Fixing the first issue and following the redirection doesn't work. In fact, it kinda makes things worse. Cloudflare returns `302 Moved Temporarily` with `Location: /`, which then makes Taiga fall into a redirection loop. Posing as a web browser by sending a different user-agent string doesn't work.

From what I can gather, Cloudflare's automatic browser check requires some JavaScript code to be run on the client. I don't think that it's possible for Taiga (and similar applications) to bypass this.

**Comment by robflop** [comment]
> Again, I don't think that it's possible to bypass this, at least without acting maliciously.

Man, that sounds bad. Would you suggest switching to the feed you mentioned to me in a forum post (http://feeds.feedburner.com/anime-rss-atom-feeds?format=xml) then?

**Comment by stormhertz** [comment]
If Nyaa is a lost cost due to their new DDOS protection, it would also be worth looking at Tokyo Tosho's RSS feed. I think it can be customized to list only anime releases, and it should work similarly, though none of my releases are out today so I can't test if it works properly.

**Comment by robflop** [comment]
> though none of my releases are out today so I can't test if it works properly.

I have no clue how to set up an RSS, so would you mind posting a link to a Tosho feed sorted to translated anime releases only? I have quite some backlog at the moment, so it should display something. 

(http://tokyotosho.info/rss.php?filter=1,11&zwnj=0 in both fields displays "no new torrents found", but i've generally noticed that i've been having some major problems with the torrent feature displaying nothing or missing a lot)

**Comment by stormhertz** [comment]
https://www.tokyotosho.info/rss.php?filter=1,10&entries=450&cat=1 
This is a feed with 450 entries sorted for Anime and Non-English, which I believe would cover translated anime releases only (however, I don't know how search term syntax filters work for Tokyo Tosho, so it won't work with searching titles in Taiga). You can try to manually access the feed and Ctrl-F to see if your releases are in this RSS, and compare them with Nyaa's RSS, as they may not track the same lists.

For me, my releases aren't in Nyaa yet, so I couldn't find them in Tokyo Tosho. However, if your releases are in Nyaa but not Tokyo Tosho, it might be delayed.

**Comment by robflop** [comment]
Well, it seems like the tosho link built into taiga and that one display the same. I believe I'm just having general problems with the torrent feature over all.

**Comment by erengy** [comment]
In theory, yes, switching to another RSS feed is the way to go. However:

- Most of the download links on other RSS feeds (including TokyoTosho) are still provided by Nyaa, so changing this setting doesn't help. Cloudflare's protection is enabled on Nyaa's download links too.

- As far as I'm aware, the only RSS feed that allows searching is Nyaa's. TokyoTosho and others don't have this feature.

@robflop You can customize your TokyoTosho RSS feed from [here](https://www.tokyotosho.info/rss_customize.php), but the default feed provided by Taiga is probably what you're after anyway.

**Comment by robflop** [comment]
Right, thanks.

**Comment by VivaLaPanda** [comment]
Nyaa says that IUAM has been off for a while. I talked to him on IRC.
Here is some data;
Recent bits of our conversation: http://puu.sh/nqAD5/1c7a2d1b2b.png
Logs: http://pastebin.com/raw/cBGnz2GM

**Comment by VivaLaPanda** [comment]
Working DL: http://pastebin.com/raw/qHiu87Nv
Failed DL: http://pastebin.com/raw/AzzaFw7Z

**Comment by erengy** [comment]
Their RSS feed now uses protocol-relative URLs for the channel `link` and item `guid`s:

```xml
<link>//www.nyaa.se/</link>
```

```xml
<guid>//www.nyaa.se/?page=view&#38;tid=789763</guid>
```

Taiga's unable to download the .torrent files because it doesn't support protocol-relative URLs.

**Comment by VivaLaPanda** [comment]
What would need to be done to add support? Would it be a major change?

**Comment by erengy** [comment]
The URL parser of Taiga needs to be updated. I've already done this, I just haven't had the time to test it out yet.

That said, using relative URLs in RSS documents is against the [specification](http://www.rssboard.org/rss-profile#data-types-url):

> In all `link` and `url` elements, the first non-whitespace characters in a URL MUST begin with a scheme defined by the IANA Registry of URI Schemes such as "ftp://", "http://", "https://", "mailto:" or "news://". These elements MUST NOT contain relative URLs.

I think Nyaa has already fixed this on their end.

**Comment by pickfire** [comment]
It really upsets me when Nyaa is using cloudflare, I can't automate the download now.

**Comment by reconman** [comment]
Cloudflare is blocking again.

**Comment by robflop** [comment]
This is not the case for me @reconman.

**Comment by reconman** [comment]
Boku no Hero Academia was not listed as torrent so I switched the feed to tokyotosho. Then the episode was listed but trying to download resulted in an 403 error.

**Comment by RozeDoyanawa** [comment]
I'm having the same issues since yesterday night.
"Last update, 1 day 2 hours ago"
"Bad response for 'https://www.nyaa.eu/?page=rss&term=HorribleSubs%201080p': 503 Service Temporary Unavailable.
URL works fine in browser after allowing cloudfare scripts.
URL does NOT work in Vuze.

//Regards

**Comment by bergerst** [comment]
@RozeDoyanawa Are you using a VPN and if yes have you set up a direct route to nyaa.se?

**Comment by reconman** [comment]
@RozeDoyanawa Are you using a VPN and if yes have you set up a direct route to nyaa.se?

**Comment by erengy** [comment]
@RozeDoyanawa Using nyaa.se instead of nyaa.eu works for me at the moment (you can change the URL from *Settings* → *Torrents* → *Discovery*).

**Comment by RozeDoyanawa** [comment]
@erengy Thanks for the .se tips, works for me now too.
@reconman I'm not using any VPN.
