### ISSUE TITLE
[NO SYNC] Update Error - HTTP error #7

### ISSUE THREAD

**Issue by Altaruss** [erengy/taiga#238]
Every time I launch Taiga, I got this error:
![1](https://cloud.githubusercontent.com/assets/17614168/13491693/114b33c8-e134-11e5-935f-984ea73aee02.PNG)

Then, after clik "ok", I have this error at the bottom, and Tagai don't update anything on MAL
![2](https://cloud.githubusercontent.com/assets/17614168/13491745/73687ade-e134-11e5-9b0d-8957d151f737.PNG)

Hope you will find a solution.
If you need more infos, ask me.

[Taiga.log.txt](https://github.com/erengy/taiga/files/156580/Taiga.log.txt)
![3](https://cloud.githubusercontent.com/assets/17614168/13491780/b7527286-e134-11e5-86b4-1ba0e78b5746.PNG)

**Comment by saulens22** [comment]
Does it sync your list? Can it search for anime? If not, something is blocking Taiga's access to the Internet. Try checking firewall settings.

**Comment by Altaruss** [comment]
Does it sync your list? Can it search for anime?

**Comment by Altaruss** [comment]
Ok, it was the Firewall, setings change without my concent...

If you're using Bitdefender Firewall:
Add a rule for Taiga.exe
In "Adapters", make sure you got this:
> Network Type to Home/Office
> Stealth Mode to Off
> Generic to Yes    => This was on "No" and blocked taiga for me

Thx for the awnser
