### ISSUE TITLE
Now Playing won't recognize VLC Media Player.

### ISSUE THREAD

**Issue by Bloodclad** [erengy/taiga#239]
Hey, so Now Playing won't recognize VLC when playing. I have had this issue for quite a while, but I paid it no mind since it's nothing major and I thought maybe I screwed something up. However, after formatting my drive and installing a clean copy of windows, the problem persisted so I thought it would be wise to let you know.
Info and what I have tried so far:
-Taiga is cleanly installed. I backed no data up, from my previous installation.
-Recognition Options: "Ignore files outside of library folders"  is unchecked, "Media Player Detection" is enabled, VLC Media Player and Windows Media Player are both checked.
-Windows Media Player is recognized but VLC is not.
-Tried running Taiga as Admin but to no avail.

PS: I really love Taiga and I could never imagine life without her!

**Comment by erengy** [comment]
Hey there. I just checked VLC 2.2.2 and had no issues with recognition. Could you tell me:

- Which OS are you on?
- Which version of VLC do you use? Is it a nightly build?
- Did you try disabling streaming media detection, if it's enabled?
- Could you give an example path and filename (e.g. `D:\Anime\Toradora\Episode 1.mkv`) that Taiga's unable to detect? Is this file located on a network drive rather than your computer?

**Comment by Bloodclad** [comment]
Hey, thanks for replying and sorry for my being late, my hands are full these days. Okay so,

1) OS: Windows 10 Pro. 32-bit
2) VLC Version: 2.2.2 Weatherwax. I'm not sure if it's a nightly though, I just downloaded the latest from their website
3)Streaming Media Detection is disabled.
4)The drive is a local one, partitioned into a C:\ and D:\. Taiga is installed on (C:) Drive, Anime are located on (D:). Example path: 
D:\Videos\Anime\Boku dake ga Inai Machi\Boku Dake ga Inai Machi - 09[720p].mkv

**Comment by wiiaboo** [comment]
Depends if the filename is shown in the window name. For some players taiga users file handles so for those it'd work even if there's no window name, but in the case of VLC taiga maybe only checks the window name.

**Comment by erengy** [comment]
> I don't understand how the skin affects recognition though :confused:

This was due to the fact that VLC gives its skinned windows a different class name. Taiga uses these names in order to detect running media players.

You can now replace your `Taiga\data\media.xml` with [this one](https://github.com/erengy/taiga/raw/master/data/media.xml) and it should work.

**Comment by Bloodclad** [comment]
> You can now replace your Taiga\data\media.xml with this one and it should work.

Yes! It worked. Many thanks for your time and help!
