### ISSUE TITLE
torrent filter for old anime in plan to watch to download

### ISSUE THREAD

**Issue by amboris** [erengy/taiga#250]
is there any way to make or torrent filter that search and select animes in plan to watch but is not aired anymore? currently i get only animes selected to download that are airing right now but dotn get older one.

cant find this feature. and somehow i get less search results then directly on nyaa.se.

**Comment by erengy** [comment]
> select animes in plan to watch but is not aired anymore

Like this?

![torrent-filter](https://cloud.githubusercontent.com/assets/1078430/14482196/e9acffd4-0142-11e6-9561-20cf7f7d1cc2.png)

> somehow i get less search results then directly on nyaa.se

This might be because of the feed you use. Quoting myself from the [FAQ page](http://taiga.erengy.com/#support):

> **Why can't Taiga find some torrents?**

> The default RSS feed URLs for Nyaa use the "English-translated anime" category (`cats=1_37`) and "Trusted only" filter (`filter=2`). By modifying these values (e.g. `filter=0`) via *Settings → Torrents → Discovery*, you can see more releases on the Torrents page. Check out Nyaa's website for other values.

**Comment by amboris** [comment]
![0](https://cloud.githubusercontent.com/assets/16787537/14487158/50c0af36-0161-11e6-9b04-1f0e93799b53.jpg)
![1](https://cloud.githubusercontent.com/assets/16787537/14487159/52bf12a0-0161-11e6-8d22-f68c3c3325bf.jpg)
![2](https://cloud.githubusercontent.com/assets/16787537/14487160/546fdb70-0161-11e6-8689-72c49482ffc2.jpg)
![3](https://cloud.githubusercontent.com/assets/16787537/14487161/56c41c56-0161-11e6-90f1-e0d9ba7e5e30.jpg)
![4](https://cloud.githubusercontent.com/assets/16787537/14487163/5846d712-0161-11e6-9c51-140478647a80.jpg)
![5](https://cloud.githubusercontent.com/assets/16787537/14487165/597f9ccc-0161-11e6-97be-192c42e10a02.jpg)
![6](https://cloud.githubusercontent.com/assets/16787537/14487167/5acb48c4-0161-11e6-99ab-1f32c75d0f8a.jpg)

i have theise setting. but filter wont select. but i can manual search and it finds.
only problem solfed are the missing torrents by disabling filter in the feeds

**Comment by erengy** [comment]
It's not possible for Taiga to search for older torrents automatically. When you hit the *Check new torrents* button (or when Taiga does it automatically every 60 minutes), it simply uses the given RSS feed to fetch the latest releases. Filters are applied on these results; they're not used for searching.

Also note that your "Select airing anime in plan to watch" and "Search plan to watch" filters are a bit messed up. You may import the following string via the *Import Filters* button on *Settings → Torrents → Filters*:

```
VEFJAQUAMS4yLjNpAeMFeJy1lMtqwzAQRdfNVwyCLEMeULqJs+oHFNp9mFjjZGAsuXo45O8r23m1YIc2zUqLmbk6947QkgOVgHlgazLlSSgPCkoM+S5TaA4KbNXVNBUYJRXJ4EZIZ6pA8aTAYEmZem9HIY/OkQlygH2jwWarVqOnZW6N5kYHUluZGjIVPbm1Dxiiby4hh8G6TNFnTLIKapSYZOcKpqvRctpgpnOQVmSINrj4ExbZJUBAwyUBG6gEDQTbofdxlxTwNvei5b7D+PMjjRds2O9IPzKB+SMT0OxzdLrvpTZtNQbqSeG1m062NVyawdgwYTMR9qFL5L6nO/s7/9AKT/DtiqgzgTWyNL1AFXuryfehH+trE8sNuWt6oTP5+Kg97l+h2BxlfVI73z8Qx0froTeRylHRAP0+kLd2Ena83U0ceSuxRS1YbsdQsya7vkwN8L8sZtW/8X/7Oo8GDO2hJufTyG3uru8adxt6Ps0vnAkKOA==
```

**Comment by amboris** [comment]
i guess closed then
