### ISSUE TITLE
is there a way to synch MAL & Hummingbird anime list?

### ISSUE THREAD

**Issue by amboris** [erengy/taiga#251]
i just made a hummingbird account and its empty when i try to sync it in taiga with the existing anime list from mal.

it would be ultra troublesome if i need to at those 1000 anime manually.

**Comment by erengy** [comment]
As it's mentioned in both the Settings dialog and the FAQ page, Taiga cannot synchronize between services.

If you'd like to copy your list from MyAnimeList to Hummingbird, you can use the MAL Import feature located in [Hummingbird's account settings](https://hummingbird.me/settings).
