### ISSUE TITLE
[bug] filter don't select items sometimes when torrents are available 

### ISSUE THREAD

**Issue by amboris** [erengy/taiga#252]
it happens quit often that filters don't select some times when torrents are available. has this something to do with feeds that use http://tokyotosho.info/?

![0](https://cloud.githubusercontent.com/assets/16787537/14494267/3852a354-018a-11e6-9948-9fe896cc661e.jpg)

**Comment by erengy** [comment]
You don't have any filter that selects the anime in your Currently Watching list, so no surprises here.

You need to either enable the "Select currently watching" filter (which was included in the ones I sent you in the previous issue), or create individual filters for each anime you want.
