### ISSUE TITLE
[Feature Request] Anime stream detection API

### ISSUE THREAD

**Issue by sarcasmloading** [erengy/taiga#254]
Hello! I love Taiga and use it every time when I'm watching anime.

I do have a suggestion.
I saw other issues (issue #77, issue #75, and issue #155 and issue #184)

Now I know you might be sick of seeing "oh, pls add x.com to the stream list", but this suggestion is different.
Is it possible for there to be an API or something else (like YAML (used in the Hapu app) or JS) so we can add our own streaming sites. The Hapu mac detection app makes a good job of this (https://github.com/inket/HAPU-rules/blob/master/rules.yaml).
One other thought backed this up. In the other requests you said "Taiga only supports **legal** streaming sites" (something along the lines of that). If you only want **legal** anime, why is the Torrents section there!?!?! That's illegal!

**Comment by erengy** [comment]
This suggestion was the premise of #184:

> So instead can you let us add our own extension to dectect streaming site in taiga?

To which I replied:

> Sorry, I don't plan on adding support for unofficial streaming sites anytime soon. **This includes indirect support as well.**

This is not just about whether they're illegal or not. Apart from the ease of access they provide, most of the unofficial streaming sites are inferior to their alternatives in every other way.

> I was once planning to add a feature that makes the list customizable, so that people could add the streaming sites they use, on their own. But adding a feature to Taiga usually means that I encourage people to use it. I feel like I don't want to do that, especially when there are better alternatives (e.g. legal streams for what's available, torrents or XDCC for the rest).

From the FAQ:

> Note that the current stance Taiga takes is that it only supports official streaming sites. There are ethical, technical, personal and strategic reasons for this.

Last year, some people have gone as far as harassing me or offering me a couple of bucks for this feature. Please, just... no.
