### ISSUE TITLE
Torrent download error: Invalid content type: text/html

### ISSUE THREAD

**Issue by amboris** [erengy/taiga#255]
since some time i got this message when i try to download torrents from taiga:
"Torrent download error: Invalid content type: text/html"
its not possible to "rightklick->download torrent" either.

but strangely if you search the torrent in the search torrent bar and select the torrent there you can download.

can you pls look in the code, maybe taiga doesn't clear the cash( in taiga) when they add new torrent in their feeds.

**Comment by erengy** [comment]
Related to #29, #124 and #228.

This is an issue with some servers that return `text/html` (or another MIME type) as the `Content-Type`, where they're supposed to return `application/x-bittorrent` instead. Basically, Taiga says, "I would like to have this .torrent file, please", but the server responds, "Here, have this HTML page".

Taiga does allow some [invalid MIME types](https://github.com/erengy/taiga/blob/620ccfcae6a383ee22adddc43082376cbcf5874d/src/track/feed_aggregator.cpp#L376-L382), but `text/html` isn't one of them. That said, I'm [planning](http://myanimelist.net/forum/?topicid=214501&show=850#msg45703892) to add a check for the `Content-Disposition` field, which should resolve the issue for *some* servers. Ultimately, it's the servers' responsibility to describe the media types properly.
