### ISSUE TITLE
Duplicate torrents selected by auto-match

### ISSUE THREAD

**Issue by sarcasmloading** [erengy/taiga#261]
The torrent auto-matcher picks up duplicates of the same episode (i.e selects Anime ep1 480p, Anime ep1 720p FanSub1, Anime ep1 1080p FanSub2).
This is really annoying as I have it set to auto-download.
Some say that setting the default fansub group to a certain one, but that doesn't stop it from picking up the same episode in a different quality.

**Comment by erengy** [comment]
Do you have the default "Prefer high-resolution files" filter enabled? When there is a 720p release of a fansub group, it should discard non-720p releases of the same group.

If you want more control, you may specify a video resolution in the same filter that you specify your fansub group preference for an anime.
