### ISSUE TITLE
Add support for Crunchyroll HLS Player

### ISSUE THREAD

**Issue by Californ1a** [erengy/taiga#269]
There's a chrome extension that replaces Crunchyroll's flash player with an HTML5 one:
https://chrome.google.com/webstore/detail/cr-hls-player/aeajdeepnjjdekpbicjhfldagkjndjid

It streams so much better than that old flash player, doesn't ever lag or buffer, but it doesn't load the next episode's page when you move to the next episode - it stays contained within the player itself. Would it be possible to have the recognition support this?

**Comment by Diablofan** [comment]
Taiga **doesn't care what the player is** on the page. Taiga only looks at two sources on the page. The _Page URL_ to determine what source the video is coming from: eg www.crunchyroll.com, and the _page title_ to identify what show/episode is playing.

After a quick test installing the plugin and using Crunchyroll trying Kiznaiver episode 5, it recognized it just fine without modifications needed to taiga. Just make sure you have streaming sources enabled in the settings and you're golden.

**Comment by Californ1a** [comment]
Yeah the problem is that when this player auto-starts the _next_ episode (if you have "auto play next episode" enabled in the extension's options), it doesn't go to that episode's page - it stays on the same page as the previous episode, so the page title and page url aren't changed, only the video stream is.

**Comment by Diablofan** [comment]
That's a problem with the extension then unfortunately. File a bug report with the dev of the extension and ask if they can change the page title when the video changes and then it should work fine with Taiga then.
