### ISSUE TITLE
Taiga freezes when playing an episode, not updating count afterwards

### ISSUE THREAD

**Issue by szernex** [erengy/taiga#271]
About 2 weeks or so ago I started experiencing a weird issue. I didn't change any of the settings, this basically started happening over night.
I'm using MPC-HC 64bit version 1.7.10 (d911f14) and the latest Taiga version (1.2.3). When I select a show and chose an episode to play or use the Play Next feature it starts MPC normally, but then Taiga just freezes up for as long as MPC is running. As soon as I close MPC Taiga starts working again but it won't update the episode watched count. This also happens when I manually start MPC to watch an episode.

**Comment by erengy** [comment]
I believe that this issue is the same as #270, so downloading [this build](http://taiga.moe/latest.html) should fix it for you.

**Comment by szernex** [comment]
Ah, sorry, didn't see that issue I guess.
Yes, that build does indeed fix the problem, thanks!
