### ISSUE TITLE
Crashes when pulling up Spring 2016 Season List

### ISSUE THREAD

**Issue by prnceichiro** [erengy/taiga#275]
As the title implies: when on Season tab, if you select Spring 2016 anime list the application is crashing. Even after restart.

**Comment by prnceichiro** [comment]
![screenshot (or animation)](https://cloud.githubusercontent.com/assets/20133405/16350364/e44b903c-3a90-11e6-8185-5cbfb6135eaf.gif)

**Comment by erengy** [comment]
For now, clicking on *Help* → *Check for updates* should work. Taiga will report that there are no updates available, but selecting a season will no longer cause a crash.

I'm closing this issue because the underlying cause is the same as in #273.
