### ISSUE TITLE
Taiga freezes when media player is open and playing

### ISSUE THREAD

**Issue by link2110** [erengy/taiga#280]
As title says, when I'm playing an ep, it freezes and can't be used, until the media player is closed. Then it goes back to working fine. However it doesn't detect that I just played EP whatvever of <anime> , so I have to manually update the list. I'm running V1.2.3 on Win 7, using MPC-HC with SVP to play.

**Comment by erengy** [comment]
This is likely the same issue as #270 and #271. Downloading [this build](http://taiga.moe/latest.html) should fix it for you.

**Comment by link2110** [comment]
http://i.imgur.com/2Gbzn0T.png

All icons/colours are missing. "Scan avaliable episodes" does not work. While it does not freeze, it doesn't detect the anime playing, despite selecting the correct folders as library folders. I haven't tested any more than that yet.

**Comment by erengy** [comment]
Did you read the instructions?

> This is not an installer; it's just the application executable. You need to copy the file inside your installation directory, replacing the old `Taiga.exe`.

**Comment by link2110** [comment]
Well that would explain it :laughing: Thanks! Works fine now.
