### ISSUE TITLE
Crunchyroll recognition fails with more than one Chrome window open

### ISSUE THREAD

**Issue by Californ1a** [erengy/taiga#281]
Even if all the other windows or tab are things other than Crunchyroll (only one CR tab), just having another Chrome window open will cause Taiga to be unable to detect a new episode after the initial episode detection. If I merge all my tabs from various windows onto a single Chrome window, then the current playing episode is immediately detected, but it cannot detect when I move on to the next episode if I have more than one Chrome window open.

It's extremely aggravating to have to merge all my windows or close/reopen Taiga whenever I go to the next episode, especially since I have multiple monitors and almost 100% of the time have more than 1 or 2 Chrome windows open, for each monitor.

This is with Taiga 1.2.3 and Chrome 51.0.2704.106 m (64-bit)

**Comment by erengy** [comment]
Closing this issue since we already have #227.
