### ISSUE TITLE
Momokuri

### ISSUE THREAD

**Issue by Zenithtb** [erengy/taiga#284]
Momokuri is being released in two episodes per release. 

It's listed as 26 episodes, but really it's 13

This means in Taiga every other episode is 'missing', and you have to manually increase the episode each time...

![untitled](https://cloud.githubusercontent.com/assets/13133658/17068683/b653a41c-5052-11e6-915f-ba3de8e9d978.png)

This is not high-priority  :)

**Comment by wopian** [comment]
No, 26 is correct. The episodes are being aired back-to-back.

**Comment by Zenithtb** [comment]
Yeah - that's what I meant by two episodes per release.

It's just that Taiga expects a series to go up by one episode, and doesn't work with Momokuri as it goes (1+2) (3+4) (5+6) etc...

**Comment by kekstarter** [comment]
That's because you've added the version that has been difused online; the TV version does not have this problem: 
![taiga_2016-07-24_18-04-30](https://cloud.githubusercontent.com/assets/10001934/17084851/23b4a656-51c9-11e6-837c-541aab02274b.png)

If you want Taiga to detect Momokuri correctly, add "Momokuri (TV)" in your list, not the ONA one.

**Comment by wopian** [comment]
@kekstarter that TV version is also wrong, it's airing on TV as two separate episodes.

Using the naming scheme for double episodes, Taiga will show it as having episode 1 & 2 available. E.g: Momokuri (TV) - S01E01-E02

**Comment by Zenithtb** [comment]
OK. Now I'm just confused. Looking at my original screenshot, what actions should I take to 'make it correct'?

**Comment by erengy** [comment]
I can't really do anything about the inconsistency. But there's a known issue in Anitomy where it's unable to parse multi-episode patterns such as `01+02` correctly, because `+` is considered to be a token delimiter.

For now, you may rename the files to read `01-02` instead of `01+02`.

**Comment by erengy** [comment]
> there's a known issue in Anitomy where it's unable to parse multi-episode patterns such as `01+02` correctly, because `+` is considered to be a token delimiter.

This issue is now fixed in erengy/anitomy@00c3f688de8fcc2fa74a146dc2d6849680ae6962.
