### ISSUE TITLE
[New streaming provider] Netflix support

### ISSUE THREAD

**Issue by OsaSoft** [erengy/taiga#288]
Recently Ive seen Netflix started stocking quite a bit of anime and even has some currently airing ones available, so I was thinking about the possibility of adding Netflix streaming recognition.

Ill probably try and look into how difficult to implement this would be and give it a try whenever I have the time to, but was wondering if more people would appreciate this.

Cheers.

**Comment by b0Stark** [comment]
As stated on the website, [http://taiga.moe/#support](http://taiga.moe/#support), under "Could you add support for other streaming sites?"

> As long as the site provides a consistent way to detect the anime title and the episode number in its URL or page title, it's possible. Some services such as Funimation, Hulu and **Netflix** aren't supported because it's technically not possible to detect the episodes this way.

**Comment by OsaSoft** [comment]
Well I guess that concludes my research into this, hah... cheers mate
