### ISSUE TITLE
MPV isn't detected when running from command line

### ISSUE THREAD

**Issue by MenacingMecha** [erengy/taiga#289]
When opening MPV normally, Taiga behaves as expected, however when playing the same file by launching from the command line, Taiga doesn't register anything as playing

![explorer_2016-07-29_18-18-32](https://cloud.githubusercontent.com/assets/19494722/17257235/19604bbc-55b9-11e6-874d-f019c86eb658.jpg)
![explorer_2016-07-29_18-21-47](https://cloud.githubusercontent.com/assets/19494722/17257307/62a0360c-55b9-11e6-9e4c-ad4957eb07c6.jpg)

**Comment by erengy** [comment]
I imagine that when you run the video from command line, the process that owns the file handle may end up being different than the one that owns the window.

That said, I did try launching mpv from ConEmu now, but Taiga was still able to detect the file.

In case it's related to security privileges, could you try running Taiga as administrator and see if you still have the same issue?

**Comment by MenacingMecha** [comment]
It will detect from command line if Taiga is ran as administrator, thank you.
