### ISSUE TITLE
Torrents download as invalid files

### ISSUE THREAD

**Issue by ghost** [erengy/taiga#29]
Attempting to download the following torrent: http://www.nyaa.se/?page=download&tid=589401
(Details from Tokyo Toshokan here: http://tokyotosho.info/details.php?id=807835 )
from Taiga causes the following error in UTorrent:
![image](https://cloud.githubusercontent.com/assets/7130743/3952708/f7f65098-26e4-11e4-92cc-d9e17ef0092d.png)

This happened as well with this one: http://www.nyaa.se/?page=download&tid=588612
(TT details here: http://tokyotosho.info/details.php?id=807305 )

Probably happened with others, not sure.

**Comment by erengy** [comment]
A relevant [issue](http://myanimelist.net/forum/?topicid=214501&show=540#msg38066597) has appeared:

>> When I try to download a torrent from project-gxs I get the error: Torrent download error: Invalid content type: application/octet-stream
>> https://i.imgur.com/Gf65tTp.png
>> This happens only with this group.
>> The RSS feed for checking new releases is from tokyotosho.
  
> Looks like the server that is located at `ws.cubbyusercontent.com`, which serves the .torrent files for project-gxs is misconfigured. It's supposed to return `application/x-bittorrent` as the `Content-Type`, but it returns `application/octet-stream` instead. Taiga [checks](https://github.com/erengy/taiga/blob/4a9b87d1530ab2e4e0dad5fc048bc7d044fbda22/src/track/feed.cpp#L405-L411) against this to avoid downloading invalid .torrent files.

I wonder if this is a common issue and I should allow `application/octet-stream`.

**Comment by gamesbe** [comment]
Noticed this issue today (Using the latest build)
