### ISSUE TITLE
[Suggestion] Add Webtorrent Support to Stream Torrent Directly

### ISSUE THREAD

**Issue by Adyel** [erengy/taiga#292]
Webtorrent is great for P2P video streaming. It works great without any hassle. It's a open source project with promising future. Please, Add support for Webtorrent . Currently Taiga doesn't detect Webtorrent. If you can, please consider adding similar mechanism to stream directly from Taiga.

Webtorrent Info : 
https://github.com/feross/webtorrent
https://webtorrent.io

Here is a sample How it Looks.  This is Streaming Instantaneously without waiting for Download to complete

![screenshot 16](https://cloud.githubusercontent.com/assets/4653623/17384525/a509fafc-59fe-11e6-8ed2-00b2effdbacc.png)

@erengy  This tag is used to get your attention :)

**Comment by erengy** [comment]
Let's see if this works:

1. Download the [latest build](http://taiga.moe/latest.html) of Taiga.
2. Replace your `Taiga\data\media.xml` with [this one](https://dl.dropboxusercontent.com/u/2298899/Taiga/temp/media.xml).
3. Run Taiga.

**Comment by Adyel** [comment]
It works. Thank You.  :100: / :100:
