### ISSUE TITLE
Compile libcurl

### ISSUE THREAD

**Issue by Stonedestroyer** [erengy/taiga#294]
Hello I can't seem to compile libcurl as there is no solution files and the wiki is outdated. 
https://github.com/erengy/taiga/wiki/How-to-Compile

**Comment by erengy** [comment]
Hi there. There is no solution file to compile libcurl, you need to use the command line for that. I now checked it with libcurl 7.50.1 just in case, and the instructions listed at the wiki page are up to date.

**Comment by Stonedestroyer** [comment]
On step 2, Open Visual Studio Command Prompt and go to <curl>\winbuild\.. Do i just go to curl and do make from there?

**Comment by erengy** [comment]
Here's what I personally do:

1. Go to `E:\Development\Libraries\curl-7.50.1\` from Windows Explorer.
2. Hold down <kbd>Shift</kbd> key and right-click on the `winbuild` directory, select *Open command window here*.
3. Enter `"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat"` (with the quotation marks).
4. Enter `nmake /f Makefile.vc mode=static RTLIBCFG=static VC=14`.

**Comment by Stonedestroyer** [comment]
Oh alright for some reason the libcurl was not a link for me so I thought it was included in Taigas repository in curl. My bad!

**Comment by tophf** [comment]
@erengy, `MACHINE=x86` parameter is missing in taiga\deps\build.bat which makes libcurl build for x64 on a 64-bit OS thus making Taiga build fail.
