### ISSUE TITLE
Suggestion: Minimize to tray and startup at boot

### ISSUE THREAD

**Issue by darknlight55** [erengy/taiga#297]
Taiga works great for me on windows 10, my only issue is that it doesn't have the option to startup at boot and minimize to tray at boot option. It has a icon in the tray when it's launched but exiting the app closes the app completely and removes the icon from tray. It would be nice to have the program running in the background in case I watch a show and forget to turn it on to update MAL.

**Comment by erengy** [comment]
Did you enable the relevant options at *Settings → Application → General*?

**Comment by darknlight55** [comment]
Oh wow... ya that would probably solve it. Thanks for the help.
