### ISSUE TITLE
Suggestion: Anime folder scanner

### ISSUE THREAD

**Issue by darknlight55** [erengy/taiga#298]
So taiga works flawlessly, but before I learned about MAL updater or Taiga I had to update myanimelist by hand. _I know archaic right?_ So because I went a few seasons without updating MAL I now have a folder full of anime I've watched 600+ GB worth to be exact.. I could go in by hand and play each show and let taiga update my list which would be faster then doing it in the browser, but what would be nice is if their was some way to scan the folder and list any show not already in MAL under plan to watch.  

Thanks

**Comment by erengy** [comment]
Closing this, since we already have #101.

[This comment](https://github.com/erengy/taiga/issues/101#issuecomment-94785054) of mine describes how the feature would work in practice.
