### ISSUE TITLE
Add started watching

### ISSUE THREAD

**Issue by Stonedestroyer** [erengy/taiga#302]
Is it possible to add the started watching information from MAL, when you edit an entry in MAL you have started watching and finished watching. Can we add that as a column or does API not parse that?

**Comment by erengy** [comment]
Do you mean these dates?

![mal-dates](https://cloud.githubusercontent.com/assets/1078430/18615510/566dfbb0-7db1-11e6-94d9-737eac3a2879.png)

**Comment by Stonedestroyer** [comment]
Yes, if possible. I know they exist at edit selection in Taiga so I know they are there, but I just want them at the view column menu as well so it can be sorted easier.

**Comment by erengy** [comment]
It's certainly possible. We already have an open issue about this at #150 though, so I'll be closing this one.
