### ISSUE TITLE
Authorization failed

### ISSUE THREAD

**Issue by MarcusGHub** [erengy/taiga#306]
I keep seeing _Authorization failed (invalid username or password)_, but I am 100% certain that they are correct. This started happening after I change my username and password for my MAL account. I updated the info in Taiga but it's not reflecting the change.

**Comment by erengy** [comment]
May be related to #170.

**Comment by MarcusGHub** [comment]
I've subscribe to the thread.

**Comment by erengy** [comment]
I'm closing this issue, but let me know if your problem is unrelated to having `<` or `:` in your password.

**Comment by MarcusGHub** [comment]
I do have `<` in my password.

**Comment by MarcusGHub** [comment]
I changed that character to something else, so it's now resolved.
