### ISSUE TITLE
Taiga shows wrong score for anime, when opening it from list (ex. plan to watch)

### ISSUE THREAD

**Issue by Atrboomy** [erengy/taiga#309]
Version: 1.2.3
Service: MyAnimelist only
When I open anime info card by double-clicking it in my list, card shows wrong score

![image](https://cloud.githubusercontent.com/assets/12371550/18858595/8ef5146a-8486-11e6-98ed-1144d9677915.png)

But, when I use search by keyword and then open anime info card, score is updated
![image](https://cloud.githubusercontent.com/assets/12371550/18858629/e447c174-8486-11e6-8bfc-b93921a7ed52.png)

One more example:
![image](https://cloud.githubusercontent.com/assets/12371550/18858682/4fd8a1ce-8487-11e6-91f1-eeb646c9d446.png)

**Comment by erengy** [comment]
It's the old score rather than the wrong score.

Unfortunately, MAL's API doesn't provide average scores when Taiga retrieves your list. They are included in search results though, which is why you see it updated after a search. You can also hit <kbd>F5</kbd> at Anime Information dialog to refresh the score.

This is yet another thing MAL has to address in their next API (which [isn't coming](https://myanimelist.net/forum/?topicid=1543851&show=100#msg47490483) anytime soon).

**Comment by Atrboomy** [comment]
Did you considered quering search by title when opening info card for score update?
Or such "workaround" is too heavy and not worth itself?

**Comment by erengy** [comment]
This is [already the case](https://github.com/erengy/taiga/blob/81518feb1b971e91b5ef5262f24ff939796f3eef/src/ui/dlg/dlg_anime_info_page.cpp#L198-L202). Although, to avoid connecting to MAL every time you open the dialog, Taiga only does so [when the information is "old enough"](https://github.com/erengy/taiga/blob/81518feb1b971e91b5ef5262f24ff939796f3eef/src/library/anime_util.cpp#L112-L141).

**Comment by Atrboomy** [comment]
Thanks
Btw, I could be wrong, but I added "Zutto mae..." a long time ago, and it had 9.50 score only first month or so, so it should updated itself (1 week update period for "Finished airing", if I understood correctly)
I will check on other titles.

**Comment by erengy** [comment]
That's an actual issue: Taiga [updates](https://github.com/erengy/taiga/blob/81518feb1b971e91b5ef5262f24ff939796f3eef/src/library/anime_db.cpp#L296) the last-modified time of the anime when it encounters new series information. However, when that information comes from `malappinfo.php` (i.e., user's anime list), it lacks the score. Then, Taiga thinks it has up-to-date information, when that information is partially outdated.

There are ways to work around this, but I've avoided them so far to not make things more complicated.
