### ISSUE TITLE
No cover in Anime Information

### ISSUE THREAD

**Issue by EngelEatos** [erengy/taiga#310]
First of all - Great app!

I have a problem with the "Anime Info"-panel. It don't display the cover. No matter which anime.

![screenshot_1](https://cloud.githubusercontent.com/assets/6306810/19013711/0d10059e-87d9-11e6-852d-fbd4e5e4db8f.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/6306810/19013712/0d329e10-87d9-11e6-96da-b31e3f0c4871.png)

My second problem is the "Seasons"-section. Taiga cannot load the anime season data.
![screenshot_3](https://cloud.githubusercontent.com/assets/6306810/19013723/4bb1b84c-87d9-11e6-922f-5b57a59d2c77.png)

**Comment by erengy** [comment]
It looks like Taiga's unable to access its own directory. Where do you have Taiga installed?

Note that installing under protected directories such as `Program Files` may cause issues if you have User Account Control enabled on your system. Generally, it's a good idea to let Taiga use the default one (e.g. `C:\Users\EngelEatos\AppData\Roaming\Taiga`).

**Comment by EngelEatos** [comment]
Thank you very much!
You were right. I installed Taiga to `C:\Program Files\Taiga`.
It works if I execute Taiga as admin.
Thank you for your help!
