### ISSUE TITLE
"HTTP error #6: Couldn't resolve host name (8;URL=)" when checking Nyaa for torrents

### ISSUE THREAD

**Issue by LordZounds** [erengy/taiga#311]
Suddenly, started today, I'm no longer able to check Nyaa for torrents (neither with checking for new episodes nor searching for releases of a show)

Other RSS feeds work fine, just Nyaa seems to be the problem.

For the first time today, I noticed some DDoS protection on Nyaa, which may be causing it? (It's possible that it's always been there and I just never noticed it though)

**Comment by subnet-** [comment]
Nyaa now seems to have cloudflare and it seems they're offline for today.

**Comment by LordZounds** [comment]
This is something that should fix itself then whenever that goes back up?

**Comment by erengy** [comment]
This seems to be the same issue as #236.
