### ISSUE TITLE
"HTTP Error #6: Couldn't resolve host name"

### ISSUE THREAD

**Issue by szernex** [erengy/taiga#314]
Started happening shortly before updating to 1.2.4 and still persists. When checking for new torrents on nyaa.se I keep getting this error, though it seemingly randomly worked a few times over the past few days. 

http://puu.sh/rD0Zf/caab24f0a4.png
http://puu.sh/rD0ZR/bee8abd426.png

I can access nyaa.se just fine and the queries also return the expected RSS feeds when opened in a browser.

**Comment by erengy** [comment]
Hi, please see #313, #311 and #236 for more information.
