### ISSUE TITLE
LAV Filter Megamix's 64-bit MPC-HC is not detected

### ISSUE THREAD

**Issue by 4naxagoras** [erengy/taiga#315]
Media recognition doesn't work as a whole. Nothing shows up on Now Playing, neither does the tray popup for media not recognized come out and, naturally, Taiga doesn't update the episode number on closing the media player.

I'm using the MPC-HC installed from the 64-bit LAV Filter Megamix acquired from imouto.my's website:

https://imouto.my/tutorials/watching-h264-videos-using-compute-unified-device-architecture-cuda
https://imouto.my/download/lav-filters-megamix-x64/

As far as I remember, everything worked fine with Haruhichan's (now outdated) KCP build.

My settings are exactly as shown on imouto.my's tutorial, except my MadVR config. NVIDIA CUVID is enabled in LAV Video Decoder.

**Software used:**
Windows 10 Enterprise N 2015 LTSB 64-bit
MPC-HC (Nightly, 64-bit) 1.7.10.252 (e91b41e) - Build Date Jul 8 2016 01:12:35
LAV Video Decoder 0.68.1.31-git
LAV Audio Decoder 0.68.1.31-git
LAV Splitter 0.68.1.31-git
madVR v0.90.24

**Comment by erengy** [comment]
What's the name of the MPC-HC's executable file? If it's something different than `mpc-hc64.exe`, [adding](https://github.com/erengy/taiga/blob/c2ba264fae23baa95419faa266db3e0053646584/data/media.xml#L175-L178) it to Taiga's `data\media.xml` should work.

**Comment by 4naxagoras** [comment]
You are correct, it was also iris.exe for the 64-bit version, and adding
`		<file>iris.exe</file>`
`		<folder>%ProgramFiles%\LAV Filters\x64\mpc-hc\</folder>`
`		<folder>%ProgramW6432%\LAV Filters\x64\mpc-hc\</folder>`
to media.xml in %appdata%\Roaming\Taiga\data\media.xml fixed it

Now it looks like this:

	<player>
		<name>Media Player Classic Home Cinema</name>
		<enabled>1</enabled>
		<visible>1</visible>
		<mode>0</mode>
		<class>MediaPlayerClassicW</class>
		<file>mpc-hc.exe</file>
		<file>mpc-hc64.exe</file>
		<file>mpc-hc_nvo.exe</file>
		<file>mpc-hc64_nvo.exe</file>
		<file>iris.exe</file>
		<folder>%ProgramFiles%\LAV Filters\x64\mpc-hc\</folder>
		<folder>%ProgramW6432%\LAV Filters\x64\mpc-hc\</folder>
		<folder>%ProgramFiles%\K-Lite Codec Pack\Media Player Classic\</folder>
		<folder>%ProgramW6432%\K-Lite Codec Pack\Media Player Classic\</folder>
		<folder>%ProgramFiles%\K-Lite Codec Pack\MPC-HC\</folder>
		<folder>%ProgramW6432%\K-Lite Codec Pack\MPC-HC\</folder>
		<folder>%ProgramFiles%\K-Lite Codec Pack\MPC-HC64\</folder>
		<folder>%ProgramW6432%\K-Lite Codec Pack\MPC-HC64\</folder>
		<folder>%ProgramFiles%\Media Player Classic - Home Cinema\</folder>
		<folder>%ProgramW6432%\Media Player Classic - Home Cinema\</folder>
		<edit mode="2">Media Player Classic</edit>
		<edit mode="2">MPC-HC</edit>
	</player>

Renaming iris.exe to mpc-hc.exe also worked, but broke Taiga's "Play Last/Next episode" because of what I assume to be windows no longer finding iris.exe, which was set as the default media player. Everything seems to work fine if you open media directly from inside MPC-HC, though.
