### ISSUE TITLE
Conversion to standalone libraries

### ISSUE THREAD

**Issue by erengy** [erengy/taiga#316]
Similar to my effort in v1.2 to separate the anime video filename parser, I'm planning to continue modularizing Taiga in v1.3. This will not only result in a simpler codebase for Taiga, but it may benefit other projects as well ([@erengy/anitomy](https://github.com/erengy/anitomy) is being used by at least three other applications).
- [x] **Media detection:** [@erengy/anisthesia](https://github.com/erengy/anisthesia) will take care of detecting running media players and web browsers, as well as retrieving information regarding the currently playing video (i.e. `base/process.cpp`, `track/media.cpp`, `track/media_stream.cpp`, `data/media.xml`). It's going to be Windows-only for a while, but the plan is to add Unix stuff too later on.
- [ ] **Advanced Title Formatting:** [WIP] [@erengy/atf](https://github.com/erengy/atf) will replace our crude implementation that currently resides in `taiga/script.cpp`. It will fix some long-standing bugs and provide more features such as conditional sections and multi-line strings. The idea is that the application provides the necessary data for custom fields (e.g. `%title%`, `%episode%`), and the library takes care of everything else. We may eventually switch to a more advanced interpreted scripting language such as Lua, but not yet.
- [x] **Semantic Versioning:** I'll just move `base/version.cpp` to [@erengy/semaver](https://github.com/erengy/semaver) and write some tests for it.
- [x] **Windows API:** I'm moving `win/*` to its own repository at [@erengy/windows](https://github.com/erengy/windows). We're going to continue using this until v2.0, for the most part.
- [ ] **libcurl wrapper:** ~I'm currently evaluating [@whoshuu/cpr](https://github.com/whoshuu/cpr) as a replacement.~ If that doesn't work out, I may move my own interface (`base/http.h` and accompanying files) to a separate repository.

## Third-party libraries

- [ ] [boost](http://www.boost.org): It has lots of things that should have been in the standard library. In particular, we could at least make use of `algorithm`, `date_time`, `filesystem` and `optional` headers. However, I'm leaning towards using my own code along with C++17 headers instead, to avoid bringing in a huge dependency.
- [x] [date](https://github.com/HowardHinnant/date): We could possibly make use of this alongside `<chrono>`.
- [x] [fmt](https://github.com/fmtlib/fmt): This seems to be a nice little library that we can use to format strings throughout the application.
- [x] [json](https://github.com/nlohmann/json): I'm considering using this instead of [JsonCpp](https://github.com/open-source-parsers/jsoncpp).

Please let me know if you have any ideas or suggestions!

**Comment by wiiaboo** [comment]
Wasn't sure if this warranted a separate issue:
Would it be possible to add something like https://github.com/stengerh/foo_tfsandbox?

**Comment by tomerghelber** [comment]
I would like to know why boost is "a huge dependency".
Because there is a lot of code? We should be happy.
Because its big? The compiler should be able to cut out the staff that aren't used.
Thanks.
