### ISSUE TITLE
Updates not downloading

### ISSUE THREAD

**Issue by hagamablabla** [erengy/taiga#319]
When I check for updates, it takes me to the changelog of the new version. I click the download button, and then it tries to download it. However, it just fails and takes me back to the changelog. I'm currently using 1.2.3

**Comment by erengy** [comment]
If you've installed Taiga under a protected directory such as `Program Files`, User Account Control may be preventing Taiga from downloading the file properly. If that's the case, try running Taiga as administrator, or installing it to the default location (e.g. `C:\Users\hagamablabla\AppData\Roaming\Taiga`) instead. If you don't want to lose your settings and history, just take a backup of `Taiga\data` before uninstalling.

**Comment by KikunXyy** [comment]
I tried running as administrator. I still can't update! I even backed up my Data, uninstalled and tried to download from taiga.moe. But I'm getting blocked by my router, it seems. I can't access http://taiga.moe/download.php and using download managers like IDM just downloads the .PHP file instead.

**Comment by erengy** [comment]
@KikunXyy This kind of false flagging happens from time to time (see #159 and [this post](http://erengy.com/blog/false-positive) for the most recent one). There isn't much I can do to "fix" it, unfortunately. I've sent false-positive reports to Baidu, Bkav and McAfee; I'm now waiting for reply.

**Comment by hagamablabla** [comment]
Running as admin a few times got it to work eventually. Thanks for the help.
