### ISSUE TITLE
use of the filters that discard noit in list force selection to 720p and not 1080p

### ISSUE THREAD

**Issue by lordage** [erengy/taiga#323]
current filter export start

VEFJAQUAMS4yLjTNAcwJeJy1lUtLAzEQgM/6K0LAs/UBemgFpYgFPfhgFUSW2c20BrPJmkwq/fcmrVUrblu78bSHzHz5ZibJdiVhxaAkaXSPO1RYEmcVUPnc46AUZ6aerQkcgldhETUUCkWPk/XImYYK55lsr3Pc4SfbW93SaCFjIgsLFWrqcaylMwLzsRRocovOKB8j4hZogYwNMa8elONsDMoHasTVnO2ebHd3o2j4LvgK6Uqw4nfh57BPg23IG4U85rVAy472WznHnnz4BtKfdPWkUXcY+vDp258lsreYh2KVrfZVgXbBET8ddz4gO1PRXznKlKDyOQ3GIFW0WjKou2lzGwvf/Fw9noN2vnhip1pWuKrwkTW+XqJ5YayVYZNbX7jm8r1DmzsC8m7Z2Uw06O/VnsXwpiKHUmFeAuHI2Ml3sRBLIPWX2gzTWN8UJNCVVtY/D/NGLJK0eDr+iZIZtWJqBCPXRmQ9yNwj7fDnl7wAwabvDXvByZuxwq33OtGkXt6+02zQXPkfWf1B9pAMdnmdDHVzlZ0lg932k6Hur7JkrIdskE6skJSMdTHY62x6MQTGsHF43lZcD22ISc2UdNR0L9Z7wDtt/wD7bQEHbQGHC91+B6d7ZV8=

end

using 
source https://www.nyaa.se/?page=rss&cats=1_37&filter=2

i have attempted to select 1080p over 720p if both are there for the same anime but when i use any filter that involved
anime watching status is or not in list deactivate 
the ones selected always end up 720p even though 1080p are list 

![capture](https://cloud.githubusercontent.com/assets/1171715/19570449/132dcb02-96c8-11e6-9284-69725db1f0e3.PNG)

**Comment by myoblastic** [comment]
I can verify this, for me I first noticed it when Haikyuu Season 3 wasn't being downloaded in 1080p. The filter selects 1080p for some anime, and mysteriously fails to select it for others. 

**Exported filter list:** `VEFJAQUAMS4yLjToARsIeJzVlEtv2zAMgM/rr2AF9Bg08Vo0HeICe2DLLtvQ7rRhCBibcbjIkqeHi/z7Snb6WDE7DdIedjAEWyL1faSsCTsqATPHWqUiZ5uhyQWU6LJlKlCtBehqM0lxWY2OBJDCuaQ8Fc748KqwpFR8aKMBVQ73i0FpN2A1kGxdmOKSxMXBq0mmVc4xMZCkkpRLhbdkZtah8zbuSgadNqmgPx5l+FKj9GGXoYDji4PJcQQP4wvwX8dgaj2wRpZxLVDFVudku+g38zPlyzmZhwKS7uCPNrmPGol/5pE6Qzm7zXa3f09FvjcOnUWxIXXmumqyQC9dR0GumkjIvDEBTa7byrAq9uvgaAdYKXeERTYBsD1owAoqiQqcbtG7uEtyuJ076W7a08RPe8QrQ4t4bHbv0rcmEpZcLAeGrJa+YVuw3H5Ya85Jz+6j+ro2HA+rHQSe3rmfH1FZP/8FXwJifN7xWhtu2Dd9DBGjs9OT8+4O3BoVRvuqR2PKo74b5BksvhpUBT2if52cJc9A/zYmvPz0sgKX9OYHGQ0rNAhT/B22NB4+W1ohwxXxCp31j/1GycnwP/GbIq/W3h8eBpnIGga04ez/bZSMx+ej/Y3e67Lkvut57x9f0TXUZGyI2P6/t+se8hau42K+AVXGxE8=`

**Using RSS feed:** 
http://www.nyaa.se/?page=rss&cats=1_37&filter=0&term=%title%

**Image of Problem:** 
Here I disabled all my filters, and set one filter to select only 1080p files, which Taiga does successfully for all files except for Haikyuu. 
![taiga_2016-10-23_13-04-28](https://cloud.githubusercontent.com/assets/3443201/19627995/18531446-9922-11e6-86f0-5ab7b13be53e.png)

**Comment by lordage** [comment]
well after testing and working with filters i got it working better. i used to select before discarding but now it seems better to discard before selecting 

this filter works better and so far selects 1080 if the rss feed has one or 720 if not will report back after a few days 

Start

VEFJAQUAMS4yLjSHAUAHeJy1lFFPwjAQx5/1UzRNeCQOxMgDM9HwQiKJipm8Lcd6SGPXzvY6wrd3YyA8OCRuPi1L73793//uOpKEKYOEpNEhF9IlYAVnKVCyCjnoDWcmqw5XUiBnqGGhUIScrC9+NaQY8nGVxxYgWF6EGfaBm7WxwvG7y4tRYrSQJYShwhQ1hXwpFcYkSWF5AVogY0NeBBJI7TjLQfkCfB9NOLtqxhhPonk9BDPpjMB4KzumTXYa9vjcGuplGj20BpuNW0O9TaPWWPNoUgkbXZWDVnxbnTfQggksaTkQMm2oK3VXSUfFkUyxbvq8Qxs7AvLuWD5+elAH8UG9DecB+k0B100Bg380f12mYdUEyEGqMpbtBqR28fcDpH26QHssvVzjnezOjt2pr1+ZBFS8p33ff8KL120NtXa4Ap3Qz24IXIJXVGPIbJvJEm9tIU1tKmekfm82fr2mzb/5a/MPK1VTceUV6wXD4Om3RlcvhUVnlC8jTgi+7QfZuU/PWcDBsG1gsAPuXf0CQCuEvA==

end

**Comment by myoblastic** [comment]
@lordage It's not the limited filters because I tried removing all filters except the "Select 1080p" one, and the episode still wasn't selected. I haven't been able to get the 1080p Haikyuu episode with your filters either, so I suspect its probably something specific to how certain anime label their video resolutions.
