### ISSUE TITLE
MyAnimeList 403 forbidden error

### ISSUE THREAD

**Issue by menma1234** [erengy/taiga#327]
When I try to sync or do anything with MAL, MAL seems to be returning an HTTP 403 Forbidden error, and Taiga shows "Unknown error (myanimelist|1|403)" (or "Could not parse search results" in the case of searching). If I trace the network packets in Wireshark, it seems that MAL returns 403 Forbidden for all of these requests. Oddly enough, if I try the exact same URLs through my web browser, they work fine. Perhaps something broke with the API key?

![ss 2016-11-02 at 08 52 45](https://cloud.githubusercontent.com/assets/9199262/19952796/6ba86348-a13e-11e6-9b56-93973fca5c1f.png)

**Comment by menma1234** [comment]
Never mind, I didn't realize there was a version 1.2.4 out and this is fixed in that.

**Comment by erengy** [comment]
To clarify: MyAnimeList now denies non-HTTPS requests to the API with a `403 Forbidden` response. Since HTTPS support for MAL was added in v1.2.4, previous versions of Taiga will no longer work properly.
