### ISSUE TITLE
Open episode discussion thread after updating list

### ISSUE THREAD

**Issue by RatedDS** [erengy/taiga#329]
Would it be possible to show the option to go to the episode discussion thread in MAL after updating an anime, like when you do it directly in MAL?

**Comment by erengy** [comment]
Episode discussion links are not provided by MAL API, unfortunately. There is an undocumented way to get them via `/includes/ajax.inc.php?t=50`, but it's not intented to be used by third-party applications. Not to mention that it makes things complicated by requiring an extra authentication process.
