### ISSUE TITLE
Growing number of FIN_WAIT2 and CLOSE_WAIT connections on proxy host

### ISSUE THREAD

**Issue by koteq** [erengy/taiga#333]
~~After updating to 1.2.4~~ my proxy server begins to welcome me with 'Too many open files' message every two weeks or so. It seems to be related to Taiga. Every time Taiga checks for new torrents two new sockets will hang in states as described below.

```
[proxyhost]:33300->[2400:cb00:2048:1::6814:4a6a]:https (CLOSE_WAIT)
[proxyhost]:3128->[homerouter]:49895 (FIN_WAIT2)
```

Where ipv6 address is belong to cloudflare which covers nyaa.se

I did read [This is strictly a violation of the TCP specification](https://blog.cloudflare.com/this-is-strictly-a-violation-of-the-tcp-specification/) article but it seems I didn't quiet get this TCP things.

I may schedule proxy service restart once a day but I wish to find better solution.

**Comment by erengy** [comment]
From what I understand, the issue is not directly caused by Taiga. But for starters, you could try disabling *Settings → Advanced → Application → Reuse active connections*.

**Comment by koteq** [comment]
Your advice helped. Sockets didn't hangs anymore.

I don't know what causes it. I build previous version from 82f0664 and the issue is still here. So I was wrong about 1.2.4 version. Maybe it's just coincidence. Also I tried different feeds and it only happens on nyaa.se

**Comment by erengy** [comment]
I recently rewrote Taiga's HTTP code from scratch (see [hypp](https://github.com/erengy/hypp) and [hypr](https://github.com/erengy/hypr)). I haven't made any changes specific to this issue, since we don't exactly know what causes it. But the new code makes use of a shared DNS and connection pool, which might provide a solution.
