### ISSUE TITLE
Update failed! Taiga's animelist

### ISSUE THREAD

**Issue by KikunXyy** [erengy/taiga#335]
I have Wake Up, Girls on currently watching on MAL.
https://myanimelist.net/animelist/kiunxyy?status=1

But it's not listed under Taiga's "Currently Watching". Though, if I search for the anime, it's listed under "In List".

http://imgur.com/a/mEMSC

The error message pops up every couple minutes for as long as I have Taiga running.

**Comment by erengy** [comment]
Deleting the anime from your update queue at History page and then synchronizing your list should get rid of the issue. Please see #328 for more information.
