### ISSUE TITLE
How exactly are proxy work?

### ISSUE THREAD

**Issue by BanD11** [erengy/taiga#338]
Is it enough to fill the 'Proxy host' field with IP:port (104.218.154.228:45554, as example)? I did so, and got this:
```
2016-11-23 14:39:23 [Error] http.cpp:93 taiga::HttpClient::OnError | HTTP error #56: Failure when receiving data from the peer
                                                                     Connection mode: 1
```
Does i do it wrong?

**Comment by erengy** [comment]
Setting *Proxy host* to `IP:port` should work (e.g. `127.0.0.1:1080`). You may also use a scheme prefix to specify which kind of proxy is used (e.g. `socks5://127.0.0.1:1080`). See [CURLOPT_PROXY](https://curl.haxx.se/libcurl/c/CURLOPT_PROXY.html) for more information.

The most likely explanation for the error is that the proxy address you're using simply doesn't work. In fact, I couldn't connect to the one in your example either. Then I tried another public proxy address and it worked.
