### ISSUE TITLE
Settings not syncing

### ISSUE THREAD

**Issue by hagamablabla** [erengy/taiga#339]
Whenever I restart Taiga, some of my settings go back to what they were before I restarted. These settings are not the default settings, just the settings I had from a while ago. I have also tried doing this with the running as administrator option, but that doesn't seem to help either.

Specifically, the option that keeps changing back is the automated torrent download function. I turn it off every time I start Taiga, but it never stays off.

**Comment by erengy** [comment]
This is likely the same issue as your previous one in #319. That is, either User Account Control or some other application is preventing Taiga from saving its settings.
