### ISSUE TITLE
Kitsu

### ISSUE THREAD

**Issue by erengy** [erengy/taiga#341]
![Kitsu](https://cloud.githubusercontent.com/assets/1078430/20766713/247bd244-b740-11e6-98a6-e4f4d72b9c40.png)

Hummingbird is [about to become](https://forums.hummingbird.me/t/goodbye-hummingbird-hello-kitsu/33238) Kitsu. This means that, within a couple of days, Taiga's Hummingbird service will stop working.

Since the new website brings about a different API, there's much more to be done than just replacing "Hummingbird" with "Kitsu" on Taiga's codebase. Also, a new version of Taiga should be able to automatically import local Hummingbird data for a smooth transition.

Unfortunately, I won't be around at Kitsu's launch to celebrate. But when I return home next week, I will start working on this issue and release a beta version as soon as possible.

**Comment by erengy** [comment]
Progress report: Development is going on at the [kitsu](https://github.com/erengy/taiga/tree/kitsu) branch. It's not in a usable state yet, but most of the basic functionality is now implemented. Current plan is to release a beta version right after Kitsu's full launch and get feedback until the service can be considered stable.

**Comment by erengy** [comment]
Hummingbird is now [being migrated](https://forums.hummingbird.me/t/hummingbird-will-be-read-only-as-we-migrate-data-over-to-kitsu/33359) to Kitsu.

You may continue using Taiga in offline mode for a while, but you will start seeing errors if you try connecting to Hummingbird. To avoid some of these errors, I'd suggest disabling auto synchronization from *Tools* menu and the *Synchronize automatically at startup* option from *Settings* → *Services* → *Main*.

When Kitsu support is ready, I'll announce the download link for the beta version in here and in the forums.

**Comment by ShaunV2** [comment]
Is there anyway you could make two versions of Taiga to support the services separately?  Would that be possible?
Sorry if this isn't the right place to post this.

**Comment by sachaw** [comment]
Is there a point, You can turn either off easily, and maintaining 2 applications becomes a low of work.

**Comment by ShaunV2** [comment]
> Is there a point, You can turn either off easily, and maintaining 2 applications becomes a low of work.

Yeah there is a point, it's so I don't have to run two instances of the same program and rather it's a lot of work or not is up to erengy not you, I currently use both MAL and formally HB (now Kitsu) at the same time so having two separate apps would be great.

**Comment by CRS-ECHO51** [comment]
I agree with Shaun. I believe two different edition of Taiga will help us to update our library fastly.

**Comment by sachaw** [comment]
Sorry @ShaunV2 thought you meant use two instances because you don't use either MAL or Kitsu, my bad, and i see where your coming from.
A better approach I think, is to have better syncing across both platforms.

**Comment by ShaunV2** [comment]
@sachaw  I do run two instances of Taiga and I have them both run at startup as well by creating registry keys in HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Run since Taiga doesn't write run registry keys there.

I would love to not have to run two instances of Taiga though.

**Comment by ovingiv** [comment]
Good evening. I am unable to sync my Kitsu account with "TaigaSetup-v1.2.5-25-g2dfd816-kitsu" build. Trying to sync my data it freezes and then it becomes unresponsive.

**Comment by erengy** [comment]
> Is there anyway you could make two versions of Taiga to support the services separately?

This is most likely never going to happen, for various reasons. The plan is to eventually make a single instance of Taiga synchronize multiple services at the same time (there's an FAQ entry for why this is not the case yet). Anyway, this should be a separate discussion.

> Good evening. I am unable to sync my Kitsu account with "TaigaSetup-v1.2.5-25-g2dfd816-kitsu" build. Trying to sync my data it freezes and then it becomes unresponsive.

Hi there @ovingiv. As I said in my previous post, it's not in a usable state yet. I'm not finished implementing all the new API endpoints, and there are a couple of other things to take care of as well. I'd suggest you to wait until I increment the version to 1.2.6-beta (or 1.3.0-beta, I haven't decided yet).

**Comment by ovingiv** [comment]
@erengy ok no problem...

**Comment by ShaunV2** [comment]
Fair enough @erengy and I look forward for when:
> The plan is to eventually make a single instance of Taiga synchronize multiple services at the same time
becomes possible.

**Comment by littleladyred** [comment]
Posting to ask how that kitsu update is coming along :)

**Comment by erengy** [comment]
I've been [working](https://github.com/erengy/taiga/commits/kitsu) on Taiga pretty much every day for a while now, and it's almost done. Everything except for Seasons page seems to be working. I'll post another comment here in a day or two, after handling that.

**Comment by erengy** [comment]
Barring potential errors that I missed, Taiga now supports Kitsu the same way it supported Hummingbird.

I've merged the `kitsu` branch into `develop` and bumped the version to 1.3.0-alpha. I'll release an official installer once I bump it to 1.3.0-beta. In the meantime, you may try out the [latest build](http://taiga.moe/latest.html). Just be aware that it may be unstable.

If you install it over a previous installation that used Hummingbird as its active service, Taiga will automatically import all local Hummingbird data and switch the active service to Kitsu. All communications with Kitsu should work as expected. Although, if you have a large library, note that Kitsu's server may take more than 10 seconds to respond in some cases.

Now I need to decide on how to proceed from here. There were lots of other things that I wanted to do for v1.3, including some architectural changes. But it might be a better idea to postpone those for a while and release a stable version with Kitsu support as soon as possible.

**Comment by KazukiMutou** [comment]
Don't wanna open a new issue for this since it's an alpha build, but I'm unable to sync with Kitsu. 
I get "Update failed: Kitsu returned an error: Unknown error (kitsu|9|404).

**Comment by erengy** [comment]
It seems that Taiga's trying to update a library entry of yours, but Kitsu says that it doesn't exist.

Did you have some queued updates before upgrading to the alpha build? In any case, try this:

1. Close Taiga.
2. Go to `Taiga\data\user\{username}@kitsu\` directory and rename `history.xml` to something like `history2.xml`.
3. Run Taiga, hit Synchronize to download your list. When it's done, close Taiga again.
4. Rename that file back to `history.xml`.

**Comment by KazukiMutou** [comment]
That indeed was the issue and the fix. Thanks!

**Comment by robflop** [comment]
Quick question: Will the history get wiped once the update for kitsu compatibility comes out? I have like 40 episodes queued up in the history right now.

**Comment by sachaw** [comment]
@robflop No,its fine, if you download the latest build http://taiga.moe/latest.html and replace it worth your existing taiga.exe in %appdata%/Taiga/Taiga.exe and open it, It'l update your list, If u want to be super careful backup your Taiga directory

**Comment by erengy** [comment]
Taiga will import all your local Hummingbird data, so that you don't lose anything. Queued updates will be sent to Kitsu when you synchronize. Unless you've manually added/deleted the same anime via the website too, you shouldn't have any issues. But if you do, let me know!

To explain what happened above with @KazukiMutou: Unlike Hummingbird, Kitsu requires unique IDs to update your library entries. Taiga didn't know these numbers at first and it was sending empty IDs to Kitsu. So I suggested using a trick to force Taiga into downloading the library first, before trying to update it. Since then, I fixed this issue in ad146274ae68cef8e17d2542714a840e8144eda2 and updated the latest build.

**Comment by mynameisnotjake** [comment]
Just downloaded. Getting an error where it says 
"Update failed
Title: Shokugeki no Souma Ni no Sara
Reason: Kitsu returned an error" "must be greater than 0: rating - must be greater than 0"

No clue why it's only the second season of Shokugeki, guess that's why this is here.
![screenshot_11](https://cloud.githubusercontent.com/assets/24959004/21718761/9fbe88b2-d46d-11e6-8058-d1e1016b4213.png)

**Comment by erengy** [comment]
Hi there Jake. I fixed that issue in eb2c4a7049892aa73cc0c7abb23997a8e99920ba, but had not updated the latest build since then. It should be okay if you get the *latest* latest build now. :)

**Comment by mynameisnotjake** [comment]
Tyty

**Comment by wopian** [comment]
Getting `Kitsu returned an error: Unknown error (kitsu|8|503) when updating my library on latest build.

**Comment by erengy** [comment]
That `8` is `RequestType::kGetLibraryEntries`, so Taiga is trying to download your library. I'm getting the same error for yours, while it works for mine. How many library entries do you have? It seems that the server is unable to respond to Taiga's request and it times out after 30 seconds.

**Comment by wopian** [comment]
Over 3000 entries.

**Comment by erengy** [comment]
Yeah, that would do it. If the upcoming API changes don't provide much performance benefits, I'll try to make Taiga get your library in chunks rather than requesting to receive it all in a single response.

**Comment by lordage** [comment]
that explains it then 👍 for me just imported my old MAL list and just got this error

**Comment by littleladyred** [comment]
Since it's almost been a month since I last posted I have come again to bother you for an update on a beta or official update for kitsu 🦊

**Comment by ShaunV2** [comment]
@littleladyred There is already a beta version available to download, refer to this [comment](https://github.com/erengy/taiga/issues/341#issuecomment-268888446).

**Comment by littleladyred** [comment]
@ShaunV2 That's an alpha version. I am using it at the moment. I was asking for an official beta, stable installer release. That a bit more specific?

**Comment by ShaunV2** [comment]
@littleladyred Fair enough.

I'm sure he will mention when an official beta or stable installer will be released.

**Comment by erengy** [comment]
> Since it's almost been a month since I last posted I have come again to bother you for an update on a beta or official update for kitsu 🦊

Kitsu's API is not stable enough for me to release a stable version yet. I could release a beta version with an actual installer, but I'm trying to use this opportunity to get #316 done first, which is going to take a while.

**Comment by auyongcheemeng** [comment]
> http://taiga.moe/latest.html

The latest build of 1.3.0-alpha as of today (18/2/2017 UTC) triggers a malware detection in Windows Defender as Trojan:Win32/Detplock

File details:
SHA256: ca356cb8b33a6a8f0aaf7b8d570e2ac4853f308998d7065bfa860f2888258216
Size: 2.1 MB ( 2235904 bytes )

**Comment by navarr** [comment]
@auyongcheemeng Could you ensure that your virus definitions in Windows Defender are up to date?

A quick Google search shows there was a similar problem with Hearthstone for a bit with out of date definitions.

**Comment by auyongcheemeng** [comment]
Yes they are (on 18/2/2017 2.58AM - v 1.235.3101.0)

**Comment by ShaunV2** [comment]
@auyongcheemeng It's a false positive, ignore it.

**Comment by wopian** [comment]
>And seriously use a better antivirus as Windows Defender is terrible.

That may have been the case in the pre-8 era, but Defender is pretty competent for casual use nowadays.

**Comment by auyongcheemeng** [comment]
As an update: definations got updated and taiga (SHA256: ca356c...258216) no longer triggers the false positive.

A side note on ShaunV2's comment: [Using any third party security software will increase the attack surface of threats](http://www.pcworld.com/article/3020327/antivirus-software-could-make-your-company-more-vulnerable.html)*

**Comment by ShaunV2** [comment]
> A side note on ShaunV2's comment: [Using any third party security software will increase the attack surface of threats](http://www.pcworld.com/article/3020327/antivirus-software-could-make-your-company-more-vulnerable.html)

No it won't, I don't care what you or anyone says Windows Defender is garbage, my Charter Security Suite is way better than that garbage.

**Comment by navarr** [comment]
Let's keep the arguments about anti-virus off this thread, it's unproductive.

**Comment by pervertkirito** [comment]
is it died?

**Comment by hagamablabla** [comment]
Still works for me.

**Comment by choco1** [comment]
If anyone wants to use their Kitsu library right now, you can use Kitsu's export functions and live-export (change on Kitsu and auto-update on MAL) to MAL and use that for now

**Comment by wopian** [comment]
Or you can use 1.3.0 alpha and update Kitsu normally...

**Comment by erengy** [comment]
v1.3.0-beta is now available:
https://github.com/erengy/taiga/releases/tag/v1.3.0-beta
