### ISSUE TITLE
Windows Defender says Taiga is a Trojan

### ISSUE THREAD

**Issue by thebitstick** [erengy/taiga#342]
It says it's a Peals.A!cl Trojan and removed it.  

I got the exe from [taiga.moe](taiga.moe) so I doubt the exe got hacked.

**Comment by erengy** [comment]
I recieved a similar report last week:
https://twitter.com/taigaapp/status/806289362380005376

VirusTotal analysis shows that both [TaigaSetup.exe](https://www.virustotal.com/en/file/407758c674696ac9ffd12c643675125f23481e8fe9d8b19570976f40ea023420/analysis/) and [Taiga.exe](https://www.virustotal.com/en/file/d3794e8ea35b045b20b87038428de183ab4a3777df852c0a0d9276d47c6901b1/analysis/) are clean according to Microsoft (and all other companies, except for Baidu).

Windows Defender acts kinda weird sometimes. Relevant paragraph from my [blog post](http://erengy.com/blog/false-positive) on false positives:

> The weird thing about Microsoft Security Essentials (and Windows Defender) is that even if they don't give you a warning for a particular file, other users with the same malware definitions can get different results. On one hand, a couple of people reported that the application was flagged as "Trojan:Win32/Skeeyah.C!plock". On the other hand, neither me nor other users got any warning...

Related issues: #319, #173, #159, #19

I now checked the file at the home page just in case, and it wasn't modified. So, it's a false positive.
