### ISSUE TITLE
Cache "scan available episodes"

### ISSUE THREAD

**Issue by minerz029** [erengy/taiga#349]
It seems like the "scan available episodes" is forgotten every time the app is closed and reopened. I think it would be better if this was cached, and updated periodically or when real-time monitor detects a change.

This would be useful with the "display highlighted anime above others" option. Currently, you have to click "scan available episodes" before the available episodes are moved to the top.

**Comment by ShaunV2** [comment]
If you don't have Taiga pointing to the correct folder location for downloaded anime you'll run into this issue (sometimes you'll need to make sure the anime in question has the right folder path), I've never encountered this issue myself.

**Comment by erengy** [comment]
I'll be closing this issue since we already have #305.

**Comment by minerz029** [comment]
@ShaunV2 I believe I have it set up correctly. I have one main anime folder, and all my shows are stored in subfolders. Taiga is just set to the main folder. 

@erengy Yeah, that's pretty much exactly what I've said. Sorry, didn't manage to find it.
