### ISSUE TITLE
Missing Winter 2017 Season Data

### ISSUE THREAD

**Issue by Hiwashi** [erengy/taiga#350]
Taiga is missing the Winter 2017 Season Data

**Comment by erengy** [comment]
I added Winter 2017 season data in ed6346120c45cce2f308f16d06a04c63eba091a6 and made it available for v1.2.5 users now.

If it doesn't appear automatically at the Seasons page, try using the *Help* → *Check for updates* menu item. You'll see a "Taiga is up to date" message, but it will silently download the latest season data and anime relations in the background.
