### ISSUE TITLE
already been taken: animeId - has already been taken

### ISSUE THREAD

**Issue by gearan** [erengy/taiga#354]
I keep getting this error popping up when I try to add certain anime to my list. This case being ACCA: 13-ku

**Comment by erengy** [comment]
Just to make sure, you're using the alpha build with Kitsu support, right?

**Comment by gearan** [comment]
yes I am using 1.3,0-alpha

it won't go away though and keeps popping up continuously even after restarting the program.

**Comment by erengy** [comment]
You need to do one of the following to make the error go away:

- Go to History page of Taiga and delete the item related to *ACCA: 13-ku Kansatsu-ka* that is at the bottom of the update queue (which has a green plus icon and says "Add to list" in its details).

- Go to your Library at Kitsu's website and remove the anime from your library.
