### ISSUE TITLE
Settings window too big for screen

### ISSUE THREAD

**Issue by avalynnrose** [erengy/taiga#355]
When I open the settings or anime information windows in taiga the window is too big and hides behind the toolbar. I have to move or hide the toolbar in order to click some buttons. It wont allow me to resize the  windows. This occurs in both the most recent stable version and in the latest version that supports kitsu.

**Comment by erengy** [comment]
Settings window is ~769x573, whereas Anime Information window is ~856x620. There shouldn't be an issue unless your screen resolution is less than 1024x768.

What's your screen resolution? Do you use a non-default DPI setting? Could you attach a screenshot?

**Comment by avalynnrose** [comment]
Yeah beginning to think its something wrong with my computer because I just noticed it in another program. My dpi is scaled up but the problem persists when I set it back to 100% and when I click disable dpi scaling on the specific program. My resolution is 1920x1080, usually scaled to 175%, but like I said it happens even at 100%. In the screenshot you can see the settings window is really large and the ok/cancel buttons are hidden behind the taskbar.
![screenshotissue](https://cloud.githubusercontent.com/assets/25086008/21902635/47fab854-d8c2-11e6-893f-2b8d97f2ded1.PNG)

**Comment by ShaunV2** [comment]
Your windows are definitely larger than they should be, I'm on the same OS and resolution (Windows 10 1080P) and I do not have this issue at all.

**Comment by erengy** [comment]
This seems to be the same issue as #126.

**Comment by ShaunV2** [comment]
Well I'm on a 40" HDTV and I sit right in front of it (which is why I have no need in messing with DPI Scaling) also higher resolutions really aren't recommend on smaller displays.

**Comment by avalynnrose** [comment]
Yeah I'm on a TV as well which is why I use the scaling like the person with the same issue does.

**Comment by avalynnrose** [comment]
Looks like using my recommended resolution of 4096 x 2160 fixes the issue. That makes everything really tiny though. Seems like its just a windows and resolution issue then.

**Comment by ShaunV2** [comment]
Well I'm not that far from the HDTV either maybe 1-2 feet if that, the TV sits on a table.

**Comment by erengy** [comment]
Ideally, Taiga should allow you to resize these windows to accommodate your situation. But as I mentioned briefly in #126, making this possible in Windows API requires considerable effort on my part, which would be quite unpleasant for me and not much of a use for most people.

I'm not planning to make any major changes on the UI in near future, so I'm afraid the situation is the same with the previous issue. For now, all I can offer is a tip: You may use the <kbd>Enter</kbd> and <kbd>Escape</kbd> keys instead of the OK and Cancel buttons that are hidden behind the taskbar.

**Comment by avalynnrose** [comment]
Okay, thanks for the tip!
