### ISSUE TITLE
Update failed: The anime (id: 33487) is already in the list.

### ISSUE THREAD

**Issue by dtmw** [erengy/taiga#356]
Hi, whenever I try to synchronize my list with Mal I get this error (title) and it doesn't actually sync with the site.. Can someone help me, please?
The version of Taiga is 1.2.5

**Comment by erengy** [comment]
Hi there,

The error means exactly what it says: You're trying to add an anime that is already in your list. In this case, the anime is [Masamune-kun no Revenge](https://myanimelist.net/anime/33487) (note the ID in the URL).

To resolve this issue, go to History page of Taiga and delete the item related to *Masamune-kun no Revenge* that is at the bottom of the update queue, which has a green plus icon and says "Add to list" in its details.
