### ISSUE TITLE
Problems with anime Rewrite: Moon and Terra

### ISSUE THREAD

**Issue by kerts93** [erengy/taiga#359]
My updated queue is giving me this error:
![image](https://cloud.githubusercontent.com/assets/4341091/21965574/71faef74-db6b-11e6-80ba-fe7577d6e04e.png)

![image](https://cloud.githubusercontent.com/assets/4341091/21965579/86e6f1d0-db6b-11e6-8f24-25aad762e3c6.png)

Using Kitsu.

**Comment by erengy** [comment]
Please see #354 for the same issue and the solution.
