### ISSUE TITLE
Settings reset

### ISSUE THREAD

**Issue by Justtaway** [erengy/taiga#360]
Unfortunately, I haven't been able to reproduce this bug, but sometimes my settings just resetting themselves randomly. But when it happens, it always happens after
I have Windows 10 14393.693, with UAC disabled completely.

**Comment by ShaunV2** [comment]
I've never had this happen once, I'm on Windows 10 with UAC always disabled.

**Comment by Justtaway** [comment]
Well, idk if it will be of any help, but my specs:
i5 4430
GTX 970 (376.19 driver version)

**Comment by erengy** [comment]
Might be the same issue as #339.

Did you try running Taiga as administrator? Is Taiga installed to a different directory than the default one? (`C:\Users\{username}\AppData\Roaming\Taiga`) Do you have any security application that might be preventing Taiga from working properly?

> But when it happens, it always happens after

...?

**Comment by Justtaway** [comment]
Actually, I tried running it as administrator, I'll test if it will help. And yes, it's different directory, it's just C:\Taiga.
Also, I have 360 Total Security, but Taiga is whitelisted here. And it's probably harmless anyway.

**Comment by xczv** [comment]
I have a similar issue, where settings just don't ever save properly. Is `C:\Users\{username}\AppData\Roaming\Taiga` supposed to be where I install Taiga?

**Comment by erengy** [comment]
> Is `C:\Users\{username}\AppData\Roaming\Taiga` supposed to be where I install Taiga?

Yes. Otherwise, User Account Control may prevent Taiga from saving its settings and other data.
