### ISSUE TITLE
Larger poster images

### ISSUE THREAD

**Issue by tophf** [erengy/taiga#362]
Currently Taiga shows very small cover images, approximately 148x200.
It'd be nice to have an option to show a larger image, for example the default size on MAL CDN is 225x350.
As for Now Playing and Anime Info, the default image can be easily transformed to an even larger original image by adding `l` before the extension dot.

**Comment by erengy** [comment]
Poster images downloaded from MAL CDN are 225×{H}px, while the ones downloaded from Kitsu are 284×402px. These images are displayed as 150×{H}px (with 2px border) at Anime Information dialog and 120×{H}px at Seasons page, with the default DPI settings.

Here's a handy table for easier comparison:

Image|Width|Height
:---|---:|---:
MyAnimeList|225|*
Kitsu|284|402
Anime Information|150|*
Seasons|120|*

As an example, changing the image at Anime Information dialog to 250×{H}px would look like this:

![anime-info-250px](https://cloud.githubusercontent.com/assets/1078430/22169633/37e76134-df7e-11e6-9c99-c3f664c104ce.png)

In my opinion, this doesn't go well with with the general design of the application and takes the focus off the actual content. Not to mention that it directly affects the window size. This could change after v2.0, but I see no benefit at making images larger at the moment.

**Comment by tophf** [comment]
I think it obviously looks way better with a large image at least on a big display I'm using. That's why an option would be nice for such users. Currently the small image is almost useless.

**Comment by erengy** [comment]
Played around a bit with different sizes for the image at Anime Information dialog. 180px (20% increase) seems to be the upper limit I could do without messing up the layout.

**Comment by tophf** [comment]
Yes, 180px is good in Seasons view.
I've also changed `group by list status` order to start from Watching, revealed titles in `sort by popularity` mode.
Here's a screenshot of my mod:

![clip186](https://cloud.githubusercontent.com/assets/1310400/22628843/60c8bb8c-ebec-11e6-889b-958d02730076.jpg)

**Comment by erengy** [comment]
v2 now uses larger poster images.

- List view: 140px (was 120px in v1)
- Media dialog: 200px, resizable up to 320px (was 150px in v1)

Taiga will download larger images from AniList/Kitsu/MyAnimeList to compensate.
