### ISSUE TITLE
All Episodes are missing?

### ISSUE THREAD

**Issue by TheJanitor13** [erengy/taiga#365]
Hey there.

Been having issues with my Anime not being added into the list.
If I have started a new dl, it will be added to my library and will show up in the list correctly.

The issue I am having is with things downloaded pre-session.
Curious if there is some setting somewhere preventing Taiga from finding my anime in the library once it has booted back up.  Because the stuff that is added right now, will not be tomorrow.

As an example.  I just downloaded 2 episodes of Anime A.  I can use Taiga to play those, right now.
Yesterday I downloaded 2 episodes of Anime B, but Taiga claims they are not in my library, even though they are exactly where taiga put them with the Daemon.

Not sure exactly what's up with this.
TIA

**Comment by TheJanitor13** [comment]
Nevermind.  I am a dunderhead.  
F5, my savior.

**Comment by erengy** [comment]
Hi there @TheJanitor13,

You can try enabling the *Scan library folders for available episodes* option from *Settings* → *Application* → *General* → *Startup* for convenience. But this is ultimately an issue related to #305, where Taiga should remember available episodes after a restart.
