### ISSUE TITLE
Main window remains disabled after restoring default settings

### ISSUE THREAD

**Issue by Hiwashi** [erengy/taiga#369]
As the title says, after I tell Taiga to restore the settings to the default, the main window will become unresponsive and freeze up. 

I'm on W10, not sure if that matters.

Not a big deal, and the system tray icon still works to exit it and after I re-open the settings will be back to default so it's just a very minor inconvenience

**Comment by erengy** [comment]
Should be fixed with ab03ad98d5f701df5b04dc938e29f031ae48c335 and 93e3097082a123ef035132bf6ab90a1d38841753.
