### ISSUE TITLE
Unresponsive tray icon; unresponsive after reinstallation

### ISSUE THREAD

**Issue by MarcusGHub** [erengy/taiga#370]
I couldn't get the tray icon to respond at all. I always had to kill the process. So, I re-installed the application and now when it starts and prompts me for username, it becomes unresponsive.

OS: Windows 10 Pro

**Comment by erengy** [comment]
Do you have any media players or web browsers running in the background? If so, does closing them help?

**Comment by MarcusGHub** [comment]
None of the above running in the background.

**Comment by erengy** [comment]
If you're not using it already, try the [latest build](http://taiga.moe/latest.html) and see if it makes any difference.

The most likely reason for the unresponsiveness is Taiga's media detection getting stuck in some process. If that is the case, closing any background applications (including ones such as Dropbox, see #270) might help.

**Comment by MarcusGHub** [comment]
It works after applying the latest build. Thanks 👍
