### ISSUE TITLE
Silent download of the latest season data and anime relation doesn't work

### ISSUE THREAD

**Issue by CRS-ECHO51** [erengy/taiga#372]
I took several attempt to update yet season and anime relation data don't get updated.
I use Windows 10 x64 1607 14393.693

**Comment by erengy** [comment]
Could it be that you are using the alpha version of Taiga, or an older stable version? That silent download functionality only works with the latest stable version, which is v1.2.5 at the moment.

**Comment by CRS-ECHO51** [comment]
I use alpha version of Taiga. Thanks! Will wait for future release.
