### ISSUE TITLE
Fansub Preference Torrent Filter stopped working

### ISSUE THREAD

**Issue by LordZounds** [erengy/taiga#373]
Seemingly for no reason, without me making any changes to my filters or updating Taiga or anything, and in the middle of the season, Fansub preference filters (the ones created when right clicking on a torrent and clicking "Select this fansub group for this anime") no longer work for me. The filter correctly does not select releases from other groups, but for some reason it does not select the selected release either. The release is not hidden or greyed out in the list, it is just not selected.

EDIT: I should note that shows that do not have specifically designated fansub groups still work fine with my blanket rule to prefer HorribleSubs (which previously would be overridden by a designated fansub group where chosen), and those torrents are selected just fine. Disabling the blanket HorribleSubs rule does not fix the problem, so it's not that suddenly they're conflicting.

**Comment by erengy** [comment]
Could you export your filters (via the rightmost button at *Settings* → *Torrents* → *Filters*) and paste it here?

![export-filters](https://cloud.githubusercontent.com/assets/1078430/9335106/d0bcc140-45da-11e5-819d-1ed73e609846.png)

**Comment by LordZounds** [comment]
Ah, right, sorry. I forgot to include that.

VEFJAQUAMS4yLjU+AkELeJy1lk1v2kAQhs/Nr1hZitQeEAmkiiLhHFpEkaKqlYh6qSJr8A4wynrX3Q9Q+us7NiRAVIPBcLLwzr77vDOzY3rkMROQejI6jiS5FKyMRAY+ncUR6JdImHy5OCOJkUANY4UyjrwN/FNDhnE05CWhjW+RbilyXoCmDKP7iw+91GhJhYBAhRlqH0fBoU2cBx9coY4WvLFxhH8CKH4zBxVY8yoS7fuLXrsA5OfpOKU1eY6SGaUwujUzSp6C96bkbSDQPcSwUvUNT0iTm6FsAVnS06VZQVrkCrTwRiwK0Sr3GXrYD3/d1P3nc5W7NMflxpyckeiqfK7WEx2yMdpNUoVvlJcrtctz1Wo44nukW7edq32cU2tCviOhQ2Mt8SmjMHbVxXlVm/PhJrHojApFxKYwX+x32oyXnysDMAdSxWJVApRJQSWv4Ovw6lQ8lmecp736CLL9BZ5RDviSNS1aoVbq7C3YPqU10pF1kliEzcFX2e+/BZQt+/3hV5X7CSlMPPntInFbcawH0mvqQqSa17Fi6v9fJ4kTCMpXsI7KnSIN1jKRellOBR6GzWb+9QGw27mtAXvUtD5k2DYY950dxnOLk2KAHm78Z7lTbE4u8TFoT0oYP0O7IIfCof908tlYz0n9fls50bgQc7SOd+z97qziNqmnvlanHZ/w34PB4El8g7ElVKLPf4x+BF+CrrqO47vd2+6Or3vdlPNJ57Hw1WQZ4ZN4CH8DDyLuHv0M9N5E5+7mrrmJ5VlbPv4BvXHa3w==

**Comment by erengy** [comment]
> Disabling the blanket HorribleSubs rule does not fix the problem, so it's not that suddenly they're conflicting.

Disabling the "Prefer HorribleSubs (until otherwise set)" filter works for me. After a quick debugging session, I was able to confirm that this filter was causing your preferred releases (FFF for *Gabriel DropOut*, Commie for *Kuzu no Honkai*) to be discarded.

It seems that this general preference filter isn't behaving as expected. In order to achieve what you want, changing your limited filters from this:

```
Condition: Episode fansub group | is | (...)
Action: Prefer
```

...to this should work:

```
Condition: Episode fansub group | is not | (...)
Action: Discard
```

**Comment by LordZounds** [comment]
Hm, alright, I'll try that then. It hadn't worked previously when I tried disabling "Prefer HorribleSubs", but I realize now that may be because I had previously manually downloaded and deleted the desired release. That said, won't the system you described discard all the releases I don't want, but not actually select the one I do (because the Prefer HorribleSubs causes it to only select HS releases)? Maybe I'm misunderstanding how they work. I'll give it a try regardless.

Thanks a lot!

**Comment by erengy** [comment]
> won't the system you described discard all the releases I don't want, but not actually select the one I do (because the Prefer HorribleSubs causes it to only select HS releases)?

Your "Select currently watching" filter selects all releases from these shows, unless they are discarded by a Discard or Prefer filter.

> Maybe I'm misunderstanding how they work.

Don't worry, sometimes even *I* forget how filters work. :')

**Comment by LordZounds** [comment]
I was able to test it now and it worked great, thanks again for your help!
