### ISSUE TITLE
Trojan:Win32/Detplock

### ISSUE THREAD

**Issue by spacesven** [erengy/taiga#376]
I downloaded the newest Beta from your site and it got deleted from Microsoft Defender. 
![image](https://cloud.githubusercontent.com/assets/8382898/23055797/1518885c-f4e8-11e6-96dc-0dcd5e2f75b1.png)

**Comment by ovingiv** [comment]
![capture](https://cloud.githubusercontent.com/assets/24558152/23056191/d4324586-f4af-11e6-8947-815d9780dcd4.PNG)

I have the latest update too but I got this.

**Comment by erengy** [comment]
It's a false positive. [VirusTotal analysis](https://www.virustotal.com/en/file/ca356cb8b33a6a8f0aaf7b8d570e2ac4853f308998d7065bfa860f2888258216/analysis/) says that the file is clean according to Microsoft. See #342 for more information.
