### ISSUE TITLE
Recognition inconsistent

### ISSUE THREAD

**Issue by indisposed** [erengy/taiga#377]
Recognition acts strangely for some series in some (as of yet I havent been able to discern them) conditions, as follows.

![frustrating](https://cloud.githubusercontent.com/assets/1807634/23100950/1b691816-f6f0-11e6-8739-a4165e67d506.png)

I've had the issue with other series and it's simply gone away, and yet others are consistent. I went as far as to completely remove taiga and reinstall, which strangely fixed the issue with Hajime no Ippo, and Keijo, however after a restart the issue returned for Keijo but not Hajime no Ippo. I've been wracking my brain as to what i'm missing as the issue has been going on for sometime.

**Comment by auyongcheemeng** [comment]
Some times, a manual 'scan for episodes' from the file menu solves this for me, (for most shows) except for some very specific titles, some episode goes missing at random although 

![capture](https://cloud.githubusercontent.com/assets/143950/23122388/f39bdd14-f79e-11e6-9402-99f09e1c813b.PNG)

**Comment by erengy** [comment]
@indisposed Does Taiga correctly identify the first six episodes of *Keijo!!!!!!!!* when you play them? Or does it ask for your help at Now Playing page?

**Comment by indisposed** [comment]
@erengy yes/no? it says "Watching: Keijo!!!!!!!! #1 (Not recognized)" in the status bar, which tells me that it's detecting the correct episode with the correct title, but still saying its not recognized. 
![nowplaying](https://cloud.githubusercontent.com/assets/1807634/23163970/c3e99056-f899-11e6-8f64-032084800e32.PNG)

**Comment by erengy** [comment]
Could you send a screenshot of the entire Now Playing page? The status bar itself doesn't yield much additional information.

**Comment by indisposed** [comment]
Haa, that got it, thanks. I didn't think to actually click the now playing. It found two instances of "Keijo!!!!!!!!" from MAL (somehow as I can't manually find any equiv), that disappeared after clicking the [?]. As I did this without taking a screenshot, it was the equiv of this... 
![this](https://cloud.githubusercontent.com/assets/1807634/23165696/53a63cf0-f8a2-11e6-918f-5708b981718e.PNG)

But I have a feeling you knew that, because that's actually impeccable design ... maybe have the 'when an episode is not recognized' option ticked by default (if I didn't somehow untick it my own damn self). 

Cheers muchly and sorry for the waste of time, more reason to be impressed with Taiga because that's an impressively elegant solution.
