### ISSUE TITLE
Display older items from RSS feeds

### ISSUE THREAD

**Issue by morizuki** [erengy/taiga#380]
Good Day again,

I wanna know if there's any feature on your Taiga that can go beyond the date of the torrent not just today and yesterday?

Thanks

**Comment by tophf** [comment]
RSS feed on a torrent tracker contains a lot of files submitted each day.
If you want to see a week or more you'll need to modify the default feed:

```
https://www.nyaa.se/?page=rss&cats=1_37&filter=1&term=HorribleSubs%201080p
```

which fetches only HorribleSubs 1080p torrents. Obviously you won't be able to use Taiga to download anything except HorribleSubs 1080p.

**Comment by morizuki** [comment]
Oh I get it.. thanks so much. I'm kinda new to RSS so I didn't know that we can mix a bunch of rss.

I'm just into BDRip and DVDRip release. THANKS SO MUCH :D 

BTW I'm not sure if my rssmix is right.

http://www.rssmix.com/u/8226561/rss.xml

**Comment by erengy** [comment]
RSS feeds return the most recent content by default. This is generally how they're intended to work. Some feeds allow pagination or other query parameters to display older items, but most of them don't.

For instance, as you may have noticed from the list of default RSS feeds at *Settings* → *Torrents* → *Discovery*, only NyaaTorrents allows searching for older releases. Tokyo Toshokan and the others don't have this functionality. Similarly, it's possible to append `&offset=2`, `&offset=3` and so on to the URL to see earlier releases. But again, as far as I'm aware, only NyaaTorrents supports this.

For the future, I see two improvements I could make to Taiga's aggregator in this context:

- It could keep a persistent history of all items it has encountered and display them when necessary. However, this would only work properly if the user runs Taiga about every day and has automatic torrent checking enabled.

- It could make use of Nyaa's pagination functionality, though I'm not sure how this would work UI-wise.

For now, the only way to see torrents beyond any limit is to manually search for them.

**Comment by morizuki** [comment]
That would be great. But why don't you just enable the torrent checking by default? There's no much different on disable and enable. If there's just a way to make a date and time checking on discovery it will be great. But it seems it's impossible.

**Comment by tophf** [comment]
@morizuki, nyaa supports `|` and `-` operators so your query on the site could be `BDRip | DVDRip` which translates to `BDRip%7CDVDRip` in Taiga's feed settings.

**Comment by morizuki** [comment]
@tophf ohhh.. I didn't know that. Thanks for that.
