### ISSUE TITLE
Can't start with windows.

### ISSUE THREAD

**Issue by xczv** [erengy/taiga#383]
Taiga doesn't start with Windows (8.1) even though I explicitly set it to, and starting the program manually gets me the following warning message:

> Your system administrator has blocked this program. For more information, contact your system administrator.

On my system, Taiga is currently installed to the following directory: `C:\Users\<username>\AppData\Taiga\` which is the recommended location to install Taiga.

My AV is set to NOT do any realtime protection/scanning, and I've set UAC to "never notify," which is supposedly tantamount to disabling it completely (I'm not actually sure how true this is.) My account is an administrator account.

**Comment by erengy** [comment]
This seems like an issue with your system rather than Taiga. Searching for the error message on Google points to Group Policy settings, or security applications such as CryptoPrevent. I'd suggest looking into these, as you may be able to resolve the issue by modifying some settings.
