### ISSUE TITLE
CustomScore raising exception in vs2017 (std::mismatch)

### ISSUE THREAD

**Issue by mchubby** [erengy/taiga#384]
https://github.com/erengy/taiga/blob/4783aa0c3c6424e932c43f01cc33e7416e8ff3e5/src/track/recognition_score.cpp#L84

(This function is triggered when a title has been detected, I reckon)

Raising "`string iterator + offset out of range`" in std::string operator+=

According to https://stackoverflow.com/q/21287985 std::mismatch is not supposed to be used on iterables of different lengths? As per the answer, I substituted it with the 4-arg form of std::mismatch

```c++
    auto mismatch = std::mismatch(title.begin(), title.end(), str.begin(), str.end());
```
and it won't raise an error.

Would it compile properly in VS2015 u3 ?

**Comment by erengy** [comment]
The scoring algorithm is used to find the most similar anime titles, when no single exact match is available. The results are then displayed on the Now Playing page, where Taiga asks for user input.

Back when I first coded this in VS2013, I think there were no overloads available for `std::mismatch` that took an end-iterator for the second range, which seems to be a C++14 feature. Modifying the code as you suggested seems to be working in VS2015 Update 3. But I'll also check if it affects the scoring algorithm, just in case.

Did you encounter any other issues compiling Taiga with VS2017? I don't think I'll be upgrading for a while, but I'd like to know whether it compiles or not, at least.

**Comment by mchubby** [comment]
No major issue overall

- I'd thought Git uses recursive submodule pulls by default since some 2.x release; not the case
(solved by ``git submodule update --init`` at repo root)

- had forgotten about how to compile libcurl
(solved by: RTFM wiki)

after that, it compiles nicely, and runs without a hitch. Tenoritaiga, banzai!

Other thoughts
- migrating a 1.2.0 hummingbird xml to kitsu went smoothly
- anime_relations.txt became anime-relations.txt
