### ISSUE TITLE
Does Taiga have a "find related" feature?

### ISSUE THREAD

**Issue by MaxRavenclaw** [erengy/taiga#385]
MALU had a related tab where you could see a list of shows that are not on your list but are related to shows that are. Does Taiga have a similar feature? If it does, I don't seem to find it.

Thanks.

**Comment by erengy** [comment]
Taiga doesn't have this feature, unfortunately. Please see #119 for more information.

> Taiga doesn't know which anime is related to another. Neither MyAnimeList nor Hummingbird provides the necessary data in their public APIs to third-party applications. Therefore it's not possible to display related anime, unless the application manually creates, manages and distributes its own relation database. It works for web applications such as MALgraph, but it's not exactly a good idea for desktop applications such as Taiga.

> I imagine that MAL Updater has a database of its own, distributed along with the application. This is actually very easy to do. I already have a recent database dump myself, which includes relations. However:
> - It requires constant effort to keep the database up to date.
> - I'm not fond of scraping HTML pages to collect the information.
> - The larger the database gets, the more unethical it becomes to distribute it without MAL's consent.

The only thing that has changed since then is that Hummingbird is now Kitsu, and their API provides information about media relationships.
