### ISSUE TITLE
Taiga doesn't ask for confirmation sometimes

### ISSUE THREAD

**Issue by asakurato** [erengy/taiga#386]
I'm heavy MAL user and I have been using Taiga for a few days. And I love it! I'd like it to ask for a confirmation when updating the list. I have set time for 1200 seconds (20 min). But sometimes, Taiga doesn't ask for confirmation, updating list automatically. I made sure that "Ask for confirmation" is ticked in settings. Not sure why or when this happens.

**Comment by ovingiv** [comment]
Are you using a media player or a streaming site?

**Comment by asakurato** [comment]
Media Player Classic. Through it hasn't happened since, or maybe I don't notice anymore

**Comment by ovingiv** [comment]
I'd suggest using a smaller number and see what happens then... Maybe try 600?

**Comment by erengy** [comment]
I tried reproducing this issue numerous times with different settings, to no avail. I'm closing this issue, but let me know if you encounter it again, along with all your recognition settings.

**Comment by asakurato** [comment]
Well, I have switched to auto-update anyway, so I don't know if the issue is there or not
