### ISSUE TITLE
Taiga tells me that i am watching an anime being played

### ISSUE THREAD

**Issue by antoman29** [erengy/taiga#387]
Taiga tells me that i am watching "Koe no Katachi" anime movie being played when I use the WebTorrent Desktop software

**Comment by tophf** [comment]
This is what Taiga does. Is there a problem?

**Comment by antoman29** [comment]
I know this is what he should do when I watch an anime but when I use this torrent software https://webtorrent.io/desktop/ Taiga tells me that i am watching "Koe no Katachi"

**Comment by erengy** [comment]
Do you mean that Taiga says you're watching "Koe no Katachi", even though you're not watching anything in WebTorrent, or watching something else? If that's the case, what does the window title of WebTorrent say?

Also note that, if you're not using WebTorrent to watch anime at all, you may disable it from Taiga's *Settings → Recognition → Media players*.

**Comment by antoman29** [comment]
It's exactly that. 
I disable WebTorrent in media player in Settings, it's good now. Thanks :)
