### ISSUE TITLE
Exclude/Discard batch torrents filter?

### ISSUE THREAD

**Issue by Thomasedv** [erengy/taiga#388]
I'm not entirely sure if it's possible to do with current filters, but it's a bit needed, as often when the season ends, there's a lot of episodes that also get a batch version, and i get a lot of duplicates. So a filter option to discard/deselect batch torrents, or some way to no select them to begin with. (Again, not sure if possible already.)

**Comment by tophf** [comment]
You can modify the RSS feed URL in options to include only `mkv` and exclude `batch`:
```
https://www.nyaa.se/?page=rss&cats=1_37&term=mkv+-batch
```
or both `mkv` and `mp4`:
```
https://www.nyaa.se/?page=rss&cats=1_37&term=mkv%7Cmp4+-batch
```
This way you'll only get the single episode torrents.

**Comment by Thomasedv** [comment]
Thanks! That works. Do you think i should close the issue? Or just keep it up?

**Comment by erengy** [comment]
You may also use [a filter like this](https://twitter.com/taigaapp/status/716472914451816449), but @tophf's method will get you more valid results.

I'll close this issue, since we can consider it resolved.

**Comment by Thomasedv** [comment]
Thanks! Will remember that!
