### ISSUE TITLE
Not recognizing KMPlayer version 4.1.5.8

### ISSUE THREAD

**Issue by Photekz** [erengy/taiga#389]
I just upgraded to this version and while it opens the video file through Taiga the Now Playing feature doesn't so it never auto-updates the episode count.

**Comment by YeAhxxx** [comment]
Same is happening to me, I updated KMPlayer from a very old version to version 4.2.1.2 and now it doesn't recognize. Please fix it fam

**Comment by erengy** [comment]
This is now fixed due to my efforts at erengy/anisthesia#1. It's going to be available in the v1.3 release.

**Comment by hlouzan** [comment]
Looks like its happening again, I just reinstalled W10 and installed the latest KMPlayer version same symptons as before. Though this time I think I'm going to either downgrade or change player, last KMPlayer version lost some features I liked (on the fly audio output switch).

**Comment by tokiioKH** [comment]
It is not working again.

**Comment by erengy** [comment]
Taiga has no issues detecting KMPlayer 4.2.2.38, which is currently the latest version available.

Added support for KMPlayer 64X with erengy/anisthesia@931da4593f37d651ae80201e6921ac2ca5e3e831. Will be in the next update.

P.S. KMPlayer's 32-bit and 64-bit versions are basically PotPlayer and MPC-HC, but worse. Also make sure to read their privacy policy. Frankly, I wouldn't run them outside a virtual machine.

**Comment by tokiioKH** [comment]
Ummm, I wonder why it is not detecting it then.
