### ISSUE TITLE
Spring 2017 season?

### ISSUE THREAD

**Issue by tophf** [erengy/taiga#390]
It has already started so we need it in the app.

Tired of waiting I've grabbed the MAL [season page](https://myanimelist.net/anime/season) 

[2017_spring.xml.zip](https://github.com/erengy/taiga/files/889107/2017_spring.zip)

with this simple code which outputs the season data into the clipboard:

```js
copy(
`<?xml version='1.0' encoding='utf-8'?>
<season>
\t<info>
\t\t<name>Spring 2017</name>
\t\t<modified>${Date.now()/1000 |0}</modified>
\t</info>` +
$$('.seasonal-anime').map(e => `
\t<anime>
\t\t<type>${['','TV','OVA','Movie','Special','ONA','Music'].indexOf(e.querySelector('.info').firstChild.textContent.split('-')[0].trim())}</type>
\t\t<id name="myanimelist">${e.querySelector('.title-text a').href.match(/\d+/)[0]}</id>
\t\t<producers>${[...e.querySelectorAll('.producer a')].map(p => p.textContent).join(', ')}</producers>
\t\t<image>${e.querySelector('.image img').src.replace('.webp', '.jpg')}</image>
\t\t<title>${e.querySelector('.link-title').textContent}</title>
\t</anime>`).join('') + `
</season>`
);
```

Pasted it into 2017_spring.xml file in data\db\season folder, edited `maxseason` in data\settings.xml and now I have the season data in Taiga. 

~Now I only need to figure out why Taiga doesn't associate the torrents like AoT2 with the new titles it fetched...~
Added in data\db\anime-relations.txt:

```
# Shingeki no Kyojin -> ~ 2nd Season
- 16498|7442:26-37 -> 25777|8671:1-12!
```

**Comment by wopian** [comment]
Spring 2017 already exists - clicking 'Check for Updates' should add it to the list.

![](http://i.imgur.com/dTEr95f.png)

**Comment by erengy** [comment]
I'll try to add Spring 2017 season and update anime relations tomorrow. I'd been away from computer for a while, so I haven't caught up with the new season yet.

@wopian For Kitsu, the current season and the next one are always available. No updates are necessary.

**Comment by deusxanime** [comment]
@wopian If I do Help > Check for Updates, it says "Taiga is up to date! Current version: 1.2.5". But if I go the Seasons section it only lists Fall 2016 and Winter 2017, no Spring 2017. Tried Refresh Data under there as well. 

![image](https://cloud.githubusercontent.com/assets/11891866/24656848/b2e92d58-1909-11e7-9863-5a14aa919cac.png)

Is that why nothing this current season seems to be downloading? I have switched series I want to download to Currently Watching and then set the download directory, release group, and adjusted filter settings. But it doesn't seem to be matching or grabbing the torrents this season and I couldn't figure out why.

**Comment by lunyx** [comment]
@erengy What is kitsu?  As far as I can see, it's a 5 month outdated branch.

**Comment by CRS-ECHO51** [comment]
@lunyx Kitsu is a service to track anime, manga, and light novel like MyAnimeList. Their adress is Kitsu.io.

**Comment by lunyx** [comment]
That's what I thought, but I don't see any provider for it listed, nor do I see anything about it on the wiki:
http://i.imgur.com/iqGeIwB.png

**Comment by tophf** [comment]
@lunix, hummingbird is the old name, now it's kitsu.

**Comment by lunyx** [comment]
@tophf Is that not supported in the stable releases?

**Comment by wopian** [comment]
Nope. It's currently only on the 1.3.0 alpha, available from http://taiga.moe/latest.html

**Comment by deusxanime** [comment]
@erengy any luck getting spring 2017 in? haven't seen it come over yet

**Comment by erengy** [comment]
Spring 2017 season is now available for v1.2.5 users. If it doesn't appear automatically at the Seasons page, try using the *Help → Check for updates* menu item. You'll see a "Taiga is up to date" message, but it will silently download the latest season data in the background.

If you're using v1.3.0-alpha and downloaded it before 387bdcfb14eb5c4b524c045277fccc3f999da0d3, please re-download the [latest build](http://taiga.moe/latest.html).

**Comment by tophf** [comment]
@erengy or WIMC:

```
# Nobunaga no Shinobi -> ~ Ise Kanegasaki-hen!
- 32829|11871:27-? -> 34978|?:1-?!
```

This is a S2 rel info I've added locally and it seems to work.

**Comment by Kadantte** [comment]
Hi , Why not u create a Python Script for do that ?!

**Comment by tophf** [comment]
>Why not u create a Python Script for do that ?!

Python doesn't have a built-in html parser which is as easy to use as that provided by a browser.
It'd be relatively easy to convert my script above to python with lxml, though, but personally I'm content with what I have.
