### ISSUE TITLE
Taiga not downloading torrents properly

### ISSUE THREAD

**Issue by musicexam** [erengy/taiga#394]
It gives the following error when I click the download button.
Torrent download error: Invalid content type: text/html; charset=UTF-8

Any idea how to resolve this?

**Comment by erengy** [comment]
Which torrents do you have problem with? Could you give an example so that I can reproduce the error?

Please see #228 and #255 for more information.

**Comment by musicexam** [comment]
I was having an issue with [HorribleSubs] Seikaisuru Kado - 01 [1080p].mkv from tokyotosho.
After discarding it, I could download the rest. Thanks!

**Comment by erengy** [comment]
This is the same issue as #228, then. Trying to download [the torrent](https://www.tokyotosho.info/details.php?id=1085377) via a browser [returns this error](https://www.nyaa.se/?page=view&tid=914700) too:

> The torrent you are looking for does not appear to be in the database.

This issue is not related to Taiga, but I'll be improving the error message shortly.
