### ISSUE TITLE
Is there a way for taiga to recognize episodes continuing from different seasons?

### ISSUE THREAD

**Issue by musicexam** [erengy/taiga#396]
I'm downloading Shingeki no Kyojin S2 and Boku no Hero Academia S2 from HorribleSubs. For some reason, they decided to number it as continuing from the first season; e.g. S2E01 is numbered E14.

When downloaded through taiga, it shows up as episode 14 in the Progress bar. Is there a way to configure taiga so that it doesn't do that, but shows up as episode 2?

**Comment by erengy** [comment]
This numbering scheme is so common that Taiga uses [a special database](https://github.com/erengy/anime-relations) to handle it. [Shingeki no Kyojin Season 2](https://github.com/erengy/anime-relations/blob/8d3b79ab81f48a4c8a70c52d7d5bddc4a744a638/anime-relations.txt#L602-L603) and [Boku no Hero Academia 2nd Season](https://github.com/erengy/anime-relations/blob/8d3b79ab81f48a4c8a70c52d7d5bddc4a744a638/anime-relations.txt#L100-L101) are both available this database, so Taiga should already be able to redirect the episodes. If it doesn't work for you, try these:

- Use the *Help → Check for updates* menu item to get the latest anime relations.
- Remove any alternative titles you added to the series in question.

**Comment by zienith2017** [comment]
1.3.0-alpha for me this worked for Hero Academia but not Shingeki no Kyojin.

**Comment by erengy** [comment]
@zienith2017 1.3.0-alpha didn't support anime relations for a while. If you downloaded it before 29884565b817bff76a6c3e2f7a842138dae6b51e, please re-download the latest build and then use the *Help → Check for updates* menu item.

**Comment by zienith2017** [comment]
@erengy Well, that was strange. It didn't seem to work for the first episode but it did for the second. I will redownload anyways. thanks
