### ISSUE TITLE
Taiga does not detect when Plex web player stops playing.

### ISSUE THREAD

**Issue by nakedpantsu** [erengy/taiga#400]
Hi,

I recently started using Taiga and while it's doing great at detecting when Plex plays a video, as the title says, Taiga does not detect when Plex stops playing/streaming.

So the episode that played is just stuck on Now Playing in Taiga and is not able to detect new videos playing with Plex unless it is restarted.

It goes back to normal when when other players start playing, though.

Thanks in advance and I would greatly appreciate it if this could get fixed.

**Comment by erengy** [comment]
Hi there. Could you give us some information about your setup? For instance, do you have multiple browser windows open? If that's the case, does having only one window fix the issue?

**Comment by nakedpantsu** [comment]
Hi erengy,

I only have 1 tab open for Plex.

Interestingly, I just updated to Win10 Creators Update and the problem seems to have gone away for now.

I'll try to test a bit to see if the problem returns.

**Comment by erengy** [comment]
This is likely the same issue as #227 or a similar one, rather than something specific to Plex.

I'm closing this issue, but let me know if you manage to figure out the circumstances that cause this problem. I haven't been able to reproduce it on my computer so far.

**Comment by nakedpantsu** [comment]
Thanks for looking into this. I'll read up on the other issue you mentioned and try to experiment some more.
