### ISSUE TITLE
Remembering downloaded torrents after a crash

### ISSUE THREAD

**Issue by deusxanime** [erengy/taiga#403]
Not sure if this is a bug or feature request, but I've noticed if Taiga crashes that when I restart it it tries to redownload many of the previous torrents it has already gotten in the past. 

I use a VPN while downloading, and have a killswitch set to kill uTorrent (force close utorrent.exe) if it disconnects. I noticed one time when it did this that Taiga found a new download and automatically caused uTorrent to start again even though the VPN was still down. So I also added taiga.exe to the killswitch, which effectively crashes it as well. That works fine, but as I said above, when that happens and then I restart Taiga it seems to re-grab many torrents that it has already previously grabbed, even days previous sometimes.

Any way to write the current state of downloads (and other stuff as well if needed) more frequently so that when it does crash it doesn't do this? Many times I've already had a renamer go through and change the name of the file so it ends up downloading a release again. I try to remember to "properly" close Taiga occasionally so that it flushes out and isn't too bad when it happens, but would be nice not to have to worry about that.

**Comment by erengy** [comment]
I closed this issue with bc340dd7ca80a0dfe62bc348b78193bf2d9fbbf9, but it's best to avoid crashing Taiga.

Does `Taiga.exe` actually crash with an error message, or does it just disappear? It should be possible to close Taiga gracefully by sending it a `WM_CLOSE` or a similar message. No need to terminate the process, if that's what the killswitch does.

**Comment by deusxanime** [comment]
Unfortunately the VPN app kills/terminates processes, no error or anything it just disappears. I know, not ideal, but don't want Taiga spinning up uTorrent when the VPN is down.
