### ISSUE TITLE
1.3.0 crashing frequently

### ISSUE THREAD

**Issue by gearan** [erengy/taiga#407]
I don't know if you are aware of this issue or not but since it is in alpha I figured I would report it. Frequently for a while now taiga has been crashing. It either just shuts itself down without any notification and when I go to my hidden icons it will show and then disappear or it will give me the windows crashing notice and then crash. I have found that this happens more frequently when I am in the process of watching anime and a new episode starts so I don't know if it was crashing while it is trying to update an anime's episode count.

Just figured you might want to know if you are not aware of it already.

**Comment by erengy** [comment]
When was the last time you downloaded the [latest build](http://taiga.moe/latest.html)? If it's been a while, please try downloading it again. Perhaps I've already fixed the underlying cause.
