### ISSUE TITLE
Support for Recognition of anime playing in Amazon prime

### ISSUE THREAD

**Issue by shubhranild77** [erengy/taiga#409]
Support for Recognition of anime playing in Amazon prime

**Comment by erengy** [comment]
You mean Anime Strike, right? I don't know if it's technically possible to support it, and I don't have the means to try it out. If you can, please provide me the window title and the URL of an episode page. Example from Crunchyroll:

- Title: "Crunchyroll - Watch Hunter x Hunter Episode 1 - Departure x And x Friends"
- URL: http://www.crunchyroll.com/hunter-x-hunter/episode-1-departure-x-and-x-friends-584886

**Comment by wongjn** [comment]
For Amazon Prime (not Anime Strike), videos are like this:

### Re:CREATORS EP14
* Title: “Re:CREATORS : Watch online now with Amazon Instant Video: Daiki Yamashita, Mikako komatsu, Inori Minase, Yoko Hikasa, Rie Murakawa, Ei Aoki: Amazon.co.uk”
* URL: https://www.amazon.co.uk/gp/video/detail/B06Y5HSYLT/ref=dv_web_wtls_list_pr_1

**Comment by erengy** [comment]
Thanks @wongjn. It seems it's not possible to retrieve episode number from Amazon Prime.

**Comment by chikorita157** [comment]
It's possible to detect using Amazon Prime Video's player, but probably not possible from reading the page title on it's own. One has to use JavaScript to accomplish this. On the player screen, if you mouse over, it will show the title and episode. It's most certainly possible to make it work through a browser extension on Windows. On a Mac, I can accomplish the detection by simply sending JavaScript commands through AppleScript.

This is what I used to retrieve the show titled episode.

document.querySelector('.title').innerHTML
document.querySelector('.subtitle').innerHTML

**Comment by Predelnik** [comment]
Possible solution is to modify document title through e.g. TamperMonkey, it can also simplify title specifically for Taiga (so if for example several services would require such treatment, the format could be the same), the only problem is having custom urls supported in some way then.
