### ISSUE TITLE
Support Kitsu's rating system changes

### ISSUE THREAD

**Issue by wopian** [erengy/taiga#411]
Kitsu now has 3 (10 point is returning soon) rating systems that map to a 20 point scale. `/users` has a new attribute `ratingSystem` which is either `simple`, `standard` or `advanced`

### Simple
- Rating drop down should show:
  - Awful
  - Meh
  - Good
  - Great
- Mapped to `2`, `8`, `14`, and `20` respectively
- Score distribution:
  - Awful (2-5)
  - Meh (6-10)
  - Good (11-15)
  - Great (16-20)

### Standard
- The old `0.5..5` ratings
- Mapped to `2..20`

### Advanced
- Rating drop down & score distribution should include `1..10` in `0.5` increments
- Mapped to `2..20`

--- 

Library entries should send `ratingTwenty` as an integer instead of `rating` as a string

To unrate send `null`

`rating` will switch to the new system once most API users have migrated to `ratingTwenty`

**Comment by erengy** [comment]
Taiga now supports all rating types from Kitsu (see 77ca87f...c1bec32).

You may try out the [latest build](http://taiga.moe/latest.html) as usual.
