### ISSUE TITLE
Error: "Invalid page value: Limit exceeds maximum page size of 500" when refreshing

### ISSUE THREAD

**Issue by sposterkil** [erengy/taiga#413]
Managed to corrupt my local DB somehow, so I nuked it and fresh-installed Taiga by:

1. downloading the 1.2 release
2. installing
3. launching once
4. closing
5. replacing Taiga.exe with the taiga.moe/latest.html build

Launched that exe, entered Kitsu credentials, and on hitting refresh the footer reads 

> Kitsu returned an error: "Invalid page value: Limit exceeds maximum page size of 500"

Can provide logs or anything else if you tell me where to look for them. :)

**Comment by ovingiv** [comment]
This is fixed with the latest build here > http://taiga.moe/latest.html

**Comment by sposterkil** [comment]
Lol, I literally just saw 9fdc6d78. which I assume fixes.  Thanks!
