### ISSUE TITLE
Automatic Subfolder creation using magnet links

### ISSUE THREAD

**Issue by kasokz** [erengy/taiga#414]
Now that Nyaa is gone, I have switched to mainly downloading through magnet links from HorribleSubs feed. 
Since that switch the automatic subfolder creation and moving files to their corresponding folders doesn't work anymore.
I am using Deluge with deluge-console as default torrent client in the settings.
Does anyone know how to get this to work when not downloading the torrent file beforehand but with magnetlinks?

**Comment by wiiaboo** [comment]
Just handling magnets the same way as .torrents does it: https://github.com/wiiaboo/taiga/commit/897a79d12e, as long as the torrent client supports magnet URIs (deluge, µtorrent, qBittorrent all support them).

**Comment by ildmg** [comment]
Sorry but I have the same issue, using uTorrent. Before switching from Nyaa everything was working normally. As soon as I changed RSS feeds (like this http://i.imgur.com/chl8rJX.png ) all my torrents are going straight to the Download folder and not to my Anime folders anymore (even if they are set and I didn't change anything).
This is uTorrent configuration, it was working before (I assume Taiga had priority over this): http://i.imgur.com/J0dKRZt.png
I've tried to disable both checkboxes for the Downloads too, but unfortunately it changes nothing.
Everything goes straight to my Download folder now.

Does anyone have any advice about this? Is it related to magnets or just to the RSS feed I'm using?

**Comment by wiiaboo** [comment]
It's due to usage of magnet URIs. Taiga for some reason just leaves magnet URIs to be handled by the OS instead of pointing the link to the torrent client like with .torrent files.

**Comment by ildmg** [comment]
Hmm I was looking into this but apparently now nyaa.si (which I'm using) is distributing .torrent files and not only mangets.
The RSS feed (https://nyaa.si/rss?c=1_2&f=0) has torrents as links, so it should work, I think. 
I really don't get why everything now goes to the Download folder, everything seems set up correctly, as it was before switching from Nyaa.
Maybe the term search with %title% (https://nyaa.si/rss?c=1_2&f=0&q=%title%) is somehow wrong and can't parse the titles correctly?

**Comment by wiiaboo** [comment]
I just said the exact reason why. Either use feeds that only point to .torrent files or wait for erengy to fix it.

**Comment by ildmg** [comment]
This is an example of a link in nyaa.si RSS feed: <link>https://nyaa.si/view/923339/torrent</link>
Not a magnet URL, points to a .torrent file.
I see that the links in panstu.cat feed are magnets, but in nyaa.si they look like torrents to me. 
That was what I was pointing out in my previous post. 
If they are still not compatible somehow, too bad I'll wait for a fix. Thanks anyways for your replies.
