### ISSUE TITLE
Allow multiple RSS feed sources

### ISSUE THREAD

**Issue by Ruhrpottpatriot** [erengy/taiga#415]
this ties heavily into #410 
Since there's no nyaa.si which is supported by HS, it seems we're going to get multiple "nyaas".
I propose that the program allows for multiple feed sources. The process could look like this:

The user adds as many feeds as he wants. Taiga then checks each of them subsequently, displaying the results as it is not. Items with the same name are not added to the list again.

This should strongly help mitigate the effects another nyaapocalypse, should it happen at some time.

**Comment by erengy** [comment]
As I mentioned in #410:

> There's also a plan to check multiple RSS feeds (see #40), but I doubt this is going to happen anytime soon.
