### ISSUE TITLE
Support for Recognition of anime playing on VRV.CO

### ISSUE THREAD

**Issue by num421337** [erengy/taiga#422]
It should be fairly easy considering they list the show and episode number in the tab.

**Comment by num421337** [comment]
also considering the funimation/crunchyroll tie-ins it has it's getting fairly popular

**Comment by erengy** [comment]
Added in 01bdc60a4bfa218155454501d6fa04ce6f99aef8, but needs some additional work for proper detection. Currently recognition is reset every five seconds due to a long-standing bug, which should be resolved after media detection code is replaced by Anisthesia and relevant modifications are made.
