### ISSUE TITLE
Anime Seasons

### ISSUE THREAD

**Issue by vonkun** [erengy/taiga#423]
Hello , can you please Add the new Data of Anime season cuz Data is out of date , or u can share with us the meathod to get that Data from MAL ...

**Comment by erengy** [comment]
From the [FAQ page](http://taiga.moe/#support):

> **When are you going to add the upcoming anime season?**
> [Season data](https://github.com/erengy/anime-seasons) is usually updated right before the majority of a season's new series begin. That means you'll get the update around the first week of January, April, **July** or October, depending on the season.
