### ISSUE TITLE
Taiga not recognizing files played from mpv

### ISSUE THREAD

**Issue by nmoorthy524** [erengy/taiga#424]
I'm using the latest build available here: https://mpv.srsfckn.biz (4/23 as of writing). The same thing happens on the previous build as well. Taiga was working fine with both builds before but recently it has stopped recognizing shows when playing through mpv. Playing the same episodes through MPC-BE and they are recognized just fine.

See the image here:
![untitled-1](https://user-images.githubusercontent.com/6493496/26934712-06e93cfc-4c1f-11e7-8a19-6c8741188626.jpg)

This is using Taiga 1.2

**Comment by erengy** [comment]
It looks like Taiga is unable to get the filename from mpv and falls back to using the window title.

Could you try running Taiga as administrator and see if it makes any difference? If that doesn't work, you can also try configuring mpv so that the window title displays nothing but the filename.

**Comment by nmoorthy524** [comment]
Yes, when I set the window title to just the filename, it seems to pick it up. Weird because it was able to detect the show correctly with all of the extra information added before.
