### ISSUE TITLE
HTTP Requests send update without clicking Update

### ISSUE THREAD

**Issue by Moravuscz** [erengy/taiga#429]
As the title says, it think this shouldn't be happening.
![clipboard01](https://user-images.githubusercontent.com/5168699/27001861-dbbaa316-4dd3-11e7-876c-8fe025b72438.png)
![clipboard02](https://user-images.githubusercontent.com/5168699/27001862-dbbad3e0-4dd3-11e7-95e3-5534a8b6dcb4.png)
The images show that I didn't click Update, yet my script has received a request with update.

My settings in Taiga currently:
![obrazek](https://user-images.githubusercontent.com/5168699/27001885-742f8850-4dd4-11e7-8a9e-9490a2418143.png)
![obrazek](https://user-images.githubusercontent.com/5168699/27001894-c7919132-4dd4-11e7-8807-724acd83be80.png)
(I should probably add some sort of a security key in the body, so that only I can poke my DB... soon™. If anyone's interested, I'll gladly share my script and DB table template for this.)

**Comment by erengy** [comment]
Hi there, and sorry for the late reply.

Taiga should be posting three HTTP requests in the following order:

1. When the delay time (30 seconds) is up: `%playstatus%` is `playing`
2. When the media player is closed: `%playstatus%` is `stopped`
3. When you confirm to update your list: `%playstatus%` is `updated`

Could it be that your script doesn't handle the `stopped` status properly?

**Comment by Moravuscz** [comment]
Let's see...
Step-by-step.

1) Open an episode
![obrazek](https://user-images.githubusercontent.com/5168699/28338543-9bc791de-6c09-11e7-9e86-884da37bfb32.png)

2) %playstatus% goes playing
![obrazek](https://user-images.githubusercontent.com/5168699/28338608-ce51f388-6c09-11e7-8fca-847be28c2055.png)

3) Stopped watching, didn't close player yet
![obrazek](https://user-images.githubusercontent.com/5168699/28339118-50b9794e-6c0b-11e7-8b38-de0d09cd96d1.png)
No change to %playstatus% yet, as you said it should be.

4) Closed player, %playstatus% should now have sent stopped and it did (according to log)
![obrazek](https://user-images.githubusercontent.com/5168699/28339356-33127aac-6c0c-11e7-96a5-382fc963fc35.png)

5) Clicked Update, %playstatus% did indeed send updated
![obrazek](https://user-images.githubusercontent.com/5168699/28339422-71a00b7c-6c0c-11e7-9f73-785b4b10f964.png)


It seems you're right... I seem to have done something I myself can't comprehend why.
![obrazek](https://user-images.githubusercontent.com/5168699/28339646-16f1d65a-6c0d-11e7-87ab-2ff0e8a9ee40.png)
Yep, I probably intended to work with stopped as well and ditched it in the process without realizing it...
*lost in thoughts* Maybe if I put a little check in the beginning if there are any records that are stopped when I receive playing for that combination of anime_id and ep... yeah... oh wait, I did... and it's a mess... gotta rework that.

I'm an idiot and this is what I get for late-night coding... I'm sorry for not seeing this and thinking this was a bug on your side.
Maybe I should've fiddled more with RequestBin and examine closely what happened when.
Thanks for opening my eyes Eren, I appreciate it. Your tip was right on spot.
