### ISSUE TITLE
Can't add anime to my list.

### ISSUE THREAD

**Issue by Kevinl581** [erengy/taiga#432]
When I try to add a new anime to my list, it says that the anime is already in my list. It does add it onto my list but the history of it is always there and keeps popping up saying that the same anime I was trying to add is already on my list. It never goes away, and when I delete the history of it, the anime in my list also disappears.

**Comment by erengy** [comment]
Once your update queue is empty, hit the Synchronize button once more to re-download your list.

I'm closing this issue, since it was resolved in 4bf3362dd5b95e3f552e794273dfb5b7abb239ae. See #357 for more information.
