### ISSUE TITLE
Ask to rate series after finishing last episode

### ISSUE THREAD

**Issue by Yozora80** [erengy/taiga#433]
Whenever I watch the last episode in a series, I would also like to rate the anime, but the current process is a little annoying: Complete the anime, try to find it in the completed tab (which gets very long, and sometimes you can forget the japanese name to the anime making very hard to find), and then rate it. It would be helpful if it just asked me when I finished.

(Also, I love this program, thank you for making it. :) )

**Comment by erengy** [comment]
We have an open issue about this at #110, so I'm closing this one.
