### ISSUE TITLE
qBittorrent Automatically Selecting Subfolder

### ISSUE THREAD

**Issue by nekosaurus** [erengy/taiga#437]
Not sure if this is really taiga related, but I recently made the switch from uTorrent to qBittorrent and one of the features that didn't transfer over was the torrent client being able to download anime to their specific subfolder. Is this possible to do in qBittorrent?

**Comment by erengy** [comment]
As it's noted in the Settings dialog, this feature is only supported by Deluge (deluge-console) and uTorrent. See #86 for more information.

Good news is that qBittorrent recently added the necessary command-line arguments, although they weren't included in their v3.3.13 release. I'm now waiting for their next release, probably v3.4.0, which will include the command-line arguments.
