### ISSUE TITLE
Bitdefender detects infected web resource

### ISSUE THREAD

**Issue by ThereisnoLion** [erengy/taiga#440]
When starting Taiga, I got a notification from Bitdefender as follows. https://snag.gy/FYlPMc.jpg

Probably a false positive, but I thought I should probably report it anyway.

**Comment by Abchrisabc** [comment]
I have BitDefender as well and it looks like it blocks the complete taiga.moe domain. 
[https://puu.sh/wHel9/0a177d7318.png](url)

**Comment by Abchrisabc** [comment]
I just put up a ticket for a false positive on the BitDefender site.

**Comment by Abchrisabc** [comment]
I haven't gotten a reply on the ticket yet (I doubt they will.) although BitDefender seems to have updated the CVD through a Signature update. I am not getting any blocking messages anymore.

**Comment by erengy** [comment]
False positives happen from time to time, unfortunately. I couldn't find any way to avoid it, so I just report any issues to AV companies (as in #159).

In this case, I have no idea why BitDefender considers taiga.moe domain infected. Infected with what, an RSS feed for application updates?

Anyway, thanks @ThereisnoLion for reporting the issue, and thanks @Abchrisabc for the ticket!
