### ISSUE TITLE
Scanning on a Google Drive File Stream causes Taiga to freeze permanently

### ISSUE THREAD

**Issue by ripdog** [erengy/taiga#443]
Hello, and thanks so much for Taiga!

I've been keeping the bulk of my anime on Google Drive recently, due to the cheap unlimited offer. To access it locally easily, I've been using two apps which mount it as a local drive - ExpanDrive and Google Drive File Stream.

With expandrive, Taiga is perfectly capable of scanning my entire collection. It takes a while, but completes.

With file stream, taiga spins forever trying to scan. There is no disk activity or network activity on the file stream or taiga processes. There's nothing recent in the taiga logs. Taiga continues to use ~10% of my CPU and won't close even from task manager.

File stream is in early access right now, so it's not available to most people. I uploaded the installer here: https://www.mediafire.com/?07s8ta70ym451rs - I hope it works for google accounts not in the program. 

If I can help debug, do tell!

**Comment by erengy** [comment]
Hi there @ripdog,

Thanks for the installer, but Google doesn't allow me to try it out, unfortunately. I see a "not enabled for your account" error instead.

As you mentioned that scanning files works with one program but not with the other, I'm inclined to think that Google's implementation doesn't communicate well with Windows APIs yet. From what I read on the web, it seems to have lots of issues at the moment. Perhaps we should wait for it to mature for a while, before diving into it.

Still, I compiled an [executable file](https://github.com/erengy/taiga/files/1187679/files.zip) for you to test. It contains just the [file search](https://github.com/erengy/taiga/blob/e6c1288d8d3a4352001c12035e0ce4d2e257d325/src/base/file_search.cpp) code from Taiga. Assuming that your Google Drive is mounted as `X:\`, simply execute `files.exe "X:\Some Directory"` and see if it's able to list all the files in that directory.

**Comment by ripdog** [comment]
Oh man, that is service for you. I can't believe you put so much effort into my little bug! Thank you!

`files.exe` was the perfect debugging tool. it turns out that it can list all the files in my google drive (surprisingly quickly), with the sole exception of my Angel Beats directory. It failed the exact same way as Taiga, utterly unquittable and using 10% CPU.

See, I somehow managed to make qbittorrent freak out and it made a gigantic (100+) stack of the same empty folder inside the same empty folder, all named `[Coalgirls]_Angel_Beats!_(1920x1080)`. 

Because the filenames at the bottom of the stack are so long, no tool (that I've found) on windows can delete the folders. At some point I was planning on booting to linux and trying to delete it from there, but in the meantime, it seems the gigantic stack was synced to google drive.

I'm not sure why File Stream triggered the error and not ExpanDrive, but either way - it's a minute edge case, and I was able to delete the folder from Google Drive, allowing both files.exe and Taiga to complete their scans.

What's your paypal? I'd love to leave you a tip for being an awesome FOSS maintainer :)

**Comment by erengy** [comment]
Thank you very much for your offer. I currently don't accept donations, but I do have a little initiative going on. Quoting myself from the [FAQ page](http://taiga.moe/#support):

> **How can I donate to Taiga?**
>
> Since 2008, Taiga has been developed and maintained by [a single person](http://erengy.com), for the most part. While getting paid for his efforts would provide some motivation, he'd very much appreciate it if you spent the money on a better cause.
>
> If you'd like to donate to Taiga, please consider saving the life of a real tiger instead. We suggest supporting non-profit organizations such as [21st Century Tiger](http://www.21stcenturytiger.org) and [Big Cat Rescue](https://bigcatrescue.org). [Let us know](https://github.com/erengy/taiga/issues/89) if you have any suggestions in this regard.

I'll consider this issue resolved, but feel free to comment further if you need anything else.
