### ISSUE TITLE
Crashes on boot

### ISSUE THREAD

**Issue by sugoooi** [erengy/taiga#444]
This seems like a really cool piece of software.
However, I cannot get to use it as it crashes right after the executable has been opened.

**Comment by erengy** [comment]
If you're using v1.3.0-alpha with Kitsu, it might be because of the same reason as [this one](https://github.com/erengy/taiga/issues/412#issuecomment-317256255). Otherwise, please provide some additional information so that we can figure out why it crashes for you.
