### ISSUE TITLE
Taiga detects visiting the Google Play Store as streaming anime

### ISSUE THREAD

**Issue by reconman** [erengy/taiga#449]
By coincidence I stumbled over some weird behavior of Taiga. When you visit the page https://play.google.com/store/apps/details?id=com.aniplex.fategrandorder.en it will tell you that "Fate/Grand Order (English)" is not in your list of shows.

I can't find anything in the whole VS project that acts when google.com pages are visited.

I'm using a self-compiled version of Taiga including the latest commits.

**Comment by facelesspanda** [comment]
it doesn't for me using the latest stable official download, so that's new.

**Comment by erengy** [comment]
Seems to be caused by 1aca6080a3014241aece45df89991a69a1600a51, which detects `plex` of `aniplex`. I'll try to fix this tomorrow.

**Comment by reconman** [comment]
Replacing
`SearchRegex(url, L"plex\\.[a-z0-9-]+\\.[a-z0-9-]+") ||`
with
`SearchRegex(url, L"\\/plex\\.[a-z0-9-]+\\.[a-z0-9-]+") ||`
fixed the issue.
