### ISSUE TITLE
RSS for AnimeBytes not working

### ISSUE THREAD

**Issue by AbelToy** [erengy/taiga#452]
The AnimeBytes RSS is not working, due to Anime titles being displayed like this (instead of just the anime title): 
![image](https://user-images.githubusercontent.com/147130/29496760-77c237fa-85d9-11e7-9a53-2cdd3780ac81.png)

**Comment by NfernoFire** [comment]
Try and run Taiga in [debugging mode](https://github.com/erengy/taiga/wiki/How-to-run-Taiga-in-debug-mode)

Check your torrent tab and adjust your filters accordinlgly.
Hope this helps!

**Comment by AbelToy** [comment]
@NfernoFire this is mostly based on the fact Taiga isn't ready to parse the RSS format of AnimeBytes. It's not a bug per-se, mostly a missing feature

**Comment by erengy** [comment]
Hey @AbelToy. Could you send me an invite for AnimeBytes, if you're able to? (My email address is available at my GitHub profile, if required.) I'd like to do some tests, and the easiest way for me would be to have access to their RSS feed.

**Comment by AbelToy** [comment]
Thank you, works perfectly!
