### ISSUE TITLE
Size column seems to be bugged

### ISSUE THREAD

**Issue by chynabrack** [erengy/taiga#453]
It's been bothering for a while but the size column is like this (I am using nyaa.si as RSS feed):
![untitled](https://user-images.githubusercontent.com/31291075/29635969-e4699f2a-881c-11e7-9481-2aeec6076c4e.png)

**Comment by Vesnyx** [comment]
Check #410 and was fixed in https://github.com/erengy/taiga/commit/73a7327dc4c2eeeae856f7441143bf4a38899737

**Comment by chynabrack** [comment]
Oh, I see. Thanks for answering
