### ISSUE TITLE
Taiga not recognizing players installed by LAV Filters Megamix

### ISSUE THREAD

**Issue by xchimp** [erengy/taiga#454]
Taiga doesn't seem to be recognizing players that [LAV Filters Megamix](https://www.videohelp.com/software/LAV-Filters-Megamix) install (MPC-HC, PotPlayer, and MPDN). Installed on their own they are recognized, but not when installed using this installer.

**Comment by erengy** [comment]
This was recently fixed when we switched to a new media detection library (see #315 and #435 for previous issues). You may try out the [latest build](http://taiga.moe/latest.html) to see if it works for you.

**Comment by xchimp** [comment]
Yep, that fixed it, thanks.
