### ISSUE TITLE
Taiga recognises WebTorrent Desktop as an unrecognised anime

### ISSUE THREAD

**Issue by hetnialoevr48** [erengy/taiga#456]
WebTorrent Desktop is a program where you can play torrents as their downloading, you can download it [here](webtorrent.io)

Every time I open WebTorrent Desktop [it "recognises" the program as an unrecognised anime](http://prntscr.com/ggcx3e)

Changing the media player to VLC from the built in media player in WebTorrent Desktop's settings doesn't really fix this. When I do this, it will sometimes detect the anime I am watching and sometimes detect WebTorrent Desktop.

Is it possible for me to make it so that Taiga doesn't detect WebTorrent Desktop as an unrecognised anime? If it is possible, how? If it is not, can you make it so that Taiga doesn't detect WebTorrent Desktop as an unrecognised anime in a future update? I think this would be an easy thing to do and I would be glad if you did it.

And is it also possible for you to make it so that Taiga recognises WebTorrent Desktop's built-in media player as a media player in a future update? I don't think this is possible and if it is possible I think that it would be tricky, since WebTorrent Desktop is a torrent client with a built-in media player, not just a media player, but I would be very glad if you somehow did it.

**Comment by erengy** [comment]
This was recently fixed when we switched to a new media detection library. Could you try out the [latest build](http://taiga.moe/latest.html) and see if it works for you?
