### ISSUE TITLE
"Could not load anime season data."

### ISSUE THREAD

**Issue by loishiin** [erengy/taiga#457]
Hello,

I have not been able to access any season information on taiga.
When I try to check any season I get the message "Could not load anime season data.", after that the screen and the message keeps flickering like it's trying to download or access the data but without success and I have to close and re-open taiga otherwise it won't stop.
If I remember correctly, I used to be able to check seasons normally when they were added manually but since then I have not been able to.

I'm using taiga version 1.2.5.
This is the installation directory: C:\Users\Déc\AppData\Roaming\Taiga\
Maybe the fact that my name has a special character could be causing problems with taiga accessing the folders but I'm not sure.
Also trying to run taiga as administrator didn't help.

I don't know what other information I could give to help narrow down the problem.

Thanks.

**Comment by erengy** [comment]
Hi there @loishiin, and thanks for the detailed report.

I recall someone having a similar issue with having `Agustín` as their username, so I imagine that it's indeed related to the special character somehow. I'll look into this.

**Comment by loishiin** [comment]
Sorry, I should have posted it before but I didn't know about the debug mode.

I don't know if this helps but I noticed this line on my log.

[Warning] discover.cpp:65 library::SeasonDatabase::LoadFile | Could not find anime season file.
Path: C:\Users\Déc\AppData\Roaming\Taiga\data\db\season\2017_summer.xml

I checked and the file '2017_summer.xml' do exist, but apparently taiga can't find it.

[Taiga.txt](https://github.com/erengy/taiga/files/1283349/Taiga.txt)
This is basically a 10 seconds log after I tried opening the season on taiga.
I removed a big part of it since I didn't know what part contains sensitive data, sorry if I removed too much.

I hope this helps.

**Comment by erengy** [comment]
Should be fixed with ccf3f3bbfd5e1d567179af2e97198edaea551aaa. You may try out the [latest build](http://taiga.moe/latest.html) to see if it works for you.

**Comment by loishiin** [comment]
Thank you very very much. I'm able to access the seasons tab with version 1.3.0-alpha.

The only thing I noticed but this may be completely unrelated is that some titles even after hiting the "Refresh data" button, they would not load all the information and a message at the bottom: "MyAnimeList returned an empty response".

Imagens showing the message at the bottom and the missing information:
![01](https://user-images.githubusercontent.com/31675741/30236109-299ab8c6-94e9-11e7-8a42-906f646d046a.jpg)
![02](https://user-images.githubusercontent.com/31675741/30236111-331915fa-94e9-11e7-921c-3bf7d5609b6b.jpg)

This could be just my shitty internet, but I thought it was worth mentioning.

Thank you again :)

**Comment by erengy** [comment]
I've taken some other precautions now in c298594f0ec6d64ec0b4e1ca1342b5221d4de7f0 and 6f86c80511d6bcf93706723b66fee164a79078fe, so I'll consider this issue fixed.

*"MyAnimeList returned an empty response"* message is mostly due to various shortcomings of MyAnimeList API: It doesn't provide a way to retrieve information using anime IDs, its search method doesn't work properly in some cases, it applies undocumented rate limiting on clients... Here's hoping they bring forth a new API soon enough.
