### ISSUE TITLE
[Feature Request] "Delete watched episodes" button

### ISSUE THREAD

**Issue by KikunXyy** [erengy/taiga#459]
Hello.

First of all, awesome work! Downloading episodes has never been so easy!

A suggestion I have is to have options somewhere to delete watched episodes:
1. File > Delete all watched episodes
2. Right click any series > Delete watched episodes

I only keep episodes I haven't watched to save space, so this would really help a lot!

**Comment by erengy** [comment]
Hi, this seems like the same issue as #187, so I'll be closing this one.
