### ISSUE TITLE
[Media player] SMPlayer

### ISSUE THREAD

**Issue by Stonedestroyer** [erengy/taiga#460]
Possible to add support for SMPlayer?

**Comment by erengy** [comment]
Taiga already supports SMPlayer. In fact, it's been supported for at least 7 years now.

Lately we had some issues detecting it (as in #133), but this was recently fixed when we switched to a new media detection library. You may try out the [latest build](http://taiga.moe/latest.html) to see if it works for you.

**Comment by Stonedestroyer** [comment]
Thanks that seems to worked or the run as admin. I am also using SVP so using their custom build of mpv with SMPlayer. But this seems to work so it can be closed! Thanks!
