### ISSUE TITLE
Seedbox and Sonarr Integration

### ISSUE THREAD

**Issue by ricksee** [erengy/taiga#461]
Is it possible in the future that we can link torrents to a server such as a seedbox so we can watch on the go with Plex or something. With the addition of Sonarr it can really help with our anime library.

**Comment by erengy** [comment]
I'm not familiar with seedboxes or Sonarr, so could you elaborate on the setup you have in mind?

**Comment by ricksee** [comment]
@erengy Well a seedbox is like a remote server for your torrents. You have the server address and login info and if you add it you can add torrent files onto it. Instead of saving it to our computer we can instead sent the torrent to the server and it will download the episodes there.And with Sonarr it organizes your library. and rename episodes to any format you choose.

**Comment by erengy** [comment]
What specific features does Taiga need to be a part of this setup? Would it simply be posting the .torrent files to a remote server, rather that opening them with a local client? If that's the case, I'd imagine you could already do this by using an intermediate application (i.e. *Settings → Torrents → Downloads → BitTorrent client → Use a custom application*).

**Comment by ricksee** [comment]
Basically just like you said just send the torrent files over to the server, similar to FTP. All I have to do is to make sure the server info is setup like hostname, username, password, port, and default download location for the files.

**Comment by ricksee** [comment]
It would also to allow automatic downloads of preferred quality and/or uploader. For instance, if I only wanted torrents of X show from X uploader in 1080p quality only, whether I want all episodes, all missing episodes, those that aired, or those that will air.

**Comment by ricksee** [comment]
Like this.
![capture](https://user-images.githubusercontent.com/21182549/30253982-b6051574-965e-11e7-9832-12d3be5e91f4.PNG)

**Comment by sachaw** [comment]
Your seedbox is just an rTorrent container, @ricksee I suggest you rethink your workflow here, it would be far easier to pass your rss into rTorrent/ruTorrent and use https://github.com/autodl-community/autodl-irssi or some other form of auto downloading and post completion moving tool (which ruTorrent has) and move them onto your pc where taiga can see them or setup an network share with SAMA (easy to do on your seedbox).
This will remove the need for an integration, I doubt this would ever work anyway due to the nature of rTorrent, unless you got taiga integration for an rTorrent windows GUI app.

**Comment by ricksee** [comment]
@sachaw To be honest I don't know what you just said.

**Comment by sachaw** [comment]
sorry, @ricksee basically, you going about it the wrong way, you can till achieve the same results but exclude taiga from the mix, what you want to do is have your torrent application to handle your rss feed for example https://nyaa.si/?page=rss or http://horriblesubs.info/rss.php?res=1080 and then point taiga/sonarr to the directory where they downloaded to and your done.

Taiga is not suited for your intended use case, but it is still a very useful tool to manage your collection.

**Comment by sachaw** [comment]
@ricksee If you want a hand setting up any of this, I'd be happy to help you over discord/skype etc.

**Comment by ricksee** [comment]
@sachaw Thank you for the response. If you can whenever your available. This will be great.

**Comment by erengy** [comment]
Did you talk about this? Should I consider this issue resolved?

**Comment by sachaw** [comment]
@erengy I'd consider it closed as this has nothing to do with taiga @ricksee hit me up on discord: sachaw#5079 or email me.
