### ISSUE TITLE
Unable to build dependencies

### ISSUE THREAD

**Issue by netrac** [erengy/taiga#462]
When attepting to build dependencies this error pops up:
```Initializing environment...
**********************************************************************
** Visual Studio 2017 Developer Command Prompt v15.0.26730.15
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x86'
Configuring libcurl...
The system cannot find the path specified.
The system cannot find the path specified.
Building libcurl for Debug configuration...

Microsoft (R) Program Maintenance Utility Version 14.11.25508.2
Copyright (C) Microsoft Corporation.  All rights reserved.

NMAKE : fatal error U1052: file 'Makefile.vc' not found
Stop.
File not found - lib
0 File(s) copied
Building libcurl for Release configuration...

Microsoft (R) Program Maintenance Utility Version 14.11.25508.2
Copyright (C) Microsoft Corporation.  All rights reserved.

NMAKE : fatal error U1052: file 'Makefile.vc' not found
Stop.
File not found - lib
0 File(s) copied
Done!
Press any key to continue . . .
```
This has been attempted on a fresh copy

**Comment by erengy** [comment]
Just tried doing it myself with a fresh copy, and had no issues. But I get the same errors as you if I manually delete the `deps\src\curl\` directory.

Could it be that you forgot the `--recursive` option while cloning Taiga? It seems like git wasn't able to clone the submodules, or at least libcurl. Retrieving the missing files via something like `git submodule update --init --recursive` should work.

**Comment by netrac** [comment]
I have run the comand you mentioned as well as redownloading the repo with the --recursive flag again with the same results.

**Comment by erengy** [comment]
The only other possibility I can think of is that the current directory is different than `taiga\deps\` when you execute `build.bat`, which is why the script is unable to locate the files.

**Comment by netrac** [comment]
Nope same directory
```
PS M:\Repos\taiga2\deps> .\build.bat
Initializing environment...
**********************************************************************
** Visual Studio 2017 Developer Command Prompt v15.0.26730.15
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x86'
Configuring libcurl...
The system cannot find the path specified.
The system cannot find the path specified.
Building libcurl for Debug configuration...

Microsoft (R) Program Maintenance Utility Version 14.11.25508.2
Copyright (C) Microsoft Corporation.  All rights reserved.

NMAKE : fatal error U1052: file 'Makefile.vc' not found
Stop.
File not found - lib
0 File(s) copied
Building libcurl for Release configuration...

Microsoft (R) Program Maintenance Utility Version 14.11.25508.2
Copyright (C) Microsoft Corporation.  All rights reserved.

NMAKE : fatal error U1052: file 'Makefile.vc' not found
Stop.
File not found - lib
0 File(s) copied
Done!
Press any key to continue . . .
PS M:\Repos\taiga2\deps>
```
I can try to build the deps manually to see if it works

**Comment by koteq** [comment]
I had VS2017 installed. When I tried to build Taiga VS shows me an error: `Element <LanguageStandard> has an invalid value of "stdcpp17"`. I had to update VS to fix that.

I was unable to build fe6f444 until I change [this line](https://github.com/erengy/taiga/blob/fe6f444683970ecf2b3653f3c3c9314d0aaf0b7a/src/base/time.h#L26) to `#include <date\include\date\date.h>`. Maybe I just messed with submodules somehow.

Also I would really love to see `git submodule update --recursive --remote --init` command somewhere on the [How to Compile](https://github.com/erengy/taiga/wiki/How-to-Compile) page. I miss it every time. Or should it be `git submodule sync`?



Sorry for offtopic. I didn't want to create an new issue for this.

**Comment by netrac** [comment]
got a Done! in the end So I guss the commit fixed it

**Comment by erengy** [comment]
> I was unable to build fe6f444 until I change [this line](https://github.com/erengy/taiga/blob/fe6f444683970ecf2b3653f3c3c9314d0aaf0b7a/src/base/time.h#L26) to `#include <date\include\date\date.h>`. Maybe I just messed with submodules somehow.

Date library's directory structure has [changed recently](https://github.com/HowardHinnant/date/commit/3c3ba6890648b7c4adcfdf082a4c3803d22f5a21), but Taiga's submodule still points to an [earlier commit](https://github.com/HowardHinnant/date/tree/v2.2). Looks like you did mess with it somehow.

> Also I would really love to see `git submodule update --recursive --remote --init` command somewhere on the [How to Compile](https://github.com/erengy/taiga/wiki/How-to-Compile) page. I miss it every time. Or should it be `git submodule sync`?

If you use the `--recursive` parameter while cloning the repository, it will automatically initialize and update each submodule. You don't need to run additional commands that way.
