### ISSUE TITLE
Adding date to previously watched series?

### ISSUE THREAD

**Issue by RedRain77** [erengy/taiga#463]
I started using Mal back in 2014 and I've only just discovered Taiga, I've never added the watched date (due to the fact that I didn't know it existed) but now taiga has been automatically adding the date whenever I watch a series and I'm loving it.

I've got three years worth of anime in my list without a date which sucks, so I was wondering if there was a way to add the date for previously watched series.

I've noticed when I'm viewing my list from within taiga I'm able to sort it by date last updated, maybe this could be used in some way?

Thanks for taking the time to look this over, Keep up the great work :)

**Comment by wenbei999** [comment]
Right click anime > Information > My list settings

or just go to MAL website and edit there

**Comment by wopian** [comment]
^ I wouldn't want to manually do that for >1000 titles

**Comment by RedRain77** [comment]
@wenbei999 , I know I could do it that way but I have no idea the exact date I watched the show but apparently taiga has some idea,

@wopian , Neither would I, it would take ages

**Comment by erengy** [comment]
@RedRain77 Would something like this work for you?

![set-date](https://user-images.githubusercontent.com/1078430/30776955-ac6398d8-a0b8-11e7-9062-1b807a8c0a8e.png)

**Comment by RedRain77** [comment]
@erengy 
Something like that would work great, but I don't seem to have that option.

How did you get to that?

**Comment by wenbei999** [comment]
:o I didn't know you could select multiple ones and do that. Thanks.

**Comment by RedRain77** [comment]
@erengy

Okay, Thanks :)

Do you know when they might be available?
