### ISSUE TITLE
qBittorrent issue

### ISSUE THREAD

**Issue by mrderp** [erengy/taiga#464]
I don't know if this is a issue with qBittorrent or Taiga specifically, but whenever qBittorrent is closed and Taiga automatically snatches more than one torrents to download qBittorrent freezes forcing you to close it from the task manager. It's a little annoyance, not a huge bug or anything but I thought it should be mentioned.

**Comment by erengy** [comment]
Hey @mrderp, thanks for the report. I'm inclined to think that it might be related to a different setting of qBittorrent that you use, perhaps one that's like "do something at startup" or like "do this before adding a torrent". I've been using qBittorrent for years and haven't had this issue.

**Comment by mrderp** [comment]
Unchecking "bring torrent dialog to the front" in qBittorrent seems to have solved this problem. Thanks for help!
