### ISSUE TITLE
Taiga not connecting to/syncing with MAL

### ISSUE THREAD

**Issue by VitalSuit** [erengy/taiga#465]
I'm not sure what I did if it's on my end or if it's an issue with Taiga but suddenly the app isn't connecting to my MAL account. I changed the password last night on MAL and also made sure to update that info on Taiga but I keep getting an "Unknown Error (myanimelist|1|403)". What can I do to fix it?

Things I've tried:
Restarting computer
Changing the password AGAIN and making sure that info is correct in the Taiga app
Uninstalling and reinstalling Taiga

Edit:

I seem to have fixed the issue by changing some of the advanced settings. I followed this post on a similar issue and it seems to have worked.

> Erengy - If you're getting this error in v1.2.5 or later, go to Settings → Advanced and set Application / Disable certificate revocation checks to true.

**Comment by erengy** [comment]
Not sure why this happened right after you changed your password, but looks like you've found a solution.

I'll just link to another relevant and long-standing issue (#170) here, for future reference.
