### ISSUE TITLE
Support for Streaming media: 9anime.to and update for RSS feeds.

### ISSUE THREAD

**Issue by manolito62** [erengy/taiga#466]
#as clear my title goes, i wish that support for **9anime.to** is added to the **streaming media recognition**, and **update the rss feeds**, deleting nyaa.se and adding others, there is really good post about some rss feeds in this github itself:

[Updates for the RSS Feed: Nyaapocalypse #410 ](https://github.com/erengy/taiga/issues/410)

**Comment by wenbei999** [comment]
Taiga only supports official streaming sites. Please don't ask about direct or indirect support for unofficial ones.

RSS feeds options are already in place for the next release.

**Comment by erengy** [comment]
Quoting from the [FAQ page](http://taiga.moe/#support):

> **Could you add support for other streaming sites?**
>
> (...) Note that the current stance Taiga takes is that it only supports official streaming sites. Please don't ask about direct or indirect support for unofficial ones.

As @wenbei999 said above, the default RSS feeds are already updated. You may download the [latest beta](https://github.com/erengy/taiga/releases/tag/v1.3.0-beta) to see them in place.

**Comment by huiboy** [comment]
Does that mean we can update using 9anime?
