### ISSUE TITLE
Since today Norton Antivirus considers Taiga as a high risk virus.

### ISSUE THREAD

**Issue by DanielRieske** [erengy/taiga#467]
As described in the title, Norton Antivirus does not let me install Taiga anymore. And even when I give it permissions to open it it refuses to install it.

Been using Taiga for years now and today my antivirus un-installs it and says it is a high risk Heuristic Virus. I know that Norton has the tendency to mark a program rather quick as a Heuristic Virus but still this concerns me. 

Anyone else with this issue?, and maybe it is an idea to make a report to Norton about this/

Filename: taigasetup.exe
Threat name: Heur.AdvML.BFull Path: taigasetup.exe
____________________________
____________________________
On computers as of 
9/30/2017 at 12:33:33 AM

Last Used 
9/30/2017 at 12:37:38 AM

Startup Item 
No
Launched 
No
Threat type: Heuristic Virus. Detection of a threat based on malware heuristics.
____________________________
taigasetup.exe Threat name: Heur.AdvML.B
Locate

Few Users
Hundreds of users in the Norton Community have used this file.

Mature
This file was released 10 months ago.

High
This file risk is high.
____________________________
http://taiga.moe/update/TaigaSetup.exe
Downloaded File  from taiga.moe
Source: External Media
taigasetup.exe
____________________________

File Thumbprint - SHA:
407758c674696ac9ffd12c643675125f23481e8fe9d8b19570976f40ea023420
File Thumbprint - MD5:
1046e605154c67d4c2d16208b3f9be66

**Comment by erengy** [comment]
I'd assume that Symantec has recently made some changes to their heuristic detection algorithms, which ended up detecting Taiga's installer as [Heur.AdvML.B](https://www.symantec.com/security_response/writeup.jsp?docid=2016-051811-2400-99) (which actually says that the risk level is "Very Low"). Taiga is certainly not a virus. See the [VirusTotal analysis of the same file](https://www.virustotal.com/#/file/407758c674696ac9ffd12c643675125f23481e8fe9d8b19570976f40ea023420/detection).

I've [reported](https://submit.symantec.com/false_positive/) it as a false positive (#19) now:

> Thank you for contacting Symantec.
>
> Your submission has been received and will be reviewed. We endeavor to respond to all submissions within 2 working days.
>
> The tracking number for your submission is: 51963, please reference this tracking number in any further correspondence on this issue.

I'll let you know when Symantec responds. Thanks for the heads up!

**Comment by erengy** [comment]
Symantec's response (emphasis mine):

<blockquote>
In relation to submission 51963.

**Upon further analysis and investigation we have verified your submission and, as such, the detection(s) for the following file(s) will be removed from our products:**

    File name: TaigaSetup.exe
    MD5: 1046e605154c67d4c2d16208b3f9be66
    SHA256: 407758c674696ac9ffd12c643675125f23481e8fe9d8b19570976f40ea023420
    Note: Whitelisting is available by downloading a RAPID RELEASE indicated in the Further Information section below or via the next Live Update
Further Information:
Required RAPID RELEASE sequence >= 187659

The latest Rapid Release definition available here: ftp://ftp.symantec.com/AVDEFS/norton_antivirus/rapidrelease
To check the current sequence number of the Rapid Release definition: http://www.symantec.com/security_response/definitions/rapidrelease
More information on Rapid Release definitions can be found: https://support.symantec.com/en_US/article.TECH103326.html

If detection persists, please contact support:
* Norton: https://support.norton.com/sp/en/us/home/current/info
* SEP: https://support.symantec.com/en_US/endpoint-protection.54619.html

Decisions made by Symantec are subject to change if alterations to the Software are made over time or as classification criteria and/or the policy employed by Symantec changes over time to address the evolving landscape.

For more information on best practices to reduce false positives:
http://www.symantec.com/content/en/us/enterprise/white_papers/b-to_increase_downloads-instill_trust_first_WP.en-us.pdf
</blockquote>
