### ISSUE TITLE
Can't sync

### ISSUE THREAD

**Issue by TiresomeLime** [erengy/taiga#468]
I got an error while trying to sync with Kitsu:
"Kitsu returned an error: The provided authorization grant is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client."
![screenshot_291](https://user-images.githubusercontent.com/13847198/31104931-8ab6acbe-a7e0-11e7-97ae-f2dc8a1ebf4d.png)

**Comment by hagamablabla** [comment]
I've been having an issue syncing as well. However, I've been getting an unknown error instead. I'm on the 1.3.0-beta version.

![taiga_2017-10-06_11-20-55](https://user-images.githubusercontent.com/1676710/31285139-91afaf66-aa88-11e7-888b-c249319f419e.png)

**Comment by erengy** [comment]
@TiresomeLime The most likely reason is that your password is incorrect. You should try re-entering it to *Settings → Services → Kitsu*.

@hagamablabla Taiga's trying to update a library entry of yours, but Kitsu says that entry doesn't exist. If you're still having this issue, could you provide some additional information about that entry?

**Comment by TiresomeLime** [comment]
@erengy I had tried that multiple times. But the error fixed itself by reinstalling kitsu.

**Comment by ShaunV2** [comment]
@TiresomeLime You mean reinstalling Taiga.

**Comment by erengy** [comment]
I'll assume that this issue is not due to a bug in Taiga, but feel free to comment if it persists.

**Comment by cheetahsweater** [comment]
this is happening for me.
