### ISSUE TITLE
Invalid files not being ignored

### ISSUE THREAD

**Issue by ovingiv** [erengy/taiga#471]
I have my anime on a separate hard drive and when I'm listening to music Taiga shows up with a notification saying that it can't find Eminem - Elevator. My music is on my E: drive and my anime is on the F: drive. What would cause this?

**Comment by erengy** [comment]
I just checked and there doesn't seem to be any issues with ignoring files outside of library folders. Besides, Taiga should be ignoring music files in any case.

Which media player do you use while listening to music?

**Comment by ovingiv** [comment]
I use the latest version of VLC 64 bit.

**Comment by ovingiv** [comment]
![untitled](https://user-images.githubusercontent.com/24558152/34921431-8a04ef52-f947-11e7-9d8d-43de452b4918.png)

Here is a photo of my settings, the song being played in VLC and it being "recognized" in Taiga.

**Comment by wopian** [comment]
I also have this happen with random video files on drive `A` sometimes being detected with Taiga restricted to scanning within drives `B` and `C`

mpv and taiga b2

**Comment by erengy** [comment]
I think I understand what's going on. Taiga actually ignores the file, but then it falls back to reading the media player's window title, even though it shouldn't in this case. I'll see what I can do about that.

Note to self: Don't break #330.

**Comment by erengy** [comment]
This ended up being more complicated than I anticipated, so I drew a map to wrap my head around all possible cases:

![media-detection](https://user-images.githubusercontent.com/1078430/35346983-d6c0e134-0144-11e8-9dd8-8f3180df118a.png)

- Video file
    - Valid video file: This is the ideal case.
    - Invalid path: This is related to Taiga's *Ignore files outside of library folders* option.
    - Invalid type: We ignore anime video files with some keywords (e.g. `OP`, `NCED`, `PV`).
- Audio file: We can check the file extension to detect the most common ones (e.g. `.mp3`, `.flac`). This fixes the current issue.
- Unknown file: Some media players have irrelevant files open (e.g. Kodi has one named `Textures.xbt`). We completely ignore these.
- No file
    - Streaming audio: It's currently not possible to detect whether the user is streaming audio or video. We choose to ignore this case.
    - Streaming video: See #330. There's no file handle involved, so we must fall back to window title.
    - No access: Taiga could not access the file handles of the media player, likely because the player is running as an elevated process. We have no choice but to fall back to window title.
