### ISSUE TITLE
Files related to airing anime detected as batch in torrents listing

### ISSUE THREAD

**Issue by asakurato** [erengy/taiga#474]
So, sometimes I get notified of the torrent of the series which are currently airing, as if there is actually a batch for the whole season, which is impossible. Here is the example. In the first pic you see Sangatsu no Lion s2 detected as a batch when in fact it's an OP for the show, as shown on the second pic. This happened to other shows as well, where actual torrents were like OP's and other stuff. Using version 1.25
![capture](https://user-images.githubusercontent.com/20476454/31579108-d85cc102-b13f-11e7-9c96-1d3406a387d6.JPG)
![capture1](https://user-images.githubusercontent.com/20476454/31579109-d88595d2-b13f-11e7-8cac-f807661dd0ed.JPG)

**Comment by wenbei999** [comment]
Change your rss feed to anime only.

**Comment by asakurato** [comment]
Well, this doesn't bother me anymore, since I have filtered everything besides currently airing (which is what I'm downloading with Taiga). But even if it's not anime, why is it detected as a batch?

**Comment by erengy** [comment]
Taiga's recognition engine is geared towards parsing anime video filenames, so it's no wonder it gets confused on anime music releases. As it's pointed out, the RSS feed you use should be anime-only.

That said, there is some chance for improvement here. I'll see what I can do.

**Comment by asakurato** [comment]
I'm not sure how to change RSS feed to anime only, but as I have filtered out batches entirely (I'm only interested in weekly releases anyway), so it doesn't bother me anymore

**Comment by erengy** [comment]
Tokyo Toshokan has a [Customize RSS Feed](https://www.tokyotosho.info/rss_customize.php) page for that purpose. After creating a custom URL, you can copy-paste it to Taiga's *Settings → Torrents → Discovery* page.

If you're using nyaa.si, the `c` parameter in the URL sets the category. `c=1_0` is for "Anime", `c=1_2` is for "Anime - English-translated", and so on. You may check out Nyaa's website for other values.

The default RSS feeds in Taiga are all set up in this manner. If you're using an older version, you can upgrade to [v1.3.0-beta](https://github.com/erengy/taiga/releases/tag/v1.3.0-beta), which includes updated default feeds.

**Comment by asakurato** [comment]
I'll probably updrade to 1.3.0. thanks for the info
