### ISSUE TITLE
Something wrong with the filter?

### ISSUE THREAD

**Issue by taigalover** [erengy/taiga#477]
I want to make a filter that is for new episodes that are currently airing and im currently watching.
Its fine when i set the "watching status" filter and the "episode count" filter.
But when i set the "airing status" filter, i set it to "currently airing" but when i close the window then i return to the window, it shows its set as "finished airing".

Example, i first set the filter:
![untitled](https://user-images.githubusercontent.com/32505754/31593548-e980fa8e-b261-11e7-90f7-13620f83bfee.png)
Then I save.
![untitled](https://user-images.githubusercontent.com/32505754/31593584-2178ee1a-b262-11e7-9709-604a0f6fedc0.png)
It shows above that it is set to "currently airing". But when i click on it again,
![untitled](https://user-images.githubusercontent.com/32505754/31593636-66c67ef6-b262-11e7-8310-b3d33c483201.png)
It shows it set as "finished airing". And when i leave it again, 
![untitled](https://user-images.githubusercontent.com/32505754/31593674-95406f44-b262-11e7-9720-d232a2f46dc4.png)
It shows it still set to "currently airing".
So i could really appreciate some clarification on this and if its just me.

**Comment by erengy** [comment]
This is just a UI bug where the value listing for airing status in Edit Condition dialog is mixed up. If you're seeing "Currently airing" in conditions list of Add New Filter dialog, the filter should work as expected. Thanks for the report, I'll fix it when I get back home.
