### ISSUE TITLE
Anime folder are already being made in qbittorent?

### ISSUE THREAD

**Issue by taigalover** [erengy/taiga#478]
The title says it all. For example i want to get an anime like one piece which ive never downloaded and never made a file for, and i get an episode from the torrent page in taiga, then i get redirected to qbittorent, then when im setting the download folder in qbittorent i see that there is a new folder in my "shows" file (which is the default folder for anime i set on taiga) called "One Piece". it does this sometimes for some shows, but sometimes it dosent, it seems to me its incomplete, but is there some traces of the feature being there?

**Comment by erengy** [comment]
BitTorrent clients usually create a folder named after the .torrent file, then download the files into that folder. I'd imagine that the cases you encounter are related to that behavior. Taiga's relevant feature does not support qBittorrent yet (but it will, as I mentioned in #86).
