### ISSUE TITLE
Taiga doesn't recognize season two of a series properly

### ISSUE THREAD

**Issue by potatoarmy** [erengy/taiga#479]
I am having an issue with Taiga not recognizing Horriblesubs' release of 3-gatsu no Lion S02E01 since they simply label it as "3-gatsu no lion - 23", while it's marked as "3-gatsu no Lion 2nd season" on MAL. 

I tried adding the release title as alternative but it won't pick it up since I'm technically watching ep23 from a show that only had 22 episodes. 

Had no issues whatsoever with Boku no Hero Academia which used the exact same naming scheme - it was detected and tracked perfectly. 
Both shows were downloaded to and ran from the same directory and I've made no relevant changes to my setup in the time between.

**Comment by kasokz** [comment]
Same problem here, maybe MAL has some other meta data for the show than it has for Boku Hero.
I don't actually know how Taiga recognizes continuous numbered follow up seasons, so that's just a guess from my side.

**Comment by erengy** [comment]
Taiga uses a file named [anime-relations.txt](https://github.com/erengy/anime-relations) to handle situations like this. *Boku no Hero Academia 2nd Season* has been in this database for a while now, but *3-gatsu no Lion 2nd Season* was [added just recently](https://github.com/erengy/anime-relations/commit/10b7976b862985b94a608d2aa9c00780891da5e7).

Taiga should recognize the series after you use the *Help* → *Check for updates* menu item to update anime relations. If it doesn't, make sure to remove any alternative titles that you added to the series.
