### ISSUE TITLE
Hi, I need help

### ISSUE THREAD

**Issue by CarmenZM** [erengy/taiga#480]
I need a RRS to download in Spanish subtitles
I can not or do not understand how to do this

Thank you

**Comment by erengy** [comment]
I'm not aware of any Spanish-only RSS feeds, but AniDex allows filtering torrents by language.

Subbed anime in Spanish language:
https://anidex.info/?page=search&id=1&lang_id=15

Corresponding RSS feed:
https://anidex.info/rss/?cat=1&lang_id=15
