### ISSUE TITLE
HTTP error #6: Couldn't resolve host name (www.nyaa.se) when searching for torrents

### ISSUE THREAD

**Issue by JarikH** [erengy/taiga#482]
Just like the title suggests, every time i try to search for a torrent i get this exact error, any idea why? ^^

**Comment by ShaunV2** [comment]
@JarikH That is because nyaa.se no longer exists, it is now nyaa.si though the beta client should've been updated to reflect this (the developer of Taiga is well aware of this).

@erengy Have you fixed this yet?

**Comment by JarikH** [comment]
@ShaunV2 thx for the comment, just changing the rss feed to: https://nyaa.si/?page=rss&term=%title% fixed it for me ^^

**Comment by erengy** [comment]
Previously at #410.

Default RSS feed options are updated in v1.3, although I should probably make Taiga automatically change the active feed too.
