### ISSUE TITLE
Taiga creating anime folders (need clarification)

### ISSUE THREAD

**Issue by taigalover** [erengy/taiga#483]
Ive brought this up before and bringing it up again because taiga is somehow making anime folder in the defauly anime directory. @erengy cleared this up by suggesting in this case its the torrent client (qbittorent) thats making these folders, not taiga. So i went and got torrents from two places, the RSS feeds i have in qbittorent, and also got torrents from the torrent page in taiga. So i first got torrents from the RSS feeds in qbittorent:

Ill be getting the torrent: Kini no Tabi (2017) 1080p from HorribleSubs.
So ill first show u what the directory file looks like around the anime that starts with the letter "k".
![untitled](https://user-images.githubusercontent.com/32505754/31831127-ee043b5c-b5f4-11e7-8eb6-a2a509f9e838.png)
Theres no sign of "Kini no Tabi" at all.
So ill proceed to the getting the RSS of the anime from qbittorent.
![untitled](https://user-images.githubusercontent.com/32505754/31831278-74ad38b6-b5f5-11e7-9cc5-c1f881932951.png)
![untitled](https://user-images.githubusercontent.com/32505754/31831333-aa534654-b5f5-11e7-8837-77b15ece7e12.png)
So i pressed ok, and now the download is running but in the directory folder theres no anime file called "Kimi no Tabi" and also the video file is just downloading without a folder at the bottom of the the list (because i didnt set a folder before i pressed "ok" to download). Here a pic of the directory folder around the letter "k" and the downloading video file without a folder.
![untitled](https://user-images.githubusercontent.com/32505754/31831530-673a2576-b5f6-11e7-994e-a263e763ad4d.png)
![untitled](https://user-images.githubusercontent.com/32505754/31831604-ac49e4da-b5f6-11e7-8801-a9884d1d6cee.png)
Ok thats it for downloading straight from qbittorent. Now ill delete the downloading video file and use a taiga torrent page to re-download the same file. So ill first go to taiga and find the same torrent:
![untitled](https://user-images.githubusercontent.com/32505754/31831709-f79ee32c-b5f6-11e7-9b06-66e1d145cd1a.png)
And download it.
(This next picture is taiga redirecting me to qbittorent after i clicked the torrent in taiga and also note that the download directory is the same as before)
![untitled](https://user-images.githubusercontent.com/32505754/31831814-5e9ae508-b5f7-11e7-9699-e7825d16ae5f.png)
So i click ok and the torrent proceeds to download just like it did when i downloaded the same folder in qbittorent, in also the same directory. So now i go to the directory and look around the files starting with the letter "k". And i get this:
![untitled](https://user-images.githubusercontent.com/32505754/31831956-d30d6316-b5f7-11e7-8ba3-ad4b95f8cfd0.png)
After downloading the same folder but using taiga this time, it makes the file "Kini no Tabi (2017)". But the actual video thats downloading is not being downloaded to that folder its being downloaded outside it (since i set it in that folder before downloading it). Here is a pic of that video file at the bottom of the list, like before:
![untitled](https://user-images.githubusercontent.com/32505754/31832123-69d1bf90-b5f8-11e7-848b-1311a2459403.png)

Note 1: In taiga my anime directory is that folder in the picture called "Shows". And that same folder is 
            the default download directory in qbittorent.

Note 2: Taiga does not move the file after download. The "Kimi no Tabi" file stays empty and the video 
             file stays where it is, at the bottom of the list.

Note 3: Here is a screenshot of my download setting in taiga:
![untitled](https://user-images.githubusercontent.com/32505754/31832635-51f3ba02-b5fa-11e7-9c28-2ac6310eeb7e.png)

So yeah thats it. This doesn't bother me at all, its actually pretty helpfull, saves me the trouble of making the folder, it even names it in a nice way. But the point of this is just to point out that taiga does make the folder, and also i wanted to know if this is just me, or if this was always there and ive just make myself look like an idiot. And also @erengy , sry for bringing this up again.

**Comment by AthabaWolfssturm** [comment]
Correct me if I misunderstood your question, but I see that you have activated the option "Create a subfolder using the anime title as its name" in the last screenshot, right under the box where you set your default download folder.

As to why it doesn't move the file, maybe qBittorrent doesn't support moving after download or Taiga doesn't send the newly created folder to the client (so that it couldn't know that this folder exists)?

**Comment by erengy** [comment]
@taigalover If you have the *Create a subfolder using the anime title as its name* option enabled, Taiga will create the folder right before opening the .torrent file, regardless of which BitTorrent client you use. Perhaps it should do that only for supported clients?

(Note that it's okay to comment on closed issues, so you could have posted this under #478 instead. I close an issue when I'm under the impression that it's resolved, but I might be mistaken.)

> As to why it doesn't move the file, maybe qBittorrent doesn't support moving after download or Taiga doesn't send the newly created folder to the client (so that it couldn't know that this folder exists)?

That is indeed the case, although Taiga will soon support qBittorrent too (see #86).

**Comment by taigalover** [comment]
Ahh, my bad, i assumed everything in the "download location" setting would only work for only supported clients. So i thought something wasn't right. Tq for clearing that up.

>  Perhaps it should do that only for supported clients?

Its a nice feature, that can be checked and unchecked to match your needs. So i see it as a plus 1 that might come in handy sometime.
