### ISSUE TITLE
v1.2.0 and v1.3.0-beta tagged on virustotal

### ISSUE THREAD

**Issue by runboy93** [erengy/taiga#484]
v1.2.0 (1/66)
https://www.virustotal.com/#/file/407758c674696ac9ffd12c643675125f23481e8fe9d8b19570976f40ea023420/detection

v1.3.0-beta (3/66)
https://www.virustotal.com/#/file/188a1b5a710e48253529fc0dede225e302fffefa10935d1b0b349543c6eac401/detection

**Comment by ShaunV2** [comment]
False Positive.

**Comment by erengy** [comment]
It is indeed a false positive, as it was the case in [all previous issues](https://github.com/erengy/taiga/issues?utf8=%E2%9C%93&q=label%3A%22false%20positive%22%20). I'm afraid I can't do anything other than file reports to AV companies.

(Detection ratio for v1.3.0-beta installer is down to 2/67 now.)
