### ISSUE TITLE
Anime Recognition in Chrome is glitched. It recognises the first anime once the software is opened but won't recognise any more.

### ISSUE THREAD

**Issue by Jasonfran** [erengy/taiga#486]
Earlier today I watched some currently airing anime and the software correctly recognised I was streaming it on Crunchyroll. But now that I want to watch something else it is still saying I'm watching the series from earlier and doesn't recognise it. Despite there being no Crunchroll tabs or any other streaming media. The only way to fix this is to restart Taiga and then it will correctly recognise the streaming media.

It's like it will recognise the first thing it sees once opened and that's it. Is this intended behavior?

**Comment by erengy** [comment]
This is likely the same issue as #227 and #281.

If you're not using it already, could you try upgrading to [v1.3.0-beta](https://github.com/erengy/taiga/releases/tag/v1.3.0-beta)?

**Comment by Jasonfran** [comment]
Ah yes that fixed it. I have multiple browsers open on different desktop views. Sorry for making a new issue. Thank you very much.

**Comment by lmmfranco** [comment]
This issue is back in 1.3.0 release. Was working almost properly on the beta, but stopped working after release update.

**Comment by ShaunV2** [comment]
Streaming detection is completely broken now, doesn't detect Crunchyroll nor VRV.

**Comment by Jasonfran** [comment]
@lmmfranco are you sure it's this exact problem? This problem was caused by having more than one Chrome window open. I've updated to 1.3.0 and this is still fixed like in the Beta. Crunchyroll detection still works too.

If I find it breaks again I'll reopen this issue.

**Comment by lmmfranco** [comment]
@Jasonfran Actually, I guess my config files were corrupt or something like this. The "Enable streaming detection" was ticked off for some reason after the update. Sorry for the false report
