### ISSUE TITLE
Not detecting files in NAS

### ISSUE THREAD

**Issue by Sulo-Hayha** [erengy/taiga#487]
Seems like Taiga struggles a bit detecting files on my NAS, works perfectly fine with the ones still on my local drive but only detects the ones on NAS if I access them or try asking to open folder where the series should be located...?
Manually pressing "Scan for episodes" seems to work most of the time but it's a bit of a hassle when it should just see them automatically.

Using latest version of freeNAS and Taiga on Win10.

**Comment by erengy** [comment]
From what I understand, you've already added your NAS to Taiga's library folders, and Taiga is able to detect new episodes when you manually scan for them. For automatic detection, the following options should be enabled:

1. *Settings → Application → General → Startup → Scan library folders for available episodes*
2. *Settings → Library → Folders → Real-time monitor → Detect new files and folders under library folders*

As far as I'm aware, the only issue with detecting files on a NAS is the one described in #371. If that's different than what you have, could you provide some additional information?

And just to make sure this problem persists in the latest version, could you try upgrading to [v1.3.0-beta](https://github.com/erengy/taiga/releases/tag/v1.3.0-beta), if you aren't using it already?

**Comment by Statharas** [comment]
I can confirm that Taiga CAN find my NAS files.
Using MyCloud 2GB here.

**Comment by Sulo-Hayha** [comment]
That is correct.
I have 3 folders in Taiga's list, one is on my local HDD and the other two on NAS.
All options you've mentioned are enabled.

#371 looks like a different issue, my NAS does not have drives go on stand-by.

**Comment by Statharas** [comment]
How did you add your nas device to the list? Can you te us the path you're using?
