### ISSUE TITLE
Automatic download filter action

### ISSUE THREAD

**Issue by wolfy852** [erengy/taiga#488]
While looking through the possible actions download filters could use, I had the idea of an automatic download action that would automatically download any files that fulfill the requirements of the filter. This would be especially useful for airing shows, as they'd be ready to watch as soon as they release.

I am aware that Taiga can download new files immediately, but this is listed as a global option under Torrents -> Discovery. The idea I have in mind is only downloading specific files automatically according to filter rules.

**Comment by erengy** [comment]
Currently, filters are only used to select or discard torrents. When the filtering process is finished, you are either notified about the selected torrents, or they're automatically downloaded, depending on your choice.

What you're suggesting is being able to say, "download these immediately, notify me about these, and ignore the others" to Taiga. I see two options for implementing this:

1. Add a new action that overrides the general notify/download setting
2. Remove the general notify/download setting for more granular options

Both options seem to increase the complexity of the system, which I'm trying to avoid (see #56, #76, #147 for more examples). The second option could perhaps be used in our new system, though.
