### ISSUE TITLE
When I select a "season" Taiga start a error loop

### ISSUE THREAD

**Issue by vegon** [erengy/taiga#490]
Every time I try to select a season on the "Seasons" tab, Taiga start a loop of error trying to load the data, the client start to "blink" (??).

It's a new install, firt time using it.

**Comment by erengy** [comment]
Hi there @vegon,

This was fixed in 6f86c80511d6bcf93706723b66fee164a79078fe, after the report in #457. If you're using v1.2, upgrading to [v1.3 beta](https://github.com/erengy/taiga/releases/tag/v1.3.0-beta) should get rid of the issue.

**Comment by vegon** [comment]
Oh, thanks. It works perfectly now.
