### ISSUE TITLE
Anime List: Progress bar uneven

### ISSUE THREAD

**Issue by Hidden2147** [erengy/taiga#492]
Very minor. Seems to be not lining up with the latest aired/available episode as shown below.

Screenshot:
![taiga_2017-11-11_16-22-25](https://user-images.githubusercontent.com/33566734/32687678-c7ac1650-c6fc-11e7-936e-e79ce99d2705.png)

**Comment by taigalover** [comment]
Screen shot for 1.3.0 Beta.
![screenshot 4](https://user-images.githubusercontent.com/32505754/32687837-162db29a-c700-11e7-9dea-00ef29adfe43.png)
Latest:812
Seen:811
