### ISSUE TITLE
Anime rating

### ISSUE THREAD

**Issue by Stonedestroyer** [erengy/taiga#497]
Is it possible to add PG and RX ratings that you can filter with on your list like on the website list itself? 
This one as example
Rating: PG-13 - Teens 13 or older

**Comment by erengy** [comment]
You mean adding a new column to Anime List, right? I'd like to do that eventually (as in #150), but age ratings aren't provided by MAL API, unfortunately.

**Comment by Stonedestroyer** [comment]
Yes a column to Anime List with the ratings if possible. I guess a solution to this would be the way seasons are done right now but that would mean someone has to scrape it and MAL does not encourage that afaik. 

If you want you can close this one and add the age thing to the other issue to keep a better track on them as it covers mostly the same thing.
