### ISSUE TITLE
Kodi DS player support

### ISSUE THREAD

**Issue by uni92** [erengy/taiga#499]
DSplayer is a fork of Kodi which uses a DirectShow-based media player, primarily useful if you want to use madVR. Support would be appreciated.

More info:
https://github.com/aracnoz/xbmc
https://forum.kodi.tv/showthread.php?tid=223175

**Comment by erengy** [comment]
I just tried this. Taiga's [latest version](https://github.com/erengy/taiga/releases/tag/v1.3.0-beta.2) was able to detect Kodi DSPlayer (17.6 Krypton) without requiring me to make any changes (although I had to run Taiga as administrator).

PS: Not sure if it's true, but according to [this thread](https://forum.kodi.tv/showthread.php?tid=222576):

> Important Notice: The developer of DSPlayer has decided to step away from this project due to personal reasons.
