### ISSUE TITLE
Seasons: Show info on mouse hover

### ISSUE THREAD

**Issue by tophf** [erengy/taiga#50]
![season](https://cloud.githubusercontent.com/assets/1310400/4764733/baf73150-5b2b-11e4-8c97-d2f18534aaa1.png)

An info card shown on mouse hover would be nice.
Simply something compact like this:

>**Psycho-Pass 2**
TV, 11 episodes, fall 2014, currently airing
Score: 8.231 (5858 users)
Action, Sci-Fi, Police
Dentsu

Even without a larger image.
I mean, if it's not possible to fetch the full-sized image then let it be a simple text, no image at all.

**Comment by erengy** [comment]
This may look different than what you expected (it's just a normal tooltip rather than a fancy card). But anyway, I managed to slip this one in before tomorrow's release:

![info-tooltip](https://cloud.githubusercontent.com/assets/1078430/12555892/fccbb3e8-c38b-11e5-8647-6a85ea734556.png)
