### ISSUE TITLE
Share support for Discord RichPresence

### ISSUE THREAD

**Issue by VIONYT** [erengy/taiga#500]
Would be nice to share your currently watching anime in a Discord RichPresence.
Discord gives for this a [RPC-Api](https://github.com/discordapp/discord-rpc) the Api needs from [Discord Developers](https://discordapp.com/developers/applications/me) an client id to post data to it.

**Comment by erengy** [comment]
Hi @VIONYT. We already have an open issue about Discord at #450, so I'll be closing this one.
