### ISSUE TITLE
Taiga no longer works with Firefox 57 (Quantum)

### ISSUE THREAD

**Issue by Shumatsu** [erengy/taiga#503]
Couldn't get Taiga to work with Plex Web App so I decided to check if other services work. Compared with Opera, as both are in support list.

Opera: 
- Plex didn't work
- Crunchyroll worked
- YouTube worked

Firefox 57:
- Plex didn't work
- Crunchyroll didn't work
- YouTube didn't work

Seems like they changed much in version 57 and like other browsers, it won't work anymore.

**Comment by erengy** [comment]
If you're using an older version of Taiga, could you try upgrading to [v1.3.0-beta](https://github.com/erengy/taiga/releases/tag/v1.3.0-beta)? It includes significant changes to media detection, and shouldn't have any issues with detecting Firefox.

**Comment by Shumatsu** [comment]
Okay, now it works with Firefox 57.
