### ISSUE TITLE
Taiga setup

### ISSUE THREAD

**Issue by sleepyanime** [erengy/taiga#504]
Hi and thank you in advance for the help!
I just downloaded taiga and was trying to figure out how to set it up.
I am sorry i am a complete noob when it comes to this so any help would be appreciated.
I stream all of my anime online from websites and would like to automate it.
I heard after setting taiga up properly it will do just that.
Please help me set taiga up.

I downloaded taiga, i made my anime list account.
from there i dont know how to set it up with online web player detection.

**Comment by erengy** [comment]
Hi @sleepyanime,

The relevant options of Taiga are available at *Settings → Recognition*. More specifically, you'll need to enable streaming services of your choice from the *Streaming media* page. Please note that only official services are supported.

For more information about various subjects, you may take a look at the [Support](http://taiga.moe/#support) section of Taiga's website.
