### ISSUE TITLE
Anime relations for AniList

### ISSUE THREAD

**Issue by wiiaboo** [erengy/taiga#505]
ie. it's not finding alternatives for 3-gatsu no Lion second season:
![image](https://i.fsbn.eu/kCHy.png)

In MAL and Kitsu it's called "3-gatsu no Lion 2nd Season" while in Anilist it's called "3-gatsu no Lion 2", could have something to do with that.

Using a build from 63edac219e86ad1f07e0e577ded518e46ab22205.

**Comment by erengy** [comment]
It's because [@erengy/anime-relations](https://github.com/erengy/anime-relations) doesn't have AniList IDs yet. I actually forgot about it, thanks for reminding. I should do this before releasing beta.2.

**Comment by wiiaboo** [comment]
Anilist does have MAL IDs available in the API. If they could be used it'd avoid an extra lookup for each new relation added.
