### ISSUE TITLE
Using AniList to Fetch Seasonal Information

### ISSUE THREAD

**Issue by tunamako** [erengy/taiga#506]
I was reading up on how Taiga uses `https://github.com/erengy/anime-seasons` to keep up to date on seasonal anime. However I noticed that in the AniList API docs, there's a simple way to fetch all anime for a given season in a single GET request: 

`http://anilist-api.readthedocs.io/en/latest/anime.html?highlight=season#browse`

which seems a lot cleaner than scraping MAL. Would this be a feasible thing to include in Taiga?

**Comment by erengy** [comment]
Hey @tunamako,

Taiga uses AniList's [newer API](https://github.com/AniList/ApiV2-GraphQL-Docs) when the active service is AniList. However, I'd rather not make Taiga rely on data from another service (AniList or Kitsu) for MyAnimeList users. There's bound to be some inconsistencies such as missing entries, outdated information or different classification.

That being said, using a proper API is certainly preferable to web scraping. Good news is that MAL is actually working on a new API that would make `anime-seasons` irrelevant, although there's no ETA yet. I'm currently waiting for that, but I'll keep your suggestion in mind. Thanks!
