### ISSUE TITLE
Anime info window - combine the Information and My list panes

### ISSUE THREAD

**Issue by tophf** [erengy/taiga#51]
![info](https://cloud.githubusercontent.com/assets/1310400/4765112/6f8bbef2-5b35-11e4-88cc-09cca3f6e4fc.png)

Such combined view provides an immediate access to everything, eliminates the need to constantly change tabs.

* The window is resizable of course and remembers its size and position (relative to the main window?).
* The right pane size is fixed, the tags and the alternative title edit fields are multi-line boxes.
* The Genres, Producers, Alternative titles fields wrap on overflow like this:
  ```
  Genres: Action, Sci-Fi, 
          Police
  ```

* The artwork may be larger (option?) - the same size as the image on MAL page.

P.S. Yeah I know it's PITA to implement, however c'mon, it's 2014 and as a user I can dream of a nifty UI.

**Comment by erengy** [comment]
The combination isn't going to happen, but I'll keep the other suggestions in mind. For keyboard-related requests, feel free to use issue #82.
