### ISSUE TITLE
Problems when it comes to Digimon Adventure Tri

### ISSUE THREAD

**Issue by Statharas** [erengy/taiga#513]
All anime sites track the anime in the 6 segments, while most torrents release them in incremental order based on their release.
Taiga is expecting 1 episodes per segment and each segment has 3-4. Horriblesubs has reached 18 episodes if I'm not mistaken.

**Comment by erengy** [comment]
Taiga handles this kind of issues using [@erengy/anime-relations](https://github.com/erengy/anime-relations). The database does have [entries](https://github.com/erengy/anime-relations/blob/708e8ce4a73e76411e37f313d1f6ef1b8fe5316e/anime-relations.txt#L196-L199) for *Digimon Adventure tri.*, but only for the 2nd and the 3rd movies at the moment. I can add the others if someone could tell me which movies consist of which episodes.

Movie|Episodes
-----|--------
1|1-4
2|5-8
3|9-12
4|?
5|?
6|?

**Comment by Statharas** [comment]
http://horriblesubs.info/shows/digimon-adventure-tri
Going by the release dates, 1-4,5-8, 9-13, 14-17, 18-21
