### ISSUE TITLE
adding a manga section to the application

### ISSUE THREAD

**Issue by KingFishy492** [erengy/taiga#515]
#### Select your issue type: (check at least one)

- [x] Suggestion

#### Describe your issue:

Is it posabiel to have a manga section to this applacation i love taiga and its great for mass edditing of things quick and simple but could he get a section to do the same things but for manga as well as the anime side that exsists already the same layout but for manga 
Thanks for reading
-Fishy

**Comment by erengy** [comment]
Hi, please see #511 for an answer to a recent question, and #107 for more information.

**Comment by KingFishy492** [comment]
Oh sorry i did think this had been asked but couldn't really find it thanks for the info!
