### ISSUE TITLE
anime isnt updating automatically

### ISSUE THREAD

**Issue by 0ANIMEFREAK0** [erengy/taiga#517]
i was watching gintama on vlc it showed that i am watching it i mean taiga showed me that i am watching gintama but didnt upadte the list
what can i do it to automaticlly update my list and i am using v 1.2

**Comment by erengy** [comment]
Is Taiga able to update any series other than Gintama?

For starters, you can try upgrading to the [latest beta](https://github.com/erengy/taiga/releases/tag/v1.3.0-beta.2) and see if it solves your issue.

**Comment by 0ANIMEFREAK0** [comment]
After updating the version it worked
