### ISSUE TITLE
qBitTorrent issue

### ISSUE THREAD

**Issue by Statharas** [erengy/taiga#518]
When using qBitTorrent, I started getting the error:
`--save-path=\\WDMYCLOUD\<dir>` is an unknown command line parameter.
Run application with -h option to read about command line parameters

I've downloaded some torrents before these and they worked fine.

**Comment by erengy** [comment]
`\WDMYCLOUD<dir>` doesn't seem like a valid path. Did you truncate it yourself?

Which anime did the torrent belong to? Could you copy-paste the designated folder of that anime, from *Anime Information → My list and settings → Local settings*?

**Comment by Statharas** [comment]
Nah, it's double slash, slash, correct directory. 
`\\WDMYCLOUD\Stathis\u_Buffer\`

Github would auto-truncate backslashes

**Comment by erengy** [comment]
Just to make sure we're not missing something obvious, which version of qBittorrent do you use?

If you're using an older version such as v3.3.16, you should either upgrade to v4.0.3 (which supports the `--save-path` parameter) or disable the *Use anime folders as the download folder option* of Taiga (from *Settings → Torrents → Downloads*).

**Comment by Statharas** [comment]
Oh crap, forgot to mention that. I am using 3.3.16 due to Bakabt's not whitelisting 4.0.3 :/

**Comment by Statharas** [comment]
Assumed solved, since it works fine on 4.0.3
