### ISSUE TITLE
[Suggestion] AniList airing data

### ISSUE THREAD

**Issue by Statharas** [erengy/taiga#520]
Airing data is available in GraphiQL form

> AiringSchedule(
> id: Int
> mediaId: Int
> episode: Int
> airingAt: Int
> notYetAired: Boolean
> id_not: Int
> id_in: [Int]
> id_not_in: [Int]
> mediaId_not: Int
> mediaId_in: [Int]
> mediaId_not_in: [Int]
> episode_not: Int
> episode_in: [Int]
> episode_not_in: [Int]
> episode_greater: Int
> episode_lesser: Int
> airingAt_greater: Int
> airingAt_lesser: Int
> sort: [AiringSort]
> ): AiringSchedule

Any chance we can get this implemented somehow? showing aired episodes and ETA of next episode?

**Comment by erengy** [comment]
Indeed, I'm planning to make use of AniList's airing data, although I'd prefer having this info on all services.

Closing this issue, since we already have #59.
