### ISSUE TITLE
is it me or can taiga not connect to nyaa.se?

### ISSUE THREAD

**Issue by ninja85a** [erengy/taiga#521]
I'm on the latest update on win 10 pro fall creators update 
when I try to refresh the results for nyaa it comes up with the error
(HTTP error #6: Couldn't resolve host name (www.nyaa.se)

**Comment by Diablofan** [comment]
Nyaa.se died a while ago (May, 2107), see #410. Switch to Nyaa.si.

**Comment by ninja85a** [comment]
I swear it worked when I first started using it which wasnt that long ago
