### ISSUE TITLE
Failed to detect Kitsu rating type

### ISSUE THREAD

**Issue by crse** [erengy/taiga#523]
I use advance rating type on Kitsu.
Taiga usually detects it and use advance rating on the list, sadly an error happened and change the rating type to regular.
I use Taiga 1.3.0-beta2.

**Comment by ShaunV2** [comment]
Looks here https://kitsu.io/posts/8863078
Download the lastest version from here http://taiga.moe/latest.html

That will fix the rating issue.

**Comment by erengy** [comment]
This was fixed in 51e4841cd636ae831ebe416edf5d5bf33178e070.

> Happened due to a recent change in Kitsu API. `ratingSystem` is no longer available in non-authenticated requests.
