### ISSUE TITLE
Plex web app not being detected

### ISSUE THREAD

**Issue by sachaw** [erengy/taiga#524]
Not sure if I'm doing something wrong, Have enabled streaming media recognition and ensured plex is enabled, also tried multiple browsers.

**Comment by erengy** [comment]
Just tried this. Taiga was able to detect Plex Web App without any issues.

Do you run Plex Media Server on the same computer or somewhere else? What's the URL for the web app?

**Comment by Yukkun** [comment]
Hi, I have the same issue. Running Plex media server on different computer, but its still in my home network. I generally access it through the app.plex.tv/desktop address though.

**Comment by erengy** [comment]
Taiga [supports](https://github.com/erengy/taiga/blob/3e4068e4e6004205c2ea79189abe90b154759fbd/src/track/media_stream.cpp#L74-L88) several URL formats for Plex, including:

- `app.plex.tv/web/`
- `localhost:32400/web/`
- `127.0.0.1:32400/web/`

Looks like they changed `app.plex.tv/web/` to `app.plex.tv/desktop` a couple of months ago. Adding that to Taiga should do the trick.

Please try out the [latest build](http://taiga.moe/latest.html) and let me know if it fixes the issue.

**Comment by Yukkun** [comment]
Seems to have fixed the issue.

**Comment by sachaw** [comment]
@erengy Your fix seems to have solved the aforementioned issue for me but I have now encountered another issue, that being that Taiga cannot detect what is playing from the fullscreen state, an example when Taiga is unable to detect that anything is playing:
Playback paused (Taiga detected), enter fullscreen (still detected), play and then pause a few times (Taiga no longer detects), and will not detect until fullscreen is exited
It may take a while for currently playing item to disappear from Taiga once in fullscreen, but it will happen.
