### ISSUE TITLE
Taiga does not allow you to search an anime on Anilist

### ISSUE THREAD

**Issue by Statharas** [erengy/taiga#531]
Specifically on right click->search. Only allows on AniDB, ANN, Kitsu, MAL, Reddit and Wikipedia
Not to mention how Violet Evergarden search on Reddit brings no results.

**Comment by erengy** [comment]
Reddit episode discussion search was fixed in 8ce159530a5aa3b62f8aa24df7355201b3b9d4e4.

**Comment by Statharas** [comment]
Was Anilist added though :P?

**Comment by wopian** [comment]
See the first commit stated above for AniList search being added (1588593)
