### ISSUE TITLE
Doesn't splitscreen properly

### ISSUE THREAD

**Issue by Qwerty-Space** [erengy/taiga#532]
When dragging to the edge of the screen, there's a gap on Windows 10, Taiga version 1.2.5

**Comment by ovingiv** [comment]
I remember having that issue before too. I suggest updating to the latest beta here: http://taiga.moe/download.php?channel=beta

Go to the location that you have Taiga installed and make a complete copy of the folder and install the beta. Everything should just work when you update it.

**Comment by erengy** [comment]
This issue was fixed with erengy/windows#4 and bc1abf41d7235a6eafa07713a97263d613bfb36e. As @ovingiv mentioned, you may upgrade to the [latest beta](https://github.com/erengy/taiga/releases/tag/v1.3.0-beta.2), which includes this fix.

**Comment by Qwerty-Space** [comment]
Cool, thanks

**Comment by Qwerty-Space** [comment]
Hi, may I suggest adding an option to Taiga settings to upgrade to the beta channel?
