### ISSUE TITLE
Reddit search only yields results when quotes are removed

### ISSUE THREAD

**Issue by TeamDman** [erengy/taiga#535]
I think a good solution would maybe be to change the search context menu entries to be moved to settings.xml, so that people can customize the url's and add their own

**Comment by TeamDman** [comment]
Currently using this userscript to fix it in the mean time:
`// ==UserScript==
// @name         Taiga Reddit Search Fix
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  Removes quotes from reddit search.
// @author       TeamDman
// @match        https://www.reddit.com/search?sort=new&q=subreddit%3Aanime%20title%3A*
// @grant        none
// ==/UserScript==

(function() {
    'use strict';
    if (window.location.href.match("%22") || window.location.href.match("\""))
        window.location.assign(window.location.href.replace(/"/g,"").replace(/%22/g,""));
    // Your code here...
})();`

**Comment by erengy** [comment]
This was fixed in 8ce159530a5aa3b62f8aa24df7355201b3b9d4e4. See #476 for more information.
