### ISSUE TITLE
Multiple season episode-count continuation issue

### ISSUE THREAD

**Issue by Assassin2244** [erengy/taiga#538]
When watching A Certain Magical Index II, the episode numbers continue from the previous season and aren't recognized. Is there a way around this aside from manually updating the episode count? I've tried checking for updates on my client but it says I am up to date on 1.3.0-beta.2

Thanks.

**Comment by such-doge** [comment]
There is a file for specifying continuing episode counts in `%appdata%\Taiga\data\db` called `anime-relations.txt`. There are instructions in the file header on how to add your own rules. You can add an entry for Index II for your personal use, but be aware that Taiga updates this automatically if a new version is found online, which it checks every time it starts up. I encourage you to submit a pull request to the [anime-relations.txt github](https://github.com/erengy/anime-relations/tree/48e711b757a8c97c1fa9284592e45de724a0922b) once you've tested that it works.

**Comment by Assassin2244** [comment]
I followed the instructions in the file and it still does not seem to be working after testing a few things. Tried removing the !, and double checked all of the anime id's. Not sure if it's significant but I am watching via Crunchyroll and not a local file.

`# Toaru no Majutsu no Index -> ~ 2nd season
- 4654|3725|4654:25-48 -> 8937|5541|8937:1-24!`
