### ISSUE TITLE
MAL API returning escaped characters in titles now.

### ISSUE THREAD

**Issue by such-doge** [erengy/taiga#539]
- & is escaped to `&amp;`
- \> is escaped to `&gt;`
- ' is escaped to `&#039;`
- " is escaped to `&quot;`

I'm not aware of any other escaped characters at the moment. &amp; is the only one I see being applied consistently. &gt; appeared for me briefly but disappeared. &#039; and &quot; are applied inconsistently. Cached entries should still appear normal but they will break once Taiga refreshes them. Here's an example of [what they look like](http://i65.tinypic.com/1tpudu.png)

**Comment by erengy** [comment]
Thanks for the report, but this was fixed in fe8e1a0a4a29cd05ec9c1c28ac1651d1084ec154. It's available in the [latest beta](https://github.com/erengy/taiga/releases/tag/v1.3.0-beta.2).
