### ISSUE TITLE
Crunchyroll history scanner?

### ISSUE THREAD

**Issue by Lesorin** [erengy/taiga#541]
Just a suggestion to add history scanner for Crunchyroll to scan and add previously watched episodes.

**Comment by ShaunV2** [comment]
I don't think that is possible at all, the queue and history is not open to the public it is private, only you can see it.

**Comment by erengy** [comment]
Importing anime from various sources (e.g. library folders, text file) is a planned feature. But scanning the history of your Crunchyroll account doesn't seem feasible, as it requires web scraping and authentication.

**Comment by Lesorin** [comment]
Thank you for the response, I'll continue adding entries manually from past history.
