### ISSUE TITLE
Torrent not downloading due to Unicode characters in title?

### ISSUE THREAD

**Issue by Yukirina** [erengy/taiga#542]
Currently using the Taiga beta 1.3, paired with deluge console. The anime in question, Yuru Camp△, can be found in RSS, but when I download the torrent, it merely says "torrent successfully downloaded" and nothing happens. Thinking Taiga/Deluge itself might be the problem, I've tried other anime, and it works perfectly fine. I'm wondering if the unicode character in the anime title is the problem, although it's merely a conjecture.

**Comment by erengy** [comment]
Please see #246 for the same issue. Apparently, they haven't fixed this in the past two years.

Taiga now supports qBittorrent and Transmission too, so at least we have some alternatives.
