### ISSUE TITLE
Libaries are not searched on startup

### ISSUE THREAD

**Issue by St0ner1995** [erengy/taiga#544]
Libraries in taiga are not searched on startup, requiring me to refresh to see what episodes i have.

I'm currently running version 1.2.5

After Application startup:
![screenshot_8](https://user-images.githubusercontent.com/4944499/37858054-5924051a-2f54-11e8-9fc7-ab41b72d7657.png)

After i manually scan for videos:
![screenshot_9](https://user-images.githubusercontent.com/4944499/37858061-64ae55a2-2f54-11e8-8ae4-9e08da518d4a.png)

**Comment by erengy** [comment]
Did you enable the *Settings → Application → General → Startup → Scan library folders for available episodes* option?

**Comment by St0ner1995** [comment]
no i did not.

my bad, even looked for the option too before posting this.
