### ISSUE TITLE
Taiga not detecting Plex with recognition enabled

### ISSUE THREAD

**Issue by GPJailbreak** [erengy/taiga#546]
I have it [opened and playing](https://i.imgur.com/SvYLwox.png) but it refuses to recognize it at all, im on the latest beta build, it didn't work on the latest stable either so i'd hoped upgrading would fix it.

**Comment by erengy** [comment]
This was fixed in https://github.com/erengy/taiga/commit/664918f790b0d22d3c0b1f11362a6c7712db8970. Please see #524 for more information.
