### ISSUE TITLE
Bulk add

### ISSUE THREAD

**Issue by Stenag** [erengy/taiga#55]
Would it be possible to add multiple anime to a list ? For example, say I want to see every Gundam. I'd like to be able to add every results from the research to my Plan to watch list.

Thank you for your time, and continue the good work !

**Comment by erengy** [comment]
This is now possible as of 3d961e4ea5ddc41d88f2d23a557a8457710c8a48 and 85c8b29f2002ee8cca6e71ae96399b6211a6c234.
