### ISSUE TITLE
Title language preference

### ISSUE THREAD

**Issue by Mornwind** [erengy/taiga#552]
I have cancelled the "Display English titles when possible" in the settings, but it didn't work. All the anime titles are always English but not Japanese. Could you please tell me how could I change them into Japanese?

**Comment by erengy** [comment]
Do you mean Romaji (e.g. `Grisaia no Kajitsu`) or Japanese writing system (e.g. `グリザイアの果実`)? Disabling that option should give you Romaji titles where available. There's currently no option to display native titles, although I'm planning to add it in a future release.
