### ISSUE TITLE
Change anime recognition

### ISSUE THREAD

**Issue by Croxino** [erengy/taiga#557]
While watching a new show I accidentally linked it to the wrong anime. How do I fix this?

**Comment by erengy** [comment]
Selecting an anime at Now Playing page adds the current title as an alternative title for it. To revert this, you can open the Anime Information dialog for the selected anime, and remove that alternative title from *My list and settings* tab. Note that it's currently not possible to do this if the anime is not in your list (#183).

**Comment by opensource0apps0enthusiast** [comment]
taiga doesn't recognize anime correctly. the anime i am watching: 

> JoJo's Bizarre Adventure: Stardust Crusaders

The anime taiga recognize it as: 

> JoJo's Bizarre Adventure: Stardust Crusaders - Battle in Egypt

I have tried changing the alternative titles, in both anime to their respective titles. but it still doesn't solve.
