### ISSUE TITLE
Idea: a page with downloaded unwatched episode files.

### ISSUE THREAD

**Issue by oxysoft** [erengy/taiga#559]
TSIA. A page/tab where you can see new episode files you've downloaded but that you haven't watched yet. Would be very useful in my opinion. You could double click an entry to open it and the rest would work just as before, and it disappears from that list once you mark that episode as 'watched'.

**Comment by erengy** [comment]
This should be covered by the progress bar indicators and the *Highlight anime if next episode is available in library folders* option. I don't think a separate page or tab is needed for this purpose, as you can easily distinguish these anime from others, especially when the *Display highlighted anime above others* option is enabled as well.

**Comment by oxysoft** [comment]
Right okay, after having enabled that option and setting the double click to open the next episode that seems to do it pretty well. I also did not know that the bottom green bar of the progress bar showed which episodes are downloaded, and that's pretty damn useful. Quick question, what's the difference between blue and red labels for anime titles?

**Comment by oxysoft** [comment]
You got it wrong, I'm talking about the label itself.

![](https://i.imgur.com/V0f9Ny3.png)

**Comment by erengy** [comment]
An anime title is highlighted if the next episode is available in library folders (and if the relevant option is enabled). The color isn't actually set by Taiga; blue just happens to be the default highlight color of Windows.

Red isn't used at all in this context (unless you're using a modified Windows theme, perhaps). There's only the red square icon, which means the anime is not yet aired.
