### ISSUE TITLE
Average score updater

### ISSUE THREAD

**Issue by PAXMA** [erengy/taiga#560]
I want Taiga to update average score for all the anime in certain list (ex. plan to watch to choose next anime to watch). But I have to open each anime manually and then taiga shows me avg score of opened anime.
Is there a way (a button or something), so I may use to update/download avg score for **all anime**?
If there is no way to do so, will you add one, please?

**Comment by erengy** [comment]
Hi, please see #548 for why average scores aren't updated the way you'd expect.
