### ISSUE TITLE
Episode number higher than episode count - Attribute to new Season?

### ISSUE THREAD

**Issue by TomQDRS** [erengy/taiga#562]
The third season of Boku no Hero Academia is titled "[Boku no Hero Academia 3rd Season](https://myanimelist.net/anime/36456/Boku_no_Hero_Academia_3rd_Season)" on myanimelist.net. However, the sub group "Horrible Subs" is continuing the episode count from the first season on, resulting in the anime not being recognized correctly: 

The newest episode is titled "Boku no Hero Academia - 39" by Horrible Subs, while it would be Episode 1 of Season 3 on MAL. 

Taiga must be recognizing the anime correctly, but probably doesn't handle the episode count being higher than the total count for what's known as the "[first season](https://myanimelist.net/manga/75989/Boku_no_Hero_Academia)" on MAL.

I'd like to suggest a feature where, if the detected episode number is higher than the episode count, the user is prompted for action in the "Now Playing" section. 
A solution for this particular problem would be to define a sort of "cutoff point" at which the episode number is actually attributed to the next season, which of course the user would have to manually search for.

**Comment by asakurato** [comment]
I don't understand, does it work for you or not? It was always been working for me on season 2 and season 3 now, I mean even if the episode is named episode 39, it is correctly detected as episode 1 of season 3. Same was with Attack on Titan season 2.

**Comment by TomQDRS** [comment]
I was unsure of whether it actually happened like this in the past or that was just me remembering it wrong! But now that you say it, you're right, this used to work correctly for me with both Attack on Titan and Hero Academia aswell. Do I need to configure something in the anime settings for this to work correctly?

Otherwise consider this issue not as a feature request and more like a bug report, because right now, with version 1.3.0, playing episode 39, "Now Playing" just says Taiga couldn't identify the title.

**Comment by asakurato** [comment]
Hmm, I just tried HS version myself and it is indeed not detecting the series (I used Erai-raws, so I assumed HS would work). I'm 100% sure I watched both Hero Aca and AOT s2 from HS and Taiga used to work,

**Comment by wopian** [comment]
Will be resolved with https://github.com/erengy/anime-relations/pull/16

**Comment by TomQDRS** [comment]
Didn't know that existed. Thanks mate!
