### ISSUE TITLE
HIDIVE Detection doesn't work when the player loads the next episode

### ISSUE THREAD

**Issue by Jasonfran** [erengy/taiga#565]
HIDIVE doesn't reload the page on the next episode like Crunchyroll does (unless CR is fullscreened), it loads it in page, asynchronously or whatever you call it, and so Taiga doesn't detect that the next episode is playing. 

Is this possible to be fixed? Does Taiga only check Chrome page loads? Or is it possible to check URL changes too since HIDIVE _will_ update the URL on the next episode load, even if it doesn't fully reload the page.

If this isn't possible to fix then is it possible to add a button to the "Now playing" page in Taiga which forces it to go to the next episode? Or add a refresh button or something?

**Comment by erengy** [comment]
The URL is changed but the page title is not, right?

Ideal solution would be for HIDIVE to update the `document.title` in addition to calling `window.history.pushState()`, when their player loads the next episode. That looks like an oversight on their part. Is it possible to tell them about this issue?

Taiga relies on the page/window/tab title to identify the anime. If the title stays the same, it wouldn't make a difference to detect the changes to the URL or to force Taiga to restart media detection. Taiga could theoretically combine the information from the title and the URL, but that'd make things a lot more complicated, so I'd rather avoid doing that.

**Comment by Jasonfran** [comment]
Okay, I'll write a support ticket asking whether they can do it.
