### ISSUE TITLE
Not yet aired anime recognition

### ISSUE THREAD

**Issue by taigalover** [erengy/taiga#568]
High School DxD Hero has an episode, but this episode is not episode 1 but its episode 0.
Here it is in my Currently watching list:
![screenshot 85](https://user-images.githubusercontent.com/32505754/38726554-0f90baa8-3f3d-11e8-9e35-9eccdb47fa05.png)

And here it is once i searched for it on nyaa.si torrent:
![screenshot 87](https://user-images.githubusercontent.com/32505754/38726584-2631de40-3f3d-11e8-8f30-f0659c927302.png)

It doesn't select it.

I have a torrent filter which searches for currently airing anime in my Currently watching list but that wouldnt work for Not yet aired anime. So i made a filter which selects Not yet aired anime in my Currently watching list:
![screenshot 88](https://user-images.githubusercontent.com/32505754/38726857-f3c07cae-3f3d-11e8-9998-7fb995c60060.png)

And it still didn't select it:
![screenshot 87](https://user-images.githubusercontent.com/32505754/38727136-c132dc22-3f3e-11e8-85c4-cae5e5f91d09.png)

What am i doing wrong? Or is episode 0 not an actual episode so taiga wont recognize it?

**Comment by erengy** [comment]
> Or is episode 0 not an actual episode so taiga wont recognize it?

Yes, it needs to be added to [erengy/anime-relations](https://github.com/erengy/anime-relations) first to be identified properly.

**Comment by taigalover** [comment]
Any plans to add it though? Or maybe wait and see if MAL adds it as a special to its database?
