### ISSUE TITLE
Parser not recognizing specific episodes

### ISSUE THREAD

**Issue by such-doge** [erengy/taiga#572]
Using Taiga 1.3. These releases are not being recognized correctly. The issue affects only the two releases mentioned below so far. Other episodes of the same series are recognized correctly.

`[HorribleSubs] Hinamatsuri - 01 [720p].mkv`
`[HorribleSubs] Caligula - 01 [720p].mkv`

**Comment by asakurato** [comment]
When you go to Now playing, there will be suggestions of which anime is playing. Click the correct one and it will recognize it from now on.

**Comment by such-doge** [comment]
@asakurato That is not the issue. Series recognition is not the issue. It fails to recognize only when the episode number is 1. Episode 2+ are recognized just fine.

**Comment by erengy** [comment]
I'll just note that this the same issue as #379 (also yours).
