### ISSUE TITLE
[Suggestion] Backup Feeds?

### ISSUE THREAD

**Issue by Statharas** [erengy/taiga#575]
Nyaa.si is down, but right now Nyaa.at is up, which according to https://twitter.com/NyaaV2 is a secondary host. It might be wise to implement this, and possibly implement an additional backup host, maybe on Anidex

Of course, changing nyaa.si to nyaa.at works only for torrent searches, as Tokyotosho points to nyaa.si

**Comment by erengy** [comment]
Nyaa.si seems to be back up now. I don't think I'll add the .at domain to the default feeds, unless .si permanently goes down.

Also note that Anidex is already available in the default feeds, along with some other alternatives.
