### ISSUE TITLE
Separate delays for list updates and automatic sharing

### ISSUE THREAD

**Issue by Shelmor** [erengy/taiga#579]
Right now there's an option to set a delay for both list updates and automatic sharing. And I think making a separate options for each of them would be good. For example: if someone wants to share immideately as he starts an episode but NOT update his list that soon - it's not possible. 
The only workaround I've managed to find is setting the delay desired for the list updates and manually clicking the "share" button on the now playing tab. Yeah, it works that way, but being able to do it automatically (by setting different delays) would be an awesome feature.

**Comment by erengy** [comment]
I'd like to explain why automatic sharing is somewhat tied to list updates.

When you open a video in a media player, Taiga tries to detect the player and identify the video. However, it can't be sure if you're actually watching it. Maybe it was a misclick. Maybe you're navigating from one file to another. Maybe you just want to take a peek... In cases like these, Taiga shouldn't make accidental updates. The delay option (2 minutes by default, 10 seconds minimum) prevents this, to some extent.

Here, what's being delayed is *recognition*. In other words, Taiga waits until the delay time is up to consider that you're watching something. When you think about it like this, it doesn't quite make sense to have multiple delays. If you're really watching something, why would you want to further delay an update?

If you find the default delay too long, you can change it to a smaller value. If you don't want your list to be updated that soon, you can enable the *Wait for media player to close* option. This is in fact the intended way to use Taiga, although the defaults are a bit different to accommodate new users (perhaps I should review them too for the next major update).

I intend to work on this in v1.4, as I mentioned in https://github.com/erengy/taiga/issues/554#issuecomment-379025045. But I'd rather find a way to make the delay more straightforward, than to introduce multiple delay options.
