### ISSUE TITLE
episode count offset

### ISSUE THREAD

**Issue by Jiyuu** [erengy/taiga#58]
in some cases different groups use different numbering schemes,
for example currently Mushishi Zoku Shou is being released,
on MAL it has its own entry called "Mushishi Zoku Shou 2nd Season" which is fine, the problem is that different groups seem to count the episode(along with the special which was counted as episodes 11+12 ) simply as part of "Mushishi Zoku Shou", thus numbering it with 13,14 etc..

this is one such example, but i fairly sure that is not the first, nor the last this would happen.

i am sure there are a few solutions to that, the simplest(but obviosly the least ideal) would be to add for every series an "offset" value thus any number it parses would be offset by said value.
that should work as long as one only watches a single fansub group and there is a simple systematic shift.

a somewhat more complex option would be to set the same value per fansub group, but i suspect that would be more complex, seeing as that i cannot see any other setting kept per group.

these are the solutions that i thought about at least, i'd just like -something- as long as it works..
any comments?

**Comment by beefeater7** [comment]
How are things going with this? I took a look at anime_db.cpp. It contains just 4 sequel titles, and requires compilation for every change. 

Why isn't this list a separate file, at least, like a txt? I know it's not an optimal solution, but it's a good stopgap until and if this is made a feature to regular users.

**Comment by erengy** [comment]
I haven't gotten to this yet, but it seems that the process almost definitely needs human supervision. My previous idea to write an algorithm to predict relations may work in some cases (e.g. *Fate/Zero*), but it fails to address the issue that is exemplified by *Mushishi*. This is how the series appears on MyAnimeList, and the relevant HorribleSubs releases are numbered:

Anime title|Episode range (MAL)|Episode count (MAL)|Episode range (sub)|Episode count (sub)
---|:---:|:---:|:---:|:---:
Mushishi Zoku Shou|1-10|10|1-10|10
Mushishi Zoku Shou Special|1|1|11-12|2
Mushishi Zoku Shou 2nd Season|1-10|10|13-22|10

Note that *Mushishi Zoku Shou Special* is considered an intermediate release and counts an additional episode. There's simply no way to make Taiga figure this out all by itself. This is kind of an extreme example, but there are other cases where a TV series is extended by a multi-episode OVA or Special (e.g. *Kokoro Connect*, *OreImo*). Simply sorting TV series with similar titles by their airing date is out of the question.

So, I'm now planning to follow @rr-'s advice and make the relation graph a publicly editable JSON file that is hosted on GitHub and/or my own server. First, I need to figure out whether I need to specialize the ordering based on fansub groups or not. Let me know if you have any knowledge on the matter. More example filenames would also be appreciated.

**Comment by erengy** [comment]
[Done](https://github.com/erengy/taiga/blob/develop/data/db/anime_relations.json).

**Comment by amboris** [comment]
hm... dunno if i should make new post, this topic is kina old to revive but still needed and havent been done jet.

my solution is that you write a simple math convert funktion added to alternative name box or add a new box called "starting episode value".
what i mean is that when taiger scan the folder it should search for the episode number+the set starting number. formula: n=a+(b)   n...update falue a....current episode count       b... set starting episode value.
this function is only for taiger episode recognizion scan and wont change the taiga update script or function.

for example.
i'm watching major current s4
season 4 have a episode range of 26
the sub group did a patch with the filename "major" without season added
i add major s4 edit
s4 starts with the episode 79
i set starting episode to 79 (in the function i want to add to scan for new episode function)
i set alternative name to major (if it doesnt recognize)
so it scans folder with the starting episode 79 ( currecnt count a=0, starting value b=79 ; n=a+(b) "1=0+(79)" )
taiga recognize episode 79 as episode 1 video player started
episode played
taiga update to 1
