### ISSUE TITLE
Firefox not detected

### ISSUE THREAD

**Issue by Abchrisabc** [erengy/taiga#580]
**Product:** _Taiga 1.3.0_
**Platform:** _Windows 10 RS3 1709_
**Classification:** _Minor Bug_

**Summary:**
The Recognition services for Taiga aren't working on Firefox Quantum 59. I have the right settings enabled, it works on other browsers.

**Steps to reproduce:** 
Enable recognition settings, use Firefox Q59, watch any supported service.

**Expected Result:** 
Taiga recognizes the anime as 'Now Playing'.

**Actual Result:** 
Taiga doesn't show the anime as 'Now Playing', or unable to identify.

**Severity:** Minor

**Attachments:**
[Screenshot of Browser, Taiga and Taiga Settings](http://prntscr.com/jbk1h2)

**Comment by erengy** [comment]
It might be because you're running Firefox as administrator. If that's the case, could you try not doing that, or running Taiga as administrator too?

**Comment by Abchrisabc** [comment]
As far as I'm aware, I don't have Firefox running as Administrator. However I did just now try to run Taiga as Administrator, but to no avail, Taiga is still not recognizing any Anime in FirefoxQ59

**Comment by erengy** [comment]
Is this still an issue? Just tested Firefox 60.0.1 and Taiga was able to detect the browser. I'm using Firefox Developer Edition 61.0b8 on a different computer and that works as well.

Could you try running Firefox in safe mode via *Help → Restart with Add-ons Disabled*?

**Comment by Abchrisabc** [comment]
It is still not detected; restarting with Add-ons Disabled also doesn't work.

**Comment by erengy** [comment]
Could it be that you have [*Prevent accessibility services from accessing your browser* option](https://support.mozilla.org/en-US/kb/accessibility-services#w_how-do-i-disable-firefox-accessibility-service) enabled? Taiga uses UI Automation to retrieve information from web browsers, and that option prevents that.

**Comment by Abchrisabc** [comment]
Seems that was the case, however the option was turned on by default as any other computer also did not work when I switched to Firefox after a long time of using Chrome.

**Comment by erengy** [comment]
I double-checked that the option (`accessibility.force_disabled` at `about:config`) is turned off by default. In other words, Taiga works in Firefox's default configuration. Perhaps you enabled the option previously, and your settings were synchronized between computers.
