### ISSUE TITLE
HTTP error #35; SSL connect error

### ISSUE THREAD

**Issue by oplexz** [erengy/taiga#581]
`2018-04-30 19:38:32 [Error] http.cpp:94 taiga::HttpClient::OnError | >>
HTTP error #35: SSL connect error
Connection mode: 1`
I tried disabling certificate revocation checks, didn't help 😢

**Comment by erengy** [comment]
I'm afraid I don't have any other suggestions than setting *Application / Disable certificate revocation checks* to `true`. I'd try restarting my computer afterwards, to be sure.

In any case, let's close this issue since #312 is still open.
