### ISSUE TITLE
MAL error to update

### ISSUE THREAD

**Issue by marioporfirio** [erengy/taiga#584]
I'm getting the error "too many failed logins attempt", my login is correct and i didnt receive these error in previous versions of taiga, i dont know if this is a taiga error or a problem with myanimelist api. Because of this error i cant use taiga more, i am being forced to use myanimelist site. I'm using taiga v1.3.0

**Comment by taigalover** [comment]
Have you tried to completely uninstall taiga, then uninstall?

**Comment by erengy** [comment]
Could you check your History page to see if there are any anime waiting in your update queue? I received a similar report just recently, and it was resolved after removing an item from the queue, which was blocking further updates (see #138).
