### ISSUE TITLE
Recognition

### ISSUE THREAD

**Issue by taigalover** [erengy/taiga#586]
Why is Hinamatsuri episode 1 not highlighted in my feed? But every other episode is? 
Pic:
![screenshot 28](https://user-images.githubusercontent.com/32505754/39965458-7a802812-56cb-11e8-8a5f-fd9c2f1c78e4.png)

My nyaa feed is an english-translated feed: `https://nyaa.si/?page=rss&q=%title%&c=1_2&f=0`

None of my filters are on in that screenshot

**Comment by erengy** [comment]
See #572 for the same issue. It happens because there are multiple anime named *Hinamatsuri*, and Taiga needs user input to resolve the ambiguity.
