### ISSUE TITLE
Entries under "Continue watching" and "History" gone

### ISSUE THREAD

**Issue by todesschnitzel** [erengy/taiga#587]
Looks like Taiga has overwritten my history.xml, which is now empty. 
Any way to trace back the issue?
Win10, V.1.3.0

**Comment by erengy** [comment]
Do you have Taiga installed in its default location (`%AppData%\Taiga\`) or a different one? If it's under a protected directory such as `Program Files`, Taiga may not be able to save its settings and other data.

Another possibility is that a security application on your system might be blocking Taiga from working properly. In that case, you can try whitelisting Taiga in that application.

I'm afraid I cannot think of any way to restore the data.

Also see #360 and #339.

**Comment by todesschnitzel** [comment]
I have it installed in its default location and nothing showing up on any log from Windows Defender. If it would show it at all....
Settings didn't reset for me, like the Library Folders.

**Comment by erengy** [comment]
Assuming that you didn't clear your history (either from *Settings → Library → Cache → Clear* or directly from History page) by mistake, I can't think of any other reason why it would be reset.

**Comment by BlackJoe23** [comment]
i just tried to switch to kitsu before closing but it gave an you can't switch service with queued update error. but when i closed the app the change was applied and it didn't show the old shows so i reverted to a backup of that version. when i changed xml to myanimelist before opening everything was back.

**Comment by erengy** [comment]
This is likely the same issue as #637.
