### ISSUE TITLE
Kitsu Sync issue

### ISSUE THREAD

**Issue by dobbleg1000** [erengy/taiga#589]
"Kitsu returned an error: The provided authorization grant is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client." is the message i get
I have reinstalled Taiga. Copy and pasted my pass to make sure it is right. I just switched to kitsu so i know all my info is right.

**Comment by asakurato** [comment]
this is probably related to the GDPR as well. See "MAL API is down" here.

**Comment by asakurato** [comment]
or you should try changing password and see if it works again

**Comment by wopian** [comment]
>this is probably related to the GDPR

No it's not. It just means the user/pass combination is invalid.

---

What are you putting in the username field? Sounds like you may be using your display name if you just joined Kitsu - the `username` field uses your [Profile URL](https://kitsu.io/settings/profile) which isn't set by default. Alternatively, you can use your email as the username field.

![](https://i.imgur.com/AahsWz9.png)

**Comment by usagirei** [comment]
Not sure if will work for you, but i seemingly fixed this on my end by setting the Profile URL the same as my username under https://kitsu.io/settings/profile

**Comment by dobbleg1000** [comment]
Same as what @usagirei said. Thanks for the help
