### ISSUE TITLE
MyAnimeList returned an error (read below)

### ISSUE THREAD

**Issue by RaisinBran36** [erengy/taiga#591]
![capture](https://user-images.githubusercontent.com/39650205/40576946-f3ec1c88-60cb-11e8-9c3d-3e04f39f1b69.PNG)

last week taiga was working fine and now, without making any changes to my computer,  it's not able to update my list or search any new shows. but the torrent searcher still works. 
ive restarted my computer, and reinstalled taiga but the problem persists

**Comment by wopian** [comment]
MAL disabled their API - see #588

**Comment by NotDaniel59** [comment]
Switch to kitsu or anilist, anilist now allows to import you MAL list via XML.

**Comment by RaisinBran36** [comment]
is there  a guide for that? i have no idea how to do it

**Comment by Dibakarroy1997** [comment]
Someone posted a [full guide on r/anime](https://www.reddit.com/r/anime/comments/8mfpvo/wanna_try_out_a_new_animelist_website_try_one_of/)
