### ISSUE TITLE
Support for recognition of mpc-qt

### ISSUE THREAD

**Issue by mfsoup** [erengy/taiga#593]
mpc-qt is a clone of mpc-hc but based on mpv. Support of this player would be appreciated.

https://github.com/cmdrkotori/mpc-qt

**Comment by erengy** [comment]
Last time I tried (v17.11), I wasn't able to run the application due to a runtime error. I'll give the latest version another try at erengy/anisthesia#1.

**Comment by erengy** [comment]
I wasn't able to run v18.03 either. Tried it on a VM with a fresh installation of Windows 10 Pro x64 (1803). Nothing happens when I execute `mpc-qt.exe`. I can briefly see it on Task Manager, but then it disappears. @cmdrkotori

**Comment by cmdrkotori** [comment]
Hmm, I build on Windows 10 Pro x64 but perhaps my dev environment is polluting the system. This means I have libraries under c:/msys2 or so. (I also have file and application scanning turned off, but I digress.) Coincidentally I also have someone complaining about it not starting at https://github.com/cmdrkotori/mpc-qt/issues/195, which smells like a graphics problem, but that's probably not what is going on here.

This is how my latest build looks with no config folder:
![screenshot_20180528_232937](https://user-images.githubusercontent.com/11322485/40616599-08b2f1dc-62cf-11e8-9b58-8d021507633c.png)

I just tested if my brother has Windows 7 x64, and v18.03 runs there. If it worked previously but is not now, remove its config folder at AppData/Roaming/mpc-qt? Perhaps geometry.json got hosed or some such.

**Comment by erengy** [comment]
@mfsoup Could you try the [latest build](http://taiga.moe/latest.html) and see if it works for you? I added mpc-qt support somewhat blindly. It *should* work, but I couldn't test it myself.

**Comment by kayabe** [comment]
i tested mpc-qt 18.03 with the latest build of taiga and it seems to work

**Comment by mfsoup** [comment]
It works on the latest build for me. Thanks!
