### ISSUE TITLE
Can't synch Kitsu

### ISSUE THREAD

**Issue by Papde** [erengy/taiga#594]
Same as issue #468 : "Kitsu returned an error: The provided authorization grant is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client.". 

Today's my first time using Taiga and Kitsu both, because of the MAL API problems. However, the comments of issue #468 do not help me. I've reinstalled Taiga, re-entered my password and account etc. But reinstalling the Kitsu add-on? Is there even a Kitsu add-on and if so, where can I find it?

**Comment by erengy** [comment]
Please make sure that you're entering your username rather than your display name. It's displayed as "Profile URL" in your [Kitsu settings](https://kitsu.io/settings/profile). See also #589.

**Comment by Papde** [comment]
Thank you very much! I didn't have a profile URL yet and made one.
