### ISSUE TITLE
Add filtering by "file extension"

### ISSUE THREAD

**Issue by Desperer** [erengy/taiga#599]
My Taiga has automatically downloaded both a .rar and an .exe file from a fake "HorribleSubs" over the past two weeks. Attempting to filter out these types of files by file name does not work. In fact, Taiga does not even recognize the extension in the filename on these files (it shows as just a .mkv when it is actually named as .mkv.rar). Attached is an example of a .rar file from Nyaa.si and how it appears in Taiga.

![image](https://user-images.githubusercontent.com/2962354/40755158-c512e372-6442-11e8-9c6f-61d2a2fe8e43.png)

I suggest adding an option to filter by file extension, in order to prevent harmful files from being downloaded automatically.

**Comment by erengy** [comment]
I'm afraid that's not possible. Contents of a torrent file are not included in RSS feeds, so there's no way to check the actual filenames or extensions. Taiga is only aware of the `title` element of RSS items, which might be a fake filename as in your case.

To avoid downloading malicious torrents, you can try using the "Trusted only" filter of Nyaa.si (by changing the `f=0` in the feed URL to `f=2`), or creating a filter to discard torrents smaller than a certain size (#510).
