### ISSUE TITLE
Life after MyAnimeList

### ISSUE THREAD

**Issue by erengy** [erengy/taiga#601]
After ten years of anime tracking, I decided to stop using MAL. This has a lot to do with its extended downtime (#588), but it's also due to years of weariness as a developer. Seeing DeNA's lack of concern for the website, its staff and its users was the last straw for me. I've lost trust in their management, and I don't want to use or promote their product anymore.

I'm currently debating whether I should remove MAL entirely from Taiga. For now, I decided to take the following actions:

- [x] Add a [list export feature](https://github.com/erengy/taiga/issues/588#issuecomment-393226127), so that people can move on to other services.
- [x] Remove instances of "MyAnimeList" from Taiga's website.
- [x] Change the default service to AniList or Kitsu, or leave it blank.

And here's some ground rules I set for myself:

- No participation: I'll no longer take part in MAL community. I won't visit the website unless I have to.
- No support: If anyone has any problems related to MAL, I will no longer try to explain that it's because how awful MAL API is. I will now recommend using one of the alternative services instead.
- No effort: I'm not going to spend any more time working with the old API, checking out unofficial ones, or devising my own workarounds.

I should note that I'm not burning bridges here. I will certainly reconsider my position, especially if the new MAL API becomes available. Nevertheless, I believe it's time I stopped complaining and took some action.

**Comment by Ricardo1991** [comment]
I have a few entries not yet synced because of the MAL downtime. I assume Taiga wont have trouble exporting them?

**Comment by erengy** [comment]
Yes, it takes your update queue into account while exporting your anime list.

In case you aren't aware, you can [export your anime list](https://github.com/erengy/taiga/issues/588#issuecomment-393226127) right now.

**Comment by moyitpro** [comment]
I have to admit that I kind of feel the same way. I already temporarily disabled MyAnimeList support and removed references for it on the Mac App Store. There is one reason why as Apple will never approve an updated version as long MyAnimeList API is down. 

I have to admit that DeNA ninja disabling the new API really annoyed me as I wasted time getting it to work. Now, seeing them disable the API was the last straw. I am not sure I am confident in them fixing this given what they did. 

If the new API ever comes back, I will continue working on it. If not, I will focus my efforts on adding other sites support.

**Comment by asakurato** [comment]
well, MAL just came back online. Would be sad if taifa stopped supporting it, as I'm not ready yet to move to another service.

**Comment by moyitpro** [comment]
@asakurato

It only depends if DeNA restores the API or even the new one. Still, I don't have much faith in them doing the right thing given their actions with ninja disabling the new official API and then the legacy API.  It's very disappointing and it's obvious that the forum mods and xinil didn't the API to be disabled, but one can only blame their incompetence and mismanagement. I feel that DeNA simply doesn't care about the efforts third-party developers put into creating innovative MyAnimeList clients that make list management easier. Why would you use MyAnimeList now that the very tools that made the experience better is gone? Sure there is the community and database, but the usability in my opinion went down the drain. Most people like myself don't want to manually edit entries and want it done automatically.

The only way they will listen is if everyone start using different services, which have gotten better and actually care about third-party apps.. Once they noticed the drop in ad revenue and activity, they will change their mind. 

tr;dr: I won't bet on the API coming back soon given DeNA's actions.

**Comment by dr4chen** [comment]
Well, as a user of MAL, this is a bit unfortunate, but I understand completely your position as a developer. MAL has genuinely insulted the community by its recent actions. I can only hope that the new API they introduce, whenever that may be, will be friendly enough to all the third-party heroes that have helped make browsing and using MAL so much better throughout the years.

Fortunately, with the site's partial restoration today, I was able to export my list and import it to AniList, so I'll just be linking my Taiga there. Thanks for your continued work!

**Comment by ShaunV2** [comment]
@asakurato Kitsu is a much better service than MAL will ever be, they have competent staff and database mods who know how to do their job right which can't be said about MAL database mods as they do not know how to do their job right at all and constantly refuse to listen to users when it comes to database entries, refusing to add separate entries to certain series when asked or not listening to their users when told a certain series has a certain amount of episodes.

I've been using Kitsu/Hummingbird since Sept 3rd, 2013 and I fully support it and no longer support MAL.

**Comment by asakurato** [comment]
@ShaunV2 wait, so you haven't been using MAL since 2013? And about the database moderators, I think this is exactly the best part on MAL. They have very strict and logical database guidelines. If they hadn't, something like Neo Yokio and Last Airbender would be on the site.

**Comment by ShaunV2** [comment]
@asakurato What I meant by them not doing their job right is not adding a separate page for Enmusubi no Youko-chan when it is needed and refusing to fix the episode count to To Love-Ru Darkness 2nd to 14 episodes instead of 12 and deleting the non-existent special.

I was using MAL with Hummingbird/Kitsu for a long time but the database mods just pissed me off too much to care about the garbage site anymore.

Just to be clear I started using MAL first a very long time ago (I believe I made the account in 2012) before I even heard of Hummingbird, due to an outage they had in 2013 I moved over to Hummingbird and have been a member ever since.

**Comment by asakurato** [comment]
I'm checking out Anilist right now, seems good. maybe I'll move there.

**Comment by chocolatkey** [comment]
If they have an app (when they put it back up), they must have an API ;)

**Comment by erengy** [comment]
@ShaunV2 @asakurato Please try to remember that this is an issue tracker, not a forum.

**Comment by SnowyNix** [comment]
I get how you feel from a developer's perspective, but to me as an end user, MAL is still the best choice hands down, easily beating out its competitors in ease of use and database completeness. And it's not just me that feels this way, MAL is the most popular site of its kind by a huge margin, so completely ceasing MAL support certainly feels to me like burning a bridge, even if DeNA's management is questionable to say the least, which it definitely is - even I, as the MAL shill here, definitely agree with that. I don't know anything about the API, so I can't blame you for being frustrated by it, you have more of a right to talk about that topic than someone like me, but even still, all things considered, I urge you to retain MAL support unless you want to lose a massive portion of your userbase. That's not me being threatening or anything, just my two cents. If Taiga stops supporting MAL, it won't make me switch to AL, it'll just frustrate me - and I'm sure that a _lot_ of people would feel the same way.

I genuinely appreciate the work you've done on Taiga and, of course, I realize that it's ultimately your call to make. Have a nice day!

**Comment by ckmox** [comment]
i do not use your app yet but i know its a popular app and i might use it sooner or later i just want to say that make Kitsu the default since that site have a MAL Sync feature on its Export option so at least when people update their Kitsu lists then their MAL lists will be updated automatically too

**Comment by magicmaster** [comment]
The only usable app bites the dust. Hope someone forks it.

**Comment by guft** [comment]
Thank you for the export feature. I've transitioned to AniList with only about 10 or so entries lost due to database differences (mostly specials that AniList doesn't track separately from the main show). Looking forward to a bright, MAL-less future.

**Comment by HyphenSam** [comment]
@SnowyNix I hope you realise the absence of an API makes supporting MAL incredibly infeasible. Erengy doesn't really have much of a choice but to drop support for MAL until they release a new API.

**Comment by SnowyNix** [comment]
@HyphenSam I definitely realize that if DENA doesn't get their shit together, there won't be a functioning API for MAL, and therefore third-party apps won't work, and in that case, it's completely understandable why Taiga would want to cease support, but erengy made it sound in the OP like he's going to be completely giving up on the website forever, which I don't think would be very fair if and when DENA gets the API working again.

The fault is obviously on DENA here, they're doing an abysmal job at managing the website, but I also think that completely stopping MAL support forever would be a bit of a foolish thing to do _if_ the API came back at some point. If it doesn't, then I really can't blame him.

**Comment by erengy** [comment]
This is not about Taiga not supporting MAL. This is about MAL not supporting Taiga and other applications.

First, there's the old MAL API that Taiga has been using since 2010 (an [API](https://en.wikipedia.org/wiki/Application_programming_interface) is what makes it possible for applications such as Taiga to communicate with MAL). It's incomplete, inconsistent and buggy. Many quirks of Taiga are directly caused by it. I've spent *hundreds of hours* trying to deal with it, and that's just me, a single developer. In case you're wondering, I'm not paid for this, not even with [donations](https://github.com/erengy/taiga/issues/89).

Throughout the years, we the third-party developers tried to help MAL in any way we can so that they improve their API. But even the simplest of our requests were left unanswered. At one point, when MAL was still owned by CraveOnline, they formally asked us what we'd like to see in a new API. We combined our efforts and provided detailed feedback. But then they stopped communicating with us, and the possibility of a new API went down the drain. Not only that, but in time, MAL has crippled their old API even more.

Two years after DeNA acquired MAL, they approached us once again, to discuss their new API. I, along with other third-party developers, have spent a lot of effort to help with its design (you can see an example in [this document](https://gist.github.com/erengy/94dd605fb9f37ec9866e439120bd9d04) I compiled). DeNA eventually began implementing our ideas. The new API was taking shape. MAL's official mobile app started using it. We were optimistic about being able to use it ourselves sometime this year. But then they cut our access to it, without much of an explanation. Then they suddenly [took the old MAL API down](https://github.com/erengy/taiga/issues/588), without a single word. It's been ten days now, and we still haven't been told if it's *ever* going to be restored.

Now, tell me: Don't you think we deserve some more respect? Are we going to act like nothing happened? How are we supposed to trust them again?

I'm aware that my decision will affect Taiga's userbase. I can understand that some users will not care as long as Taiga keeps working. But at what cost? Our continued suffering?

Nothing's going to change if we keep accepting whatever MAL throws at us. If we have any chance at actually getting a better service, I believe this is it. It's up to us to convince them, DeNA in particular, that they hurt their users *and* their company. Their actions must have consequences.

To clarify, the latest incident is almost entirely DeNA's fault. MAL staff I know feel quite bad about the whole situation. Please understand that my attitude is not toward any person.

If MAL restores their old API as is, Taiga's current version (and at least the next version) will continue to work as before. What I'm *not* going to do is to spend any more effort in trying to overcome its shortcomings. This includes compiling and releasing further [seasonal data](https://github.com/erengy/anime-seasons) for MAL users (other services don't have this problem, because they provide much better APIs). This is, of course, assuming that their API comes back online. I don't expect this to happen anytime soon.

Despite everything, I haven't lost all hope. MAL can still pull itself together. But if they want us to keep working together, they're going to have to do more than an apology.

**Comment by taigalover** [comment]
Doesn't seem like the API is coming back anytime soon according MAL's twitter reply
![image](https://user-images.githubusercontent.com/32505754/40888408-41891f9a-6789-11e8-8e66-e696423c5433.png)

**Comment by CDB-Man** [comment]
Well, as a mod on AniDB, we already saw an influx of users coming our way and abandoning the MAL ship.

**Comment by KikunXyy** [comment]
Wow, MAL's worse than I thought. Thanks for elaborating, Erengy. As a developer myself, I can understand your frustration to some extent. Fully support your decision on this.

**Comment by asakurato** [comment]
I think we will have API back soon
![capture](https://user-images.githubusercontent.com/20476454/41122315-2de931a2-6aac-11e8-909b-6036a17b15e9.JPG)

**Comment by erengy** [comment]
@asakurato See https://github.com/erengy/taiga/issues/588#issuecomment-395689578. Also note that #588 is more appropriate for news regarding MAL API.

**Comment by BlackJoe23** [comment]
A shame mal is so enormously disrespectful towards developers since I really like that they have builtin update history like taiga. (you can't export it though...)

**Comment by Statharas** [comment]
I second tge motion that Anilist is selected by default. Comparing both websites, Anilist feels fresh, while MAL feels dated, and the service provided, although Anilist still has some quirks, it is much better and from my own experience, stable.

**Comment by ShaunV2** [comment]
@Statharas Kitsu is actually better than both MAL and Anilist.

**Comment by rld243** [comment]
You can't hide your profile or list on Kitsu (or I didn't find out how). That's a problem for me. So I'd prefer Anilist for now.

**Comment by ShaunV2** [comment]
@rld243 There are options to prevent your posts from appearing on global under privacy (there is no way to hide it completely, I don't understand the need to fully hide your profile that just defeats the purpose of having one) and yes you can hide your library, per library entry that is not the whole library at once.  Go to your library and click on edit to a series and set the privacy to public or private.

**Comment by Statharas** [comment]
Anilist is made on the Laravel framework, providing incredible API tools, v2 update moved onto Angular, and besides the fact that its service so far has been incredible, the developer behind it is very co-operative and has proven to be reliable in the past.

**Comment by rr-** [comment]
>Life after MyAnimeList

I switched to a simple text file about 4 years ago… and never looked back.
(Precisely due to the reasons mentioned by @erengy, for which I can fully vouch as the developer behind MALgraph.)

**Comment by taigalover** [comment]
@rr- Wait what? A text file? How does that work? Do you have a PTW? Do you update episode by episode? How do you know what you completed?

**Comment by Fixkey** [comment]
@taigalover it looks like he is having a list on his website: [https://sakuya.pl/anime.htm](url)

**Comment by rr-** [comment]
@taigalover Wow that's a lot of questions :)

>A text file? How does that work?

It's just a regular .txt file. You can edit these with pretty much anything.

>Do you have a PTW?

Yes

>Do you update episode by episode?

No

>How do you know what you completed?

I just add a line with the anime title after I finish something.

>Do you not engage in forums, or you're not interested in the social aspect of the Anime-sites?

I was never really interested in online anime forums to begin with, I mostly discuss anime with a bunch of buddies.

>How do you get recommendations?

I get these from my friends, I also look up recommendations and tags I like on anidb.

>Then how do you use Taiga?

Unfortunately I don't ever since I quit MAL (plus I switched to Linux a few years back), but it's an excellent piece of software I recommend to anyone.

**Comment by Ruhrpottpatriot** [comment]
Let's hope that dropping MAL can speed up development of other features that weren't possible because the MAL API sucked balls. Like actually having the ability to update multiple trackers at the same time (I have some ideas how that could work without too much work on Taigas side)

**Comment by 9Morello** [comment]
Is there any free/libre MAL alternative?

**Comment by moyitpro** [comment]
@9Morello 

It's right on Taiga's website. It supports [AniList](https://anilist.co/) or [Kitsu](https://kitsu.io/)

**Comment by 9Morello** [comment]
@moyitpro My bad, I checked AniList's repository and it is almost empty. Kitsu doesn't seem to have a link to their repository on their website, so I assumed it was proprietary. Good to know it's free.

**Comment by wopian** [comment]
AniList is closed source as far as I'm aware. Kitsu does have a link to their repo in the feed sidebar - really needs to be in more places imo, as it's not visible until you register/login atm

**Comment by Kovaelin** [comment]
Does anybody have any news on whether or not ANN plans on expanding their API beyond just the encyclopedia?

**Comment by YoshiYogurt** [comment]
As a MAL user and Mac/Linux user I've been eagerly awaiting a Unix release of Taiga. Guess I'll keep waiting for the MAL API to come back. On the slim chance that Taiga ever functions with MAL again and releases a non-windows version Ill finally be able to use this app.

**Comment by rr-** [comment]
@YoshiYogurt You might be interested in https://github.com/z411/trackma

**Comment by Fcort237** [comment]
currently what anime database do you recommend? myanimelist, anime planet, Taiga, Kitsu etc? what do you use? I want to make an anime website =? please help me

**Comment by darkash** [comment]
https://twitter.com/myanimelist/status/1030444972489809921

finally they gonna give some ETA and info about API, welp

**Comment by Tenome** [comment]
I think it's good to move away from MAL. They got bought out, and now they're even removing the fansubs section. It's clear what they're becoming.

**Comment by servicemx** [comment]
Hey what do we put for RSS feeds? Taiga no longer works for me and I do not know what to do. Please help. Thanks!!!!

**Comment by taigalover** [comment]
More than 40% increase in AniList users wow. And less than 10% increase in Kitsu users. Damn no love for Kitsu.

**Comment by Kovaelin** [comment]
> More than 40% increase in AniList users wow. And less than 10% increase in Kitsu users. Damn no love for Kitsu.

It was pointed out to me that Kitsu had some professionalism issues of their own in the past, which is why I joined some other friends on AniList instead.

**Comment by CDB-Man** [comment]
I only maintain a barebones MAL list to show my IRL friends.  All of my real data is on AniDB; where I'm also a senior mod. I kept the MAL account active because it was "super slim and lacking in detail", which works well for non-enthusiasts.  I thought about migrating to AniList or some other service, but that was more work than it is worth, especially since my primary account has always been AniDB.

**Comment by ifonefox** [comment]
MAL has been bought by Media Do.

> I’m super excited to announce - MyAnimeList has been acquired by MEDIA DO HOLDINGS Co., Ltd.（Media Do)! As an established eBook and Manga datastore and distributor, headquartered in Tokyo, Japan, I believe Media Do is uniquely positioned to slingshot MAL into being the number one ‘all-things’ anime and manga platform.

> What does this mean? In the short term, not a lot will change. A bunch of logistics and legal hurdles are still being worked out, so DeNA will continue the day-to-day maintenance for at least the next few weeks to come. In the less-short term, it means a new dedicated team, a new schedule of priorities, and a new vision for MAL’s future! Having chatted with the Media Do group a number of times now, I’ve been delighted to share in their excitement and enthusiasm for improving and growing MAL.

> It’s been roughly four years since DeNA took the helm with MAL’s development, and they successfully guided us through a very difficult growth state. I will forever be grateful to DeNA’s team, and their tireless translators. We’ve come a very long way, and we wouldn’t be here without their care and support.

> I have no doubt good things are in store for us this year! Thank you everyone for your support and continued involvement in our amazing community.


https://myanimelist.net/forum/?topicid=1761834

**Comment by Statharas** [comment]
> I hope that "new vision for the future" includes an API.
Or, you know, you could export your list and import it over AniList
https://anilist.co/settings/import

**Comment by moepoi** [comment]
I think moving to kitsu is the right choice. it has a good app and very useful features

**Comment by tophf** [comment]
Might be worth adding to the first message that Taiga can be used with MAL just like before if you set up a kitsu account as a default one, import your MAL list, and enable the export feature in the account settings on kitsu.io site.

**Comment by thoughtsunificator** [comment]
i really want anidb support probably going to do it myself idk why you would go for MaL even though anidb might not be the coolest api out there still their data and api wont disappear out of nowhere like MaL anidb is from far the most reliable source afaik

**Comment by ifonefox** [comment]
> https://jikan.moe/ dont tell me you guys havent heard of this unofficial mal api btw?

From the first post in this thread by the developer: 

> And here's some ground rules I set for myself:
> ...
> No effort: I'm not going to spend any more time working with the old API, checking out unofficial ones, or devising my own workarounds.


I'd also like anidb support, but it uses a direct UDP-based API, rather than HTTP like all the other services taiga supports. I wouldn't be surprised if that would cause issues integrating the API. I don't see it happening unless someone else adds it, or they make a full HTTP API that can both read and write.

**Comment by FireFtw** [comment]
> Might be worth adding to the first message that Taiga can be used with MAL just like before if you set up a kitsu account as a default one, import your MAL list, and enable the export feature in the account settings on kitsu.io site.

This works flawlessly. Absolutely no reason to mess with a 3rd party API or anything when this works just fine.

Now only if more people who wanted MAL integration back knew about it.

**Comment by Atario** [comment]
Can confirm, Taiga → Kitsu → MAL hack works.  I just wish Kitsu was also capable of picking up changes within MAL by itself

**Comment by 9Morello** [comment]
I'm also using Taiga -> Kitsu -> MAL. However:
1. Kitsu overwrites the timestamps in your MAL profile. So if you cared about keeping the day you started/finished an anime, that information is lost.
2. At one point in time, Kitsu simply stopped updating my MAL profile. I had to re-sync..
3. There's a trust relationship here. You have to provide your MAL password to the Kitsu service. In the case of a data leak by Kitsu, both accounts are compromised.

**Comment by thoughtsunificator** [comment]
I didn't say it should be implemented.

Even if the integration of anidb doesnt work flawlessly it is still better than nothing.
