### ISSUE TITLE
Add a possibility to change the behaviour of animes getting set as completed

### ISSUE THREAD

**Issue by MasaruKondera** [erengy/taiga#603]
I would highly appreciate it if a function (checkbox in settings maybe?) could be added which let me decide if I want to set a score for an anime before it gets set as completed or afterwards when it got set to 12/12, 24/24 etc. episodes watched.

Right now it sets the anime as completed instantly when it gets updated to 12/12, 24/24 etc.

Thx for hearing me out!

**Comment by erengy** [comment]
We already have #110 for the same request, so I'll be closing this one.
