### ISSUE TITLE
Anilist: Score Issues from Edit Anime Popup

### ISSUE THREAD

**Issue by menma1234** [erengy/taiga#605]
Couple issues I noticed:
* Since Anilist allows decimals, when I tried to set a score with a decimal point from the "Anime Information" popup, it doesn't let me input it and shows the "Unacceptable Character" tooltip.
* I have my rating system set to 10-point with decimal, but when I type in 5 for example, it ends up as 0.5. Entering 50 gets me 5 properly.

I'm on v1.3.0.

**Comment by erengy** [comment]
The second issue should be fixed with 8ca620c1253956712d2eb504b85b77c424a613af. But I'm afraid I'll leave the first one be for now, because fixing it requires too much effort for such a small thing.
