### ISSUE TITLE
Last Updated

### ISSUE THREAD

**Issue by Kynarr** [erengy/taiga#612]
I've switched over to Anilist as the MAL issue makes it so Taiga is not compatible for the time being.

I've been able to set up everything just about the same and overall it functions as well as before, with the exception of the column *Last Updated* which now appears as Unknown for all anime I haven't updated since setting up my Anilist account. As my MAL account was created many years ago, I could sort by *Last Updated* to have a decent indication of what time period I've watched a particular anime. I could also then see precisely which anime I've seen last, in order.

I find absolutely no use to the behavior of Last Updated as it stands, as my list now behaves as a clusterfuck of the many anime I've watched over the years, many of which are only kept there for the form, but now cloud my ability to quickly determine when I've last watched an anime, and which are still relevant.

Is there a way to make is so *Last Updated*'s date is determined based on the *Date Completed* of an anime, rather than it being based on ANY update to a given anime? Or to add a new column function to Taiga that works like that? Basically, I just want to be quickly able to tell what date I've completed any given anime, and to sort by ascending/descending order of completion.

I hope this is something that can be addressed quickly, as I believe it would make Taiga so much better!

Thank you for your help and for making Taiga. This program has seriously improved my ability to sort, watch and update anime. It has been awesome!

**Comment by Kynarr** [comment]
That is... EXACTLY what I'm looking for! I'm happy to find someone had the wants and skills to do that already. I'd definitely love to see this implemented!

**Comment by erengy** [comment]
MyAnimeList doesn't include the `my_last_updated` field in their exported lists, for some reason. Which is why other services are unable to import it.

@joshstar Could you make AniList check for that field (a Unix timestamp) too? I'm asking because I can make Taiga include it in the XML file it exports, in addition to the standard fields.

@gunt3001 Adding more columns to Anime List was indeed planned for a long time now (#150). I think we'll have a couple of things to discuss, but please do send it as a PR.

**Comment by Kynarr** [comment]
@erengy 

I appreciate your quick answer! Based on #150, it seems you had the idea to include the end date almost 3 years ago already. Would this be a lot of work to implement? Do you take donations?

I figure this is a very valuable addition to Taiga. I would hope, especially with the MAL debacle causing us to rethink everything anime list related, that this can be added sooner rather than later! It would make moving to a new service much less a hassle, maybe an addition even.

**Comment by gunt3001** [comment]
Ah, I remember seeing #150 but it's been so long I completely forgot!

Looking at the issue there are definitely things to discuss (like how to format date, column title). I submitted a PR #613 with some rationale and let's see where we can go from there.

**Comment by erengy** [comment]
@Kynarr You can now try it out in the [latest build](http://taiga.moe/latest.html).

**Comment by Kynarr** [comment]
@erengy Amazing! Thank you so much! :)
