### ISSUE TITLE
Update failed error message

### ISSUE THREAD

**Issue by jowslive** [erengy/taiga#614]
Full message: "Update failed: AniList returned an error: Validation error: The selected id is invalid."

Not sure what is causing this.

![sem titulo](https://user-images.githubusercontent.com/25793173/41129677-9402fa7c-6a89-11e8-91c5-fd07a58c9a32.png)

**Comment by LordMrcS** [comment]
Something similar is happening with Kitsu. (and MAL is down, out of options now...)

![image](https://user-images.githubusercontent.com/6921937/41137717-18fe8e52-6ab3-11e8-9920-ffed1e5dbd12.png)

**Comment by LordMrcS** [comment]
@jowslive by the way, just tested Anilist and it worked fine. Just had to authorize it.

**Comment by jowslive** [comment]
@LordMrcS I tried re-authorizing AniList but the error is still there.I think the problem is being cause by one of the animes in my currently watching list

**Comment by jowslive** [comment]
@LordMrcS Fixed it by clearing all my anime history (some of them I had to delete one by one because the clear history option was not erasing them)

**Comment by erengy** [comment]
@jowslive AniList returns that error when you try to update an entry that is no longer in your list (i.e. you probably deleted it via the website). If it happens again, deleting the relevant items in your update queue at History page should suffice.

@LordMrcS Kitsu returns that error when you try logging in with your display name rather than your username. See #595 for more information.

**Comment by Knetsu** [comment]
good afternoon. someone knows how to solve this error of the taiga program if you know something please tell me  
![image](https://user-images.githubusercontent.com/86329876/123011880-3d782480-d38f-11eb-9aa3-05f8521526cd.png)

**Comment by LordMrcS** [comment]
> 
> 
> good afternoon. someone knows how to solve this error of the taiga program if you know something please tell me
> ![image](https://user-images.githubusercontent.com/86329876/123011880-3d782480-d38f-11eb-9aa3-05f8521526cd.png)

Why are you replying on a three year old closed issue? Why not just submit a new one?

**Comment by Knetsu** [comment]
sorry I didn't know anything. she just wanted to know how to fix this error
