### ISSUE TITLE
Feature request : Sync anime/manga entries between MAL - Anilist - Kitsu

### ISSUE THREAD

**Issue by sam5558** [erengy/taiga#615]
Hello there,

First let me thank you for this wonderful project, i really like using taiga.
I have to be honest, i heard of taiga before but i really used it after MAL going Down recently which is when i switched to Anilist.

So, as i saw that you added an export list feature, maybe it can be usefull to add a sync feature between MAL, Anilist & kitsu, for people suffering for the management of multiple accounts.
This way when i add an entry in MAL for eg, i can have a sync button that'll fetch new entries in MAL and add them in Anilist and/or Kitsu. And vice versa.

Maybe i'm dreaming but i think it can be interesting for users using MAL as primary entry and Anilist as backup.

**Comment by erengy** [comment]
Hi. Please see the "Why can't Taiga synchronize between services?" entry at the [FAQ page](http://taiga.moe/#support).
