### ISSUE TITLE
"Notify Me" and "Download Immediately" options under "Torrents" > "Automation" > "When there are new torrents" is not functioning at all

### ISSUE THREAD

**Issue by OthmanEmpire** [erengy/taiga#616]
Problem
======
The intention is to fully automate the process of checking for new anime torrents and downloading them without any user intervention (apart from watching anime at the end of the process ;)). It seems that Taiga offers this feature however I have never been able to get it working. This is important because I would like to automatically schedule anime downloads at night when I'm sleeping.

Replicating the Problem
================
1. Disable all Taiga filters
2. Enable "Download immediately" under "Settings" > "Torrents" > "Automation"
3. Hit the "Check new torrents" button (you should see some downloadable anime titles).
4. The downloadable anime titles do not download automatically rather I need to select them all and hit download. This is the problem.

Other Settings
==========
* Microsoft Windows 10 Home v1803
* qBittorrent v4.1.1

Fetching of the RSS feed seems to be working correctly as I've deleted the folders under AppData > Roaming > Taiga > data > feed , and when I hit "check new torrents" it generates a new `feed.xml` file that looks all correct (quick glance). 

I suspect the problem stems from the issue of "No new torrents found" in the third image below (highlighted in yellow) . That is strange considering that there is a lot of downloadable torrents shown.

![image](https://user-images.githubusercontent.com/5261295/41182308-c6a84e06-6b7d-11e8-92c7-01d5a65c3dfd.png)

![image](https://user-images.githubusercontent.com/5261295/41182340-da0502b4-6b7d-11e8-9988-c604bc21c1de.png)

![image](https://user-images.githubusercontent.com/5261295/41185012-eca8dc88-6b8c-11e8-9f20-35fef4409014.png)

Expected Behaviour
=============
Just like the "Notify me" setting under "Settings" > "Recognition" > "Behaviour" > "When an episode is recognized", the normal behaviour I would expect that when a new torrent is available, I would get a notification through the Windows notification centre or Taiga would download the torrents automatically  and hence they would appear downloading on my torrent client.

**Comment by erengy** [comment]
All torrents are in a neutral state by default. They are selected or discarded using filters. If you have no filters enabled, no torrents will be selected. You can read more about filters at the [Support](http://taiga.moe/#support) page.

**Comment by OthmanEmpire** [comment]
I see, thanks for the reply. I guess trying to take the negation approach for filters has backfired. I think the simplest solution in my case is to have a final filter that selects all remaining torrents after discarding.

So I tried to do that but it hasn't been working too well. I managed to get Taiga to download all Torrents once but after deleting the files and moving folders around, I can't get Taiga to do the same behaviour again. There are actually two issues I came across but let us go step by step otherwise it will be confusing.

Currently, I have just enabled one filter (see below) to select all torrents but it is no longer selecting any torrents. I believe this is because Taiga no longer acknowledges these torrents as new torrents, stating "No new torrents found" even though I have canceled and deleted the download files. In `data` > `feed` > `history.xml`, I tried deleting the file to clear the torrent history but that files keeps getting generated again when I restart Taiga. How can I purge the history? 


Filter to select files that are not 10 MiB (the intention to select all torrents essentially):

VEFJAQUAMS4zLjAZAYIDeJy1081KAzEQB/CzfYqQF2gVwcumoAfxogcreFxmk2k7MJus+VjUpzdp0a7FtUrpKZDM/PMLQyqK2ArQkZxVMiCjjlK0EPVaSWCWwnXbM4NLSJwP0ULDaJSMPqEUFlpUcrHpFNe5Yz45q7SzhkqfyPst2qjkkhjrQO9YItFDdF5J6yK+JOAgRQ+cctD5TNzTjRTT+aSaFlxevxkNBQ3e/Ixck8GBcJmTv4i3YENqxnjYUXAG65V3qdsj5vIIZHfIO+c95SsWqQmnoD5icJxK3SFun1Nc7Xf1B+RXF7P/gO3b38DPpZ7saoybAvo6RIgpDIV7s9/Sjgi4PMUwHvA1jr2LnQauP4cBPRCXiF+IT5tPM1B+AHBkNIQ=

**Comment by OthmanEmpire** [comment]
Alright, found the solution. It seems that I had to shut Taiga and then delete `history.xml` as Taiga seems to have that file loaded into memory and creates it everytime I hit refresh. After deleting the history, Taiga now   selects all non-discarded torrents as intended and queues them up on my torrent client.

Thanks for the prompt response and I'm glad everything is working as intended now. I will mark this issue now as closed.
