### ISSUE TITLE
Discard torrents for dropped anime

### ISSUE THREAD

**Issue by Statharas** [erengy/taiga#618]
5char

**Comment by erengy** [comment]
Do you have a filter that is supposed to discard them? Please export your filters (using the rightmost button at *Settings → Torrents → Filters*) so that I can take a look.

**Comment by Statharas** [comment]
I never figured i'd need a filter to actually stop pinging me about anime i've dropped; that's one of the reasons I actually dropped them, so I wouldn't download their episodes.


VEFJAQUAMS4zLjADA94QeJzVl1tPGkEUx5/rpzjdxPTJCnhZacWkVSlEraZobWIMOewe2CmzM3QuKH76ngFvgYC16sM+bbJz+//mXGdbOMoBEye0qkWWJCUughxdktUiVKMI9GAyllIXveRBUtiRlNYiZzxFoDCnWtQar4TEG0PKyRFchS2E6kU7S++2E61SEbYBnpbzhFrkLZm2dei8DWeQQadNLaI/HiX/GaL0vG05gtWdpe3VoJK/C8VK+UyxKAwLBFQiJxAKBhIVOD2RPk93Tg6f1l0Z634B+MYC8FTYBE06z0xh2hAdzYHfm6xm7BQeJoPSbkWoFSmsm9zIywxX+n/9iyx3J35sIppA4BCFDHOBBsLqlOw86bfjbeXzDpnH6iXdK1++3Xt5vgmlTlC273a7P3/BdZyOGebeyMBQNwh6/oWcjFdCJnrZiiGrpR9L7Qr59DUMRUq6/bBqgf64Uho8Q/+/h+JFHZX1nUv4KbQkB/tDMj22MKmx+tvY5EWV8lYlnm+SO6ae0X6wAKShjREso+U79m2B9ghdBkdokgwO0CA08LfI0XhoWuqjgIOR9lb7/kj3/RRsNa6WigWLRoZc2lRwmhHUDarr62mo6nplrUhQx+yLUnO2aYpplK31tULZp84pfpWuHbvhIXKG31eJNjQTYnH5FagOtDbCWc8+/rZQ31Ehn8OlC05R3KD4BM0cbRZ4+F/d9/thfMYNN9aqL6fczUbev3UGGQpp4VCoaUsFhnKR/K8h+EcwhpkOpXKpVIoLFUtfOV8H/2qQ0fAlwZRygbA2y1Xe3CwSV8uRUPbzt9ANlmZSQ7lY1bfBDRG0kkxrCXvXe9DY/3E8U2TjzUIxHWrLArBHwHK7ku2Uwnnz13GrNVue4kJV2rqXEo74ZSXhhDGS99xIDIUNh3NjmLC40YxDrm8UKgOea4chb3DfpwW/X+DI33CJ5Go101xUN+KtIqGNmwt+EY6Yrpc5uGgQDkl9sFAnkpfQ/Ah8ig2O25X6ik+bsmUprr6CLc92d884FB6j/gXg2LhL

**Comment by erengy** [comment]
Adding a new general filter should do the trick:

```
Name: Discard dropped
Condition: Anime watching status | is | Dropped
Action: Discard matched items
```

I think it makes sense to add this to Taiga's default filters.

**Comment by Statharas** [comment]
Yup, exactly what I made. Definitely should be in by default.
