### ISSUE TITLE
Downloaded bar is again not aligned with the seen bar

### ISSUE THREAD

**Issue by Statharas** [erengy/taiga#619]
![image](https://user-images.githubusercontent.com/2414202/41217021-45345bb0-6d5f-11e8-8c44-53fd32fbbdfc.png)

Running on 1.3.0

**Comment by erengy** [comment]
This is the same issue as #492, which should be fixed in the [latest build](http://taiga.moe/latest.html).

**Comment by Statharas** [comment]
*ahem* do I have to delete previous data or should it work out of the box

**Comment by erengy** [comment]
Let's give this another try. Could you try re-downloading the latest build now?

**Comment by Statharas** [comment]
Pixel perfect.
