### ISSUE TITLE
Official discord server for taiga

### ISSUE THREAD

**Issue by 0ANIMEFREAK0** [erengy/taiga#620]
i know it isn't app related
and i know that if u have any problems with the app u can submit the issue here but there are little issue that new users run into 
and the issue is not bug or code related 
so if we have a discord server we can help the new guys if they have problem with the app
so will there be any official discord server for taiga

**Comment by erengy** [comment]
It's quite new, but there already is a Discord server for Taiga: https://discord.gg/yeGNktZ

This was added to the [support page](http://taiga.moe/#support) a few days ago.
