### ISSUE TITLE
Taiga not recognizing anime in Plex when episode is switched in fullscreen mode.

### ISSUE THREAD

**Issue by TheInfamousAlk** [erengy/taiga#623]
2nd edit: I have learned that after several minutes of the episode playing in fullscreen, taiga shows no media is playing. It seems to stop recognizing the show shortly after I enter into fullscreen. It stays for at least 3 minutes. Sometimes it stays for longer. I can't find a pattern to how long taiga retains the correct "now playing" status. The issue may be with recognizing the anime in fullscreen, not with the act of switching episodes. 

So the plex web app (chrome, windows 10, everything the latest version) automatically starts a new episode when one episode finishes. Taiga fails to update the currently playing episode when I have fullscreened the video in the plex web app, and plex switches to a new episode, without breaking fullscreen. When the new episode starts playing, taiga thinks there is nothing playing. The "now playing" page empties right when the episode switches. To get taiga to recognize the new episode, I must exit fullscreen and with the video playing, wait a few seconds for taiga to recognize it, then enter fullscreen again. This happens when plex automatically starts playing a new episode after one ends, as well as if I manually skip forward or backward in the episode playlist using the forward/back buttons next to play/pause. And by "fullscreen" I am referring to the fullscreen button built into the plex player. However, I tried to duplicate while using google chrome's fullscreen (f11) and it produced the same results. (Plex's fullscreen and chrome's fullscreen are independent and can be activated independently of each other)

Edit: I just noticed this while switching between Hinamatsuri episode 8 and 9. The plex server is on the same machine that I am watching from. I have 3 monitors and this happens on all of them. It does not matter which window is in the foreground. I don't think this is useful info but too much info is better than not enough.

**Comment by erengy** [comment]
This issue is the same as #445, and related to #317. It was also mentioned in #524.

This is, unfortunately, not something I can fix at the moment.
