### ISSUE TITLE
[Suggestion] Checksum comparison to indicate if torrent file is already downloaded

### ISSUE THREAD

**Issue by Statharas** [erengy/taiga#626]
It would be useful, really. And by that, I don't necessarily mean actually running checksums, mainly comparing the downloaded file's with the one online, as seen here
![image](https://user-images.githubusercontent.com/2414202/41508309-54bd54ba-724b-11e8-8a9b-629f6842ccda.png)

**Comment by erengy** [comment]
As far as I know, those are SHA-1 hashes of the torrent metadata, rather than of the downloaded files. I don't see how we could make use of that.

**Comment by Statharas** [comment]
Sometimes fansubs release a second version of the show, plus, with a warning, you can avoid adding it on your tracker

**Comment by erengy** [comment]
Those hashes are no more useful for us than the filenames, which Taiga already makes use of in various ways. Please elaborate if I'm missing something here.

**Comment by Statharas** [comment]
Afaik they are checksums of the file. The gains are that episodes aren't being re-downloaded if it exists in the library, viewer can actually see which torrents he has downloaded already and help complete collections. It's not a huge deal, more of a QoL
