### ISSUE TITLE
Invalid anime id.

### ISSUE THREAD

**Issue by wooles** [erengy/taiga#627]
After exporting my list from mal to anilist Taiga started returning an error: 

> Update failed: AniList returned an error: Validation error: The selected id is invalid.

I was trying to find out what causing the problem and it looks like that during a migration one or more titles were placed incorrectly in my list, you can see here:
![cuywsmi 1](https://user-images.githubusercontent.com/9068595/41508768-075ccd78-724a-11e8-8fc5-aa703cbf08e9.png)
Taiga recognises this anime as dropped but when i open "Dropped" tab it's not there
![ma0kimd 1](https://user-images.githubusercontent.com/9068595/41508787-40439d74-724a-11e8-8dea-6e109e446d14.png)

What's more i can't select and delete it from my library.
https://gfycat.com/EdibleDeliriousCollardlizard

**Comment by erengy** [comment]
See #614 for the same issue:

> AniList returns that error when you try to update an entry that is no longer in your list (i.e. you probably deleted it via the website). If it happens again, deleting the relevant items in your update queue at History page should suffice.

If you're unsure about what to delete, send a screenshot of your History page and I'll let you know.

**Comment by wooles** [comment]
Thanks for response, i've deleted it from queue and everything is working fine now.

**Comment by bbtora** [comment]
@erengy 

I would like to add that I've encountered this issue too.

Cleared the history, tried to sync the list and re-authorize AniList too but nothing works for me till now.

**Comment by erengy** [comment]
@bbtora Could you post a screenshot of your History page?

**Comment by bbtora** [comment]
It was empty before I started watching but anyways...

![taiga_2018-07-13_00-24-46](https://user-images.githubusercontent.com/23010526/42653489-3d93f950-8633-11e8-9e21-072aad83d07c.png)

**Comment by erengy** [comment]
Do you still get the same error, even though there's nothing in your update queue?

**Comment by bbtora** [comment]
No, I only get the error when I try to delete titles from my list (which I had already deleted from the website) but for some reason the titles show up in the list despite syncing.

**Comment by erengy** [comment]
Ah, that's what you mean. That issue has been fixed quite some time ago in b5c77ee941b2e9f4f446948826c4519d0526eebd. I haven't released an update yet, but you can get the [latest build](http://taiga.moe/latest.html), which includes the fix.

**Comment by bbtora** [comment]
Oh thanks. Nice to see it's already fix and ready for next update.
