### ISSUE TITLE
Taiga fails to detect episodes of specific anime

### ISSUE THREAD

**Issue by Statharas** [erengy/taiga#629]
This has to go with a bit of a backstory. Nozo x Kimi was an anime on my watching list before taiga, and I had a folder for it. Obviously, autism stroke uTorrent back when I was still stupid enough to use it, and everything ended up getting stored in there, including some Nisekoi episodes. Funny enough, Taiga thought Nisekoi episodes 2 and 3 were the other two episodes of Nozo x Kimi, which I ignored for a while. After moving stuff around, Taiga stopped considering those two episodes as the anime, and would show them as missing. I moved the episode to my root folder along with the ones I downloaded.
![image](https://user-images.githubusercontent.com/2414202/41517888-36e723cc-72c7-11e8-949a-2747fbe68b76.png)
Now, after telling Taiga the anime episodes are stored there, Taiga shows 0 episodes downloaded. I've tried rescanning and stuff like that to no avail. It doesn't even find the first episode.

**Comment by Statharas** [comment]
![image](https://user-images.githubusercontent.com/2414202/41517917-64c03e32-72c7-11e8-8365-915206649938.png)
Taiga view

**Comment by erengy** [comment]
Adding `Nozo x Kimi - OVA` as an alternative title for the series might work.

**Comment by Statharas** [comment]
That solves it. Keep this open for a while in case the issue rises up again where the alternate title solution does not apply.
