### ISSUE TITLE
Wakanim doesn't work with Taiga

### ISSUE THREAD

**Issue by TheFunyGaming** [erengy/taiga#630]
Hello, i've just trying Wakanim (Website & Windows Application) with taiga but it's not work, the episode was not detected

It's possible to solve this error?

P.S. : I used the french version of Wakanim and sorry for my english

**Comment by erengy** [comment]
Hi. Looks like they changed their website recently, which broke Wakanim detection for Taiga.

Could you try the [latest build](http://taiga.moe/latest.html) and see if it fixes the issue? (You need to copy it to your installation directory.)

**Comment by TheFunyGaming** [comment]
Okay ^^

**Comment by TheFunyGaming** [comment]
It's work thank ^^
