### ISSUE TITLE
MAL export synch issue

### ISSUE THREAD

**Issue by amboris** [erengy/taiga#631]
i having a big issue with the synch tool. it wont let me switch from MAL because i have anime updates in queue. and i have tons of episode that didnt synch because the api is gone and i am not sure if i lose all my update that are still in que to synch.

pls need a solution without losing data.

**Comment by erengy** [comment]
You can [export your list](https://github.com/erengy/taiga/issues/588#issuecomment-393226127) from Taiga, which will include queued updates.

After importing your list to AniList/Kitsu and making sure that it's up to date, you can delete all the queued updates, and then change the active service.
