### ISSUE TITLE
Taiga does not recognize a sequel of anime

### ISSUE THREAD

**Issue by Tensai-Otaku** [erengy/taiga#633]
Basically, it won't recognize a sequel of an anime unless the episode number starts from 1 if the episode number begins from episode 13 it won't recognize and I will have to update it manually.

**Comment by erengy** [comment]
Taiga can handle this kind of situations, but the anime must be manually added to [anime-relations](https://github.com/erengy/anime-relations).

**Comment by Tensai-Otaku** [comment]
Could you give me an example, I didn't get it lol

**Comment by erengy** [comment]
You can just tell me the filenames you're having trouble with and which anime they belong to. I'll create the rules and update anime-relations, which will then be distributed to all Taiga users.

**Comment by Tensai-Otaku** [comment]
It's a horrible subs title for Shokugeki no Souma S3 13-24 they are actually related to Food Wars The Third Plate: Totsuki Train arc.

**Comment by erengy** [comment]
There's already [a rule](https://github.com/erengy/anime-relations/blob/486781b4e23f6f853c5213091c912e4afa8dadbc/anime-relations.txt#L665-L666) for that. You just need to add `Shokugeki no Soma S3` as an alternative title to *Food Wars! The Third Plate*.

**Comment by Statharas** [comment]
@erengy We could get a rule that says "if Episode#>MaxEpisodes, ask user if this is S2". You could also allow Users to send an e-mail when this happens, so that they can be added for future releases.
