### ISSUE TITLE
Problem with recognition

### ISSUE THREAD

**Issue by rierku** [erengy/taiga#634]
After the problems with MAL (and not noticing it for a month because getting new episodes worked fine) I tried to switch to Kitsu or Anilist. I exported my (outdated) list from MAL and imported it to Kitsu first. After switching over List providers, I noticed that Taiga suddenly wanted to offer me old episodes, which is understandable since the list was not up to date. In the process of bringing everything up to date, I noticed Taiga wouldn't recognize anything. Neither from the Anime libraries nor from anywhere else. I tried switching Anime List providers, resetting the settings, reinstalling Taiga, rebooting etc. It still won't recognize any files anymore and doesn't go to "Now playing" anymore either. 

I'm using Taiga 1.3.0 Standard (not the one with the export features) and Windows 10 pro 1709. I'll try updating Windows if that helps for now, but I thought I'd post here anyways. I'll report back after it's been done. Thank you.

**Comment by erengy** [comment]
Which media player do you use? Is Taiga able to open it when you try playing an episode that is available in your library folders? What do you see at Now Playing page afterwards?

**Comment by rierku** [comment]
Update to 1803 complete, issue persists. I'm using Media Player Classic with CCCP. Starting an episode out of Taiga works fine. When I start up an episode (tried with Persona 5 and BHA from Horrible Subs and Nanatsu no Taiasi from Chyuu Subs ), Taiga does nothing. Changing to the Now Playing site manually just shows me:
-Continue Watching , Scan available episodes (etc.) 
Scan doesn't return anything, try random opens a random episode

-You've watched 10 episodes in the last week.
-There are at least 15 new episodes available in the library folders

Recently Finished airing:
*some shows*

**Comment by erengy** [comment]
Was Taiga able to detect the same media player before you changed the active service? I just tried installing CCCP on a Windows 10 1803 and didn't have any issues.

Make sure the following options are enabled:

- *Tools → Enable anime recognition*
- *Settings → Recognition → Media players - Enable media player detection*
- *Settings → Recognition → Media players - MPC-HC*

Disable the validation options at *Settings → Recognition → General*, just in case.

You can also try running Taiga as administrator.

**Comment by rierku** [comment]
Tried all that, didn't work, though. 

But, I tried reinstalling again, but this time running the uninstall first, then manually deleting all leftover files and folders in the Local/Roaming/Taiga Folder and then installing again. (Before, I just ran the setup again to install over it)

Now, it seems to work again properly with Kitsu. I tried it one more time with the MAL account but of course it couldn't get a list and when I started an episode, it recognized it, but didn't know what it is anymore. Switching back to Kitsu, it worked again.

I tried to remember when it last recognized something, but it must've been a while ago, probably since the MAL API went down. Could it be that something about the recognition "got stuck" when the MAL API went down?

**Comment by erengy** [comment]
> Could it be that something about the recognition "got stuck" when the MAL API went down?

I don't think that's possible. The active service would only make a difference in the identification process. The issue you had, however, was with media detection: Taiga couldn't detect the player or retrieve the currently playing file.

We couldn't figure out the cause, but I'm glad it worked out for you in the end.
