### ISSUE TITLE
Showing time until next episode and Notifications

### ISSUE THREAD

**Issue by Statharas** [erengy/taiga#635]
I haven't gone much into the AniList docs, but from a rough check, the date and time where the next episode airs should be available through the API. Currently, the Anime List tab is barren. I believe that Taiga should be able to display such a timer. Maybe this can open up an opportunity for specific notifications, like, "Notify when next episode available" or "Notify when Batch is available".

**Comment by asakurato** [comment]
why would you need option for "Notify when next episode available" or "Notify when Batch is available" when there is torrent downloading anyway? Unless you watch on official sources...

**Comment by cptchi** [comment]
Torrents -> Discovery - Automation -> Notify Me does the job for me.

**Comment by Statharas** [comment]
Thing is, sure, you get notifications, but sometimes you might miss them. It'd be nice filling in the empty room with more info, plus it allows for more features to be developed in the future.

**Comment by erengy** [comment]
Closing this issue, since we already have #59. (Did you forget about #520 too?)

**Comment by Statharas** [comment]
Yeah, actually forgot about that
