### ISSUE TITLE
Anime Information: Allow changing rewatch count

### ISSUE THREAD

**Issue by adam-tj** [erengy/taiga#636]
![image](https://user-images.githubusercontent.com/9314405/42132636-3917386c-7d1c-11e8-9610-e0319d2ba1fb.png)

![image](https://user-images.githubusercontent.com/9314405/42132648-68593bac-7d1c-11e8-8446-5d93fe869848.png)

As you can see from the screenshots there is no "Rewatched" entry on Taiga, at least for anilist.

**Comment by asakurato** [comment]
I don't know about anilist, but MAL api had limitations on "rewatch time". where Taiga (and all other 3-party  apps) couldn't read rewatch count. Maybe Taiga is programmed not to take rewatch time count from any service because of that.

**Comment by Maelstrom1** [comment]
Now that the MAL API is (still) down, and both Kitsu and Anilist support rewatch counters, (I think), is this a possibility?

**Comment by erengy** [comment]
This was implemented in ec836bcd5003043b9a0520fc86d462b4a2b189ae. It's now available in v1.4.1.
