### ISSUE TITLE
Allow list update notification box to appear without delay

### ISSUE THREAD

**Issue by RailsD** [erengy/taiga#638]
When I launch a new episode, I'd like to have the "update episode" box appear without delay. In the past, I was able to lower the delay to 0 seconds and it worked as I wanted, but within the last few patches the minimum delay is 10 seconds. 

My reasoning is thus: 

The notification box takes focus from the media player. I don't update series until the episode is finished due to the possibility of not finishing the episode, so I have to click back onto the media player to allow keyboard shortcuts to be used while watching (pausing, back, etc.) This is fine when launching an episode, but not when it happens 10 seconds after starting.

**Comment by erengy** [comment]
> I don't update series until the episode is finished due to the possibility of not finishing the episode

In that case, you should enable the *Wait for media player to close* option. With that, Taiga would display the confirmation dialog when you close the player or play another episode. Of course, you could always disable the *Ask for confirmation* option to avoid the dialog. This is in fact the intended way to use Taiga.

**Comment by RailsD** [comment]
> enable the Wait for media player to close option

I have to admit, I had no idea this existed. I must have overlooked the option.  This is what I was looking for, so thanks for the explanation. 

Additionally, thanks for all the work on the app, I can't possibly imagine not using it anymore.
