### ISSUE TITLE
Anilist List Sync when deleting from Website vs Client

### ISSUE THREAD

**Issue by xodiack** [erengy/taiga#640]
I removed Black Clover from my PTW on Anilist's site rather than through Taiga. It remained on my client list even after re-syncing. Adding it back through Anilist's website and then deleting it from Taiga's client appears to have worked correctly.

It appears to happen with any entry, and probably occurred for others I removed during cleaning up of my list. As far as I can tell the problem only happens when deleting an item from my list through the website instead of the client. Adding a series does not seem to have this syncing issue.

**Comment by erengy** [comment]
This was recently fixed with b5c77ee941b2e9f4f446948826c4519d0526eebd. It's going to be in the next update.
