### ISSUE TITLE
MAl error

### ISSUE THREAD

**Issue by FouNdat1on** [erengy/taiga#643]
I actually downloaded taiga today,cuz a friend told me that it will  be much easier to manage and track anime through it,but when i synchronized my anime it gave me an error....

![capture](https://user-images.githubusercontent.com/40854858/42314448-77bef6fa-805e-11e8-8056-2dd4d682acda.PNG)

This error is not even completely visible so i can't make out what the problem is...is it because the mal was down or something?

**Comment by erengy** [comment]
MAL has disabled their API indefinitely. See #588 and #601 for more information.
