### ISSUE TITLE
taiga doesnt recognize cowboy bebop

### ISSUE THREAD

**Issue by hrmb26** [erengy/taiga#644]
Taiga is not recognizing cowboy bebop i dont know why. Everything is fine with the rest of my anime

**Comment by erengy** [comment]
Could you give an example filename that Taiga is unable to identify? What do you see on Now Playing page when you play that file?

**Comment by hrmb26** [comment]
I just try to play next episodio and just get the could not find episode x my files are named as follows
![screenshot_2](https://user-images.githubusercontent.com/29465684/42321697-dcda0cbe-8027-11e8-94bb-870197e4e3bf.jpg)

**Comment by hrmb26** [comment]
![screenshot_1](https://user-images.githubusercontent.com/29465684/42321712-e5527b60-8027-11e8-8370-edde01aa78aa.jpg)

**Comment by erengy** [comment]
Double-click on *Cowboy Bebop* in your list, go to second tab and add `Cowboy Bebop TV` as an alternative title to the series.

Or, manually play an episode, go to Now Playing page and click on *Cowboy Bebop*, which will do the same.

**Comment by hrmb26** [comment]
It is working now, thanks.
