### ISSUE TITLE
Not downloading .torrent files

### ISSUE THREAD

**Issue by MightEMatt** [erengy/taiga#648]
Whether automatically or manually downloading torrents, the client returns "Successfully downloaded the torrent file." but no .torrent files are being downloaded to the feed folder. If I recheck for available torrents, it no longer auto-selects the files it falsely downloaded. If I delete the contents of the feed folder when restarting the client, it again re-selects the missing torrents. Downloading again results in the same issue.

This has persisted through re-installs and computer restarts. It doesn't seem connected to file names as I've tried downloading a couple dozen currently airing and recently aired shows.

**Comment by erengy** [comment]
> the client returns "Successfully downloaded the torrent file." but no .torrent files are being downloaded to the feed folder.

That's odd, because Taiga displays that message only after checking if the downloaded .torrent file exists on disk. Otherwise it says: "Torrent download error: Torrent file doesn't exist"

The only exception I can think of is magnet links. Which RSS feed do you use? Do you have the *Settings → Advanced → Torrents / Use magnet links if available* option enabled?

**Comment by MightEMatt** [comment]
I do not have magnet links enabled, but I just tried switching around the RSS feeds and it seems to be a problem with HorribleSubs feeds; maybe something to do with their new web design. Anyways Nyaa.si still seems to work so I'll use that for now. Thanks for the help.

**Comment by erengy** [comment]
That explains it. The links in HorribleSubs' RSS feeds are magnet links:

```xml
<item>
  <title>[HorribleSubs] One Piece - 844 [720p].mkv</title>
  <link>magnet:?xt=urn:btih:OCS4C3CPGUXZWNKPWRRWV5DFQYV276DM&amp;tr=http://nyaa.tracker.wf:7777/announce&amp;tr=udp://tracker.coppersurfer.tk:6969/announce&amp;tr=udp://tracker.internetwarriors.net:1337/announce&amp;tr=udp://tracker.leechersparadise.org:6969/announce&amp;tr=udp://tracker.opentrackr.org:1337/announce&amp;tr=udp://open.stealth.si:80/announce&amp;tr=udp://p4p.arenabg.com:1337/announce&amp;tr=udp://mgtracker.org:6969/announce&amp;tr=udp://tracker.tiny-vps.com:6969/announce&amp;tr=udp://peerfect.org:6969/announce&amp;tr=http://share.camoe.cn:8080/announce&amp;tr=http://t.nyaatracker.com:80/announce&amp;tr=https://open.kickasstracker.com:443/announce</link>
  <guid isPermaLink="false">OCS4C3CPGUXZWNKPWRRWV5DFQYV276DM</guid>
  <pubDate>Sun, 08 Jul 2018 03:16:19 +0000</pubDate>
</item>
```

Perhaps Taiga should display a different message (e.g. "Found magnet link") in these situations.

**Comment by MightEMatt** [comment]
Ah, I didn't even think to check the links on their feed, silly me. Well thanks for the clarification anyways.
