### ISSUE TITLE
Not all the categories properly seen

### ISSUE THREAD

**Issue by taigalover** [erengy/taiga#651]
In the "Anime information" screen , there isn't enough space for all the "Categories" to be properly seen.
![image](https://user-images.githubusercontent.com/32505754/42419872-a32c2040-82ef-11e8-96be-cc4f449ca48b.png)

Well i don't know if its too important because you could just click on the image and be redirected so you can find the full information page, but i thought it might be worth mentioning.

**Comment by erengy** [comment]
I'm aware of this, but it won't be fixed until v2. Closing the issue because it doesn't need tracking.
