### ISSUE TITLE
Add a Custom title/Alternative titles column in the Anime List

### ISSUE THREAD

**Issue by hot36952** [erengy/taiga#655]
I am from China and hope that Taiga can add custom titles. Custom titles can help users find and manage their favorite animation lists. I hope that Taiga can fulfill this request,just like this:
![qq 20180714140222](https://user-images.githubusercontent.com/21011227/42721643-b7e1ed14-8770-11e8-8f3d-559251539d33.jpg)

**Comment by erengy** [comment]
Closing this issue because we already have #132 and #150 open.

**Comment by hot36952** [comment]
I know that I can only display English titles or Roman title, but I hope that I can set any language (English, Romaji, Japanese, Chinese) custom titles for any animation, not just English, Romaji. 
Just add a display column, you can enter custom text, you don't need to modify the current Anime title.
