### ISSUE TITLE
Column for airing day

### ISSUE THREAD

**Issue by Daiz** [erengy/taiga#660]
Seeing as Taiga already has an idea of when shows are airing (as indicated by the episode availability bar), it would be nice if there was a column along the lines of "Air Time" that at least listed the day when the show is airing (eg. Monday, Tuesday, etc). If there's even better information available (like eg. JP broadcast time), it could even show localized time, so eg. "Monday 18:00", and then sorting by this column should obviously sort by day-time accordingly. For shows that aren't currently airing, this column should probably be empty (so they would sort after currently airing shows). being able to tell at a glance when my weeklies are airing would be a nice quality of life improvement.

**Comment by erengy** [comment]
We already have #59 and #150 for this topic, so I'll be closing this one.

Recently in f1203d82598a64cd9d6e1238799c37f93ff35c04 I made Taiga retrieve information from AniList about the next airing episode, which is a start. Not sure if I'll add a new column for it yet, but I'll see what I can do.
