### ISSUE TITLE
Webroot picks up uninstaller as adware

### ISSUE THREAD

**Issue by SheepKid12** [erengy/taiga#661]
**I'm sure this is only a minor issue, but I thought that I would at least mention it to the developer, just in case a fix is possible.**

So yeah, I have an interesting issue to report. I use Webroot on my system, and when I attempted to install your software a little while ago, it was picked up as "W32.Adware.Gen". If you check my VirusTotal scan of the uninstaller [here](https://www.virustotal.com/#/file/3645652206f1ab13c08817e618a70428db8797b60455b441c8f4735bc6fcc215/detection), Webroot (which is what I use) and 2 other AV engines pick it up, while every other engine comes back clean. I had to use VirusTotal because I'm not at my laptop with webroot installed (I think it's only a single license thing), and I wanted to make sure I had the correct information to report.

I have reported this as a false positive to webroot through their support form, and I'm not sure it would be easy to fix this if they don't respond to me/still say it's adware. If they do say it's not adware, if I can, I'll close the issue (or at least ask for it to be closed).

**Comment by Statharas** [comment]
Quick google search says that it's because the uninstaller is packed.

**Comment by erengy** [comment]
Hey @SheepKid12, and thanks for the report.

We have a long history of [false positives](https://github.com/erengy/taiga/issues?utf8=%E2%9C%93&q=label%3A%22false+positive%22), and there's practically no way to avoid them. I usually end up filing reports to multiple companies after each release of Taiga, although this is the first time I'm seeing an issue with the uninstaller. It's basically the default executable file of [NSIS](http://nsis.sourceforge.net/Main_Page), so there's not much I can do here.

**Comment by SheepKid12** [comment]
@erengy Makes sense. Should I close this issue now?
