### ISSUE TITLE
why is this anime gray on torrent

### ISSUE THREAD

**Issue by 0ANIMEFREAK0** [erengy/taiga#663]
![screenshot_87](https://user-images.githubusercontent.com/35454710/43049385-db035d42-8e18-11e8-81fb-0a35cdc0a9e5.png)

**Comment by 0ANIMEFREAK0** [comment]
![screenshot_88](https://user-images.githubusercontent.com/35454710/43050211-c534de6a-8e26-11e8-91c9-c45e059e9293.png)

**Comment by 0ANIMEFREAK0** [comment]
its still grayed out

**Comment by 0ANIMEFREAK0** [comment]
![screenshot_89](https://user-images.githubusercontent.com/35454710/43050231-fa1a394a-8e26-11e8-818c-8d5f745d1860.png)

**Comment by erengy** [comment]
Just tested it myself and Taiga didn't have any issues identifying the same release. It must be related to some setting of yours. Did you previously add `Yuragi-sou no Yuuna-san` as an alternative title to another anime, such as the OVA? If so, try removing it.

P.S. Please don't spam. Every time you post a comment here, GitHub sends notifications to many people. Also note that our [Discord server](https://discord.gg/yeGNktZ) is more appropriate for quick questions like this.
