### ISSUE TITLE
Data lost

### ISSUE THREAD

**Issue by 123khaled123** [erengy/taiga#664]
I just restarted my pc and when It came up Taiga has lost all my data. Anyway to get them back? specially filters! 

![Image of Yaktocat](https://i.imgur.com/ZtCRp2U.png)

**Comment by erengy** [comment]
Is Taiga installed to its default location (`C:\Users\{username}\AppData\Roaming\Taiga`) or somewhere else?

See #360 for the same issue. You can find additional information at the [support page](http://taiga.moe/#support) under Common Issues.

**Comment by 123khaled123** [comment]
it's installed in it's default location. 
I have it on exclusive security in both Kaspersky and malwarebytes.

**Comment by erengy** [comment]
You can check your `Taiga\data\settings.xml` file to see if your filters are still there. But I doubt that'd be the case; either Taiga wasn't able to save them on exit, or it couldn't read them after the restart but has already overwritten them by now. I'm afraid I can't think of any way to restore your settings.

**Comment by 123khaled123** [comment]
Thank you for your time!
