### ISSUE TITLE
No available episodes found

### ISSUE THREAD

**Issue by pervertkirito** [erengy/taiga#669]
here some screenshot of what I mean
![](https://i.imgur.com/405gQag.png)

![](https://i.imgur.com/OPNx3aM.png)

**Comment by erengy** [comment]
Taiga is able to identify the file when you play it, which means it's not a recognition issue.

Do you have that Video folder added as a library folder? Did you make Taiga scan for available episodes?

**Comment by pervertkirito** [comment]
Yup... as you can see on second screenshot, recognition worked fine

Yes, I have set library folder to /.../downloads/video/ which is where the video is located
tried Scan available episodes a few times... still no luck

**Comment by erengy** [comment]
What's the full path of the folder? (e.g. `C:\Downloads\Video`)

What type of storage is it? (e.g. internal drive, USB disk, NAS)

Is Taiga able to detect the other files in the same folder or in other library folders?

Which version of Taiga do you use?

**Comment by pervertkirito** [comment]
folder path  `C:\Users\«username»\Downloads\Video`

storage type: internal drive

Yes... taiga detect other anime

Latest(1.3.1)

**Comment by pervertkirito** [comment]
ok this weird... I try cut and paste to another folder... and set library folders to new location... still got same result
but then I cut and paste back to original folder... I got this result
![](https://i.imgur.com/A4nTbLE.png)
