### ISSUE TITLE
AniList: Seeing everything on custom lists in my "currently watching" (for example)

### ISSUE THREAD

**Issue by eXmendiC** [erengy/taiga#671]
This is not really a bug. Some people probably like that, but I don't.
I sort some shows in custom lists, because I don't want to see them in 'currently watching', 'planned' etc. and now my "currently watching" is full of shows I don't want there. Everything was fine with 1.3.0-beta.2.
I would be glad if it's possible to somehow disable seeing all shows you've on custom lists (or even better: just certain custom lists), if it's not possible adding custom lists as a new tab.
For now I'll stay with 1.3.0-beta.2.

**Comment by erengy** [comment]
Closing this issue since we already have #590. What I have in mind is to display custom lists in separate tabs, which should cover your use case.
