### ISSUE TITLE
Discrepancy with title of certain anime

### ISSUE THREAD

**Issue by Statharas** [erengy/taiga#672]
The anime is 
https://myanimelist.net/anime/37281/Joshiochi__2-kai_kara_Onnanoko_ga_Futtekita
https://anilist.co/anime/101981/Joshi-Ochi-2kai-kara-Onna-no-Ko-ga-Futte-kita/
https://nyaa.si/?f=0&c=0_0&q=Joshi+Ochi

Not only is the title mismatched between sites, it is also mismatched with BOTH on Nyaa.

Honestly, this is bugging me quite a lot. Not because of the mismatch, but the fact that there's no common structure when it comes to services. The community is very disorganized in some stuff, leading to holes in future services and such.
Personally, I would try to push out an ID system, that would be enforced over anime torrents as well. I really don't see why it would be hard to organize torrents with an ID rather than rely on string matching. But seeing as how MAL and Anilist databases do not agree with eachother, this becomes even more confusing.

**Comment by erengy** [comment]
Titles don't have to match exactly for Taiga to be able to identify them. Here are the titles in question:

Source|Title
:---|:---
MAL|`Joshiochi!: 2-kai kara Onnanoko ga... Futtekita!?`
AniList|`Joshi Ochi!: 2-kai kara Onna no Ko ga... Futte kita!?`
Nyaa|`Joshi Ochi! 2-kai kara Onnanoko ga... Futte Kita！？`

And here are the same titles after Taiga [normalizes](https://github.com/erengy/taiga/blob/d560f4d0bc2284069732912afa5106ad59cd13e3/src/track/recognition_normalize.cpp) them before comparison:

Source|Normalized title
:---|:---
MAL|`joshiochi2kaikaraonnanokogafuttekita`
AniList|`joshiochi2kaikaraonnanokogafuttekita`
Nyaa|`joshiochi2kaikaraonnanokogafuttekita`

Not sure why you chose this anime as an example, but Taiga is able to identify it out of the box, without any issues. In other cases, you may have to add an alternative title.

Your suggestion regarding the ID system is not related to Taiga, but let me just say that, good luck.

**Comment by Statharas** [comment]
Chose it specifically because Taiga couldn't find a single episode, it did find episode 2 weeks ago
