### ISSUE TITLE
Idea : Adding airing anime calender or countdown tab 

### ISSUE THREAD

**Issue by yashiro03** [erengy/taiga#673]
The idea is to add a tab with a table of the time and the day of the airing animes in the currently watching list . It would be a cool feature combined with a notifier or something  like that .

Taiga is a great app ! Thank you

**Comment by erengy** [comment]
Thanks for the suggestion, but I'll be closing this issue since we already have #59 and #57.

(Other similar issues: #660, #635, #582, #520, #165)
