### ISSUE TITLE
Discord: Add option to hide fansub/raw group

### ISSUE THREAD

**Issue by mnh48** [erengy/taiga#675]
Currently, it will show fansub/raw group where I get the anime from:
![discord_2018-08-11_00-32-35](https://user-images.githubusercontent.com/12217018/43969863-185886ce-9cfe-11e8-8f6b-62ad6b2419cb.png)
Here, the anime is by Erai-raws.

I would want to hide it, because I don't want to show that I'm actually watching the anime from a fansub/raw group, especially since I'm in a few anime-related Discord servers where fansubs or raw or illegal unlicensed contents are not allowed to be discussed at all.

All of anime I watch from fansub/raw group are the ones not available in my country only (either because all streaming services excluded rights for my region, or no one licensed them here, or it's banned because didn't pass censorship board), in other cases I'll try as much to watch legal streams.

It should just be an option, not remove it completely, because some people will want to show it, but there will also be people who want to hide it.

**Comment by purposelycryptic** [comment]
I haven't used Taiga with Discord, but I believe it uses the same configurable string, which you can edit under advanced options - it gives you a variety of variables to use, and you should be able to simply remove the group variable from it.

**Comment by MuhdNurHidayat** [comment]
I tried to change the string in the advanced setting, and restarted Taiga.
But it still shows the group name in Discord, even though it didn't show on notification anymore.

**Comment by erengy** [comment]
That option doesn't affect anything but episode notifications. What you see on Discord is currently not changable through the UI. However, you can do this:

1. Close Taiga.
2. Open `Taiga\data\settings.xml` and search for `discord`.
3. Remove the `$if(%group%,by %group%)` on that line and save the file.
4. Restart Taiga.

> I don't want to show that I'm actually watching the anime from a fansub/raw group, especially since I'm in a few anime-related Discord servers where fansubs or raw or illegal unlicensed contents are not allowed to be discussed at all.

That sounds like a legitimate reason for the request. I'll see what I can do.

**Comment by purposelycryptic** [comment]
@erengy - My apologies, did not intend to spread bad information; I have never actually used Discord, and mistakenly assumed that the option was meant as a universal formatting tool for Taiga's notification/status display functions. I should have properly tested/confirmed before writing, but my enthusiasm in thinking I could help got the better of me.
