### ISSUE TITLE
Feature Request: Night/Dark mode 

### ISSUE THREAD

**Issue by WokgranX** [erengy/taiga#679]
As pretty much everything else already took notice of how it is better to have darker themes which are more pleasant to the eye on big screens, I kindly request to have this feature also considered in Taiga.

It is specially painful sometimes to switch from youtube, anilist, reddit and even Nyaa (all in night mode) to a bright-white taiga screen to search for the torrents to download. It would be very appreciated! 

(Doesn't help much since I use a ultrawide 29" monitor and just love everything at a darker/black shade)

Nonetheless, this app is a lifesaver! **Thank you very much for your excellent work and excellent app**! I just love how those wacky episode numbers of the fansubs which do not respect season counting are still counted smoothly with Taiga (as in, 1st ep season 2 being numbered as "episode 13" instead of "1" and Taiga recognizing both numbering ways). It was always such a pain with MALUpdater, to have to manually input those eps.

**Comment by taigalover** [comment]
He's said it before in #320, #304 and #576 that:

> there are currently no plans to add themes to Taiga. In fact, I won't be making any significant changes on the UI until v2.0.

And he provided a suggestion in #320 for a way to use a dark theme.
There's a longer discussion if you're interested, in #121 about Ui customization.

**Comment by WokgranX** [comment]
Thank you very much for the answer. Sadly the high contrast ("dark" windows) theme just wrecks the hole harmonized interface. And Taiga does not inherit the built in "dark mode" of windows 10 either. Nice tips and well, I consider this closed and hopefully we can see this on v2.0.
