### ISSUE TITLE
Taiga doesn't ignore network streams if "Ignore files outside of library folders" option is checked

### ISSUE THREAD

**Issue by rld243** [erengy/taiga#680]
Latest git version (47e2cde)

I use mpv for playing youtube and IPTV streams and noticed that Taiga tries to identify them even when I have "Ignore files outside of library files" option checked.

How to reproduce:
1. "Ignore files outside of library folders" option should be checked
2. Open any http(s):// or udp:// stream using mpv from command line, e.g:
`mpv "https://www.youtube.com/watch?v=OdOE1ykDaPw"` 
(youtube-dl is needed in PATH or mpv folder)
3. Go to "Now Playing" and notice that Taiga tries to identify stream

Not really big issue, but still worth reporting I guess.

**Comment by erengy** [comment]
This is the intended behavior. When you're watching a stream, Taiga reads the window title of the media player. There's no file to be ignored, which is why that option doesn't apply.

See #471 and #330 for relevant issues.

**Comment by rld243** [comment]
Ok. Thanks for the answer.
