### ISSUE TITLE
Suggestion: Selecting fansub when playing an anime through Taiga

### ISSUE THREAD

**Issue by AdsonEsteves** [erengy/taiga#681]
It just so happens that this season I'm watching Shoujo☆Kageki Revue Starlight through two fansubs, ACSS and Starlightsubs. So I end up watching by ACSS first beacuse the video quality is better and then I re-watch by Starlightsubs because the subs are better. And since I do that, I download the episode from both of them.
I like to play the episode through Taiga, but in this case I need to play it by going on the folder because Taiga always select ACSS, and I can guess why, it probably just selects the first matched video that appears on the folder and plays it.
So I'd like something to select the fansub to play the episode, like on the context menu from the Anime List.

Since its a very especific issue and will rarelly happen (probably next season wont happen), I will just leave this as a sugestion.

**Comment by taigalover** [comment]
Have you tried setting a fansub preference in the 'Anime Information' window?
You can do this by:
-Right clicking a series and selecting 'Information'
-Go to the 'My list and settings' tab
-Go to the bottom of this tab and select change
-Enter whatever fansub you want

For your case you can first enter ACSS then after your episode is finished, you can erase ACSS and enter Starlightsubs. Hope this helps.

**Comment by AdsonEsteves** [comment]
@taigalover 

The only thing it does is select that Fansub on the torrent Filter, but it still plays only ACSS

But even if it was possible this way, to need to enter the information window and change the fansub writing it, would be a pain, if it was the case I would prefer playing from the folder, I could get there faster through Taiga.

But Thanks for the help.

**Comment by erengy** [comment]
This is similar to #70 in the sense that Taiga must be able to find all variations of an episode, rather than simply playing the first one it encounters in library folders. Once the necessary work is done, I'll consider displaying a prompt to the user in cases like this. Thanks for the suggestion.
