### ISSUE TITLE
Suggestion: Show latest aired episode number.

### ISSUE THREAD

**Issue by inexplicabro** [erengy/taiga#682]
I wanna know how many episodes have aired. Maybe you could add a 'latest episode' column next to the progress column or something.

**Comment by taigalover** [comment]
To check for the latest episode of a series, hover your mouse over the progress bar of the series.
For example, One Piece:
![screenshot 149](https://user-images.githubusercontent.com/32505754/44410584-5638ae00-a597-11e8-87eb-cb5f1825f60b.png)
Hope this helps.

**Comment by inexplicabro** [comment]
thanks! I feel so stupid now...
