### ISSUE TITLE
Feature request: Allow adding 'notes' as a column in the tab listviews

### ISSUE THREAD

**Issue by Xabis** [erengy/taiga#684]
Whenever I put a show on hold (or dropped), I add a quick note as to why. For example, for movies, I will add the release date if one is published.

It would be nice to be able to select that as a customizable column in the listview so that I do not have to open the info panel for each item.

**Comment by erengy** [comment]
Thanks for sharing your use case. I do plan on adding a column for notes. We have a generic issue at #150 for Anime List columns though, so I'm closing this one.
