### ISSUE TITLE
Taiga/Deluge Won't Download To Anime Directory

### ISSUE THREAD

**Issue by FallenAndroid** [erengy/taiga#688]
I've seen this issue brought up a few times, but I've been running into it since I started using Taiga a few days ago, and have attempted every fix in every related issue thread I've seen for it. Deluge is not running in classic mode and is connected to the local daemon. 

I Attempted to set deluge-console.exe instead of deluge.exe as the target torrent client, but then when attempting to add a torrent from Taiga, nothing happens. Target directory that it's SUPPOSED to be downloading to is D:\Media\Anime, and Deluge's default is D:\Downloads, where it continually keeps putting the anime from Taiga regardless of what settings, or fixes I try.

**Comment by erengy** [comment]
Just checked in case the latest version of Taiga broke anything, but that wasn't the case. Here's what I did:

1. Installed `deluge-1.3.15-win32-py2.7.exe` and ran Deluge.
2. Started the daemon and connected to it.
3. Enabled the relevant options of Taiga at *Settings → Torrents → Downloads* and set the custom application path to `C:\Program Files (x86)\Deluge\deluge-console.exe`.
4. Downloaded a random torrent and saw that the download path was correct (`D:\Downloads\Anime\{Anime Title}` in my case).

You can try the following to see if Taiga's sending the parameters to Deluge correctly:

1. Run Taiga in [debug mode](https://github.com/erengy/taiga/wiki/How-to-run-Taiga-in-debug-mode).
2. Download a torrent via Taiga.
3. Open `Taiga\Taiga.log` and check the lines near the end following `Aggregator::HandleFeedDownloadOpen`, which should give you the application path and the command-line parameters.

**Comment by FallenAndroid** [comment]
Not sure what changed after restarting Taiga with the debug mode parameter, but it appears to be working now. It had to have been Deluge acting up instead of Taiga, if it wasn't able to send torrents to Deluge through deluge-console.exe before, for whatever reason. Sorry for opening the apparently pointless issue. 😥
