### ISSUE TITLE
Order torrents by name

### ISSUE THREAD

**Issue by diksm8** [erengy/taiga#69]
When you search for an anime and download all the torrents at once one the application gets them in the order from highest to lowest. So you have to manually arrange them in your torrent client when they get added.

**Comment by Zyst** [comment]
This could be implemented by making the Torrent tab "Download" button download from bottom to top, as opposed to how it works right now (top to bottom).

Interesting suggestion

**Comment by erengy** [comment]
The current order is actually better for another set of users, where their torrent client asks for confirmation: Taiga downloads the .torrent files in 3-2-1 order, the torrent application displays the latest confirmation dialog on top, which in turn places the downloads in 1-2-3 order.

In other words, the order depends on the torrent application's settings as well. There is no perfect solution here, but perhaps I can reverse the download order when the user is using uTorrent and has the download-to-anime-folder option enabled.

**Comment by rr-** [comment]
Having it configurable sounds much better than hardcoding stuff for different clients.

**Comment by erengy** [comment]
I'm trying to keep the number of options to a minimum, but yeah, I'll probably go with that this time.

Note to self: Consider internally sorting marked torrents by episode number rather than release date in order to handle edge cases.

**Comment by diksm8** [comment]
I disabled my confirmation when taiga downloads a torrent, if I get a torrent normally I get the confirmation.

**Comment by erengy** [comment]
These options are available as of abb7a9d5557548db03514e471250019cd6415282:

![download_queue](https://cloud.githubusercontent.com/assets/1078430/6627367/423a3ba6-c906-11e4-8c67-842fdf03d191.gif)
