### ISSUE TITLE
Add Netflix recognition support

### ISSUE THREAD

**Issue by hugoboissiere** [erengy/taiga#690]
Hi,

Since Taiga can recognise what you're watching in streaming sites such as Crunchyroll etc, do you think it'll be possible to add Netflix to the list of supported sites?

**Comment by erengy** [comment]
From the [FAQ](https://taiga.moe/#support):

> **Could you add support for other streaming sites?**
>
> As long as the site provides a consistent way to detect the anime title and the episode number in its URL or page title, it's possible. Some services such as Hulu and **Netflix** aren't supported because it's technically not possible to detect the episodes this way. Let us know if you have another service in mind.
