### ISSUE TITLE
Implementing MAL API

### ISSUE THREAD

**Issue by suabahasa** [erengy/taiga#692]
I have analyse MAL API on MAL android client (last version).
feature:
- anime list
- update list
- search
- seasson
and others that still in testing

**Comment by suabahasa** [comment]
I will post here soon, so u can implement it to taiga

**Comment by wopian** [comment]
See https://github.com/erengy/taiga/issues/687#issuecomment-416035103 and https://github.com/erengy/taiga/issues/601

**Comment by erengy** [comment]
Thanks, but that's not going to help.

If you're talking about the official (but unlisted) [mobile application](https://play.google.com/store/apps/details?id=net.myanimelist), the new API it uses was already documented at [MyAnimeList/mal-api-docs](https://github.com/MyAnimeList/mal-api-docs) before they took it down. Third-party developers don't have access to it yet.

If you're talking about the unofficial ones, see @wopian's comment above.

In any case, we're now waiting until MAL makes a public release of their new API.

**Comment by suabahasa** [comment]
I use API from official MAL mobile client

**Comment by suabahasa** [comment]
@erengy 
here the api [https://gist.github.com/suabahasa/61754f37a24026224f7af14766aa85c1](https://gist.github.com/suabahasa/61754f37a24026224f7af14766aa85c1)

import to your [insomnia application](https://support.insomnia.rest/)

feature:
- token
- season
- suggestion
- my list
- update list
- anime detail
- search anime
