### ISSUE TITLE
Taiga crashes when Discord screen sharing window is opened

### ISSUE THREAD

**Issue by mikenzb** [erengy/taiga#696]
When opening the Discord application window for screen sharing, Taiga will crash., Discord will not allow me to select the Application I want to screen share until Taiga is fully closed. 

More Information: 
OS: Windows 10 Pro 16299.547 (1709/RS3)
Taiga 1.3.1
Discord PTB

Steps to reproduce:
1. Start watching an anime episode (through VLC in my case)
2. Taiga has a queued list update (Ask for Confirmation is enabled in Taiga after 120 seconds)
3. Call a Friend on Discord
4. Click on Screen Share in Discord 
5. Click on `Application Window` Screen sharing
6. Taiga crashes

Using `AppCrashView` I was able to check the dmp files of the crashes and it tells me the crashes are `An unhandled exception was encountered during a user callback.` and `Access Violation` and the Fault Module is `USER32.dll`

I also tried waiting for the Confirmation Popup and dismissed it, however, Taiga still crashes.

Image:
https://i.imgur.com/PwJywa3.png

**Comment by oplexz** [comment]
Can reproduce.
Actually it happened to me before, but I never paid attention to it and just restarted Taiga.

**Comment by hugonun** [comment]
This is most likely a Discord issue. Related links: [1](https://www.reddit.com/r/discordapp/comments/8mcva5/discord_stream_screen_share_w_sound_crashes/), [2](https://www.reddit.com/r/discordapp/comments/8pp8zs/screen_sharing_with_audio_crashes_whatever/)

Not running Discord as an admin fixes the issue.

**Comment by Tenrys** [comment]
I am not running Discord as an admin and this is still happening following the steps in OP.
