### ISSUE TITLE
Opera is not detected

### ISSUE THREAD

**Issue by SSorion** [erengy/taiga#698]
Previously Taiga recognized the animes I was watching perfectly fine. I use crunchyroll on Opera. But now it doesn't recognize them anymore. 
Taiga version: 1.3.1
Opera version : 55.0.2994.61 64b
I don't know what else to add other than the versions but if you need anything I'll provide

**Comment by SSorion** [comment]
What kind of sample link? A video where I show everything or just a crunchyroll anime link. I can do the video if wanted indeed.
Settings look like they're on so it may not be that.

**Comment by erengy** [comment]
@GabrielDuarteM The issue was fixed with the commit linked above. You can try it in the [latest build](https://taiga.moe/latest.html).

**Comment by GabrielDuarteM** [comment]
@erengy I just downloaded it yesterday, I'm using version 1.3.1, and according to the software, it doesn't have any updates:
![image](https://user-images.githubusercontent.com/7675500/47308315-9bb14000-d607-11e8-9167-c19702220507.png)

Yet, when I open up any anime on Crunchyroll using opera, taiga just ignores it.

![image](https://user-images.githubusercontent.com/7675500/47308399-dfa44500-d607-11e8-84d0-617c9e5041b1.png)
Same episode, but on chrome:
![image](https://user-images.githubusercontent.com/7675500/47308757-eda69580-d608-11e8-9900-17d0f1d8db97.png)

**Comment by erengy** [comment]
@GabrielDuarteM v1.3.1 was released in August. This issue was fixed two weeks ago. There's no official release that includes the fix yet. The link in my previous comment is for a nightly build that includes all the changes made since v1.3.1. Are you saying that you downloaded the latest build from that link, but still having the same issue?

**Comment by GabrielDuarteM** [comment]
@erengy My bad, I thought that the latest build was being referred to the latest version, and it is indeed fixed on the version you linked to me.

Any plans on releasing a new version? August was quite a time ago, and I'm sure there are at least some bug fixes, judging by the commit history 😃
