### ISSUE TITLE
Taiga detects entire VLC playlist as playing.

### ISSUE THREAD

**Issue by Freddiex** [erengy/taiga#699]
I like to queue up more than one episode of anime so that I don't constantly have to go back and forth between apps, and can watch from further back, on a sofa or chair. VLC is my preferred player and has no option to autodetect the next episode, so there's no other way of doing this. Unfortunately, Taiga seems to detect a random one of the sometimes 50+ queued files as the currently playing episode, and so will update my progress to a random place, or not at all if the "ignore episodes further than current" option is selected. It seems odd that Taiga wouldn't just detect the only episode that is actually currently being played, and I've been left wondering whether there's any way around this.

**Comment by ovingiv** [comment]
How much time do you have set for it to update to your list? 
![image](https://user-images.githubusercontent.com/24558152/45523506-41fb6180-b78f-11e8-9957-4d0d89348654.png)
By default it should update it after 120 seconds has passed.

I should add I do notice this happening as well when I open my watch playlist when binge watching a series however it updates to the current episode that is currently playing. I also use the latest update for VLC 64bit.

**Comment by erengy** [comment]
Likely the same issue as #628 and #677.
