### ISSUE TITLE
Custom Streaming Sites

### ISSUE THREAD

**Issue by DevScyu** [erengy/taiga#702]
Would it be possible to allow users to add their own streaming media websites with the correct regex for anime name and episode number?

**Comment by erengy** [comment]
From the [FAQ](https://taiga.moe/#support):

> **Could you add support for other streaming sites?**
>
> (...) Note that the current stance Taiga takes is that it only supports official streaming sites. Please don't ask about direct or **indirect** support for unofficial ones.

See #184 and #254 for previous issues.
