### ISSUE TITLE
Issue when adding anime to Kitsu list: "Please set up your account before adding anime to your list"

### ISSUE THREAD

**Issue by 9Morello** [erengy/taiga#704]
I added my Kitsu account details to Taiga, but currently I can't add new anime into my list. I've tried searching for an anime and adding it, but it's showing this error:

"Please set up your account before adding anime to your list"

* Adding animes through Kitsu's website works
* Updating animes that are already on my list works
* Adding a new anime through Taiga **doesn't** work
* Not sure if this is related at all, but I was previously using a MAL account. After adding my Kitsu account,  I swapped the active service to it in the Settings. Taiga apparently downloaded my list without any issues.

If you want me to test something else, please ask.

**Comment by ShaunV2** [comment]
Did you setup your profile url instead of leaving it set with the random number it uses?  You are signing in with your email address and not user id right?

I don't think the last point is related to the issue at all.

**Comment by 9Morello** [comment]
@ShaunV2 Yes, I signed in with my e-mail address.

I hadn't setup my profile url when I made this issue. After seeing your comment, I set it to use my nickname on Kitsu instead of the random number. It didn't seem to change anything on Taiga.

On Taiga, going into Services --> Kitsu --> "Go to my profile" sends me [here](https://kitsu.io/users), which 404s.

**Comment by ShaunV2** [comment]
Mine gos directly to my profile without giving me a 404 error, it sends me [here](https://kitsu.io/users/Shaun).  It shouldn't be users at the end to begin with it should be the profile url as in the name you put there.

You'll have to ask @erengy to further troubleshoot the issue as I've never had the problem with adding anime through Taiga although my account is 5 years old so I never had to manually set the profile url.

**Comment by 9Morello** [comment]
My bad, I hadn't checked the FAQ before posting this issue here. After taking a look at it, it seems none of the questions are related to this issue.

**Comment by 9Morello** [comment]
Update: it works now. I didn't do anything, but I just tested adding an anime today and it worked.

**Comment by erengy** [comment]
For future reference, all you need to do is:

1. Set up your Profile URL in Kitsu settings: https://kitsu.io/settings/profile
2. Restart Taiga and synchronize.
