### ISSUE TITLE
Feature request: Add support for dynamic streaming sites

### ISSUE THREAD

**Issue by nico-abram** [erengy/taiga#707]
Something like a configuration file with the url and the regex/es required

**Comment by ifonefox** [comment]
From the [FAQ](https://taiga.moe/#support):

> Could you add support for other streaming sites?
>
> ...Note that the current stance Taiga takes is that it only supports official streaming sites. Please don't ask about direct or indirect support for unofficial ones.

Regex for site discovery has been asked for before #707
