### ISSUE TITLE
Different torrent search results when space in name

### ISSUE THREAD

**Issue by NotDaniel59** [erengy/taiga#711]
Shouldn't it show the same results whether or not there is a space?
![2018-10-09_15-45-09](https://user-images.githubusercontent.com/28601384/46673556-57bb4580-cbda-11e8-8414-4f733a96249a.gif)

**Comment by slevir** [comment]
If you look carefully at "filename" column, you will see, that filenames do indeed contain or not contain the space depending on your query. "Anime title" column is detected by Taiga (non-space version happens to be the alternative title for the series, on anilist at least), but Taiga can't match search results *before* search is completed by the torrent site you're using.

**Comment by erengy** [comment]
Search results depend on the search algorithm of the torrent site you selected. Taiga simply passes on your query, retrieves the results, tries to identify them and applies your filters.
