### ISSUE TITLE
Recognize anime titles outside of our list

### ISSUE THREAD

**Issue by panhartstuff** [erengy/taiga#712]
It seems that Taiga doesn't recognize the anime played in the video player, unless said anime is already in our list. There should be an option to disable this

**Comment by erengy** [comment]
Anime recognition isn't limited to your list, it's limited to Taiga's local anime database. At first, this database is empty. Once you set up your account and synchronize, Taiga becomes aware of all the anime in your list. As you continue using Taiga, search results and seasonal anime are added to this database too, which can then be recognized. In other words, Taiga isn't aware of every anime that exists; it only knows about the ones it's seen before, in your list or elsewhere.

For additional information, you can read the anime recognition section at the [support page](https://taiga.moe/#support).

**Comment by panhartstuff** [comment]
Is there a reason why Taiga can't lookup directly to the online database (MAL, Anilist, etc.) instead of our local database?

**Comment by erengy** [comment]
There are various reasons for that, but most importantly, it would raise some privacy issues. You wouldn't want Taiga automatically sending the names of everything you watch to a web service.
