### ISSUE TITLE
Taiga resetting with reboots

### ISSUE THREAD

**Issue by KrisKamweru** [erengy/taiga#713]
I've had Taiga be completely reset twice in the past few days after a reboot. Configurations, signed in accounts, library location, preferences, etc are all lost each time. Basically it's like I just installed taiga again

Luckily both times my list has been synced with kitsu, so I haven't lost anything. It's just a hassle to set up again to my exact preference.

Is there a way I can capture logs, or anything I should monitor in case it should happen again? So that I can help you guys see what's going on? I'd love to help

P.S. One of the reboots was a security patch update, and one was a regular restart.

**Comment by asakurato** [comment]
I thought I was the only one lol. I wondered why my history and some preferences just kept reseting. At least torrent filters are fine, or that would be disaster.

**Comment by eslamsidereel** [comment]
same problem here

**Comment by erengy** [comment]
For v1.4, I entirely rewrote how application settings are handled. It now supports locked access from multiple threads and serialization with backup files. I haven't figured out what exactly is causing this issue, but these changes should help.
