### ISSUE TITLE
HTTP error #6: Couldn't resolve host name (taiga.moe) on startup

### ISSUE THREAD

**Issue by Yukirina** [erengy/taiga#716]
I set Taiga to start automatically with Windows 7, and whenever my OS boots up, Taiga tosses that error at me. There's no real consequences I think, outside of the fact that Taiga doesn't boot up after I exit out the error, so I have to start it up again.

I am assuming this error pops up because Taiga boots up before my network adapter is paired to the internet (I'm using ethernet), so I'm not sure how to make Taiga boot up slower to prevent the error from showing up.

**Comment by Shumatsu** [comment]
That'd probably require you to use third-party software to delay Taiga's start.
