### ISSUE TITLE
Update failed

### ISSUE THREAD

**Issue by SmilingCoffin** [erengy/taiga#72]
Here's the message that I keep getting.

I don't really know why this happened, it was working fine yesterday.
![error_screenshot](https://cloud.githubusercontent.com/assets/3726687/5824913/f34fdaaa-a0e7-11e4-84b1-2883e2fd7b36.png)

**Comment by rr-** [comment]
>MyAnimeList.net is currently down for maintenance.
>
>MyAnimeList.net is currently undergoing extensive server maintenance from 10am-6pm PST.
>We apologize for the inconvenience and hope to be back online as soon as possible!
>
>Thank you,
>The MyAnimeList Team

Source: http://myanimelist.net/

**Comment by SmilingCoffin** [comment]
I am so used at Taiga updating my list, I did not even realized they were
under maintenance.. Huge fail on my part.

**Comment by erengy** [comment]
In case you missed the [news](http://myanimelist.net/forum/?topicid=1345095) (emphasis mine):

> This server migration is the start of something I'm personally thrilled to tell everyone. **MyAnimeList has been acquired by a new investor company!** Starting the 20th, we will be running on their servers. This means CraveOnline's involvement with MyAnimeList will cease after January 20. I can't even begin to express how hyped I am for what our new owners can bring to the table for us!

> 2015 is going to be a HUGE year for MyAnimeList. So if we have any migration issues next week, I ask everyone to please think of the big picture: **we've got a new team working on MAL (an actual development team!)**, and a company to hold our hand and get us the help we need. It might start out a little bumpy, but I'm confident our new owners will get things working. I know that soon our long list of features and bug fixes will finally get the attention they deserve. I can't speak to specifics yet, but we'll be making announcements soon after the migration!

PS: Kurumi best girl. :+1:
