### ISSUE TITLE
How to change anime recognition

### ISSUE THREAD

**Issue by nwb22** [erengy/taiga#721]
Hi, I have problem like in this post https://github.com/erengy/taiga/issues/557 but I can't change any anime with wrong name I'm using Taiga with kitsu, any advice how to do this?

**Comment by erengy** [comment]
Hi there. Did you also accidentally click on a wrong title at Now Playing page? If so, did you try removing the alternative title as I explained in #557? Normally, that's all you need to do. If that didn't work for you, please elaborate on what you did exactly and what went wrong.
