### ISSUE TITLE
Kitsu returned an error: Client authentication failed due to unknown client

### ISSUE THREAD

**Issue by hellflames21** [erengy/taiga#722]
![image](https://user-images.githubusercontent.com/44457907/47478233-b4e10900-d820-11e8-97ea-4b1c500580df.png)
not really sure what to do with this came back after work to find that i cant connect to kitsu, 
tried uninstalling and reinstalling but it didnt do anything

**Comment by erengy** [comment]
I can reproduce the issue. Looking into it now.

**Comment by theKAKAN** [comment]
Mine got fixed by re-entering the password.  
Also, see that your Kitsu username is actually your email address 😄

**Comment by serjflint** [comment]
Same here. Even tried to build from source. Will wait for solution from Kitsu

**Comment by erengy** [comment]
Should be fixed with hummingbird-me/hummingbird-server@dd0cba6d9bc169a60c86e7c22486d239e0b60e92.

**Comment by hellflames21** [comment]
awesome, taiga has connected and loaded my list again
