### ISSUE TITLE
Add support to OKanime.com (media provider)

### ISSUE THREAD

**Issue by Abady321x123** [erengy/taiga#728]
Media provider website: https://okanime.com

**Comment by ifonefox** [comment]
Is OKAnime a piracy site? If so, Erengy won't add it.

From the [FAQ](https://taiga.moe/#support): 

> **Q: Could you add support for other streaming sites?**
> A: ...Note that the current stance Taiga takes is that it only supports official streaming sites. Please don't ask about direct or indirect support for unofficial ones

**Comment by Abady321x123** [comment]
@ifonefox oh, thank's for noticing me. (closed)
