### ISSUE TITLE
Suggestion: add button to delete episodes already seen

### ISSUE THREAD

**Issue by AceTF** [erengy/taiga#729]
probably kind of easy to realize: A fast way to delete episodes that I have already seen and are still on my harddrive. I have to do this manually once in a while since the automatic torrent downloads keep filling up my harddrive; is this a possible request?

I love taiga btw - thanks a lot for this useful app!

**Comment by erengy** [comment]
We already have #187 for the same suggestion, so I'll be closing this one. Cheers.
