### ISSUE TITLE
Fix web browser support

### ISSUE THREAD

**Issue by Chet9999** [erengy/taiga#73]
I already selected google chrome as a media player, but when I watch a new episode, nothing in Taiga changes.

**Comment by erengy** [comment]
Works fine here with Google Chrome v40.0.2214.91 m (64-bit). Which media provider (e.g. Crunchyroll) do you use? Have you enabled it from *Settings → Recognition → Media provider* as well?

**Comment by Chet9999** [comment]
I understand now.
I didn't realize I needed to do that.

Also, can you add support for http://kissanime.com/ ?
