### ISSUE TITLE
Downloading torrents same episodes.

### ISSUE THREAD

**Issue by cartals** [erengy/taiga#730]
We can download new torrents automatically. But it downloads same episodes from different fansubs like "horrible subs goblin slayer 12", "erai raws goblin slayer 12" how can i solve that issue.

**Comment by AdsonEsteves** [comment]
@cartals 

Adding a filter to the torrents may solve, just write what is your preffered fansub on the filter
![image](https://user-images.githubusercontent.com/8836540/50576688-3d21f280-0dfe-11e9-962e-a435aaac6a71.png)

**Comment by erengy** [comment]
This is indeed how the default filters work. You're supposed to expand upon it by setting up some filters according to your preferences.

To make sure Taiga doesn't download any episodes other than the ones you want, I'd suggest disabling the following default filters:

- Select currently watching
- Select airing anime in plan to watch

Then, you can create limited filters for the series you want, telling Taiga which fansub groups and video resolutions you prefer.
