### ISSUE TITLE
Season data download automatically

### ISSUE THREAD

**Issue by cartals** [erengy/taiga#731]
We download season data one by one, how can i download all of them in once.
TR
ingilizcem daha fazla yetmedi @erengy abi dataları tek tek yükleyeceğimize hepsini tekde indirme yolu yok mu örnek veriyorum seasona a girince ilk de az anime gözüküyor refresh data diyince diğer animeler geliyor tek tek uğraşması cok zor.

**Comment by taigalover** [comment]
There isn't currently an option for this, season data can be downloaded by first selecting the season the clicking the "refresh data" button.

**Comment by erengy** [comment]
That basically means downloading the entire anime database of the selected service, or a large portion of it for the past decade or so. Requesting the relevant data on demand and in small pieces is the more feasible and ethical thing to do, I believe.

(Bütün anime sezonlarını tek seferde indirmek demek, seçili anime sitesinin bütün anime veritabanını veya büyük bir bölümünü indirmek demek. Bunu yapmak şu an mümkün/makul/etik değil ne yazık ki.)
