### ISSUE TITLE
Suggestion: optional thumbnails

### ISSUE THREAD

**Issue by NanoCats** [erengy/taiga#732]
A feature that I loved from Anilist among others, is the ability to have a view featuring thumbnails along with the rest of the anime titles like so: 

http://puu.sh/Cr9u1/977047b5cf.jpg  (alternate list view, which would include thumbnails)

**Comment by BarbaBlannk** [comment]
I suscribe this propose, also an optional carrousel would be nice.
Thanks all developers that work in Taiga.

**Comment by erengy** [comment]
Closing this issue because we already have #87 for the same topic.
