### ISSUE TITLE
Taiga recognizing anime as older one with same name

### ISSUE THREAD

**Issue by KazukiMutou** [erengy/taiga#735]
Trying to get it to recognize Dororo, but when I watch it it's recognizing it as the 1969 anime Dororo to Hyakkimaru. If I give it the alternative title Dororo, it'll say that it can't recognize it. 

Filename is [HorribleSubs] Dororo - 01 [1080p].mkv, it's listed as Dororo (どろろ, Dororo to Hyakkimaru) on Kitsu.

I remember having this issue in the past, but I can't remember how I resolved this. Any ideas?

**Comment by Rx2TF** [comment]
Having the same issue with Mob Psycho 100 II

**Comment by erengy** [comment]
@KazukiMutou Both series have the same primary title, so Taiga cannot resolve the ambiguity without your input. Normally, when you play the episode, it displays the following at Now Playing page:

![now-playing-dororo](https://user-images.githubusercontent.com/1078430/51739362-5850ec80-20a2-11e9-9528-71cde4f50fed.png)

All you need to do is to select the second one, which adds `Dororo` as your alternative title to the series. After that, Taiga will prioritize that series.

In your case, you may have accidentally added the alternative title to the older series too. Removing that should resolve the issue.

@Rx2TF Remove any alternative titles you added to the S1 and S2, then see #743 for a similar issue.
