### ISSUE TITLE
Adding anime via search returning error

### ISSUE THREAD

**Issue by Midtan** [erengy/taiga#740]
When trying to add an anime to my Kitsu list via Taigas search tab, Taiga returns the error

> Please set up your account before adding anime to your list.

Using latest Taiga (1.3.1) and Kitsu. Syncing my list is working flawlessly, there is no problem when updating the watched episode count or editing the status of a series.

**Comment by erengy** [comment]
See #704 for the same issue:

> 1. Set up your Profile URL in Kitsu settings: https://kitsu.io/settings/profile
> 2. Restart Taiga and synchronize.

This will likely resolve #739 too.

**Comment by Midtan** [comment]
That seemed to do the trick concerning both issues.
Thank you.
Closing both.
