### ISSUE TITLE
"Use anime folders as the download folder" - Transmission setup

### ISSUE THREAD

**Issue by Mene-sama** [erengy/taiga#741]
I have recently started using Taiga. The issue I'm having is "Use anime folders as the download folder" function doesn't work with Transmission. I did some research and found out that it's related to Transmission daemon and remote, but after playing around with settings for hours I'm yet unable to get it working. It still downloads 

In short, I'm looking for a way to get Transmission to save files where Taiga tells it to. Any help is appreciated.

**Comment by erengy** [comment]
- Select "Daemon" and "Command-line tools" while installing Transmission.
- Make sure Transmission Daemon is running in the background.
- Go to Taiga's *Settings → Torrents → Downloads*, select "Use a custom application" and enter the path to `transmision-remote.exe`.
    - e.g. `C:\Program Files\Transmission\transmission-remote.exe`

That is all. Just tried it out with a fresh installation of Transmission 2.94 and it worked as expected.

**Comment by Mene-sama** [comment]
"Use a custom application" did the trick. Thanks a bunch, I'm closing the issue.
