### ISSUE TITLE
Taiga incorrectly detecting episode

### ISSUE THREAD

**Issue by ZeroSiks** [erengy/taiga#743]
Taiga does not correctly detect the episode of Mob Psycho 100 II.
![img](https://cdn.discordapp.com/attachments/382176290331164683/537920702544740352/unknown.png)

**Comment by erengy** [comment]
Just tested this, but Taiga didn't have any issues identifying the correct episode.

- What's the filename? (e.g. `[HorribleSubs] Mob Psycho 100 S2 - 01 [720p].mkv`)
- What's the name of the directory in which the video file is located? (e.g. `Mob Psycho 100 II`)
- Which service do you use? (e.g. AniList, Kitsu, MyAnimeList)
- Which media player do you use?
- Did you add any alternative titles to the series? (see *Anime Information → My list and settings*)

**Comment by erengy** [comment]
Most likely explanation is that you're running MPC-BE as administrator. This prevents Taiga from reading the path of the video file, so it falls back to using the window title. Anitomy cannot parse the title correctly, which results in this issue.

If that's the case, you have two options:

1. Do not run MPC-BE as administrator, or run Taiga as administrator too.
2. Go to MPC-BE's *Options → Player → Title bar*.
    - Select either *Display full path* or *File name only*.
    - Uncheck *Replace file name with title*.

---

Note to self: We can probably add ` - \d+: ` (or even ` \d+: `) as an episode pattern to Anitomy. Example title: `Mob Psycho 100 II - 03: One Danger After Another ~Degeneration~`

**Comment by ZeroSiks** [comment]
I don't see how MPC-BE runs as admin when I just open it normally. But running Taiga as admin fixed the issue for me. Thanks 😃
