### ISSUE TITLE
Scan available episodes at startup

### ISSUE THREAD

**Issue by HekutoruMAC** [erengy/taiga#746]
Currently I need to select "Scan available episodes" from the file menu or press F5 every time I launch Taiga to get them recognized. Using Windows 10 with a dedicated Anime folder.

**Comment by erengy** [comment]
Did you enable the *Settings → Application → General → Startup → Scan library folders for available episodes* option?

**Comment by HekutoruMAC** [comment]
No, I'm sorry, my bad. Thank you for your patience...
