### ISSUE TITLE
Taiga not transfering files correctly. 

### ISSUE THREAD

**Issue by bgi123** [erengy/taiga#749]
![image](https://user-images.githubusercontent.com/15849763/51889409-2a4c0080-235f-11e9-9bd3-ece1884ff56b.png)

I see the downloads are done with qbittorrent, but they aren't in the folders I set, but in the default folder path of qbittorrent instead.  How can I fix this problem?

**Comment by erengy** [comment]
I imagine this is related to your qBittorrent settings rather than Taiga.

To be sure, you can run Taiga in [debug mode](https://github.com/erengy/taiga/wiki/How-to-run-Taiga-in-debug-mode) and try downloading a torrent. You should then see something like this at the end of the log file:

```
2019-01-29 20:51:28 [Debug] feed_aggregator.cpp:397 Aggregator::HandleFeedDownloadOpen | >>
Application: C:\Program Files\qBittorrent\qbittorrent.exe
Parameters: --save-path="D:\Anime\Mob Psycho 100 II" --skip-dialog=true "C:\Users\bgi123\AppData\Roaming\Taiga\data\feed\bnlhYS5zaQ==\[HorribleSubs] Mob Psycho 100 S2 - 01 [720p].mkv.torrent"
```

**Comment by bgi123** [comment]
I did the debug mode and it does do something like that. What can I change with qbittorrent to get it to work?

**Comment by bgi123** [comment]
Okay. I got it to work. You need to go to download settings in bittorrent and set "Default torrent management mode" to manual. It is default as automatic.

**Comment by erengy** [comment]
Just checked if they changed it in recent versions of qBittorrent, but that wasn't the case. The option is set to Manual [by default](https://github.com/qbittorrent/qBittorrent/blob/bb3ad8acd31d9976796ffc048faab020a6f8e702/src/base/bittorrent/session.cpp#L339), so you must have changed it to Automatic yourself.
