### ISSUE TITLE
Add Kissanime.com to the media providers list

### ISSUE THREAD

**Issue by Chet9999** [erengy/taiga#75]
Kiss Anime has a huge collection, and streams in HD.
I use it often, and so do some friends.
It would help if you added support for it.

Thanks ^_^

**Comment by rr-** [comment]
![hehe](https://cloud.githubusercontent.com/assets/1045476/5915288/0242adbe-a604-11e4-846b-afa9ab801f79.gif)

**Comment by erengy** [comment]
> **[Could you add support for other streaming sites?](http://taiga.erengy.com/#support)**
> As long as the site provides a consistent way to detect the anime title and the episode number in its URL or page title, it's possible. Some services such as Funimation and Hulu aren't supported because it's technically not possible to detect the episodes. Let us know if you have another in mind. ***Note that the current stance Taiga takes is that it only supports official streaming sites.***
