### ISSUE TITLE
Fails to detect episodes of a specific anime

### ISSUE THREAD

**Issue by Sugihiru** [erengy/taiga#754]
I have real-time monitor activated, also tried restarting Taiga, but it still doesn't recognize the episodes of the anime Dororo. Here's the filenames I've tried :

> [HorribleSubs] Dororo - 01 [720p].mkv
> [HorribleSubs] Dororo - 02 [720p].mkv
> [HorribleSubs] Dororo - 03 [720p].mkv
> Dororo - 01.mkv
> Dororo 01.mkv

**Comment by erengy** [comment]
See #735.

**Comment by Sugihiru** [comment]
Thanks, sorry for the duplicate !
