### ISSUE TITLE
Taiga wrongly detects (or doesn't detect at all) Sangatsu no Lion with official episode names in it

### ISSUE THREAD

**Issue by asakurato** [erengy/taiga#756]
So if you name files like Sangatsu no Lion 01 - Chapter 1 Rei Kiriyama @ Chapter 2 The Town Along the River, Taiga will detect it as episode 2 (probably because there is chapter 2 there, but why ignoring chapter 1 then?). Same happens with season 2, but it is not recognizing anything in this case. Filenames with only Series title and episode number works fine. Using Taiga 1.3.1.

**Comment by erengy** [comment]
Parsing filenames with multiple numbers is complicated. Taiga (or rather, [Anitomy](https://github.com/erengy/anitomy)) looks for known patterns. If there is none, it selects the rightmost number as a last resort. This is why you see Taiga picking up the `2`.

I don't think there's anything I can do in this case. If you're okay with renaming your files, you can do various things to indicate the episode number:

- `Sangatsu no Lion 01 - ...` *(original)*
- `Sangatsu no Lion - 01 - ...` *(added ` - `)*
- `Sangatsu no Lion - Episode 01 - ...` *(added ` Episode `)*

**Comment by asakurato** [comment]
I have pretty much standardized naming for my archives, so I don't really want to rename them. If it can't be done, than so be it, I will update manually on rewatches :D
