### ISSUE TITLE
better discord rich presence

### ISSUE THREAD

**Issue by owaimori** [erengy/taiga#757]
hi and sorry for bad english >w> i'm zero at programming but i see some other discord rich presence things and maybe this is possible to do with taiga too (sorry if it isnt possible to do)
sorry about russian in screenshots >w> it should be clear what I mean

i think would be nice:

- show not the time that the episode is open in the player, but those remaining until the end of the episode (and "paused" if paused)
- instead of taiga's icon grab a anime poster from myanimelist / kitsu / anilist / something

Is it possible to make it look like right instead of left?
![untitled-1](https://user-images.githubusercontent.com/31232219/53135026-a1ee0380-358a-11e9-89fd-9b7f72f0f97b.png)  ![untitled-2](https://user-images.githubusercontent.com/31232219/53135402-22f9ca80-358c-11e9-85e5-f2cc1e871b29.png)

if it helps i see "remaining" thing in the aimp [plugin](https://github.com/Exle/AIMP-Discord-Presence). and in this plugin i saw that the icon changes depending on whether you listen to music from a local storage or from a link. 

i think you can implement the same thing, considering that the taiga already saves posters in the `AppData\Roaming\Taiga\data\db\image`

**Comment by crse** [comment]
All image appeared on Discord Rich Presence are uploaded to Discord server via Developer Portal.
Unless Discord makes a change to allow the application to get the thumbnail image from third-party source, I don't think this is possible.

**Comment by erengy** [comment]
Hi there @owaimori,

Those are all good suggestions I'd like to implement, but unfortunately none of them are possible at the moment:

- Taiga cannot show the remaining time, because it isn't aware of the state or the length of the video in your media player.
- Discord doesn't allow doing the following via RPC:
    - Setting the activity type to "Watching" rather than "Playing"
    - Dynamically changing the application name
    - Uploading images rather than using pre-uploaded assets
