### ISSUE TITLE
Add an "or" operator to the Filter options

### ISSUE THREAD

**Issue by Zyst** [erengy/taiga#76]
It would be nice if we could program an or operator to conjoin a set of rules.

For example:
![Default watching filter](http://puu.sh/f5LQB/549e967158.png)

Allows us to select stuff in our watch list.

So I have another rule:
![Plan to watch filter](http://puu.sh/f5Mtd/46051d812c.png)

That allows me to select stuff that starts airing. It feels like those two rules could fit nicely in one with an `or` operator.

These two can be neatly (Stretching the meaning of the word 'neatly') seen as:
`((animeTitle.isCurrentlyWatching();) or ((animeTitle.isPlanToWatch();) and (animeTitle.isCurrentlyAiring();))`

I absolutely adore messing around with the filter settings, and it would be awesome it we got to the point where we could have more complex rules all handled inside a single filter.

All in all the fact that you allow us to set Filters in the first place is bloody amazing. I'd just love to take it a notch further.

As a post scriptum, maybe consider adding the second rule I have as a default rule? It is handy as heck and a lot of the acquaintances I introduce to Taiga seem to struggle with that kind of functionality, similar problem to what people like #57 might have. Some people told me they forgot to switch to "Currently Watching" when the show started airing and they completely forgot to watch the show altogether. And by a lot of people I mean me.

**Comment by erengy** [comment]
The idea sounds nice to my programmer mind, but as with #56, I'm afraid this would make the filter system even more complicated than it already is for the regular user. The direction I'd like to take is to make the system easier to use without dumbing it down, although I haven't been able to find a satisfying solution so far. I don't think this addition helps in that regard, but I may revisit the idea for v1.4 and further releases.

Your second suggestion about creating another default rule makes sense, and I appreciate your honesty about the facts. :)

**Comment by Zyst** [comment]
Fair enough, have a good one mate.

**Comment by erengy** [comment]
Added the new default torrent filter in 7eff799b20043f24f30480aed877513a2446d672.
