### ISSUE TITLE
Kitsu: Cannot add anime from plan to watch to watching

### ISSUE THREAD

**Issue by Coldfryan** [erengy/taiga#760]
Only with Kitsu though, anilist and myanimelist are working fine.
Maybe its changing the general list type of an entry. Can't say for sure.

**Comment by theKAKAN** [comment]
Kitsu is having some problems as well. For example, their search isn't working.  
I'll not be surprised if this issue is related to Kitsu itself.

**Comment by erengy** [comment]
What exactly happens when you try moving an anime to your *Currently Watching* list? Do you see an error message?

**Comment by Coldfryan** [comment]
I'll let you know if I am back from work!

Am Mi., 27. Feb. 2019 um 11:17 Uhr schrieb Eren Okka <
notifications@github.com>:
