### ISSUE TITLE
Taiga only selects 5 most recent torrents when looking up a series

### ISSUE THREAD

**Issue by Toonv5** [erengy/taiga#764]
How can i get Taiga to select the entire series if there's only single episodes available? At the moment it will only find the 5 most recent episodes, even if i add a filter for only one group.

**Comment by skipfie** [comment]
you'll need to search specifically for the series on nyaa, since the RSS feed is only the 50 latest entries

**Comment by Toonv5** [comment]
Unfortunate, but nothing to do about it.

**Comment by purposelycryptic** [comment]
If you ind yourself in this situation more frequently, I'd suggest using ShanaProject - once you've added your private RSS to your torrent client, you can select a single episode from the Group you want in the res you want, hit 'Follow', and, assuming you leave the settings as is, it will send all the episodes to your client.

Definitely beats grabbing releases an episode at a time, especially if you're trying to get multiple 2-cour series at a time.

**Comment by Toonv5** [comment]
Thanks, it's a lot faster than manually finding the magnet link for every torrent.
