### ISSUE TITLE
I can not open the Program in my PC--------------

### ISSUE THREAD

**Issue by AkkuaMagunusu** [erengy/taiga#769]
I can not open the Program in my PC--------------
I already tried to disable Antivirus and even open as ADM, but nothing changes!

**Comment by tophf** [comment]
Use **procmon** or **sysmon** to produce a log file capturing the launch process of Taiga, review it to make sure no personal data exists, then attach it here. There are should be tutorials for these utilities that show how to use them properly, it's not too complicated.

**Comment by AkkuaMagunusu** [comment]
Sorry, I'm not familiar with this tool --- I downloaded Procmon, but I do not know how to proceed!

**Comment by erengy** [comment]
Please see #770 in case it is the same issue.
