### ISSUE TITLE
Add moetube.net to the media provider list

### ISSUE THREAD

**Issue by Chet9999** [erengy/taiga#77]
A new site that streams with in HD, with no ads, and allows free downloads.
The url contains the episode name and number, so it should be able to work if you add it to the media provider list.

Thanks

**Comment by erengy** [comment]
It seems quite nice, but as I emphasized on issue #75:

> Note that the current stance Taiga takes is that it only supports **official** streaming sites.

---

@rr-

![moetube](https://cloud.githubusercontent.com/assets/1078430/5923451/4e8cacbc-a65c-11e4-8861-392c4a249d53.jpg)

**Comment by Wopian** [comment]
Then alternatively let us add our own sites that taiga can detect?
