### ISSUE TITLE
Please just use a 3rd party API to make MAL work again

### ISSUE THREAD

**Issue by DigitalCorgi** [erengy/taiga#771]
I know you've said you don't want to use a 3rd party API to make MAL work again in taiga, but please just do it anyway, every other app and program that interfaces with MAL has done it.  I know you said you didn't like DeNA, but now MAL is owned by a different company, so maybe they're gonna be better.  Please, I don't like routing my MAL list throught kitsu to make it work. please please please do this.

**Comment by Nevalopo** [comment]
I am also here checking in every now and then to see if there are going to be any updates regarding MAL

I don't like using Kitsu to update my MAL entries since it's very slow and inaccruate with their weird point system. One day maybe we will get MAL for Taiga agian :(

**Comment by wopian** [comment]
>inaccruate with their weird point system

You can change from the (horrible) default smiley ratings in your [user settings](https://kitsu.io/settings/profile)

**Comment by Nevalopo** [comment]
> > inaccruate with their weird point system
> 
> You can change from the (horrible) default smiley ratings in your [user settings](https://kitsu.io/settings/profile)

oh had no idea. Thanks!

**Comment by alvahn** [comment]
@wopian thanks

**Comment by glordit** [comment]
It's offically been over one year since MAL was hacked, if the API isn't working by now. It's never going to work.

**Comment by ifonefox** [comment]
@glordit There is still hope.

https://github.com/erengy/taiga/issues/588#issuecomment-497026960

> I am part of the Slack for MyAnimeList and all I can say is Xinil said that the closed betafor the new API is coming soon.

[Blog post by the same user](https://malupdaterosx.moe/2019/05/17/myanimelist-api-update-2/)

Moyitpro wrote MAL Updater OS X, an MAL updater like Taiga, so I don't think they're lying about this knowledge.

**Comment by erengy** [comment]
There's no third-party API that can update your list (see #687). Some developers just traveled back to 2008 in order to keep their applications working.

There won't be any updates until MAL releases their new API, which will [happen sometime in September](https://myanimelist.net/forum/?topicid=1794878) at the earliest.
