### ISSUE TITLE
All saved data gone sometimes if computer crashes

### ISSUE THREAD

**Issue by Eyadish** [erengy/taiga#772]
As Taiga stores the settings in the appdata folder, it (atleast several times to my experience) leads to wiped data sometimes with computer crashes. Often had the issue before when I had computer problems, but as I've solved those, the Taiga haven't been an issue for a long time.

Until today. Was forced to shutdown my computer via the powerbotton, and ALL settings in taiga is gone. When openinging you are greeted with a "Please login to your service" (or what it says) and I have to setup all settings again, that include torrent filters too.

**Comment by taigalover** [comment]
Has happened to me a couple times back when i also had computer problems. So I learned to make a backup of the appdata folder. But now i only make backup of my filters, the rest of the settings i can remember.

**Comment by erengy** [comment]
See https://github.com/erengy/taiga/issues/713#issuecomment-551085763.
