### ISSUE TITLE
i need help 

### ISSUE THREAD

**Issue by 0ANIMEFREAK0** [erengy/taiga#775]
i installed a custom dark theme for win 10 then this happened 

![image](https://user-images.githubusercontent.com/35454710/56083635-73353080-5e49-11e9-82b8-cfb460aebb5d.png)

i thought downloading eagleshadows theme.xml might fix it but i couldn't find the file 
 is there anyway i can fix it without reverting back to my old theme

**Comment by erengy** [comment]
Restarting your computer should fix it. See #398.

**Comment by 0ANIMEFREAK0** [comment]
it worked sorry for the late reply

**Comment by corewwwi** [comment]
do you still have the eagleshadows's theme.xml? that link isn't working anymore.
