### ISSUE TITLE
Taiga doesnt recognize MPVnet

### ISSUE THREAD

**Issue by kempol181** [erengy/taiga#784]

**Comment by erengy** [comment]
It's not supported at the moment (see the list at *Settings → Recognition → Media players* or erengy/anisthesia#1).

A link would be appreciated, because I see multiple projects with that name.

**Comment by asimovitsch** [comment]
Not OP, but I would presume it's [this one](https://github.com/stax76/mpv.net).

**Comment by snow344** [comment]
Bump

**Comment by 0ANIMEFREAK0** [comment]
@erengy do u need to push a whole new update to taiga to include this player?
or can u just update [anisthesia](https://github.com/erengy/anisthesia) and itll pull the file from there
just like it did with [anime-relations](https://github.com/erengy/anime-relations)

i dont know is there any big difference between this 2 players other than some extra gui functionality on mpv.net. I am trying to ditch mpv and switch to mpv.net the thing thats holding me back is there isn't any option to sync taiga with mpv.net. so if isn't too much to ask can u please include mpv.net syncing in the next update of taiga

**Comment by erengy** [comment]
> do u need to push a whole new update to taiga to include this player?

Yes. If you don't want to wait:

1. Download the latest `players.anisthesia` file and place it under `Taiga\data\` directory.
2. Restart Taiga.

Make sure to delete the file after updating Taiga, so that it doesn't override any future updates.

**Comment by Bodyx** [comment]
> > do u need to push a whole new update to taiga to include this player?
> 
> Yes. If you don't want to wait:
> 
> 1. Download the latest `players.anisthesia` file and place it under `Taiga\data\` directory.
> 2. Restart Taiga.
> 
> Make sure to delete the file after updating Taiga, so that it doesn't override any future updates.

Thank you so much for this comment, I'm just a new average end user that knows nothing about github or much of these programs from Github that you devs are making. 

BUT, this worked like a charm! Tyvvvvm :D
