### ISSUE TITLE
Taiga fails to load the nyaa.si rss feed

### ISSUE THREAD

**Issue by Artins90** [erengy/taiga#786]
I have been experiencing a strange issue since yesterday, the torrents tab stays empty when pressing the Check new torrents button or when triggered by the automatic timer.
The rss update seems to work only once every 20-25 tries when pressing the check button repeatedly.
The connectivity to the the rss feed https://nyaa.si/rss?c=1_2&f=0 works fine via Chrome at the first try.
So far I have tried to reinstall Taiga, I have emptied all the cache categories under settings and I have attempted a second install to a different drive to no avail.

I own only 1 PC so I would appreciate if someone could confirm this issue.
Thank you for your time.

Version 1.3.1
Windows 1903

**Comment by Mystixc** [comment]
> I own only 1 PC so I would appreciate if someone could confirm this issue.

Yeah, I just tried doing this and it doesn't seem to work at the first try.

**Comment by serjflint** [comment]
You can try to use a proxy in the advanced settings. It worked for me

**Comment by Artins90** [comment]
I think this issue can be closed, it resolved itself after a couple o days.
I don't think it was a connectivity problem since I was able to open the nyaa rss feed using any other rss software other than taiga while the issue was ongoing.
