### ISSUE TITLE
Add to list from Season does not work

### ISSUE THREAD

**Issue by Bu11etmagnet** [erengy/taiga#789]
This is what I did:
1. Created a  Kitsu account and imported MAL export.
2. Set Kitsu as active service and metadata provider
3. Filled in Kitsu account details
4. Selected Spring 2019
5. Right-click on Carole+Tuesday and selected Add to list > Currently watching
6. "Please set up your account before adding anime to your list" appeared in the status bar.

**Comment by erengy** [comment]
Set up your Profile URL in [Kitsu settings](https://kitsu.io/settings/profile). Then restart Taiga and synchronize.

**Comment by Bu11etmagnet** [comment]
That did it, thanks.

**Comment by MMDF** [comment]
I experienced the same problem and had to search through issues to find this. Can you add a pop up asking the user to set their profile URL whenever it is needed?

**Comment by erengy** [comment]
@MMDF Added a note in 2abada5ef3fb34353ea18419f746b568a5fb567e that says "make sure to set your profile URL".
