### ISSUE TITLE
Can you add Setting Export option like Jdownloader?

### ISSUE THREAD

**Issue by movibeast** [erengy/taiga#793]
HI, So as I can see in latest Taiga there is no option to export the setting. It will be great if you will add it. Other things I really liked it. It it like a charm.

thanks

**Comment by erengy** [comment]
Hi there,

All settings are stored in `Taiga\data\settings.xml`. You can simply copy that file to "export" your settings. If you'd like to export everything including your history, just copy the entire `Taiga\data\` directory.

It's also possible to only export your torrent filters. To do that, go to *Settings → Torrents → Filters* page and click the *Export* button.
