### ISSUE TITLE
Option to set first episode for sequel seasons

### ISSUE THREAD

**Issue by Lazzil** [erengy/taiga#794]
I'm having issues using Taiga with the second season of Boku no Hero Academy. As soon as I started S2 EP1, it misread the file and mistook it for S2 EP14 due to the way it's named in the torrent. S1 has 13 episodes, and S2 has 26, but the files are listed as 1-39 in the torrent I downloaded for it.

I know this is probably not a good idea to automate since there might be some inconsistencies in how episodes are tracked and labeled, but would you consider adding an option to manually set the first episode of a season for a designated series and then allow Taiga to readjust the position accordingly? It'd be a lot less frustrating than having to rename the files (plus the issue of keeping them active on torrent clients; I like to seed back when I can).

**Comment by erengy** [comment]
This is already handled with [erengy/anime-relations](https://github.com/erengy/anime-relations).

Relevant rules for *Boku no Hero Academia*:

```
# Boku no Hero Academia -> ~ 2nd Season
- 31964|11469|21459:14-38 -> 33486|12268|21856:1-25!
# Boku no Hero Academia 2nd Season -> ~: Hero Note
- 33486|12268|21856:0 -> 35262|13313|99308:1
# Boku no Hero Academia -> ~ 3rd Season
- 31964|11469|21459:39-63 -> 36456|13881|100166:1-25!
```
