### ISSUE TITLE
Couldn't detect files of a recent anime

### ISSUE THREAD

**Issue by iZN1337** [erengy/taiga#798]
So I've got Ace of Diamond or Diamond no Ace's episode. It's not detecting them at all and I have to manually increment the episodes which is something I use this to avoid.

The anime I'm talking about: [Diamond no Ace Act-II](https://anilist.co/anime/105749/Diamond-no-Ace-Act-II/). (I use _AniList_ synced with Taiga)
And I'm downloading the episode which names it "Ace of the Diamond act II" and this is the full name of an episode: `[Commie] Ace of the Diamond act II - 12 [DC83FEC4].mkv`
Taiga Version: 1.3.1

Now I've tried manually entering the name in the alternative titles and also have tried checking "Use the first alternative title to search for torrent" which still doesn't fix the issue. It can't be the folder because I keep my anime in one folder, and it has already selected the right one. There are no fansub group preferences meaning it's set to "None" by default and yet it doesn't work. Tried resyncing again and again too. 

I thought I'd finally post and I apologize if a solution was already discussed here, I couldn't find one for now. Please help me out and great work on Taiga by the way as my other anime are updated without any issues.

**Comment by iZN1337** [comment]
OK now it detects it when I check "Now playing" but the episodes are still not detected.

![Taiga_2019-06-27_13-25-02](https://user-images.githubusercontent.com/5579012/60250176-8e0f3100-98df-11e9-9121-c9f2c62a9053.png)

![Taiga_2019-06-27_13-26-15](https://user-images.githubusercontent.com/5579012/60250205-9e271080-98df-11e9-8592-0edfb7d0255c.png)

**Comment by erengy** [comment]
Just tried it out and Taiga correctly identified that file as *Diamond no Ace Act II*. You don't need to set any alternative titles in this case, because Taiga already gets the relevant one from AniList.

If this is still an issue, try removing any alternative titles you set for this series and *Diamond no Ace: Second Season*. That's the most likely reason Taiga is mixing them up for you.
