### ISSUE TITLE
Taiga replaces Start Date and Finish Dates when I synchronize them in bullk...

### ISSUE THREAD

**Issue by moreorlessnotarealproblem2** [erengy/taiga#800]
...on certain items in my Currently watching, Finished and Dropped lists. The date started and finished incorrectly are set to the current date. I'm aware this can be done in bulk manually. But it's really annoying if it just makes up stuff or outright replaces already put-in info. Is there a way to stop this? I'm afraid synchronizing things in the future will randomly give anime wrong dates. 

This is while syncing to Anilist.  I'm not sure if this is a bug in Taiga itself.

**Comment by erengy** [comment]
Taiga automatically sets start and finish dates when you update the first or the last episode of a series. But it never overwrites an existing date, unless you do it manually. If you think there's a bug in the latter case, please provide an example so that I can reproduce the issue.
