### ISSUE TITLE
Solution for MAL's api problem

### ISSUE THREAD

**Issue by lukaursic** [erengy/taiga#802]
Create account on Kitsu and sync Taiga to it. Then go to kitsu.io -> Library -> Manage Library -> Export Library -> Setup Export to MyAnimeList Account -> then log in with your mal credentials. That should be it. If you are new to Kitsu, you should export your MAL list and import it to Kitsu.

Now if you change something in Taiga, Kitsu and MAL should update the changes.

**Comment by ShaunV2** [comment]
Not really a solution and MAL has been known to cause issues with Kitsu's MAL sync, the feature isn't reliable anyways since it is known to randomly get disabled without you being notified about it.

This solution doesn't help Taiga at all to begin with.

**Comment by erengy** [comment]
This is indeed a workaround to keep your MAL account updated, and it's mentioned at Taiga's FAQ page.
