### ISSUE TITLE
Extreme lag and unresponsiveness

### ISSUE THREAD

**Issue by LHJ** [erengy/taiga#804]
I don't know what caused this and can't really investigate further (as I fixed it by reinstalling Taiga) but Taiga had, since a few months at the least, been suffering constant, extreme delays in responding to input.  
For example: 

- Tabbing to Taiga would usually do nothing visually, and play the Windows "ding" BUT bring the window to the front (meaning alt-tabbing would show Taiga as being the window in focus, while it being behind whatever other windows you were trying to bring it in front of).  
- Pressing any button, e.g. "Check new torrents" or "Synchronize list", would show as depressed after 1-2 seconds and then perform the action. 

I checked to see if someone else had reported the same issue but the closest I saw was some other issue where the persons computer was slowing down, this seemed contained to Taiga.  
I was on whatever the latest version is (updated not too long ago I felt like) and I would occationally check for updates in the hopes that it might fix it.  

As mentioned at the beginning this went away when I finally uninstalled and reinstalled Taiga yesterday, I don't know what changed but considering that I've been using it for a long (maybe 4-5 years?) time and never reinstalled it maybe that's why? 
(You could probably close this as unreproducible, I'm just thinking if someone else comes across the same problem and searches they might find this and contribute to finding the cause)

**Comment by erengy** [comment]
It sounds like Taiga's main thread was somehow too busy to manage the UI. We could try a couple of things if the issue was reproducible, but as you say, that is no longer the case.

I'm glad a reinstall worked out for you, and thanks for the information!
