### ISSUE TITLE
HTTP error #56: Failure when receiving data from peer

### ISSUE THREAD

**Issue by KimoriWasTaken** [erengy/taiga#806]
I'm trying to setup my nordvpn proxy in Taiga but I keep getting error #56 when I use `Proxy Host: de525.nordvpn.com` , or when I put `socks5:de525.nordvpn.com` in there it gives me error #5.
Other addresses don't work either, [NordVPN IP picker](https://nordvpn.com/de/servers/tools/)

How exactly do you set up a proxy in Taiga?

**Comment by erengy** [comment]
#338 could help.
