### ISSUE TITLE
How to choose resolution 480p?

### ISSUE THREAD

**Issue by vajahiki** [erengy/taiga#809]
I can't figure out how to use filter on Taiga. I try to make a filter to choose 480p resolution instead of 1080p and 720p, at the end none 480p are being pick by the filter. Please guide me...

**Comment by Venipa** [comment]
try this [Video](https://i.mavis.moe/f/xZCzoC8vob/2019-08-02-19-22-09.webm)

**Comment by erengy** [comment]
Depends on what exactly you want. If you want nothing but 480p, you can create a filter such as:

    Episode video resolution | is not | 480p -> Discard

This will discard all releases in other resolutions, and then your other filters will do the selecting.
