### ISSUE TITLE
[Suggestion] Torrent RSS with User-added Titles

### ISSUE THREAD

**Issue by akaUriel** [erengy/taiga#81]
I've edited a title for an ongoing series via the right-click > edit > Titles function. While this works for recognition of files on my local machine, it still does not pick up releases on RSS using the updated title. 

I think it would be a convenient update.

**Comment by erengy** [comment]
Filename recognition works just the same whether it's a torrent file in the RSS feed or a local file on your computer. In other words, alternative titles are used in both places.

Are you sure that the relevant torrents are not discarded by some filter? Alternatively, the filenames in question may have a slightly different name than your alternative title. If that's not the case, could you write down the alternative title you've added, and an example filename that doesn't get recognized on the RSS feed?

**Comment by akaUriel** [comment]
I've tried re-searching for torrents with filters disabled and same results.
Current example is Dog Days" from HorribleSubs.

So the alternative title is set as Dog Days S3, as HS releases them.
This picks up the file when saved in my local folder and shows it available for playing, but not in RSS for downloading.
