### ISSUE TITLE
Saving torrent filters to different file

### ISSUE THREAD

**Issue by asakurato** [erengy/taiga#812]
I just randomly lost my data when I turned on my computer today. I have read previous issues where Taiga might not be able to save settings on exit and when launched, it overwrote old settings file with new one.

My suggestion is, why not auto save torrent filters to different file so we at least don't lose filters when this happens? And either have ability to manually save filters to those file with let's say, a button or CTRL+S or Taiga could auto save it when filters get changed (so when overwrite happens, it will only overwrite settings and not filters).

Another side note, when I looked at data folder in Appdata, my username folder was still there, with it's history and all. Can I somehow at least restore that?

Edit: Seems like after posting this, my history came back by itself.

**Comment by asakurato** [comment]
it happened again :(

**Comment by erengy** [comment]
See https://github.com/erengy/taiga/issues/713#issuecomment-551085763.

Saving *some* settings to a different file wouldn't really help. Same issue could happen to *that* file too.
