### ISSUE TITLE
FireFox Quantum (68.0.2 (64-bit)) Not Detecting PLEX web app

### ISSUE THREAD

**Issue by MrPiethon** [erengy/taiga#814]
It works perfectly fine with Chrome.

I have the following addons installed:
- Cookie AutoDelete
- Decentraleyes
- uBlock Origin

current plex webapp url: https://app.plex.tv/desktop

I found the earlier references with firefox not working, but it does not seem to be applicable to the latest version.

**Comment by erengy** [comment]
See https://github.com/erengy/taiga/issues/580#issuecomment-392729398.
