### ISSUE TITLE
[TR] Anidb Support?

### ISSUE THREAD

**Issue by cartals** [erengy/taiga#817]
TR: @erengy Abi 4 yıl önce biri yazmışta hiç mi şansımız yok ya anidb severler için :( inşallah bir ara müsait olduğunda ekleyebilirsin olmazsa da canın sağolsun :)
ENG: Hi, i read request which is 4 years ago, i wonder is there have any possibility for add anidb ?

**Comment by erengy** [comment]
Not going to happen until AniDB improves their HTTP API. See #188 for the previous discussion.

(AniDB doğru düzgün bir HTTP API'ı sunana dek olmaz bu iş. Bildiğim kadarıyla da buna sıcak bakmıyorlar.)
