### ISSUE TITLE
Suggestion: Ability to pin anime to top of list in "Plan to watch"

### ISSUE THREAD

**Issue by NotShige** [erengy/taiga#820]
I was just browsing on my "Plan to watch" list when I saw a particular anime that I should've watched months ago. I thought that it would be a REALLY great feature to pin shows to the top of the list so that I would be reminded constantly to watch a particular show or particular shows ASAP.

A color-coded priority system would also be great too, where shows would have a red mark on them to signify that you should watch this ASAP, yellow where it might signify that you may want to watch this, and green where it's not really that important to watch it.

Great program as always! 👍

**Comment by erengy** [comment]
Closing this issue since it's basically the same request as #247.
