### ISSUE TITLE
Kitsu list syncing error?

### ISSUE THREAD

**Issue by Rainee4563** [erengy/taiga#821]
Hey guys I got an error here whenever I try to sync my list with kitsu it gets an error 

"Update failed: Kitsu returned an error: "cannot exceed length of media: progress - cannot exceed length of media" any idea what that means

https://i.imgur.com/ThgoWTs.png

**Comment by erengy** [comment]
The error message says that you're trying to update your progress to a bigger number than the total episode count of an anime, and that Kitsu doesn't allow it.

The anime in question is at the bottom of your update queue, if you scroll down that list in History page. Should work if you try synchronizing again after deleting that line.

If you're unsure of what to delete, post a screenshot of the bottom of your queue, or send me your `Taiga\data\user\{username}\history.xml` file and I'll let you know.

**Comment by Rainee4563** [comment]
Thanks I managed to fix it Keep up the good work on taiga
