### ISSUE TITLE
Torrents only looks for latest episode

### ISSUE THREAD

**Issue by DJScias** [erengy/taiga#822]
Hello there,

This is an issue I've been having for a while and while I can live with it.. It does make me have to jump through a few hoops.

Let's go with `Dumbbel Nan Kilo Moteru?` as the example anime.

There's currently 10 episodes out and I have 6 of them in my folder:
![image](https://user-images.githubusercontent.com/439655/64474303-c3ec5380-d173-11e9-8c1b-938fffa81c60.png)

Now my routine is that every so often I open Taiga and I click Torrents to get all my missing torrents. This works fine, but it only grabs the "last released one" as seen here:
![image](https://user-images.githubusercontent.com/439655/64474317-e5e5d600-d173-11e9-88cf-4886ce95ab4f.png)

The only way I can get it to display all my missing torrents, as it once used to do by default when I clicked "Torrents" I have to search on it specifically:
![image](https://user-images.githubusercontent.com/439655/64474323-fc8c2d00-d173-11e9-8108-ee70c43c2408.png)
![image](https://user-images.githubusercontent.com/439655/64474326-0150e100-d174-11e9-8eef-fbde2e38747f.png)

At first I thought it was my filters, but I disabled all my custom ones one by one and none of them gave a change. The following filters are in effect:
![image](https://user-images.githubusercontent.com/439655/64474334-1af22880-d174-11e9-81d2-ffe6a6ad1513.png)

The custom ones are:
- Prefer high-resolution files: I made this look for 1080p instead of 720p+
- Discard low-resolution files: I made this check for less than or equal to 720p
- [Fansub] HorribleSubs Anime: Discard + Deactivate torrents not by the HorribleSubs fansub group

All the other ones, to my knowledge (as they're far too advanced for me) are default.

Is there any way I can get the normal "Torrents" routine, where I just click on it without having to do a specific anime search, to once more give me all the missing episodes except the last one?

Thanks in advance.

**Comment by erengy** [comment]
Hi, please see #764, #694, #571, #380 and #250 for similar issues. Basically, it's not related to your filters, it's just how RSS feeds work. The workarounds described in previous discussions might help you.

**Comment by DJScias** [comment]
Hello there,

Thank you for the reply. I've started using the custom RSS feed offered by ShanaProject as suggested in #764. With this it gets both the ones I've missed and the latest ones I'm following which is exactly what my use-case required.

This can probably be locked unless you feel differently about it.
