### ISSUE TITLE
anilist returned an error invalid token

### ISSUE THREAD

**Issue by guft** [erengy/taiga#826]
This issue appears to be back (see: #649 )

Windows 7 64bit
Taiga 1.3.1
Anilist account info on request

Error occurs trying to sync local data to Anilist. According to the previous issue, this was caused by a problem with requesting anime studios from anilist.

**Comment by erengy** [comment]
Try re-authorizing from *Settings → Services → AniList*. It's probably because your access token has expired.

**Comment by Phr33d0m** [comment]
Having same problem as @guft I tried re-authorizing and I can confirm that it solves the issue. Thanks @erengy !

**Comment by guft** [comment]
That fixed it.
