### ISSUE TITLE
Not showing downloaded episodes on completed tab

### ISSUE THREAD

**Issue by GibiDroidZ** [erengy/taiga#827]
#534 #753 
Some issues may be intermittent. I'm currently using v1.3.1 and I'm still encountering issues with missing downloaded episodes not being shown when you hover on the **completed** and **dropped** tabs. It shows on others tabs however. 
Not sure if helpful but I notice it happens on tabs where there's no + or - when you hover on the progress bar.

**Comment by erengy** [comment]
#753 was fixed long after v1.3.1's release. The fix is going to be available in Taiga's next version.
