### ISSUE TITLE
Please add auto-sync/detection support for MPV.Net?

### ISSUE THREAD

**Issue by Shopkeeper26** [erengy/taiga#829]
I see an issue was closed with this before but taiga still doesn't have support for mpv.net.

Basically it's a more windows friendly version of MPV with a gui added. I'd like to request auto-sync list support with MPV.Net

here is the github page for said project. https://github.com/stax76/mpv.net

**Comment by kiriya-aoi** [comment]
https://github.com/erengy/taiga/issues/784
