### ISSUE TITLE
Gets confused between Hunter x Hunter (2011) and 1999

### ISSUE THREAD

**Issue by Qwerty-Space** [erengy/taiga#830]
I can't get it to recognise it as Hunter x Hunter (2011)

**Comment by erengy** [comment]
Try adding `Hunter x Hunter` as an alternative title to the new series (actual solution depends on the filenames).

**Comment by Qwerty-Space** [comment]
Ah I didn't realise that was possible.
However, I have set the folder for it, yet it still doesn't track the episodes in that folder.

**Comment by VoidsShadow** [comment]
This issue should be labeled as Closed as a solution was found.

**Comment by erengy** [comment]
Setting the anime folder simply tells Taiga where to look first while scanning for episodes. It doesn't directly affect the recognition process.
