### ISSUE TITLE
Opera GX Support

### ISSUE THREAD

**Issue by nattadasu** [erengy/taiga#832]
Opera have another version of their browser, [Opera GX](https://www.opera.com/id/gx), which Taiga seems didn't support yet. It would be nice if Taiga can recognize what I currently watch on Opera GX.

**Comment by Davoleo** [comment]
I'm using Opera GX right now and Taiga recognises yt episodes just fine 🤔

**Comment by nattadasu** [comment]
....hmmm, I'm not sure as I recently use Chrome for daily browser, but might they (Opera team) made a change to the browser? ._.
But yep, when I open the issue, Taiga seems can't recognize the browser with what I currently watching yet.

**Comment by erengy** [comment]
Apparently https://github.com/erengy/anisthesia/commit/d782df25d50b10fcd2078c2c340eaf747a6da59e works for Opera GX too, so there's no need to specifically add support for Opera GX.

Taiga|Opera & Opera GX detection
---|:---:
v1.3.1|❌
[Latest build](https://taiga.moe/latest.html)|✔️
`develop` branch|✔️
