### ISSUE TITLE
Taiga partially loses MAL's list

### ISSUE THREAD

**Issue by DarkElve** [erengy/taiga#836]
Seems there are some problems with big lists. Out of my 3526 entries, Taiga only shows 2526.
I've dumped JSON, and it seems there's everything. Though 1001 "node" entries come in first and third, 1000 in second and 528 in the last one (except two first with authentification).
After parsing there's a 1000 "\<anime\>" entries missing in an "anime.xml" in "data\user\DarkElve@myanimelist" and some entries missing in lists in application.

**Comment by erengy** [comment]
Looks like nodes from the first page were being discarded. Could you try again with e76feb8e6fc98453ed65323df0b7fa82c8937c52?

**Comment by DarkElve** [comment]
Yes, now it works fine. Thanks.
