### ISSUE TITLE
Additional Legal Streaming Support

### ISSUE THREAD

**Issue by chikorita157** [erengy/taiga#84]
This list on Reddit shows all the legal streaming sites:
http://www.reddit.com/r/anime/wiki/legal_streams_/_downloads

I have recently added AnimeSols and Anime on Demand (aka Animax UK) support to my program as they provide the episode number in the page title. I thought this list would be helpful in improving the streaming recognition in Taiga, so I decided to share it.

**Comment by erengy** [comment]
Thanks. Anime Sols is pretty easy to add, but as far as I can see, Animax UK displays the episode number *only if* there's no episode title, which doesn't seem to be a common occurrence.

**Comment by chikorita157** [comment]
Yep, I noticed that when I looked at another episode. It makes me wonder why Animax UK is very inconsistent with episode numbers and they don't even show it in the DOM either...

**Comment by erengy** [comment]
Added support for Anime Sols in 799c21f93f497aba537e9759190202a23ddef525.
