### ISSUE TITLE
Detect Alternative Anime Sources?

### ISSUE THREAD

**Issue by APerson4645** [erengy/taiga#840]
Taiga detects in the browser from places like VRV, YouTube, CrunchyRoll, etc., but I see no option for stuff like 9anime or other sites. I was wondering if there was some way it could be integrated into Taiga? Or some option for users to add their own anime sites and define the fields?

I don't see why'd there be something about using these alternative methods of streaming considering Taiga will already actively search for and download torrents for you.

**Comment by inexplicabro** [comment]
Torrents are in a gray area in terms of legality. Illegal streaming sites like kissanime, gogoanime, etc. will not get support.
