### ISSUE TITLE
Taiga doesn't recognise Crunchyroll

### ISSUE THREAD

**Issue by UMRPL** [erengy/taiga#843]
I have problem with Crunchyroll (both app and browser) not being recognised.

MPC-HC works fine for me. 
Youtube also isn't being recognised.

Browsers I use:
Opera and Opera GX

**Comment by erengy** [comment]
This is an issue with Opera rather than Crunchyroll. See https://github.com/erengy/taiga/issues/698#issuecomment-431768228. Was fixed in the [latest build](https://taiga.moe/latest.html).
