### ISSUE TITLE
VVVVID.it support

### ISSUE THREAD

**Issue by Davoleo** [erengy/taiga#855]
I'd like to request support for this website https://vvvvid.it/
It's an official Italian sub/dub streaming service

The name of the series can be found in the url, while the episode number is displayed in the body of the document
Example show name: ID:INVADED
Example show link: https://www.vvvvid.it/show/989/id-invaded/1107/541525/jigsawed&r

this is a pretty famous service and it's licensed a lot of shows that you can only watch in streaming from there, hence the reason of my request

**Comment by erengy** [comment]
I couldn't access the website due to region restriction. But from what I can see, page titles are in `{Episode Title} - VVVVID` format. Taiga extracts the anime title and the episode number from the page title, so I'm afraid VVVVID cannot be supported.

**Comment by Davoleo** [comment]
that's unfortunate, thanks for looking into it though
