### ISSUE TITLE
Taiga removing animes on my list when syncing

### ISSUE THREAD

**Issue by mastereverything** [erengy/taiga#859]
syncing with anilist is removing titles from taiga's list instead of adding them to anilist. I have only noticed this with ID:Invaded so far

**Comment by darkash** [comment]
> syncing with anilist is removing titles from taiga's list instead of adding them to anilist. I have only noticed this with ID:Invaded so far

it's probably the anime is merged on anilist, I noticed so of it is missing on my list, but it turns out it's merged to the other related listing

you should check yours
