### ISSUE TITLE
settings.xml is invalid xml

### ISSUE THREAD

**Issue by Bu11etmagnet** [erengy/taiga#861]
Trying to open settings.xml with notepad++ (with XML plugin) produces the following error dialog:
```
---------------------------
XML Tools plugin
---------------------------
XML Parsing error at line 182: 

xmlParseCharRef: invalid xmlChar value 3
```
Line 182 contains the following:
```
		<mirc enabled="0" multiserver="0" useaction="1" mode="1" channels="#kitsu, #myanimelist, #taiga" format="&#03;04$if($greater(%episode%,%watched%),Watching,Rewatching):&#03; %title%$if(%episode%, &#03;03%episode%$if(%total%,/%total%))&#03; $if(%score%,&#03;14[Score: %score%]&#03;) &#03;12%animeurl%" service="mIRC" />
```
I'm sure this doesn't affect Taiga itself, but it would be nice if other tools won't complain about an XML file written by Taiga.

**Comment by erengy** [comment]
It's a control character for [mIRC color codes](https://www.mirc.com/colors.html). [Apparently](https://en.wikipedia.org/wiki/Valid_characters_in_XML) XML 1.1 allows it, whereas XML 1.0 does not.

Not sure if I should do something here, but thanks for letting me know. See also https://github.com/erengy/taiga/issues/842#issuecomment-571712192.

**Comment by erengy** [comment]
Closing this so that we have a single issue for XML files (#842).
