### ISSUE TITLE
Add to list does not work with Kitsu

### ISSUE THREAD

**Issue by MrPiethon** [erengy/taiga#862]
Account is already set up with Kitsu and updates everything accordingly. When trying to add an anime through taiga, it does not add the anime. It just displays the message "please set up your account before adding anime to your list"

**Comment by erengy** [comment]
Please see #789, #740 and #704 for the same issue.

> 1. Set up your Profile URL in Kitsu settings: https://kitsu.io/settings/profile
> 2. Restart Taiga and synchronize.

**Comment by wopian** [comment]
The error message should probaby be made for explicit to avoid these issues popping up. I.e, telling the user if their account doesn't have a Profile URL set.
