### ISSUE TITLE
Can't update to the nightly build to fix an issue

### ISSUE THREAD

**Issue by TKoBuquicious** [erengy/taiga#866]
I am using Opera GX and taiga doesn't recognize anything I watch on VRV or other streaming sites so I tried to update to the latest nightly version by replacing the .exe in the install folder because that one apparently recognizes it and has a bunch of other fixes, but everything stays the same inside taiga. The version number (1.3.1), the fact it can't recognize Opera GX, everything. I don't know what exact information might be relevant so if you need anything specific, let me know. 

Btw, will there be a new regular release any time soon since the last one was in 2018?

**Comment by TKoBuquicious** [comment]
I did some testing and apparently it does now recognize it, but it seems to have issues recognizing stuff on the other monitor.

**Comment by levirod** [comment]
what have you done? I'm with same issue
