### ISSUE TITLE
Not yer aired animes are finished

### ISSUE THREAD

**Issue by Venipa** [erengy/taiga#867]
![image](https://user-images.githubusercontent.com/17952364/80807287-0cea8f80-8bbd-11ea-8c34-2c6773a2c575.png)

**Comment by wopian** [comment]
I'm not seeing anything wrong in the screenshot. Re:Zero 2 doesn't air until July 2020 (it was postponed from an April release due to COVID-19).

**Comment by erengy** [comment]
That section shows anime in your plan-to-watch list that has finished airing in the past 7 days.

It's probably because the service you're using previously had an end date for the series. This issue (#549) was fixed in 5514c7f3f76e2e185bf0ec84ffea41f06b312289, it's going to be in the next update.
