### ISSUE TITLE
[Feature request] auto rename badly named anime

### ISSUE THREAD

**Issue by eslamsidereel** [erengy/taiga#869]
It would be great if auto renaming could be implemented into taiga. I used filebot a couple of times but the biggest problem is that it costs a lot.
I hope you could consider implementing this feature.

**Comment by wopian** [comment]
Microsoft has a first-party replacement for Filebot in PowerToys

https://github.com/microsoft/PowerToys
https://github.com/microsoft/PowerToys/blob/master/src/modules/powerrename/README.md

**Comment by eslamsidereel** [comment]
Sorry for the late reply. I tried PowerToys and it's very good I liked it. I also found this software "Tiny Media Manager". It renames the anime after matching it with ANIBD. 
Thanks
