### ISSUE TITLE
Can't figure out how to automatically download anime

### ISSUE THREAD

**Issue by Qewar** [erengy/taiga#871]
I'm managing to filter the episodes I want to download in the torrents page but the episodes just won't get downloaded, not sure what I'm missing. I'm using HorribleSubs 1080p RSS.

![image](https://user-images.githubusercontent.com/50082459/82089583-c6804f00-96eb-11ea-9060-7d477317f8a7.png)

Think I got it, nevermind.

**Comment by inexplicabro** [comment]
> I'm managing to filter the episodes I want to download in the torrents page
If filters work and you find the episodes you want to download, at least one entry should be checked in the downloads screen, but I don't see anything that's checked in your screenshot.

Anyway if you want faster support come on over to the discord server.
