### ISSUE TITLE
Manually updating Progress

### ISSUE THREAD

**Issue by darkred3** [erengy/taiga#875]
When manually updating Progress for an anime by pressing the + button a number of times in quick succession the update will fail. More precisely: Only the first + will be registered on MAL while every further increase will be ignored. Taiga registers it correctly tho, both on the Progress bar and the History tab. history.xml also saves normally.

Version: 1.4.0-alpha

**Comment by paulo27ms** [comment]
I suggest adding a queue system to Taiga. I encountered this issue with moving a lot of titles between lists. Taiga simply tries to send the updates too fast and MAL will deny most of them.
