### ISSUE TITLE
Odd sorting behavior

### ISSUE THREAD

**Issue by paulo27ms** [erengy/taiga#879]
Using a build from May 29th.
I believe I saw a commit about some sorting changes and it seems like something did change because sorting is a bit messy.

Sorting by title (once) and then by season (once) seems to return this at the bottom of the list.
![image](https://user-images.githubusercontent.com/13546823/83342024-f2055b00-a2e1-11ea-8df8-516ca52df934.png)

This is the top.
![image](https://user-images.githubusercontent.com/13546823/83342027-02b5d100-a2e2-11ea-9062-6977355e2431.png)

It stays fine until here.
![image](https://user-images.githubusercontent.com/13546823/83342032-16613780-a2e2-11ea-9169-90b4bed667ba.png)

At first I thought I was seeing some odd sorting related to sorting by last updated but it seems like sorting in general is pretty wack as no combination of sorting is mixing well together.

Also, if I keep sorting by season (just clicking the column multiple times) it actually returns 4 sets of results instead of the expected 2.
I want to mention something else related to sorting but maybe it's being caused by this issue so I'll save it for later.

**Comment by erengy** [comment]
I couldn't reproduce this issue, but it might be fixed with 5337c5774cbd97da38a25cba38e32ffe9da7813e.

**Comment by paulo27ms** [comment]
Seems alright and the other odd behavior I was thinking about also seems fixed, guess it was the issue with the sorting giving 4 different results instead of 2 that was confusing me.
