### ISSUE TITLE
Status not correctly identified in list search

### ISSUE THREAD

**Issue by paulo27ms** [erengy/taiga#881]
I think in the previous version I had compiled it'd show Currently watching and Plan to watch correctly but On hold would show as Dropped, now it seems they all show as Plan to watch. 
Also, the counts are off.

![image](https://user-images.githubusercontent.com/13546823/83359856-f595f200-a374-11ea-8c90-a4e9250fc8b5.png)

**Comment by paulo27ms** [comment]
After fixing the issue with the outdated theme, this seems to be working correctly again.
I'm not sure if the counter is meant to be there but if the count isn't a thing and was merely caused by the bug then this can closed.

![image](https://user-images.githubusercontent.com/13546823/83364203-8d0c3c80-a397-11ea-9ce2-fe15f9a309ac.png)

**Comment by erengy** [comment]
Should be fixed with 88c9e556db141dd3b0c7d3c6d292bd0e527a1184, though I couldn't fully reproduce the issue.

**Comment by paulo27ms** [comment]
Seems to be it. I'll report back if it breaks again.

![image](https://user-images.githubusercontent.com/13546823/83384983-44c53c80-a3e0-11ea-9606-c4e4428daaea.png)
