### ISSUE TITLE
Anime folders not being saved in all cases

### ISSUE THREAD

**Issue by paulo27ms** [erengy/taiga#886]
There seems to be some inconsistency in saving the folders in anime settings and I'm finding it really hard to troubleshoot currently.

In some cases Taiga just straight up never associates a folder to the anime, even when it finds episodes, and in those cases if you try to open the anime folder it'll tell you it didn't find the folder but if you press No on setting a folder manually, it'll open the folder where the episodes are anyway, it'll still not save the folder location in the settings. If you press Yes and then cancel it also opens the correct folder.
Doing a full scan or a single anime scan does nothing for this.

In my current testing it happened the most with anime in my HDD, as it was populating the list with the anime it was detecting, half the anime didn't get a folder saved even though when I went to open the folder through Taiga it opened the folder just fine.

This also happens outside of the HDD though but again, the odd behavior is making it hard to troubleshoot. I have had cases where I downloaded anime through Taiga (meaning Taiga created the folder where it'd save the episodes) and it still didn't detect the folder correctly.

I'm not entirely sure if this is related to the folder names, examples:
Space Dandy S1 [BD 1280x720 h264 AAC] - Doesn't detect
Space Dandy S2 [BD 1280x720 h264 AAC] - Detects
Jormungand [Season 1] (BD 1280x720) - Detects
Jormungand - Perfect Order [Season 2] (BD 1280x720) - Doesn't detect
I can give more examples if needed.

When restarting Taiga the anime with no folder will not have anything recognized until I do a full scan again.

This does seem to be entirely on an anime-per-anime basis because even if I remove all the folders from every anime, the exact same anime will recognize the correct folder every time.

**Comment by erengy** [comment]
Just to be sure, are you using a recent build that includes 88f0af89355aa5b7f5145ff8b2945ae41004e054? Before that, anime folders were not being saved unless other settings were modified too.

P.S. Not related to this issue, but do you think Taiga is now in a usable state with MyAnimeList? I imagine you've been using the alpha version for a while now. I feel like it's ready for a beta release, but wanted to hear a second opinion.

**Comment by paulo27ms** [comment]
I was using a build from the 1st of June so I believe that was included. 
I did recompile just now and deleted my settings files along with that and the problem persists.
This is something I believe was an issue even a couple years ago but my memory could be tricking me.

I have been using the alpha for around 3 weeks but overall it seems pretty good to me, all the issues I found related to the new API are fixed and Taiga's behavior is as I remember it from the time of the old API. 
In terms of stability with the API it has been more than ready I'd say, only real issue I had initially compared to the old API was moving a lot of anime at once between lists but https://github.com/erengy/taiga/commit/d34fc720379482c371940a56a61df204b252d513 has fixed that as well in the meantime.

**Comment by erengy** [comment]
> In some cases Taiga just straight up never associates a folder to the anime, even when it finds episodes

Taiga doesn't set the anime folder based on what's inside (more specifically, doesn't do it while scanning). This is the same issue as #352, although the perspective is different.

> in those cases if you try to open the anime folder it'll tell you it didn't find the folder but if you press No on setting a folder manually, it'll open the folder where the episodes are anyway

In that case the anime folder is unknown but Taiga opens the path of the next episode (which may or may not be the same location). You can confirm this by checking if a file is being selected in the directory. The behavior you described is unintentional though, so I'll fix that shortly.

**Comment by paulo27ms** [comment]
With these changes, was Taiga still not meant to set an anime folder? I don't see a reason for it not to.
Now when I try to open the folder, even without a folder set, it opens the folder with the first episode without a prompt. This is 99.9% of the cases I'm sure. I don't see a particular reason for Taiga to not save the folder with the first/next episode if it can't do it automatically, not saving that folder just means you have to do a full scan every time you open Taiga and saving it would just mean that in that really small number of cases you'd have to do a full scan anyway, overall it'd be a lot more beneficial.
By the way, even anime with folder set highlight an episode when I open their folder.
