### ISSUE TITLE
Unidentified anime without episode getting filtered by episode number filter

### ISSUE THREAD

**Issue by paulo27ms** [erengy/taiga#889]
Potentially intended but

![image](https://user-images.githubusercontent.com/13546823/84298367-ecf8a500-ab46-11ea-878b-33e7b6d6cf0b.png)

gets filtered by

![image](https://user-images.githubusercontent.com/13546823/84298265-bde23380-ab46-11ea-842f-72a441afbd95.png)

issue seems to centered around the fact that the "episode" for these torrents is the same as the %watched% parameter for unidentified anime as

![image](https://user-images.githubusercontent.com/13546823/84300170-d738af00-ab49-11ea-8f8f-2a97dbcb2db2.png)

does not filter those torrents.

I'd also potentially suggest a %unknown% value for the Episode number element. This would enable users to filter out these torrents with the following

![image](https://user-images.githubusercontent.com/13546823/84300672-7a89c400-ab4a-11ea-965c-286cd28dcb51.png)

The following does accomplish the same thing even if %watched% is modified but %unknown% could prove more intuitive in these cases

![image](https://user-images.githubusercontent.com/13546823/84302383-16b4ca80-ab4d-11ea-9b99-8e377c05da6b.png)

**Comment by erengy** [comment]
Episode number, `%watched%` and `%total%` are all resolved to an empty string for an unidentified anime. Empty string is equal to empty string, so the condition is met. I don't think there's any way around this in the current system without breaking other cases such as #639.

As for `%unknown%`, you can simply leave the condition value blank for the same effect.

**Comment by paulo27ms** [comment]
I didn't suggest anything because I'm not sure how the current system is structured and how susceptible to changes it is but instead of an empty string perhaps handling %watched% as -1, %total% as 0 and the episode parsed as 0 would be a solution but maybe this would raise other issues I'm not seeing in other places.
That said, it's not as if the current method is dysfunctional as you can just do a "Anime ID is not 0 (?)" in the first filter to keep those torrents from being excluded (you'd never want to apply this filter to torrents without an ID anyway as it's impossible for you to have watched something from an unknown ID).

It's just something I figured I'd mention, if it's something you think is worth revisiting in the future feel free to reopen.
