### ISSUE TITLE
Kitsu 404 causes not to update

### ISSUE THREAD

**Issue by Venipa** [erengy/taiga#902]
if an anime does not exist on kitsu it returns a 404 while trying to sync.
once the error shows up you cant sync anymore until you remove the entry from the update/sync queue.

Error if anime does not exist in kitsu
![image](https://user-images.githubusercontent.com/17952364/85945314-4a5d6600-b93d-11ea-8ab4-2d8e2cdc268a.png)

**Comment by erengy** [comment]
Duplicate of #706.
