### ISSUE TITLE
Heads Up! False positive in VirusTotal.

### ISSUE THREAD

**Issue by Screenbones** [erengy/taiga#904]
When I ran the Taiga setup utility in VirusTotal, three of the engines picked the file up:

- SecureAge APEX: Malicious (_very helpful_)
- Bkav: HW32.Packed
- Ikarus: Trojan-Ransom.Cerber

The third one is particularly worrisome for me. Individuals who are not familiar with this program may see this, and determine it's not worth the risk of installing the program, especially after Googling what Cerber is. I think it would be very useful to try to figure out why the file is showing up as Ransomware, and getting rid of the offending code.

This is for the beta file, by the way - the one that supports MyAnimeList.

[Here's a link to the VirusTotal scan](https://www.virustotal.com/gui/file/c8c776e3309314f4d8f813476d165b83bc9bafb8f9d9d8ed4278738dcc78d43b/detection)

**Comment by erengy** [comment]
Thanks for the heads up, but I uploaded the files to VirusTotal myself right after releasing the beta, so I'm aware of the situation (see the first submission date, and my vote at Community tab).

Taiga has a long history of [false positives](https://github.com/erengy/taiga/issues?q=label%3A%22false+positive%22). One of these previous issues even led to an entire [blog post](https://erengy.com/blog/false-positive). Long story short, there's no viable way to prevent false positives, all I can do is to report them and hope for the best.

I just sent an email to Ikarus (false-positive@ikarus.at), will update this comment if I get a reply.
