### ISSUE TITLE
taiga is going tsundere with me (not opening)

### ISSUE THREAD

**Issue by Eldhelion** [erengy/taiga#905]
I used taiga until it stopped working with MAL, but did not uninstalled with hopes would come back someday, recently I saw the beta (1.4)
installed it over my previous instalation, but taiga simply didnt open.

I tried compatibility mode (win 7/8), as admin, allow in firewall, tried uninstall e fresh install.... and nothing.
ah, antivirus also had no problems with it

any ideas?

in the taiga folder I have 4 itens : /data, taiga.exe, taigasetup.exe and uninstall.exe

I use win 10

**Comment by erengy** [comment]
Might be the same issue as #770.
