### ISSUE TITLE
Taiga won't recognise No Guns Life 2

### ISSUE THREAD

**Issue by ramma1** [erengy/taiga#906]
I'm stuck on this page.
![image](https://user-images.githubusercontent.com/63622130/87107488-369df200-c2a3-11ea-85ae-86b66bc9012e.png)
When I click on search and choose No Guns Life 2, set it as watching and click ok, nothing happens.
![image](https://user-images.githubusercontent.com/63622130/87107561-66e59080-c2a3-11ea-8be5-8740044fb1ed.png)
I have added an alternative name (No Guns Life) which is similar to the file name: [HorribleSubs] No Guns Life - 13 [720p].mkv
Thanks

**Comment by kiriya-aoi** [comment]
There's no anime-relations mapping No Guns Life episode 13+ to No Guns Life 2. You can contribute it yourself if you like. https://github.com/erengy/anime-relations

**Comment by ramma1** [comment]
I would love to contribute but I don't understand anything that the guide tells me to.
