### ISSUE TITLE
How do I make it so Taiga doesn't download an episode of each fansub group?

### ISSUE THREAD

**Issue by Qewar** [erengy/taiga#907]
So in my filter I have "episode fansub group contains Erai-raws" and "fansub group contains HorribleSubs", what I hoped Taiga did was download the one who comes out sooner but instead it's downloading both episodes from both fansub groups so I end up having a lot of duplicate episodes, is there a way to only have it download one out of the two?

Filter:
VEFJAQUAMS4zLjGlAdkGeJy9lE1r4zAQhs/dXzEIyp5KkqULPcR7KA3k0EN3U+jRTKxJKpA17khK6L+v5KSJW3DSNnQPxmDNvHre+fDYBKoBq2DYFcqTpSooqDFUj4VC96yAm82ZpgVGmw7J4dySLlSQSAoc1lSoO6EFCUxng8k/9efH2bhip03OhKRZkwuFosZ41lQuhWOThUkwsBQqxQY0zitYoY1JbcoiJl0yi/P0cXCy3kTQXAiuN2LjQTad3m+8a+MrFL03b+3e/KPR1OP8ZpMHt3+P+V4lES6FPNuYI7rIubBb2NHwatgcAH3fpC7n4SbN2kxY50Tjln280ZOUPmCIvotITxHtvqaj70REIwkQ0JmawDhoLDoIvEHv464p4HHuX/0D9THjvz8zRN0N+sAQaeGmIT1wHLJta3w4rUuXp7odfqPbtpukU5vTs0Jjcyxs18UfWycX6znJmyWiHfb5Vvu837/lCm35qra7/0At7lsPX/uDaMphKwy9RdkFwN39w2kzPvqvM/45m+x+BtC8dpZRw7xtU2+vF8ZSWSW1JcvzAd7r9r/QZX4Bb9Jb6A==

**Comment by paulo27ms** [comment]
Set one of them to be a prefer filter.

**Comment by Asinin3** [comment]
![image](https://user-images.githubusercontent.com/15137035/88057394-2e965a00-cba1-11ea-95b1-fde6d6060c7d.png)
This isn't the place for support, use Taiga's discord channel not an issue tracker. https://discord.gg/yeGNktZ
