### ISSUE TITLE
Long synopsis' lack a scroll bar

### ISSUE THREAD

**Issue by Volatar** [erengy/taiga#910]
If a synopsis goes on long enough it goes past the info pane size, but lacks a scroll bar. One has to highlight and drag to scroll the text if they want to read it.

Example:

![image](https://user-images.githubusercontent.com/1719182/88307271-baab9d00-ccd9-11ea-8408-d5e07738e978.png)

**Comment by erengy** [comment]
This is unfortunately a trade-off. It's not possible to make an [edit control](https://docs.microsoft.com/en-us/windows/win32/controls/edit-controls) display a scroll bar only when necessary; it's either always visible (`WS_VSCROLL`) or not.

I previously tried using a [rich edit control](https://docs.microsoft.com/en-us/windows/win32/controls/rich-edit-controls) instead, which automatically hides the scroll bar if not needed (unless `ES_DISABLENOSCROLL` style is used). But that comes with its own problems such as varying line height and redraw issues...

In the end, I decided to keep the synopsis area as is until v2.

**Comment by paulo27ms** [comment]
By the way, you can drag a selection and it'll scroll down as you select (it'll also stay down after you stop selecting), this at least allows you to read the rest of the text.
