### ISSUE TITLE
Add option to manually change recognized title

### ISSUE THREAD

**Issue by neewos** [erengy/taiga#913]
Today I ran into the following issue: I'm playing a file called
`Kyoukai no Kanata -I'll Be Here- Kako-hen.mkv`
but it's being recognized as
`Kyoukai no Kanata Episode 0: Shinonome`
instead of
`Kyoukai no Kanata Movie: I'LL BE HERE - Kako-hen`.

Renaming the file does the trick, but I'd like to avoid that.
Instead, is it possible to add an option to pick another entry, like when Taiga is unable to identify the title?

I apologize if it's a duplicate, I looked around but didn't find this issue yet.

**Comment by wopian** [comment]
Add `Kyoukai no Kanata -I'll Be Here- Kako-hen` as an alternative title to the `Kyoukai no Kanata Movie: I'LL BE HERE - Kako-hen` library entry.

![image](https://user-images.githubusercontent.com/3440094/88486484-c0251380-cf75-11ea-95f6-02632290d4c9.png)

**Comment by neewos** [comment]
It worked, thank you!
