### ISSUE TITLE
Use the "anime-offline-database" to sync between services?

### ISSUE THREAD

**Issue by Andy2244** [erengy/taiga#916]
Just wanted to make sure you are aware of this project?
https://github.com/manami-project/anime-offline-database

This projects list should help to map the services to each-other.

**Comment by paulo27ms** [comment]
Kitsu supports migration from MAL at least. Thought other services did as well? MAL lets you import from AniDB, probably not with the best results though.
Think this should be a task for the user.

**Comment by Andy2244** [comment]
> Think this should be a task for the user.

Its a real pain to manually sync/update the lists, so having it all in the app that already does the scrobbling makes sense to me. 

Yet i understand the time restrictions and would also rather see trakt + simkl support first.

**Comment by Andy2244** [comment]
Similar mapping project here: https://github.com/ScudLee/anime-lists
