### ISSUE TITLE
Automatically add playing anime to list

### ISSUE THREAD

**Issue by Matth7878** [erengy/taiga#919]
I have been using Taiga for 6 months and I just discovered that it wasn't adding and keeping track for new anime I was playing and were not in my list.
It would be nice to have an option to auto add anime not already in your list.

Issue #101 is somewhat related but I think it's not the same. 
After reading comments I think it's more about automatically adding anime present in library folder and not about adding new anime you play.

**Comment by erengy** [comment]
Please see #712 for the same issue.
