### ISSUE TITLE
edit discord presence

### ISSUE THREAD

**Issue by MrScopes** [erengy/taiga#920]
we should be able to edit how the discord presence displays, for example, instead of "Playing **Taiga**" it could be "Watching **Anime**", all editable in the settings - it could honestly be like every other recognition setting where there's the "Edit format string" option

**Comment by Repulles** [comment]
Discord doesn't allow to have "Watching" instead of "Playing", but still e.g. option to change "taiga" or icon to your own custom would be cool.

**Comment by MrScopes** [comment]
> As for now discord doesn't allow you to have "Watching" instead of "Playing", but still e.g. option to change "taiga" or icon to your own custom would be cool.

I'm not experienced in discord rich presence applications, but there could be a way taiga could take your discord auth token and set up a user account (even though it's technically against tos)

**Comment by MrScopes** [comment]
> As for now discord doesn't allow you to have "Watching" instead of "Playing", but still e.g. option to change "taiga" or icon to your own custom would be cool.

it would be nice if we could at least change "Taiga" to the actual anime or something

**Comment by crse** [comment]
> it would be nice if we could at least change "Taiga" to the actual anime or something

App name section is not dynamic by the design. The only way to changed it is via the developer section manually.

![20-10-08_t07-37-59-296PM](https://user-images.githubusercontent.com/8639337/95459389-ca17b980-099d-11eb-9226-75f6323d73e4.png)

However, merely changing "Taiga" to "anime" is doable.

**Comment by BluTree** [comment]
You can't change the "Taiga" nor the icon. In fact, the discord rich presence is very limited when implementing it. The "Taiga" is the name of the application you register to discord in order to use the rich presence, and you must upload all the image files to use it in the presence. And, unless you're a big company, you're limited to 100-150 images you can upload.

**Comment by erengy** [comment]
Please see #757 and #450 for previous discussion.
