### ISSUE TITLE
Taiga Beta is detected as malicious

### ISSUE THREAD

**Issue by Josexv1** [erengy/taiga#921]
Different Browsers are detecting the latest Taiga Beta setup `Taiga 1.4.0-beta.2` file as a virus.
Virustotal detects it as [Malicious](https://www.virustotal.com/gui/file/c8c776e3309314f4d8f813476d165b83bc9bafb8f9d9d8ed4278738dcc78d43b/detection), just  1/69 detection rate.

I checked the file and didn't find anything malicious, but it's worth checking why it's been flagged.

**Comment by wopian** [comment]
See https://github.com/erengy/taiga/issues/904

**Comment by Josexv1** [comment]
Good, i'll comment in the Virustotal scan, and close this issue.

**Comment by wopian** [comment]
SecureAge APEX has removed the false positive
