### ISSUE TITLE
Minor error when starting Taiga

### ISSUE THREAD

**Issue by moonantonio** [erengy/taiga#922]
**Issue:**

When the application starts, an ssl error appears.

![Captura](https://user-images.githubusercontent.com/7427480/91242511-ecd07480-e747-11ea-853f-7a586cbb4e32.PNG)

If I remove the message, it starts normally without any problem.

Taiga 1.3.1

**Comment by kiriya-aoi** [comment]
https://github.com/erengy/taiga/issues/312

**Comment by moonantonio** [comment]
Hello, antivirus blocks some taiga connections, especially **F-SECURE**. 
* **Solution:** Add Taiga manually to whitelist.

Thanks @kiriya-aoi  for the help; D
