### ISSUE TITLE
[Bug] Taiga 1.4.0-beta2 can't see any torrents from HorribleSubs

### ISSUE THREAD

**Issue by CloroxBleachChan12** [erengy/taiga#924]
If you use the HorribleSubs RSS feed to check for new releases, Taiga just comes up with a blank list (or rather, no list at all) of new torrents. I've also used a "RSS-mix" URL, that mixes both the feeds of Erai-raws, and HorribleSubs, but Taiga only displays the torrents from Erai-raws, as if it's filtering out every release from HorribleSubs on purpose.

And yes I've checked my filters, there is nothing there that should filter out anything from a specific group.

The only thing that has changed on my setup is that I've updated from the last stable release of Taiga to v1.4.0-beta2 in order to make use of the new MAL integration.

The reason this has become an issue for me personally, is because Erai-raws seems to be in a slump for the past week, with no new releases since 22 August.

**Comment by paulo27ms** [comment]
It's probably some issue with your RSS feed URL, either way, HS is dead now so revisit this issue.

**Comment by CloroxBleachChan12** [comment]
It's not. I use the exact same URL's in the stable release of Taiga, and it works fine. So it's definitely a code issue. But yes HS is dead now, so it doesn't matter anyways.

**Comment by erengy** [comment]
This issue was fixed in 746d87d24618d13ed44242922e56ec44901aed11.
