### ISSUE TITLE
[Feature Request] Add aria2 for torrents with custom output locations and parameters

### ISSUE THREAD

**Issue by nate-moo** [erengy/taiga#928]
For example there could be a section with custom params and you could input your own aira2 params alongside the output file location. Also seeder numbers and other things. I can provide more info on this if required.

**Comment by erengy** [comment]
891e547ea4bf483423847aae6804166c49f5b5f4 adds basic support for aria2 (i.e. `--dir` parameter is used to set the download path). Custom parameters is something planned for all clients in the future.
