### ISSUE TITLE
Sorting by Season does not sort by year first

### ISSUE THREAD

**Issue by Reeevu** [erengy/taiga#929]
Hello, I've noticed that sorting by Season does not sort by year first and only does sort season-year when I expect it to sort year-season in that order.

**Comment by erengy** [comment]
Hi, could you post a screenshot? It's clearly sorted by year first on my end.

![sort-by-season](https://user-images.githubusercontent.com/1078430/95681752-469ed800-0bea-11eb-8b24-47a99d61bdf9.png)

**Comment by Reeevu** [comment]
[https://i.kyaa.gg/pm3ga.png](url)

**Comment by erengy** [comment]
It looks like you have the *Settings → Application → Anime list → Display highlighted anime above others* option enabled, so the first five entries are displayed at the top and are sorted among themselves.

**Comment by Reeevu** [comment]
This fixed the issue, thank you.
