### ISSUE TITLE
[Feature Request] Add Microsoft Edge (Chromium) support for streaming media detection

### ISSUE THREAD

**Issue by asphereofficial** [erengy/taiga#930]
Since the new Microsoft Edge is based on Chromium engine, I would like to request the team to add Microsoft Edge support for streaming media detection.

**Comment by Abchrisabc** [comment]
I believe this is already working and doesn't require any modifications, I have been using the new Edge for a while now and I can confirm that it properly recognizes for the sources that I use (_Crunchyroll, HIDIVE and Plex_).

**Comment by erengy** [comment]
See #808. It's already available in v1.4 beta.
