### ISSUE TITLE
Visual Entry Duplication Glitch

### ISSUE THREAD

**Issue by Davoleo** [erengy/taiga#931]
Version: `1.4.0-beta.2`

Steps to reproduce this:
1) Drag and drop an entry from the PTW list to the Watching list
2) See how all Watching list entries except the one you've dragged get duplicated 
3) Change active tabs and see how everything goes back to normal

If the steps mentioned above don't work try playing the episode from taiga and then drag it when it's in the "Now Playing" state

Screenshots:
![dupe](https://user-images.githubusercontent.com/24458276/93366585-a86a5d00-f84b-11ea-8622-587dd7848a8a.png)
---
After Changing tabs
![after](https://cdn.discordapp.com/attachments/423475967051169815/755536994725134396/unknown.png)

**Comment by erengy** [comment]
Are you still having the same issue? I've been trying to reproduce this every once in a while, but no luck so far.

**Comment by paulo27ms** [comment]
I remember having this issue back when the update queue was a bit buggy, it'd keep duplicating entries every time it updated the list but I don't suppose that's the cause here.

**Comment by Davoleo** [comment]
mmh, looks like I can't reproduce it anymore either, I'll close this thread for now and re-open in case this issue arises again
