### ISSUE TITLE
Add background process

### ISSUE THREAD

**Issue by ranshaa05** [erengy/taiga#933]
i noticed that when the app is closed it does not detect when the user is watching an episode.
what im suggesting is to add a background process for the app that will allow it to detect when the user is watching an episode even when the app's UI is closed.
perhaps an option to enable/disable this process is also a good idea. this way updating your anime list will be truly automatic.

**Comment by paulo27ms** [comment]
Use close to tray.

**Comment by ranshaa05** [comment]
> Use close to tray.

well this is embarrassing...... in my defence i had only downloaded the app today so i guess i didn't look deep enough 😅😅
