### ISSUE TITLE
Anime Information: Display average score of reviews

### ISSUE THREAD

**Issue by toprak** [erengy/taiga#934]
Merhaba abi, derdimi ingilizce anlatamadım yüksek ihtimal. Şunu yapsan çok güzel olur, animelere tıkladığımızda bilgi aldığımız kısımda rating bölümü var ya, onun hemen altında da incelemelerin ortalamaları olsa çok yararlı olur aynı metascore sitesi gibi. Teşekkürler.

**Comment by erengy** [comment]
AFAIK neither AniList nor MyAnimeList provides this in their APIs. Not to mention that Kitsu has reactions rather than reviews.

---

Bildiğim kadarıyla AniList ve MyAnimeList bu veriyi API'larında sunmuyor. Kitsu'da ise zaten inceleme yok, kısa reaction'lar var.
