### ISSUE TITLE
anilist broken

### ISSUE THREAD

**Issue by darkash** [erengy/taiga#935]
![image](https://user-images.githubusercontent.com/2842880/94970986-0ecfca80-0530-11eb-86f7-c768dd7c398a.png)

seems like something is changing on anilist side, recently see cloudflare pops up once in a while

I've tried re-authorize multiple times and it doesn't do the trick

version used: 1.4.0-beta.2

**Comment by wopian** [comment]
AniList is currently experiencing a DDoS attack

**Comment by darkash** [comment]
> AniList is currently experiencing a DDoS attack

oh yeah, it worked once in a while it seems, I will close this since it seems to be invalid issue
