### ISSUE TITLE
Torrent filter for example, only 1080p torrent doesn't work

### ISSUE THREAD

**Issue by SolimanGit** [erengy/taiga#937]
I tried to have only 1080p torrent from the rss but filtering video directly doesn't work and "contain" with 720p or 1080p in the description doesn't work. either.

**Comment by asakurato** [comment]
if you want just 1080p files, use "Episode resolution is not 1080p"

**Comment by SolimanGit** [comment]
Thank you for taking your time to respond but it doesn't work.

**Comment by paulo27ms** [comment]
Needs more information, what RSS feed? Taiga might not be recognizing the resolution for that feed.
Check the column that says video, it'll show the resolution Taiga detects.
This should work 
![image](https://user-images.githubusercontent.com/13546823/96123229-73a10280-0eea-11eb-8c9f-64a302091851.png)
But I'm not sure that includes 1080p HEVC for example, worse case you use this 
![image](https://user-images.githubusercontent.com/13546823/96123278-81ef1e80-0eea-11eb-9e41-7da8178f47a4.png)
And as long as resolution is in the filename it'll catch it.

**Comment by SolimanGit** [comment]
I'm using nyaa.si for both rss feed and i think on nyaa it's broken since i have on my torrent feed anime which are not on my plan to watch or currently watching as you ca see below.
![image](https://user-images.githubusercontent.com/43494167/96129070-6ee24b80-0ef6-11eb-898a-70ce49383af3.png)

And for the filter I did what you told me but it doesn't that is weird. But thx for your response

**Comment by paulo27ms** [comment]
Are you sure you're setting your discarded items to be hidden instead of normal discarding?
I do not have this issue. Please export your whole filter list and paste here.

**Comment by SolimanGit** [comment]
Ok, i'm dumb. I forgot to change the match condition so it's working now. Thx for your help
