### ISSUE TITLE
The discord rich presence feature stops working when i start watching e.g. next episode.

### ISSUE THREAD

**Issue by Repulles** [erengy/taiga#938]
So as the title says the discord rich presence feature stops working when i start watching e.g. next episode, unless i disable this feature in taiga setting and re-enable it.

So for example i'm watching one episode the rich presence works, everything fine etc. but when i finish watching the episode and go watch the next ep it stops working and i have to re-enable it in taiga settings.

**Comment by erengy** [comment]
Is this still an issue? Just tried it out, but everything worked as expected.

Note that the delay time at *Settings → Recognition* affects automatic sharing too. In other words, the next episode will appear on Discord only after the delay time is up. See the relevant section at the [support page](https://taiga.moe/#support) for more information.

**Comment by Repulles** [comment]
Umm yeah i had delay set to about 200+ seconds...
Now it's working. thx
