### ISSUE TITLE
Release portable zip package for windows

### ISSUE THREAD

**Issue by sakibarifin** [erengy/taiga#941]
Taiga appears to keep settings in the program folder. It seems to work like portable apps. Hence, I would like to request the release of portable zip package alongside the setup installer in future releases.

**Comment by erengy** [comment]
Not sure if all file archivers have this feature, but you can unpack Taiga's installer with 7-Zip as if it was a .zip file.

![7zip-extract-exe](https://user-images.githubusercontent.com/1078430/95657608-08d47d80-0b1e-11eb-894c-de3e171b322e.png)

**Comment by sakibarifin** [comment]
Yes, I have been using a similar work around by copying the install files. I think it would be better to release a zip package since portable apps are becoming more popular these days and they can be moved around using a flash drive to use on several computers.

**Comment by paulo27ms** [comment]
I think that's present in a lot of installers but it's very easy to forget that it is a thing.

**Comment by rollingmoai** [comment]
+1 for this, unpacking the NSIS installer would leave other unnecessary files. A proper zip package would be great.
