### ISSUE TITLE
More Seasons

### ISSUE THREAD

**Issue by darkred3** [erengy/taiga#946]
Please expand the seasons to the 1910s where the earliest known animations were released. To get season data for years earlier than 1960 you currently have to manually zap through them by clicking the <- button.

![seasons](https://user-images.githubusercontent.com/33666486/97809895-438a8b00-1c70-11eb-9016-79cf659a1fe0.jpg)

**Comment by erengy** [comment]
There are [196 anime](https://anilist.co/search/anime?sort=START_DATE_DESC&year%20range=1900&year%20range=1959) released between 1907-1959. Only 24 of them have season information available. I don't think it makes sense to browse them using Seasons page.
