### ISSUE TITLE
Add source

### ISSUE THREAD

**Issue by willyreza** [erengy/taiga#947]
Please source from Indonesian subtitle. This is good app. Thanks😄

**Comment by darkash** [comment]
> Please source from Indonesian subtitle. This is good app. Thanks😄

you can use rss feed for that

change the one with filter by title using this format instead

```https://nyaa.si/?page=rss&c=1_3&f=0&q=%title%```

![image](https://user-images.githubusercontent.com/2842880/98581473-1d11c300-22f4-11eb-9e17-e94739acc420.png)

and check "check new torrents automatically" + "notify me"

that way whenever a new non-english translated anime is release, the app will notify you (including non-indonesian sub as well)

as there's no way to distinguish them, you have to bear with it (imo supporting 1 or 2 specific non-international language is kinda not scalable)
