### ISSUE TITLE
Anime Information: Allow typing fractional scores

### ISSUE THREAD

**Issue by BoredOY** [erengy/taiga#949]

**Comment by paulo27ms** [comment]
This is tied to the service you're using. MAL won't allow fractional scores. Other services already have support for them if the service allows you to do it.

**Comment by BoredOY** [comment]
> This is tied to the service you're using. MAL won't allow fractional scores. Other services already have support for them if the service allows you to do it.

I am using Anilist as my service, and I still cannot type periods into the textbox. I can change the score fractionally through the up and down arrows or by editing the ones or tenths slot, but if I delete the period I cannot re-type one.
