### ISSUE TITLE
Multiple synchronization

### ISSUE THREAD

**Issue by xSojo** [erengy/taiga#950]
I'm currently updating MAL with Taiga and manually Anilist.

I think this could be a major change but it could be great if you could update the episodes in more than 1 site at the same time.

For example, I use https://tachiyomi.org/ to read manga and it gives the option to update multiple sites.

**Comment by kiriya-aoi** [comment]
https://github.com/erengy/taiga/issues/366

**Comment by erengy** [comment]
Please see the [FAQ](https://taiga.moe/#support) section for more information.
