### ISSUE TITLE
Discord Rich presence status gets stuck

### ISSUE THREAD

**Issue by asakurato** [erengy/taiga#953]
I noticed recently, when I close the player, my status still says that Taiga is open playing the episode. See screenshot. Status gets changed if I play any other episode. Tried mpv and MPC-HC. Status only clears if I restart Taiga. Restarting Discord or PC didn't help. I'm on 1.4.0 beta 2.
![image](https://user-images.githubusercontent.com/20476454/101069161-1143b480-35b3-11eb-8ea5-36acd72260a6.png)

**Comment by BluTree** [comment]
I have the same problem. I noticed it only today, I didn't have the issue yesterday. Taiga didn't update, so I think it's more a problem on the Discord side than the Taiga side.

**Comment by asakurato** [comment]
> I have the same problem. I noticed it only today, I didn't have the issue yesterday. Taiga didn't update, so I think it's more a problem on the Discord side than the Taiga side.

I believe so too, it has something to do with discord.

**Comment by BluTree** [comment]
It seems to be fixed for me. I don't even know if it really was something on Discord's end, because the app didn't update at all and the problem disappeared

**Comment by asakurato** [comment]
Seems to be fixed for me, so it must have been really discord thing. I'll be closing this.
