### ISSUE TITLE
Taiga Won't Update When Using Secondary Player

### ISSUE THREAD

**Issue by george-emerald** [erengy/taiga#955]
I am using the latest version (1.3.1) on Windows 10 and I primarily use MPC-HC which is my default player. It recognizes fine and updates when I use that, but when I use mpv, it shows up on my now playing as it should since I have it enabled in settings; but, there is no "Update in 0 seconds (waiting for media player to close)" on the bottom right corner and no update if I close mpv. This started happening recently (it was working before) and it's really bothersome, because I use mpv when my laptop is unplugged since it doesn't drain the battery in 40 minutes like MPC-HC does.

**Comment by darkash** [comment]
> I am using the latest version (1.3.1) on Windows 10 and I primarily use MPC-HC which is my default player. It recognizes fine and updates when I use that, but when I use mpv, it shows up on my now playing as it should since I have it enabled in settings; but, there is no "Update in 0 seconds (waiting for media player to close)" on the bottom right corner and no update if I close mpv. This started happening recently (it was working before) and it's really bothersome, because I use mpv when my laptop is unplugged since it doesn't drain the battery in 40 minutes like MPC-HC does.

If you've watched them before taiga won't call an update
I've used mpc-hc as main player and both vlc and mpv as secondary player occasionally, these players works fine event in the beta version

**Comment by george-emerald** [comment]
> > I am using the latest version (1.3.1) on Windows 10 and I primarily use MPC-HC which is my default player. It recognizes fine and updates when I use that, but when I use mpv, it shows up on my now playing as it should since I have it enabled in settings; but, there is no "Update in 0 seconds (waiting for media player to close)" on the bottom right corner and no update if I close mpv. This started happening recently (it was working before) and it's really bothersome, because I use mpv when my laptop is unplugged since it doesn't drain the battery in 40 minutes like MPC-HC does.
> 
> If you've watched them before taiga won't call an update
> I've used mpc-hc as main player and both vlc and mpv as secondary player occasionally, these players works fine event in the beta version

I hadn't watched them before, taiga just recognized them as playing when using mpv but refused to update when it would update if I used mpc-hc. The bug is no more though, so I'm closing the issue.
