### ISSUE TITLE
Two Cour Anime

### ISSUE THREAD

**Issue by joaoandre120** [erengy/taiga#960]
Hi guys,

Re Zero 2 Season, is airing its second part (Re.Zero kara Hajimeru Isekai Seikatsu 2nd Season Part 2), but taiga is recognising only the first part. Is there a way to make it recognize the right one?
Versions tested:
1.3.1 with Kitsu and AniList
1.4.0-beta.2 with MAL

Thanks

**Comment by erengy** [comment]
Relevant rule was added with https://github.com/erengy/anime-relations/commit/9e1c957437ffad2505f05501d9f5f0a76ff37703. Use *Help → Check for updates* to get the latest relations.

**Comment by joaoandre120** [comment]
I tried, but it only says "Taiga is up to date!" and the version. But still not working.

**Comment by erengy** [comment]
What's the filename? When you play the file, what do you see on Now Playing page? Is it being incorrectly identified as the first part of S2, or is it not being identified at all?

**Comment by joaoandre120** [comment]
The file name is '[Erai-raws] Re.Zero kara Hajimeru Isekai Seikatsu 2nd Season Part 2 - 02 [1080p][Multiple Subtitle] (2).mkv";
Now Playing page show the first part of S2;
And the player I'm using is the MPC-HC (If makes difference), and it's showing the file name on the title.

**Comment by erengy** [comment]
This turned out to be the same issue as #748. Added a workaround with d1a9debd326518bd29fdeff7073b005a45b87f34.

**Comment by joaoandre120** [comment]
It's still not working? Is there any config I can do?

**Comment by paulo27ms** [comment]
It won't work until Taiga is updated or you compile it yourself.

**Comment by joaoandre120** [comment]
Thanks, I'll try to compile it.

**Comment by erengy** [comment]
Feel free to compile it, but you can also copy the [latest build](https://taiga.moe/latest.html) over your v1.4 beta installation directory.
