### ISSUE TITLE
Torrent list not showing torrents / not refreshing properly

### ISSUE THREAD

**Issue by WokgranX** [erengy/taiga#964]
I don't know the reason (perhaps due to a new windows update) but since the last few days Taiga is not being able to retrieve the list of available torrents anymore. It simply says that there are no torrents available, even though I know that to not be true.

![image](https://user-images.githubusercontent.com/42485901/105252984-5620ac00-5b5d-11eb-9ee7-6d3d18905060.png)

When I click on refresh it seems to try to retrieve it from Tokyotosho and then informs the same error as state above "No new torrents found". Is there a fix for this issue? 

It seems to be working if I manually type the anime name and ask it to search though... 

![image](https://user-images.githubusercontent.com/42485901/105253162-b1eb3500-5b5d-11eb-9875-0c5972496e59.png)

**Comment by WizardRason** [comment]
Seems like the rss feed is down at the moment for tokyotosho, where it checks for new releases by default. They seem to be aware of the issue according to their [site](www.tokyotosho.info), so if you wait a bit it will probably be fixed relatively soon, or there are other feeds you could swap to instead. Just choose another link from the dropdown 'RSS feed for checking new releases.'

**Comment by WokgranX** [comment]
True, the issue seems to line with Tokyotoshokan, I switched both to nyaa and now it is working perfectly. Wonder what happened this time around. I will close the issue as I believe the problem is not related to Taiga itself
