### ISSUE TITLE
Status Code: 403 Error on Anilist

### ISSUE THREAD

**Issue by Ahegyao** [erengy/taiga#975]
All of a sudden I've been getting this error which won't let me update or sync with my Anilist account. I know this has been an issue on MAL's API before. Is Anilist experiencing the same problem?

**Comment by erengy** [comment]
AniList is under a DDoS attack: https://twitter.com/AniListco/status/1362362557869260802

Their API is currently disabled:

![error](https://user-images.githubusercontent.com/1078430/108412148-87fb6000-723a-11eb-80d5-b36267db0171.png)

**Comment by Ahegyao** [comment]
I see. Quite unfortunate. Hope they get through this asap. Thanks for the notice.

**Comment by erengy** [comment]
https://twitter.com/AniListco/status/1363249941443981315

> With the site having been online to all users for the last 18 hrs, we are happy to say that the attack has been fully mitigated.
> 
> Thank you for your patience and support throughout the outage! 💕
