### ISSUE TITLE
Taiga can't find Re:Zero Season 2 Part 2 episodes

### ISSUE THREAD

**Issue by Bu11etmagnet** [erengy/taiga#977]
Even though "Open containing folder" can open the correct folder, and there are episodes there, "Play next episode" just results in an error message in the status bar: "Can not find episode #6".
When play is started by hand, Taiga displays the "Now playing" notification. However, the episode count is not increased.

**Comment by erengy** [comment]
Could you give an example filename?

See also: https://github.com/erengy/anime-relations/issues/73#issuecomment-779998564

**Comment by Bu11etmagnet** [comment]
[Erai-raws] Re.Zero kara Hajimeru Isekai Seikatsu 2nd Season Part 2 - 12 END [720p][Multiple Subtitle].mkv

**Comment by MeGaNeKoS** [comment]
mostlikely becouse the "END" part. i'm using the same library and got the same problem. after i remove the "END" part it work well again.

F.Y.I i'm using anitopy which is python version of anitomy

**Comment by erengy** [comment]
Closing because it's the same with other "Part 2" issues.
