### ISSUE TITLE
Deluge auto

### ISSUE THREAD

**Issue by Mightyyt** [erengy/taiga#978]
Hi, I really need help because i'm actually running Taiga on my Raspberry PI 4 but the only torrent client in .exe that works for taiga and which is supported for Box86 is Deluge, the only problem is i want to use taiga as an auto catalog updater for my plex server BUT everytime taiga autodownload a torrent and automatically starts the download on deluge, it asks for an user interaction to choose the file destination etc... which is not necessary while i'm using uTorrent on windows. Any Deluge's alternative? I really need to finish this project,
Regards.

**Comment by erengy** [comment]
You need to run Deluge as a daemon and connect Taiga to `deluge-console.exe`. See #688 and #229 for more information.
