### ISSUE TITLE
[FEATURE REQUEST]

### ISSUE THREAD

**Issue by Mightyyt** [erengy/taiga#981]
Support multi RSS feeds with with custom name, like for example: 

- Airing Animes: nyaa.si/***
- Movies: nyaa.si/**
- Anime's seasons: nyaa.si/****

**Comment by Mightyyt** [comment]
The reason is that I use different fansubs groups for different type of animes like movies and complete seasons

**Comment by erengy** [comment]
Duplicate of #40.
