### ISSUE TITLE
Transmission but linux's

### ISSUE THREAD

**Issue by Mightyyt** [erengy/taiga#984]
Hi, is there any way I can set-up Transmission on debian as a torrent client for Taiga?

**Comment by Mightyyt** [comment]
@erengy

**Comment by erengy** [comment]
I don't think that's possible. Running Taiga on Wine should be practically the same as running it on Windows.

**Comment by consoleaf** [comment]
You can try using an auto-add script that recursively checks the directory Taiga downloads torrent files to (`~/.wine/drive_c/$USER/Application Data/Taiga/data/feed/`) and adds all new .torrent files to Transmission.
