### ISSUE TITLE
Manga list export

### ISSUE THREAD

**Issue by Johndoedyou** [erengy/taiga#986]
I know that manga support is not planned, but what would be nice is if we could export the manga list like we can with anime already.

**Comment by paulo27ms** [comment]
You can export your list from MAL's site, there's no reason to implement this.

**Comment by Johndoedyou** [comment]
I should have mentioned I'm talking about anilist, which you can't do this on.

**Comment by crse** [comment]
I think you should request this feature directly to AniList developer, not Taiga, since this software doesn't even have manga tracking feature.

**Comment by Cuanim** [comment]
Get this https://github.com/hohMiyazawa/Automail. It has support for exporting your lists. And crse is right, you should've contacted Anilist developers directly.

**Comment by erengy** [comment]
> I know that manga support is not planned, but

Sorry, but you can't export your list without having manga support first.
