### ISSUE TITLE
Error autodownloading and recognition for sequels

### ISSUE THREAD

**Issue by alealclag** [erengy/taiga#988]
Yesterday, BNHA season 5 was released, but it wasn't recognized by the torrent checker since subsplease names it as BNHA (not BNHA 5). When I added "Boku no Hero Academia" as an alternative title, it did recognized, but as said on issue #396 , it should automatically be recognized. 

Also, today happened the same with Yuukoku no Moriarty, but even when added the alt title, neither it was marked by the torrent checker nor recognized when played.

**Comment by paulo27ms** [comment]
You need to wait for anime-relations.txt to be updated (or update it yourself). Nothing wrong with recognition.

**Comment by alealclag** [comment]
oh ok, didn't know that, thanks!!!!
