### ISSUE TITLE
Taiga Falsely Recognizes My Hero Academia 5 Episodes

### ISSUE THREAD

**Issue by george-emerald** [erengy/taiga#989]
It recognizes "[SubsPlease] Boku no Hero Academia - 89 (1080p) [1053CB4A]" as Boku no Hero Academia 5 Episode 89. It has recognized this episode naming scheme for years now; it also just did with Attack on Titan Final Season for me, so I don't know what could be wrong.

**Comment by paulo27ms** [comment]
You need to wait for anime-relations.txt to be updated (or update it yourself).

**Comment by paulo27ms** [comment]
Erengy has to approve the change to the file, we don't know how long that can take as he can be busy.
After that change is done, that file should be updated when Taiga checks for a new update or if you check for updates manually. I'd recommend setting it so Taiga checks for updates when it launches so it updates that file when you open Taiga that day, if Taiga is always on for you then check for updates manually every once in a while.

**Comment by george-emerald** [comment]
I have the option for it to check when it launches, though I do have it running for days at a time. I checked out the file and I understand the format, but it seems like you have to know the amount of episodes a season will have to register it and the number of episodes isn't out yet for BnHA 5.

**Comment by paulo27ms** [comment]
The edit is already here: https://github.com/erengy/anime-relations/pull/76/files

And it'll wAndwithoutt issues.

**Comment by george-emerald** [comment]
So, it updated now that I checked for updates, or do I have to manually edit it since it's not approved yet?

**Comment by paulo27ms** [comment]
It's not approved yet, you need to manually edit the file.

**Comment by erengy** [comment]
Sorry for the delay, I was out of town for the past two weeks.

https://github.com/erengy/anime-relations/pull/76 is now merged and available for Taiga.
