### ISSUE TITLE
Taiga fails to identify Mars Red episodes

### ISSUE THREAD

**Issue by Amerr-r** [erengy/taiga#990]
Can't seem to add it manually either. Here is the file name I'm having trouble with: [SubsPlease] Mars Red - 01 (1080p) [D6681E73].mkv

**Comment by paulo27ms** [comment]
Your anime might be outdated, Taiga doesn't recognize anime that isn't airing. Open the entry and press F5 to refresh it and try again.

**Comment by Amerr-r** [comment]
> Your anime might be outdated, Taiga doesn't recognize anime that isn't airing. Open the entry and press F5 to refresh it and try again.

I see, it seems anilist is still listing it as not yet aired unlike myanimelist. I guess I'll just have to wait until they update it.
