### ISSUE TITLE
Feature: Download Torrent to temporary path & once completed move to named folder

### ISSUE THREAD

**Issue by Venipa** [erengy/taiga#991]
I've realized something while downloading directly onto my NAS Network Drive, im having net issues since im using up all my bandwidth and while that happens my fritzbox cuts the internet due to high usage of their ports somehow.

Maybe a feature like this would be more suitable if possible.
1. Download Torrent to temp folder
2. After download done the temp folder/files moves to the desired anime folder

This could be done with some torrent clients, maybe qbittorrent with an parameter to move completed files to the anime folder

**Comment by paulo27ms** [comment]
Consider limiting the download speed.

**Comment by Venipa** [comment]
> Consider limiting the download speed.

thats what im doing now but its not a really efficient solution, downloading 100gb's of batch anime's takes hours...

**Comment by BinToss** [comment]
Tixati, for example, has this feature built-in, but I'm unsure if the relevant feature has a startup argument.
It can categorize torrents by keywords and more.

Each category has options for their own default Download and Finished directories, but the UI/UX makes it so having more than a dozen or so categories can get out of hand; it's a list with no search feature. The layout of the window can be changed, but making the list's panel larger doesn't resolve the issue of having one category per anime.
However, these categories can be manually sorted and have separators inserted between them, so if you're willing to put up with the somewhat frequent management of categorization, Tixati's features provide a good solution to your issue.

**Comment by FreezyLemon** [comment]
qbittorrent has a global setting for this (Settings -> Downloads -> Keep incomplete torrents in)
I don't think you can set it for each torrent..

I don't really see how this would help your problem though, are you running the torrent software on your PC and using NAS storage from there? Consider running a torrent client on your NAS.

**Comment by erengy** [comment]
I don't think this can be done on Taiga's end. It's up to the torrent client where to keep incomplete downloads. As others have mentioned, some clients do have their own options for this, but AFAIK there's no relevant command-line parameter other than what Taiga already uses.
