### ISSUE TITLE
Fatal error: Taiga freezes after updating impossible episode count

### ISSUE THREAD

**Issue by darkred3** [erengy/taiga#993]
_Taiga 1.4.0-beta.2 Windows 10_

I downloaded some twitter videos with jdownloader for Mashiro no Oto Mini (ID: 46119) which have a format like _1360151658429247488_1360151658429247488.mp4_ and placed them inside a folder called Mashiro no Oto Mini which caused Taiga to automatically recognize them and update my list. The above filename gets recognized as episode 2147483647 (dunno how Taiga calculates this since I don't see that number in the filename at all). Taiga successfully updates this episode count no problem, even tho it shouldn't since this number is just impossible. But the real problem is, as soon as you try to open the _Anime List_ page, Taiga freezes. Even restarting doesn't work. The only thing that seems to work is to replace the _program_ section in settings.xml with the default values.

**Comment by paulo27ms** [comment]
Go to your tracker's website and change the episode there.
You can also enable this option that I have disabled:
![image](https://user-images.githubusercontent.com/13546823/114268914-ac361a80-99fb-11eb-96fe-3c23886b5bfc.png)
Which will prevent this in the future.

**Comment by darkred3** [comment]
I simply changed the folder name so it won't recognize them automatically anymore. Yes the update went through, there's simply a problem with the _Anime List_ page being unable to handle it as you said. After modifying the _settings.xml_ the episode count displayed in Taiga was set to 9999 I believe, while MAL was still at that ridiculous number. But I think this issue should be fixed on Taigas side.
