### ISSUE TITLE
Crunchyroll Beta Detection

### ISSUE THREAD

**Issue by Nats1113** [erengy/taiga#994]
Crunchyroll has a beta thing that I decided to try out, but it seems that Taiga cannot detect Crunchyroll if you opt into the beta. It works fine if you go back to classic, so it's not a fatal issue, but I'm assuming classic mode will be going away at some point. Thanks, and I apologize if I waste any ones time.

**Comment by ifonefox** [comment]
Taiga detection isn't working with Crunchyroll beta for me either. It looks like the beta's page titles don't have the episode numbers, just the show title and episode title.

**Comment by hotsno** [comment]
In case any of you are interested, here's a browser extension that does many things similar to Taiga and might work with Crunchyroll beta: [MAL-Sync](https://malsync.moe/)

**Comment by ryban** [comment]
I would recommend sending feedback to the beta and hope they do something about it. In the very likely event that they do not update the page title, I made a hacky [userscript](https://gist.github.com/ryban/d5d66b51618a98d242d4519ebc1e3b3e) that makes the beta work for me.

**Comment by quetsalkoatl** [comment]
I submitted a feature request for the beta to include the episode number in the <title> Tag. We'll see if they add it. Please do the same if you what Taiga to continue working on CR in the future: https://crunchyrollux.zendesk.com/hc/en-us/requests/new

**Comment by erengy** [comment]
Seems weird that they're including the episode number in `og:title` but not in `title`, e.g.:

- `SPY x FAMILY | E1 - OPERATION STRIX`
- `SPY x FAMILY OPERATION STRIX - Watch on Crunchyroll`

It'd be a simple change on their end, but now that the beta is over, I doubt they're going to make it.

I'm planning to remove Crunchyroll and Funimation support before releasing v1.4. Then perhaps we'll look into another solution such as #1084.
