### ISSUE TITLE
Issues with the bot

### ISSUE THREAD

**Issue by anime731** [erengy/taiga#997]
need help

**Comment by BinToss** [comment]
Creating an Issue or support ticket without explaining the issue wastes everyone's time.
I'm not trying to be passive-aggressive about it—I simply don't want you to be inconvenienced like this in the future.

So, what seems to be the issue? Also, what do you mean by "bot"? I don't recall Taiga having any bot-like features.

**Comment by paulo27ms** [comment]
Just seems like spam/wrong repo.
