### ISSUE TITLE
Sync mal data to taiga

### ISSUE THREAD

**Issue by 4zjata** [erengy/taiga#999]
When i update my list from my phone or browser taiga dont use new data and overwrite it with old data. Taiga should update itself when updating myanimelist with other apps.

**Comment by paulo27ms** [comment]
You have to hit the refresh button.
Taiga isn't going to magically guess when you update your list and updating it on a schedule isn't something erengy seems interested in doing.

**Comment by 4zjata** [comment]
ok i did something weird that time, my bad.
